### ISSUE TITLE
fTrem support for MEI4 broken

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#1002]
It seems that Verovio doesn't consider the proper attributes for fTrems in MEI4 anymore. `@measperf` has been replaced by `@unitdur`, and `@slash` has been replaced by `@beams`. C.f. https://music-encoding.org/guidelines/v4/elements/ftrem.html#attributes

XSLT transforms:
https://github.com/music-encoding/encoding-tools/blob/3f5ffc414b64d578477a8a55bb7863199ab8f372/mei30To40/mei30To40.xsl#L2203-L2221 
https://github.com/music-encoding/encoding-tools/blob/3f5ffc414b64d578477a8a55bb7863199ab8f372/mei30To40/mei30To40.xsl#L2339-L2357

**Comment by lpugin** [comment]
I don't think `@measpef` was ever used by Verovio. Correct? I will change `@slash` to `@beams`.

**Comment by kepper** [comment]
I don't know what was supported – we just found that it's broken, and that those are the attributes that have changed ;-) Thanks for taking this up so quickly – again :-)

**Comment by lpugin** [comment]
Fixed
