### ISSUE TITLE
Note ids in MusicXML import

### ISSUE THREAD

**Issue by chfin** [rism-ch/verovio#1005]
I would like to match notes in the SVG output with notes in a MusicXML input. The simplest solution would be to set `xml:id`s on notes in the MusicXML, which would then be used as ids in the SVG. However, unlike with MEI input, verovio does not keep `xml:id`s in MusicXML input.

Something like this has been suggested in #923 and #379, but it seems that this has not been addressed yet.

**Comment by lpugin** [comment]
This 59555f2d8289bed716c90aa8e3bb22e98503810b should do it, shoudn't it? Please fix it if necessary

**Comment by chfin** [comment]
Awesome, works! Thanks a lot.
