### ISSUE TITLE
Have distinct glyph ids in the SVG for each font

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#1010]
I have noticed a regression with Verovio 2.0.2 on issue 858 (https://github.com/rism-ch/verovio/issues/858)
Indeed, this issue was related to the possibility of displaying several lines on the same page with different fonts.
The solution proposed for Verovio 1.1.6 was a workaround consisting of using:

```
var svgimage = "<img style='width: 100%' src='data:image/svg+xml;base64," + btoa(svg) + "'/>";
$("#output").html(svgimage);
```

instead of just:

`$("#output").html(svg);`

Unfortunately with Verovio 2.0.2, it doesn't work any longer in some situations.
Here's the case:

```
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="http://www.verovio.org/javascript/jquery.min.js" type="text/javascript"></script>
<script src="./verovio-toolkit.js" type="text/javascript"></script>
<script type="text/javascript">var _pn_msv_vrvToolkit = new verovio.toolkit();</script>
</head>
<body>
    <div id="output"></div>
    <script type="text/javascript">
        jQuery(document).ready(function($){
                               //you can now use $ as your jQuery object.
                               $.ajax({
                                      url: "https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei"
                                      , dataType: "text"
                                      , success: function(data) {
                                      var svg = _pn_msv_vrvToolkit.renderData(data,
                                                                              {
                                                                              //avoid using inputFormat
                                                                              font: "Gootville",
                                                                              scale: 100,
                                                                              noLayout:0,
                                                                              breaks:"none",
                                                                              adjustPageHeight: 1
                                                                              }
                                                                              );
                                      //Workaround : Otherwise does not take into account different fonts in same web page with verovio 1.1.6
                                      var svgimage = "<img style='width: 100%' src='data:image/svg+xml;base64," + btoa(svg) + "'/>";
                                      $("#output").html(svgimage);} // end success fn
                                      //$("#output").html(svg);} // end success fn
                                      , error: function(data) { console.log("pn_msv error loading file https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei");}
                                      });
                               }); // end jQuery(document).ready(function($)
        </script>
</body>
</html>
```
 Thanks for helping.

BTW: I had asked when the workaround was scheduled to be correctly implemented, but never got an answer...

**Comment by lpugin** [comment]
Could you be more precise about the regression and in what situation in does not work? I do not see what was changed in Verovio that can make the workaround not to work anymore.

**Comment by efreja** [comment]
Hello Laurent,

I was surprised myself but it's a fact...
For describing the regression I couldn't be more precise than providing the test case above.
Use verovio-toolkit.js 1.1.6, it displays the score. With 2.0.2, it doesn't : The svg is good (you see it if you use $("#output").html(svg) instead of $("#output").html(svgimage)). But when embedded in the <image>, the image does not display.

Thanks..

**Comment by efreja** [comment]
Hello Laurent,

I'm not quite sure of the issue title as the problem appears for 2 separate SVGs in the same page..
Anyway, on my pov, regarding my WordPress plugin [https://wordpress.org/plugins/music-sheet-viewer/](url), this is a regression as I can't upgrade the Verovio version (either I lose the functionality or I deliver code that breaks in some situations).

What do you propose ?

Thanks

**Comment by craigsapp** [comment]
There are two problems in the options:

```javascript
{
        font: "Gootville",
        scale: 100,                                                           
        noLayout: 0,                                                           
        breaks: "none",                                                        
        adjustPageHeight: 1                                                   
}   
```

The first problem is that `noLayout:0` should be removed (it is an old option replaced by `breaks`).  The second problem is that breaks should be set to `auto` rather than `none`.  The `none` option can be used, but it means to display an single infinitely long system with no line breaks.

So the options should instead be:

```javascript
{
        font: "Gootville",
        scale: 100,                                                           
        breaks: "auto",
        adjustPageHeight: 1                                                   
}  
```

There was still a problem displaying the rendered music, so the above problems were not critical.

Instead the problem are the "é" characters in the SVG image (for Frédéric Chopin) which are causing the image to not be displayed.   This is demonstrated by turning of the header (the header with title information will be shown by default in the new version of verovio):

```javascript
{
        font: "Gootville",
        scale: 100,                                                           
        breaks: "auto",
        noHeader: 1, 
        adjustPageHeight: 1                                                   
}  
```

Adding `noHeader:1` is not a complete solution since it would be possible for text content within the music (such as within some lyric text).   You will have to figure out how to specify the SVG content embedded in the `<img>` tag is in UTF-8 character encoding, since it seem that that is the problem.

Here is the view I get when making the three changes to the rendering options in your code:

![Screen Shot 2019-03-12 at 7 15 30 PM](https://user-images.githubusercontent.com/3487289/54248813-3f3db700-44fb-11e9-9d12-40f669d44446.png)

Example code (same as you give with a more saner indenting as well as altering the input options for verovio:

```html
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="http://www.verovio.org/javascript/jquery.min.js" type="text/javascript"></script>
<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit.js" type="text/javascript"></script>
<script type="text/javascript">var _pn_msv_vrvToolkit = new verovio.toolkit();</script>
</head>
<body>
<div id="output"></div>
<script type="text/javascript">
   jQuery(document).ready(function($){
      //you can now use $ as your jQuery object.
      $.ajax({
         url: "https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei"
         , dataType: "text"
         , success: function(data) {
            var svg = _pn_msv_vrvToolkit.renderData(data,
               {
                  //avoid using inputFormat
                  font: "Gootville",
                  scale: 100,
                  breaks:"auto",
                  noHeader: 1,   
                  adjustPageHeight: 1
               }
            );
            //Workaround : Otherwise does not take into account different fonts in same web page with verovio 1.1.6
            var svgimage = "<img style='width: 100%' src='data:image/svg+xml;base64," + btoa(svg) + "'/>";
            $("#output").html(svgimage);} // end success fn
            //$("#output").html(svg);} // end success fn
         , error: function(data) { console.log("pn_msv error loading file https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei");}
      });
   }); // end jQuery(document).ready(function($)
</script>
</body>
</html>
```

**Comment by efreja** [comment]
Hello Craig,

Thanks for your quick answer. Yes I checked that there's an issue with btoa and UTF-8 encoding.
And a simple solution seems to be : https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_escaping_the_string_before_encoding_it.
I've tested it and it works. I'll run other tests, though.
Another workaround until this issue is fixed.

NB : Concerning the `noLayout` options I had already got rid of it for my next version. Thanks

**Comment by craigsapp** [comment]
The solutions on that page are good to know about.  How have you made it work?  It seems like all of those solutions have dedicated encode/decode functions that must be paired, so encoding with one of their equivalents to `btoa()` may not be decodable directly by `atob()` (the 3rd solutions rewrites those two functions, though).

**Comment by efreja** [comment]
Well I just copied the code in question in the page...
Here's the final code:

`<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="http://www.verovio.org/javascript/jquery.min.js" type="text/javascript"></script>
<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit.js" type="text/javascript"></script>
<script type="text/javascript">var _pn_msv_vrvToolkit = new verovio.toolkit();</script>
<script type="text/javascript">
    function b64EncodeUnicode(str) {
        // first we use encodeURIComponent to get percent-encoded UTF-8,
        // then we convert the percent encodings into raw bytes which
        // can be fed into btoa.
        return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g,
                                                    function toSolidBytes(match, p1) {
                                                    return String.fromCharCode('0x' + p1);
                                                    }));
    }
</script>
</head>
<body>
<div id="output"></div>
<script type="text/javascript">
   jQuery(document).ready(function($){
      //you can now use $ as your jQuery object.
      $.ajax({
         url: "https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei"
         , dataType: "text"
         , success: function(data) {
            var svg = _pn_msv_vrvToolkit.renderData(data,
               {
                  //avoid using inputFormat
                  font: "Gootville",
                  scale: 100,
                  breaks:"auto",  
                  adjustPageHeight: 1
               }
            );
            //Workaround : Otherwise does not take into account different fonts in same web page with verovio 1.1.6
            var svgimage = "<img style='width: 100%' src='data:image/svg+xml;base64," + b64EncodeUnicode(svg) + "'/>";
            $("#output").html(svgimage);} // end success fn
            //$("#output").html(svg);} // end success fn
         , error: function(data) { console.log("pn_msv error loading file https://www.verovio.org/examples/downloads/Chopin_Etude_op.10_no.9.mei");}
      });
   }); // end jQuery(document).ready(function($)
</script>
</body>
</html>`

I didn't tell particularly the browser how to decode that base64 string : I can confirm that at least Firefox, Chrome and Safari know how to decode it...

**Comment by efreja** [comment]
Hello,

This workaround (svg inside an img) unfortunately doesn't work if we want to have the notes highlighted when played (see https://www.verovio.org/tutorial.xhtml?id=topic03) : SVG is mandatory for this!!

This is a major drawback, and I had to disconnect the font feature for scores played and highlighted with Music Sheet Viewer version 2.2 (https://wordpress.org/plugins/music-sheet-viewer/)

Is it possible to raise the priority of this feature ?

Thanks
