### ISSUE TITLE
Vertical justification of staves/systems on page

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1011]
It would be useful to implement vertical justification of staves and systems in verovio to fill the printable region given by the `--page-height` parameter.  This feature is somewhat related to issue #1004 (so it might be useful to deal with them at the same time).

There should be at least two models for vertical justification, where the unused vertical spacing is distributed:
(1) by dividing it equally between each system.
(2) by dividing it equally between each staff.

There should also be a hybrid model where the extra space can be proportionally allotted to each of the base cases above.  For example, maybe `--justification-factor 0.5` would mean that 50% of the extra space would be allocated to expanding the space between staves, and 50% for expansion between systems.  Then `--justification-factor 0.0` could mean case 1 above, and `--justification-factor 1.0` could mean case 2 above (or vice versa).   The presence of this option could trigger justification, or a separate option could turn justification on (or off).

There is another refinement which would also be very useful: when staves are typeset with a tight spacing, there is a greater likelihood that the actual spacing between staves/systems is unequal due to extra padding needed to avoid collisions between objects (notes, slurs, etc.) between any two staves/systems.  When vertical justification is added to spread out the staves, the extra vertical space should first be applied to make the staves/systems equally space before assigning the rest of the extra space to separate the staves/systems further.   In other words, there should be two steps in the vertical justification process: (1) adjust staves/systems towards being equally spaced (perhaps according to the ratios of the parameters `--spacing-staff` and `--spacing-system`, and (2) further spreading of the staves and systems would be equally distributed after the point where they are equally spaced.

**Comment by lpugin** [comment]
Moved to the wish list

**Comment by craigsapp** [comment]
Implemented with options:

```
 --justify-include-last-page       Justify including the last page
 --justify-systems-only            Justify systems only and not staves
 --justify-vertically              Justify spacing vertically to fill the page
```
