### ISSUE TITLE
Place tempo text above chords

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#1026]
Just a quick question: Is it possible to place tempo elements above harm elements in the rendering per element?

Somewhat related: #437

**Comment by lpugin** [comment]
No. This duplicates with issue https://github.com/rism-ch/verovio/issues/445

In any case, it needs to be discussed in MEI repository https://github.com/music-encoding/music-encoding first

**Comment by sonovice** [comment]
For future reference - There is a discussion over here: music-encoding/music-encoding#390

**Comment by sonovice** [comment]
Infact, MEI v4 lets the user define the order:

> In MEI v4, this is handled by `@aboveorder` / `@beloworder` on `<staffDef>`. C.f.
> 
>     * https://music-encoding.org/guidelines/v4/attribute-classes/att.staffitems.html
> 
>     * https://music-encoding.org/guidelines/v4/data-types/data.staffitem.html
