### ISSUE TITLE
Problem with lyrics

### ISSUE THREAD

**Issue by minamouse** [rism-ch/verovio#103]
Files with the `<syl>` element seem to not render. For the page of examples here (http://ddmal.github.io/mei-test-set/vexflow-demos.html), there should be two more rendered examples (`TC.Prokofiev.mei` and `TC.Prokofiev.pref.mei`), but since they both have `<syl>` elements in them, they don't show up. When I remove these things, the rendering works again.

``` javascript
function pictureExample(myMEI)
        {
            var fileName = "MEI/vexflow/" + myMEI;
            var vrvToolkit = new verovio.toolkit();
            vrvToolkit.setOptions(JSON.stringify({scale: 40, adjustPageHeight: 1}));
            var xhr = new XMLHttpRequest();
            xhr.onload = function(args)
            {
                var svg = vrvToolkit.renderData(xhr.responseText, "");
                document.getElementById("output").innerHTML += "<h3>" + myMEI + "</h3>" + svg + "<hr/>";
            }

            xhr.open("GET", fileName);
            xhr.send();
        }
        pictureExample(
            "Bartok-WeddingSong-altered.mei"
            );
        pictureExample(
            "Bartok-WeddingSong.mei"
            );
        pictureExample(
            "Demo.BachCPrelude.mei"
            );
        pictureExample(
            "TC.Prokofiev.mei"
            );
        pictureExample(
            "TC.Prokofiev.pref.mei"
            );
```

However, they do seem to work when they are in a `<verse>` element, like in the `TC.Hyphens.Verses.mei` example on this page (http://ddmal.github.io/mei-test-set/vexflow-others.html), even though the different verses themselves don't work.

**Comment by lpugin** [comment]
This is indeed not supported. However different (e.g., multiple?) verses
should work.

**Comment by mborsodi** [comment]
Ah, yes! It does, however, only work when `n` is a number? The file I mentioned above had the verses labelled as `"verse_1"`, which I guess is why it wasn't working.
