### ISSUE TITLE
cross-staff chords articulation problem

### ISSUE THREAD

**Issue by susannecox** [rism-ch/verovio#1037]
in cross-staff chords, articulation like stacc.dots are placed strangely:
![Ohne Titel2](https://user-images.githubusercontent.com/40765557/56213673-ca5f1f00-605c-11e9-9bd7-e62210fc62de.jpeg)
can be found here: https://github.com/BeethovensWerkstatt/module2/blob/dev/data/works/Op.14.1_PianoSonata.xml
mdiv1, measure 15/16
might be related to #957

**Comment by lpugin** [comment]
Duplicates with #957
