### ISSUE TITLE
automatic tuplet numbers

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#104]
I'm not sure if this is a weird bug, or was done on purpose, but when nothing is specified in a `<tuplet>`, the automatic number that appears over the tuplet is 65535. Everything works fine when you specify the `num` and `numbase` attributes, though.
![screen shot 2015-06-03 at 11 17 37 am](https://cloud.githubusercontent.com/assets/11529868/7963721/26192014-09e2-11e5-803b-3170947d9321.png)

**Comment by ahankinson** [comment]
@mborsodi could you provide a link to the MEI test file?

**Comment by craigsapp** [comment]
65535 is a recasting of a -1 as a signed short int into a signed int.  So
somewhere in the code, -1 is being used to indicate lack of a tuplet, then
later that number is changed to a signed number, and since it is positive
it is printed...

**Comment by lpugin** [comment]
Correct. This is why I picked this one because it is an easy fix ;-)

**Comment by mborsodi** [comment]
I think I fixed the example above (for the jMEI2Midi project), but here's another one: 
[gh-pages](http://ddmal.github.io/mei-test-set/complete-examples/Parker-Gillespie_ShawNuff.html)
[mei file](https://github.com/DDMAL/mei-test-set/blob/develop/complete-examples/Parker-Gillespie_ShawNuff.html)

**Comment by lpugin** [comment]
It won't show the cast unsigned short anymore, so this is fixed. Result will still be unpredictable with only num or numbase attributes. Closing for now
