### ISSUE TITLE
MusicXML import: Endings not supported

### ISSUE THREAD

**Issue by earboxer** [rism-ch/verovio#1043]
Loading a musicXML file fails to include the endings (prima volta, etc). (A simple example is [45b-RepeatWithAlternatives.xml](https://raw.githubusercontent.com/cuthbertLab/musicxmlTestSuite/master/xmlFiles/45b-RepeatWithAlternatives.xml) from the [Unofficial MusicXML test suite](https://github.com/cuthbertLab/musicxmlTestSuite).

**Comment by earboxer** [comment]
In (partwise) musicXML, an ending is made up of two tags
```
part > measure > barline[location=left] > ending[type=start]
part > measure > barline[location=right] > ending[type=stop], measure > barline > ending[type=discontinue]
```

> 	Endings refers to multiple (e.g. first and second) endings.
	Typically, the start type is associated with the left
	barline of the first measure in an ending. The stop and
	discontinue types are associated with the right barline of
	the last measure in an ending. Stop is used when the ending
	mark concludes with a downward jog, as is typical for first
	endings. Discontinue is used when there is no downward jog,
	as is typical for second endings that do not conclude a
	piece.

(it also has a number attribute)

In MEI, it is

`score > section > ending > measure`

**Comment by wergo** [comment]
Would be great to have. See #1035.

**Comment by rettinghaus** [comment]
@wergo If you have a great idea how to implement this, please go ahead. From my perspective it's anything else than easy.

**Comment by wergo** [comment]
@rettinghaus, I had a close look at `iomusicxml` to understand that it is not trivial. I will try to understand the code better. Let's see how far I get.

**Comment by wergo** [comment]
@earboxer, could you test the ending import implementation please?

**Comment by earboxer** [comment]
Looks great to me!
