### ISSUE TITLE
Missing Hypen in Syllabification in latest verovio version

### ISSUE THREAD

**Issue by cividini** [rism-ch/verovio#1050]
In the latest Verovio version online, hyphen for the syllabification of the text under the notes are missing **after** the system break. According to "Behind bars" they should appear not only before, but also after the system break. In the previous Verovio version, hyphen appear correctly both before and after the system break.

**Comment by lpugin** [comment]
Fixed with d167437b1684f7ec0e8ad6be69d9990daa881354
