### ISSUE TITLE
Toolkit: Document units on `pageHeight` and `pageWidth`

### ISSUE THREAD

**Issue by earboxer** [rism-ch/verovio#1055]
What are the units on pageHeight and pageWidth?

`vrvToolkit.getAvailableOptions().groups['1-general'].options.pageHeight.description` should say more than "The page height"

The tutorial at https://www.verovio.org/tutorial.xhtml?id=topic01 shows

```
var zoom = 30;
    pageHeight = $(document).height() * 100 / zoom ;
    pageWidth = $(window).width() * 100 / zoom ;
    options = {
                pageHeight: pageHeight,
                pageWidth: pageWidth,
                scale: zoom,
                adjustPageHeight: true
            };
    vrvToolkit.setOptions(options);
```

Would it make sense/be possible to have a `pixelHeight` and `pixelWidth` option to set the SVG size without needing to be a product with the scale?

**Comment by lpugin** [comment]
Units are indeed pixels with scale = 100. If we add another option then we will raise other issues. For example, which one of scale or pageHeight should be preserve in order to obtain the desire output.
If you have a good solution, please make a PR.
