### ISSUE TITLE
Toolkit: Add breaks option for only line breaks [enhancement]

### ISSUE THREAD

**Issue by earboxer** [rism-ch/verovio#1056]
Currently, the options for 'breaks' are

* none - shows the whole song as 1 line
* auto - automatically formats the song
* encoded - Takes the system breaks (line breaks) and page breaks from the file

What do you think about an additional option for breaks

* line - Take the system breaks (line breaks) from the file, automatically paginate.

(So if you have a file that has breaks encoded for A4, you can change it to US Letter or US Legal, and the only change would be the lines (systems) moving to different pages).

**Comment by earboxer** [comment]
This is easier said than done.

As far as a start, I've gotten to modifying `Doc::CastOffDoc` to include `castOffEncoding` (from `Doc::CastOffEncodingDoc`) instead of `castOffSystems`, but I've only gotten mixed success (really no success at all so far).

**Comment by earboxer** [comment]
So, we need the `Pb::CastOffEncoding` to not run, 
```diff
-params->m_currentPage = new Page();
-assert(params->m_doc->GetPages());
-params->m_doc->GetPages()->AddChild(params->m_currentPage);
```

then, we need to run the pagination CastOffPages

**Comment by lpugin** [comment]
It is not clear what you want to achieve. Could you clarify?

**Comment by earboxer** [comment]
Sure. For the following example, imagine that `<br>` is a section break, and `<hr>` is a page break

Say that my source file looks like

```
Measure 1, Measure 2
<section break>
Measure 3, Measure 4
<page break>
Measure 5, Measure 6
<section break>
Measure 7, Measure 8
```

Currently, `--breaks encoded` shows that file as encoded
```
Measure 1, Measure 2
<section break>
Measure 3, Measure 4
<page break>
Measure 5, Measure 6
<section break>
Measure 7, Measure 8
```

`--breaks auto` squishes it wherever it wants, it might look like
```
Measure 1, Measure 2, Measure 3
<section break>
Measure 4, Measure 5
<section break>
Measure 6, Measure 7
<page break>
Measure 8
```

But the location of the section breaks and page breaks could change based on the target size.


`--breaks none` shows just
`Measure 1, Measure 2, Measure 3, Measure 4, Measure 5, Measure 6, Measure 7, Measure 8`

`--breaks line` should keep the section breaks, it might look like

```
Measure 1, Measure 2
<section break>
Measure 3, Measure 4
<section break>
Measure 5, Measure 6
<page break>
Measure 7, Measure 8
```

It might also look like 

```
Measure 1, Measure 2
<page break>
Measure 3, Measure 4
<page break>
Measure 5, Measure 6
<page break>
Measure 7, Measure 8
```

or

```
Measure 1, Measure 2
<section break>
Measure 3, Measure 4
<section break>
Measure 5, Measure 6
<section break>
Measure 7, Measure 8
```

**Comment by lpugin** [comment]
OK. I am not completely convinced that this is very useful. As you pointed out, it is not trivial because it is mixing encoded layout and calculated layout. Can you make a PR?

**Comment by earboxer** [comment]
"it is not trivial" is right... I created a WIP PR. Hopefully someone can lend some understanding into why it isn't working fine.

**Comment by lpugin** [comment]
This feature request is now a WIP PR https://github.com/rism-ch/verovio/pull/1069
