### ISSUE TITLE
LibMEI: improve consistency

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1057]
Update `data_KEYSIGNATURE` to `data.KEYFIFTHS` and apply it to `ATT_KEYSIGLOG` like in `ATT_KEYSIGDEFAULTLOG`.

see:
https://music-encoding.org/guidelines/v4/data-types/data.keyfifths.html

**Comment by lpugin** [comment]
I agree this needs to be fixed. However, I did not understand this change in MEI
https://github.com/music-encoding/music-encoding/commit/82e2648261eaf6afecc32e976789dd67fbab36bc
The data type ("Indicates the location of the tonic in the circle of fifths.") does not seem to represent a key signature. Any thoughts?

**Comment by rettinghaus** [comment]
It seems to be an unfinished revision around the discussion we had [here](https://github.com/music-encoding/music-encoding/issues/525). Which could also explain why [this](https://github.com/music-encoding/music-encoding/issues/590) happened. 
Best would probably to switch back in MEI until we (hopefully) reached a consensus on this?

**Comment by lpugin** [comment]
OK, then we should open an issue in music-encoding
