### ISSUE TITLE
<parts> not supported?

### ISSUE THREAD

**Issue by davidrizo** [rism-ch/verovio#1059]
When using an input file with the structure detailed below (taken from MEI guidelines), _verovio_ outputs the warning: `"[Warning] Unsupported '<parts>' within <mdiv>"`
```
<body>
   <mdiv n="1" type="movement">
      <parts>
         <!-- markup of performers’ parts goes here -->
      </parts>
   </mdiv>  
</body>
```
It would be very useful to be able to render a given part specified through a command line option

**Comment by lpugin** [comment]
Yes, I agree. Maybe for now you could apply a simple XSLT that puts the part into a temporary score?

Since this is a very general feature request so I will be closing the issue. OK?

**Comment by davidrizo** [comment]
You're right, it can be solved this way
Thanks !!
