### ISSUE TITLE
Support for endings

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#106]
Anything inside an `<ending>` element doesn't show up in verovio:

![screen shot 2015-06-03 at 2 42 14 pm](https://cloud.githubusercontent.com/assets/11529868/7968421/bbe69e02-09fe-11e5-8d25-fb1d5013d4e2.png)

Also, the repeat positioning is not always correct. First, most obviously, is the problem of repeats at the beginning of a system - since it's part of a `<barline>` element, it gets put way over on the left, which not only overlaps with the clef, but is actually in the wrong place - it should actually be put after the clef, key signature and (if present) the time signature as well.

![screen shot 2015-06-03 at 3 00 47 pm](https://cloud.githubusercontent.com/assets/11529868/7968884/68adbf42-0a01-11e5-987d-8069edb12fd2.png)

Also, in the above example, where there are changes after a repeat sign, instead of being positioned like they would be with normal bars (like above), they should be placed after the repeat sign, to show that the changes don't take place in the repeat. Like below, this means that these things, rather than coming before or after a bar line, like they normally would, they have to go in between repeat signs:

![screen shot 2015-06-03 at 3 04 13 pm](https://cloud.githubusercontent.com/assets/11529868/7968947/d1640ce4-0a01-11e5-8c13-f4df91029c00.png)

**Comment by lpugin** [comment]
Positionning of the repeats has been fixed in d8be65507c7a8cfebc2d997dedd036c8317e728e

I am changing the ticket to ending feature request

**Comment by lpugin** [comment]
Added in 5c220491196aa428f99ea9118bd027906de52c03. Documentation will be added in the next release.
