### ISSUE TITLE
Logical error calculating maxHeight in `Slur::AdjustSlurCurve`

### ISSUE THREAD

**Issue by valeriyvan** [rism-ch/verovio#1067]
There's logical error in calculation of maxHeight inside of method `Slur::AdjustSlurCurve`

<img width="972" alt="Screenshot 2019-05-16 at 12 21 45" src="https://user-images.githubusercontent.com/1630974/57846881-779c9280-77d5-11e9-8192-b9cf53162e77.png">

Not understanding logic I can't fix this.
But there's definitely something wrong here.

**Comment by lpugin** [comment]
The analyser is confused by the re-assignment of maxHeight added when the code below was commented. This is work in progress.
