### ISSUE TITLE
LibMEI: refine GetRend()

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1068]
@lpugin We have a `TEXTRENDITIONLIST` but the matching methods `TextRenditionListToStr` and `StrToTextRenditionList` are missing.

refers to #1066

**Comment by lpugin** [comment]
What do you mean ?
https://github.com/rism-ch/verovio/blob/5427b908472e21f05dcd1cc1cfb1237f4c877918/libmei/attconverter.cpp#L2383-L2456

**Comment by rettinghaus** [comment]
I meant this one:
https://github.com/rism-ch/verovio/blob/develop/libmei/atts_shared.cpp#L6671-L6699

**Comment by lpugin** [comment]
OK, then you meant `data_TEXTRENDITION`. This is a compound data type in MEI, which is not handled by libMEI. They need to be implemented by hand. See https://github.com/rism-ch/verovio/blob/develop/include/vrv/attalternates.h
Once `data_TEXTRENDITION` is added we can change the code generated by libMEI to have `@rend` of this type.

**Comment by lpugin** [comment]
See https://github.com/rism-ch/verovio/blob/develop/include/vrv/att.h and https://github.com/rism-ch/verovio/blob/develop/src/att.cpp for example converters of alternate data types

**Comment by lpugin** [comment]
This is a feature request, I am closing the issue
