### ISSUE TITLE
format option in JS toolkit

### ISSUE THREAD

**Issue by chfin** [rism-ch/verovio#1072]
It seems like the JS toolkit does not support specifying the input format (i.e., `--format` in the command-line interface). Instead it relies on discovering the input format automatically, which sometimes fails.
Is there another way to specify the input format in the JS toolkit, or can this option be added?

**Comment by lpugin** [comment]
There is an inconsistency. The JS option in `inputFormat` and not `format` as it should be. I changed it and `inputFormat` will be deprecated.

**Comment by chfin** [comment]
Thanks a lot!
