### ISSUE TITLE
Input format discovery fails on some MusicXML files

### ISSUE THREAD

**Issue by chfin** [rism-ch/verovio#1073]
Autodiscovery of the input format fails for some of the MusicXML files for no apparent reason. For example, the MusicXML generated from https://github.com/craigsapp/mozart-piano-sonatas sometimes works without specifying the format (e.g. `sonata15-1.xml`), but sometimes it fails with
```
Warning: Trying to load unknown XML data which cannot be identified.
[Message] Unsupported format
```
(e.g. `sonata01-1.xml`, see attachment [sonata01-1.xml.txt](https://github.com/rism-ch/verovio/files/3190900/sonata01-1.xml.txt))
Adding `--format xml` resolves the issue, so the problem seems to be with the format discovery, not the file itself.

**Comment by lpugin** [comment]
I suspect the root element to be beyond the search limit
https://github.com/rism-ch/verovio/blob/80d135a8f6621968d775a5a7092d25ea14de16f8/src/toolkit.cpp#L170

**Comment by chfin** [comment]
What about using the doctype if available?

**Comment by chfin** [comment]
Maybe add
```
if (initial.find("<!DOCTYPE score-partwise ") != std::string::npos) {
    return musicxmlDefault;
}
```
and analogous versions for `score-timewise` and `opus`?

**Comment by chfin** [comment]
see #1074
