### ISSUE TITLE
docs for python toolkit

### ISSUE THREAD

**Issue by mxordn** [rism-ch/verovio#1075]
I encountered some errors with the new version of verovio, while setting options in the python-toolkit. It seems that the API has changed, but I couldn't find any documentation for it.

E.g.: `vtk.setPageHeight()` isn't availabe anymore.

Could anyone help me out, or maybe I've overlooked something?

**Comment by mxordn** [comment]
Ok I found the option's list from `getAvailableOptions()`

Now I just wonder how to get rid of the filename at the top and the logo ("MEI engraved with Verovio") at the bottom of my svg, when loading a musicxml file. Is there an option for this, that I've overlooked so far?

**Comment by lpugin** [comment]
No, there is no option for this

**Comment by lpugin** [comment]
Sorry, I forgot about it, there is actually one. If you really feel ashamed of having the footer you can pass the option --no-footer ;-)

**Comment by mxordn** [comment]
I already tried --noFooter and --noHeader with the python-toolkit but without success. That was my code:

```
pyToolkit.setOption("noFooter", "True")
pyToolkit.setOption("noHeader", "True")
```

Resizing pageheigth etc. worked well this way. I'm not ashamed of the footer but my pageheight is not that high and the footer is placed across my lowest lyric-line :).

**Comment by mjwalter** [comment]
This issue helped me learn how to set the page height using the Python bindings. However, the docs are still out of date.
