### ISSUE TITLE
music notation not displayed after refresh page firefox 67 android 9.0

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#1077]
![verovio refresh](https://user-images.githubusercontent.com/16167955/58240045-6cec7b00-7d4a-11e9-9d94-edcef97f363e.jpg)

After a few times refreshing the page of the mei-viewer in firefox 67 android 9.0 on my samsung note 9 notation doesn't display.

**Comment by lpugin** [comment]
Looking the console it looks like this is a memory issue and I can reproduce it with Firefox 66. Everything works with Chrome and Opera for me, so it looks like a Firefox issue. I just tried with Firefox beta and it seems to work normally there.

**Comment by sannedubois** [comment]
Thanks Laurent,

indeed firefox beta doesn't have the problem.

Kind regards,
Derk

Op do 23 mei 2019 om 12:35 schreef Laurent Pugin <notifications@github.com>:
