### ISSUE TITLE
Memory requirements?

### ISSUE THREAD

**Issue by edellaq** [rism-ch/verovio#1089]
I'm trying to integrate verovio in a vue.js/Nuxt Single Page Application that I'm working on.
After including it on the project, I wasn't able to complete webpack/eslint processing due to insufficient memory.
I'll go after that later (have other things to take care of before) but meanwhile I wonder if anyone knows how much memory should I expect to be used (Could be that my iMac hasn't enough... ? )

**Comment by lpugin** [comment]
Are you using the NPM package? If yes, the you can specify how much memory you want to allocate to it: https://www.npmjs.com/package/verovio#memory-allocation
The default is 256MB
