### ISSUE TITLE
Warning: "Elements <scoredef> ignored"

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#110]
Hello there,

First, many thanks for the great project.

We are moving our MusicXML collection to MEI, and we would like to use Verovio for browser interactions (in the moment all scores are produced with Lilypond).

We are facing several issues, so a bit of help would be welcome. First: we get the following
warning:
[Warning] Elements <scoredef> ignored
[Warning] Elements <scoredef> ignored
[Warning] Unknown @dur dur '6'
[Warning] Unknown @dur dur '0'
[Warning] Unknown @dur dur '0'
[Warning] Elements <scoredef> ignored
[Warning] Unknown @dur dur '6'

And as a result, the score seems to be transposed in some kind of weird clef. For your convenience, you can look at the content here: http://neuma.huma-num.fr/corpus/motetimprime. The first score (Astier. MI.1 Beati omnes qui timent Dominum) exhibits the issue. We added a link to the MEI file, to the Verovio output, and you can compare it with the Lilypond output.

Note that MEI files are obtained by the MEI XSLT transformation.

Thanks in advance. Please get back to me for any additional detail.

Cheers

Philippe

**Comment by ahankinson** [comment]
Hi Phillipe,

At first glance you appear to be using a very old version of MEI:

http://couch.db.huma-num.fr/neuma/motetimprime:MI0001/mei.xml <http://couch.db.huma-num.fr/neuma/motetimprime:MI0001/mei.xml>

This is claiming meiversion="2010-05"

Are you using the latest version of the musicxml2mei XSLT?

https://github.com/music-encoding/music-encoding/blob/master/tools/musicxml2mei/musicxml2mei-3.0.xsl <https://github.com/music-encoding/music-encoding/blob/master/tools/musicxml2mei/musicxml2mei-3.0.xsl>

-Andrew

**Comment by rigaux** [comment]
No we don't. Let me fix this. Thanx.

**Comment by rigaux** [comment]
Hmmm now we get the following error with the XSLT file. We are using saxon9he.

Error at xsl:value-of on line 1790 column 101 of musicxml2mei-3.0.xsl:
  XPST0017 XPath syntax error at char 0 on line 1790 near {.../beats]/attributes/time/bea...}:
    Cannot find a matching 1-argument function named {http://saxon.sf.net/}evaluate().
  Saxon extension functions are not available under Saxon-HE
Error at xsl:value-of on line 1794 column 61 of musicxml2mei-3.0.xsl:
  XPST0017 XPath syntax error at char 0 on line 1794 near {...ime][1]/attributes/time/bea...}:
    Cannot find a matching 1-argument function named {http://saxon.sf.net/}evaluate().
  Saxon extension functions are not available under Saxon-HE
Error at xsl:value-of on line 3858 column 17 of musicxml2mei-3.0.xsl:
  XPST0017 XPath syntax error at char 0 on line 3858 near {.../beats]/attributes/time/bea...}:
    Cannot find a matching 1-argument function named {http://saxon.sf.net/}evaluate().
  Saxon extension functions are not available under Saxon-HE
Error at xsl:value-of on line 3862 column 63 of musicxml2mei-3.0.xsl:
  XPST0017 XPath syntax error at char 0 on line 3862 near {...ime][1]/attributes/time/bea...}:
    Cannot find a matching 1-argument function named {http://saxon.sf.net/}evaluate().
  Saxon extension functions are not available under Saxon-HE
Stylesheet compilation failed: 4 errors reported

**Comment by ahankinson** [comment]
I think certain saxon extensions aren't available under Saxon HE. I believe Oxygen ships with the commercial versions of Saxon PE or EE, so if you have Oxygen you might try it with that.

**Comment by rigaux** [comment]
OK, we found the version 9 B1 of saxon which includes the necessary extensions. Seems to be much better: we are going to run the conversion again for this collection. More to come probably: many thanks for your help.

**Comment by lpugin** [comment]
Great! Keep us posted
