### ISSUE TITLE
using verovio with React

### ISSUE THREAD

**Issue by uqsbolla** [rism-ch/verovio#1102]
Hi there,

I am writing some OMR software using deep learning in React, and wanting to display the results using verovio.

However, integrating verovio with React, yields a "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory".  The full stack trace is below.

It seems that this issue was also flagged in the "lpugin/verovio-react" github project  (that uses the verovio-dev module).  Supposedly this integration worked until recently.

Any ideas would be greatly appreciated, and hopefully useful (considering the wide use of React.js).

Cheers!

Scott

<--- Last few GCs --->

[38109:0x103000600]   160610 ms: Mark-sweep 1870.2 (1943.0) -> 1870.1 (1944.0) MB, 1692.6 / 0.0 ms  allocation failure GC in old space requested
[38109:0x103000600]   162346 ms: Mark-sweep 1870.1 (1944.0) -> 1869.9 (1912.0) MB, 1735.0 / 0.0 ms  last resort GC in old space requested
[38109:0x103000600]   164156 ms: Mark-sweep 1869.9 (1912.0) -> 1869.9 (1911.5) MB, 1810.1 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x157dfe525879 <JSObject>
    2: set [native weak-collection.js:1] [bytecode=0x157dc0a55f91 offset=62](this=0x157d1c2adab9 <JSWeakMap>,key=0x157dbda8cd01 <Node map = 0x157d4ee41081>,value=0x157d1eb67059 <JSArray[0]>)
    3: node [/Users/scottbolland/Dropbox/visualStudioProjects/test-verovio/node_modules/@babel/traverse/lib/index.js:~87] [pc=0x8b0ab65492a](this=0x157dbe49fa59 <JSFunction traverse (sfi = 0x157d8a655b49)>,n...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::EnsureCapacity(v8::internal::Handle<v8::internal::ObjectHashTable>, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::ObjectHashTable::Put(v8::internal::Handle<v8::internal::ObjectHashTable>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/usr/local/bin/node]
 7: v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/usr/local/bin/node]
 8: v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x8b0ab2a3918
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-verovio@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-verovio@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by lpugin** [comment]
I think the best way around this will be to use a worker. I will try to update the verovio-react example.
In any case, and as you pointed out, the issue duplicates with https://github.com/lpugin/verovio-react/issues/1

**Comment by edellaq** [comment]
Would you also consider also Vue.js as an emerging framework,?
Some examples would be useful too...

**Comment by lpugin** [comment]
This repository https://github.com/lpugin/verovio-app-react gives an example how to use the Verovio App in react.

**Comment by WolfgangDrescher** [comment]
@uqsbolla I had a similar problem and realized that there was a small error in my `webpack.config.js` where i tried using verovio as an `externals`. Its hard to read the built verovio file but im my case it looked like verovio somehow recognized `ENVIRONMENT_IS_NODE` as `true` because of this and therefore verovio tried to import `fs`. Fixing this bug everything worked just fine.

Also see https://github.com/lpugin/verovio-react/issues/1#issuecomment-545071732.
