### ISSUE TITLE
turn@form="upper"/"lower" attribute mixed up

### ISSUE THREAD

**Issue by wergo** [rism-ch/verovio#1112]
Starting from MEI 4.0.0 the `@form` attribute of the `<turn>` element changed from normal/inverted ("norm"/"inv") to `"upper"/"lower"`. 

The "normal" turn is SMuFL U+E567 and is rendered correctly as default in Verovio:
<img width="424" alt="Bildschirmfoto 2019-06-28 um 11 45 32" src="https://user-images.githubusercontent.com/45632600/60333811-4699ab00-999a-11e9-8df8-e84b3afcae42.png">

However, it is rendered in Verovio with the atttribute `form="lower"`, but in the MEI specs and the guidelines it is called `form="upper"` (see https://music-encoding.org/guidelines/v4/content/cmn.html#cmnOrnamentsTurns and https://music-encoding.org/guidelines/v4/elements/turn.html). 

Please correct me, but this needs to be swapped, doesn't it?

Correct should be: 
"upper" -> SMuFL U+E567 (default)
"lower" -> SMuFL U+E568

<img width="414" alt="Bildschirmfoto 2019-06-28 um 11 37 34" src="https://user-images.githubusercontent.com/45632600/60340004-b2840f80-99aa-11e9-8ea2-01bbffc600e6.png">

Test MEI code: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000570801425">
                <score xml:id="score-0000001735307554">
                    <scoreDef xml:id="scoredef-0000001441064676" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001517883020">
                            <staffDef xml:id="staffdef-0000000732589255" clef.shape="G" clef.line="2" key.sig="1f" meter.count="2" meter.unit="2" meter.sym="common" n="1" lines="5">
                                <label xml:id="label-0000000534747154" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section >
                        <measure n="0">
                            <staff n="1">
                                <layer n="1">
                                    <note dur="4" oct="4" pname="a" stem.dir="up" />
                                    <note dur="4" oct="4" pname="a" stem.dir="up" />
                                    <note dur="4" oct="4" pname="a" stem.dir="up" />
                                    <note dur="4" oct="4" pname="a" stem.dir="up" />
                                </layer>
                            </staff>
                            <dir staff="1" place="below" tstamp="1">lower</dir>
                            <turn staff="1" tstamp="1" form="lower" />
                            <dir staff="1" place="below" tstamp="2">upper</dir>
                            <turn staff="1" tstamp="2" form="upper" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by craigsapp** [comment]
Yes, the mappings of the turn types to the graphic symbols should be switched.

This one for a regular turn should be "upper", meaning that the first interval goes upwards:

<img width="172" alt="Screen Shot 2019-06-28 at 2 09 25 PM" src="https://user-images.githubusercontent.com/3487289/60341302-4f947780-99ae-11e9-8f42-3ac701a922ba.png">

(This is usually the most common type of turn).

And the inverted, or lower, turn goes down on the first interval:

<img width="171" alt="Screen Shot 2019-06-28 at 2 09 31 PM" src="https://user-images.githubusercontent.com/3487289/60341322-5fac5700-99ae-11e9-96ee-bfabcb1c6e4d.png">

The reason for the switch in names was probably make the naming convention uniform with mordents.  The term "upper mordent" and "lower mordent" are unambiguous, but  an"inverted mordent" can be either the upper or lower forms depending on what the repertory things is a "normal" mordent is.  Turns do not have this ambiguity, as an inverted turn is always the "lower turn".

**Comment by wergo** [comment]
Thanks for the confirmation and the quick fix!
