### ISSUE TITLE
KeySig change with naturals not showing up

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#112]
%G-2$xFCGD@3/4 =38//$nFCGD@c 1-/4.''E8xC2'B/2B-/1-/2-4.''D8'B

![image](https://cloud.githubusercontent.com/assets/689412/8124575/41bf87fc-10dd-11e5-999e-21d200a41e57.png)

**Comment by mborsodi** [comment]
I think this is related to issue #105

**Comment by lpugin** [comment]
Fixed with 747638a7df7ac63ab886cedc7b571d2a122d70a2
