### ISSUE TITLE
Overlay outputs

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#1120]
Hi Laurent (and all),
Is it possible to show two choices at the same time? Or at least have Verovio render two MEIs with the exact same spacings etc., even if the musical content has slight variations in pitch and rhythm between these MEIs?

**Comment by lpugin** [comment]
What you can do is to make the spacing linear (with --spacing-linear) and then overlay two outputs. You probably also need to make the staff spacing wide enough to make sure it does not change with the content.

**Comment by sonovice** [comment]
Thanks!
