### ISSUE TITLE
Question: Mid-measure barlines?

### ISSUE THREAD

**Issue by yzeon** [rism-ch/verovio#1123]
Is it possible to insert a barline in the middle of a measure? It woud be useful when using time signatures with subdivisions, e.g., 2+3+2/8, etc.

**Comment by rettinghaus** [comment]
Try the barline element.

**Comment by craigsapp** [comment]
Do you mean like this?:

<img width="1127" alt="Screen Shot 2019-07-16 at 7 55 45 PM" src="https://user-images.githubusercontent.com/3487289/61317620-a77f0b00-a803-11e9-9600-2580c4d9ec63.png">

It can be done now by treating every sub-measure as a measure.  Of course, this would not match the intended meaning (which would be suboptimal for analysis purposes). 

The attribute `measure@join` seems most appropriate for indicating the sub-measures.

Alternatively you could probably add `measure@control="false"` to indicate the sub-measure barlines.

https://music-encoding.org/guidelines/v4/elements/measure.html

**Comment by yzeon** [comment]
@craigsapp: yes that's exactly what I mean visually, however, I'd rather not breakup the measures...
@rettinghaus: I actually did try `<barLine form="dashed"/>` but, if I'm not mistaken, it does not seem to respect the bar.thru settings in `<staffGrp>`. Is there a way to have it do so?

**Comment by rettinghaus** [comment]
@yzeon I‘m not too shure about MEI itself, but it’s definitely not implemented in Verovio.

**Comment by yzeon** [comment]
Ok, thank you guys.
So, I started looking into this... basically followed the WIKI to make a fake barline element attachable to a measure using the tstamp property. However, to have it "aligned" between note/chord events I need to give it a slightly smaller tstamp value than the actual beat position. This is obviously a suboptimal solution. Is there any WIKI/tutorial that explains how I could have my custom object aligned properly, avoiding notes/chords/accidentals across the staves?
