### ISSUE TITLE
time signature and cut time

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#114]
When the mei file has the time signature spelled out, but also a symbol defined, they both show up in the music. 
For example in [this file](https://github.com/DDMAL/mei-test-set/blob/develop/complete-examples/MEI/Czerny_op603_6.mei) the score def has `meter.count="4" meter.unit="4" meter.sym="common"`.
In Verovio this then shows up as:
![screen shot 2015-06-17 at 4 11 52 pm](https://cloud.githubusercontent.com/assets/11529868/8217458/96a9a018-150b-11e5-8977-e20b2b86f62d.png)

**Comment by rettinghaus** [comment]
This is a copy of #82 and should have been fixed already.

**Comment by lpugin** [comment]
Indeed. This is still in the develop branch
