### ISSUE TITLE
Remove caesura(?)

### ISSUE THREAD

**Issue by dominikmeixner** [rism-ch/verovio#1140]
I'm not sure what this, I'm guessing it is supposed to be a caesura. When looking at the svg it's drawn by polygon pointers.
```
<g class="system" id="{....}">
<polygon points="976,5501 1516,5141 1516,5006 976,5366 " />
<polygon points="976,5321 1516,4961 1516,4826 976,5186 " />
```

Is there any way to not render them, or do I have to remove them after rendering?
![verovio_svg_caesura](https://user-images.githubusercontent.com/19434297/64363839-dfd7e400-d011-11e9-8336-bd79576a8fca.png)

**Comment by lpugin** [comment]
It is a system divider commonly found in orchestral scores. With piano scores we normally do not have it. It quite likely appears in your case because of an extra useless `<staffGrp>` in your encoding. You need to make sure you have only one `<staffGrp>`. Something like:
```xml
<scoreDef>
  <staffGrp symbol="brace">
    <staffDef/>
    <staffDef/>
  </staffGrp>
</scoreDef>   
```
