### ISSUE TITLE
percussion parts not working

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#115]
Percussion clefs aren't supported yet, it seems. They show up as this right now:
![screen shot 2015-06-17 at 4 24 26 pm](https://cloud.githubusercontent.com/assets/11529868/8217781/55b3efbc-150d-11e5-8025-3d23722bea82.png)
Staff lines are also not working, though. In this case, one line staves. However, any other number of stave lines (other than 5) don't work.

**Comment by lpugin** [comment]
Added in 2178f3afd62a2ecb582b5f1b2eb75fa0d5111c5b
