### ISSUE TITLE
alternate way of encoding key

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#116]
Key signature can also be encoded in mei by using `key.accid` and `key.pname` (pname being the tonic note, and accid being the accidental of that note, if any), but this doesn't work in verovio, yet.

**Comment by rettinghaus** [comment]
`@key.accid` and `@key.pname` won't make much sense without`@key.mode`. So basically there would be necessary a mapping to `@key.sig`. 
What should be done if either `@key.pname` or `@key.mode` is missing (and no `@key.sig` present)?

**Comment by lpugin** [comment]
I opened an issue for this music-encoding/music-encoding#354
