### ISSUE TITLE
up and down octaves in clefs

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#117]
For moving clefs up or down an octave (`clef.dis="8" clef.dis.place="below"`), it seems to only be supported on treble clef right now. When found on bass clefs it doesn't work and it actually shows up like this:
![screen shot 2015-06-17 at 4 24 26 pm](https://cloud.githubusercontent.com/assets/11529868/8218248/c4385d2c-150f-11e5-980c-4c7fd7d2894c.png)

Also, it's not too common, but other displacements don't work at all. (I'm not sure if anything else exists, other than one and two octaves).
![screen shot 2015-06-17 at 4 42 40 pm](https://cloud.githubusercontent.com/assets/11529868/8218263/e29da25e-150f-11e5-9356-00a24dd57e09.png)

**Comment by lpugin** [comment]
Extended in 2178f3afd62a2ecb582b5f1b2eb75fa0d5111c5b

**Comment by donbyrd** [comment]
FWIW, I know of no published examples of two-octave displacement. But it could be useful for things like CMN sketches or transcriptions of synthesized music, where one could go so far above the treble clef (and perhaps below the bass clef) that one-octave displacement would still leave you with a lot of ledger lines,

**Comment by craigsapp** [comment]
I am using it already :-)

![screen shot 2016-09-06 at 3 28 54 pm](https://cloud.githubusercontent.com/assets/3487289/18275324/b0575780-7446-11e6-8f63-98d0fb613868.png)

**Comment by lpugin** [comment]
@donbyrd you are right. It is actually possible to have in MEI even three-octave displacements with ```@dis="22"```. 

However, I left the three-octave displacement unsupported for now because I could not find the corresponding single-glyph clef in SMuFL.

**Comment by craigsapp** [comment]
> It is actually possible to have in MEI even three-octave displacements with @dis="22".

Who snuck that in?  It was hard enough to get agreement on including the 15ma up/down clefs...
