### ISSUE TITLE
Long loading times

### ISSUE THREAD

**Issue by Noroxs** [rism-ch/verovio#1176]
When loading the file [Weber: Der Freyschütze](https://github.com/Freischuetz-Digital/data-music/blob/master/musicSources/freidi-musicSource_A.xml) into Verovio it takes 70 to 100 seconds to load the file/first movement.

Other big files I tested (~37000 lines) only take 2 seconds of loading time.

How is the length of a file related to the load time? 
How could the load time be improved?

**Comment by kepper** [comment]
I wouldn't recommend to operate on that file directly – that's a ~70mb file with 3100 measures of the Freischütz (split across 17 movements), but no single pitch at all. I suggest to read the readme.md of that repo about the setup of these files, and then go for the files in the [ready-for-use](https://github.com/Freischuetz-Digital/data-music/tree/master/ready-for-use) folder…

**Comment by Noroxs** [comment]
This would only help for this specific file.
But imagine a case where I get such a big file and can't use a different one. 

So my questions are still relevant for me.

> How is the length of a file related to the load time?
How could the load time be improved?

**Comment by lpugin** [comment]
This the times I get for loading and rendering the complete content. This looks fairly linear to me. 

Hummel_Concerto_for_trumpet.mei | 6MB
real	0m3.826s
user	0m3.429s
sys	0m0.290s

Brahms_StringQuartet_Op51_No1.mei | 659 KB
real	0m0.468s
user	0m0.396s
sys	0m0.049s

Ahle_Jesu_meines_Herzens_Freud.mei | 60 KB
real	0m0.067s
user	0m0.039s
sys	0m0.022s

So the best way to improve the loading / rendering time is to pass to Verovio only the data you want to render.

**Comment by lpugin** [comment]
@Noroxs any ideas what the problem is for you?

**Comment by Noroxs** [comment]
It's not directly a problem. It's more of an inconvenience. I like to gather some information like. 
Example:
- Number of pages in the document
- Number of measures per page

My intention is to give the user feedback as fast as possible. 
That's why I asked for optimisation methods.
