### ISSUE TITLE
auto-generated headers

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1178]
By default Verovio generates an `pgHead` out of the information in `title` (as far as no `pgHead` is encoded). 
The `--no-header` option supresses the `pgHead` in the output.
Problem is, there is no way to differentiate between encoded and generated headers. I have some files with encoded `pgHead`, others without, but only want the encoded ones to be shown. 

Perhaps the `--no-header` should be changed in a way breaks are handled: 
* `--header auto` the default behavior like now
* `--header encoded` uses only encoded `pgHead`
* `--header none` prints no header at all

**Comment by lpugin** [comment]
Sounds good. Can you make a PR for this? Let me know if you need some guidance.
