### ISSUE TITLE
Clef truncated when the bounding box of the music content is too small

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1183]
In some cases the SVG gets cut off on the lower end.
Example: https://opac.rism.info/metaopac/search?View=rism&documentid=450110080

**Comment by craigsapp** [comment]
Very cut off:

<img width="1207" alt="Screen Shot 2019-11-05 at 9 20 35 AM" src="https://user-images.githubusercontent.com/3487289/68230082-4004eb00-ffad-11e9-99c7-57c4da8114e1.png">

**Comment by rettinghaus** [comment]
What happend there?

**Comment by craigsapp** [comment]
Now they are showing for me:

<img width="1207" alt="Screen Shot 2019-11-05 at 10 53 15 AM" src="https://user-images.githubusercontent.com/3487289/68236520-2a49f280-ffba-11e9-8d11-43e208a1fbe8.png">

**Comment by craigsapp** [comment]
And the SVG image gets cut-off for the case of soprano clefs:

<img width="217" alt="Screen Shot 2019-11-05 at 10 54 37 AM" src="https://user-images.githubusercontent.com/3487289/68236621-5bc2be00-ffba-11e9-838e-6f1a4178ba19.png">

I suspect that notes are checked for calculating the bounding box, but not the clefs (so if there were a low note below the soprano clef, the image would no longer be clipped).

**Comment by rettinghaus** [comment]
Seems to be working in RISM OPAC properly now. There is currently version 2.2.0 in use.
