### ISSUE TITLE
numbering vs order

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#119]
Right now, it looks like Verovio doesn't take numbers into consideration (like `<staff n="1"/>`). 
Can we assume that the mei file will always have the staves, or anything else for that matter, in the right order? 
I've already found examples of where this is not the case (like [this one](http://ddmal.github.io/mei-test-set/complete-examples/Bach_BrandenburgConcert_No.4_II.html), where the harpsichord staves have been switched). It seems counterintuitive to have them in the wrong order, but it does happen.

**Comment by lpugin** [comment]
It does. With your example the content of the staves is properly switched (10 and 9). However, there is indeed a problem with the brace because in this file the order in the scoreDef does not correspond to the order of the staves. This does not make sense to me. It works if you change the scoreDef with:

```
<staffGrp xml:id="P9" symbol="brace" label="Harpsichord" label.abbr="Hpschd.">
    <staffDef n="10" lines="5" clef.line="4" clef.shape="F" ppq="2" key.sig="1s" key.mode="major"/>
    <staffDef n="9" lines="5" clef.line="2" clef.shape="G" key.sig="1s" key.mode="major" xml:id="P9-I9"/>
</staffGrp>
```

I am not sure what we should expect to see if the order of the staves differs from the staffDef one

**Comment by mborsodi** [comment]
Wouldn't you want them to stay in the order that they are numbered in, regardless of what order they're in in the file? Or is there a case where the staves can change order?

**Comment by lpugin** [comment]
If I understand correctly, MEI assumes the order of the scoreDef to be the expected one. It does not have to be the numbered order. Verovio's limitation is that the order of the staves has to correspond. However, they do not have to be all there. So we can have a scoreDef with staves 1, 2, 3, 4, 6, and 5 and then have only staves 6 and 5. This should work, I think.

**Comment by mborsodi** [comment]
Oh ok, so we basically have to assume that the encoding is correct, and if not, that's not Verovio's problem.
When it comes to excluding staves, actually, what Verovio does is somewhat problematic, because it changes staves in the middle of a system, without indicating it. In the excerpt below, measure 5 is staves 2 & 3, and measure 6 is staves 1, 2 & 3.
![screen shot 2015-06-22 at 9 30 50 am](https://cloud.githubusercontent.com/assets/11529868/8282866/7e4b8770-18c1-11e5-98a3-f776cc00bf4e.png)

**Comment by lpugin** [comment]
MEI expects to have a scoreDef in between measure 5 and measure 6. I'll close the issue for now. OK?

**Comment by mborsodi** [comment]
Oh, ok. Thanks

**Comment by lpugin** [comment]
Thanks for reporting this, which needs clarification in MEI.
