### ISSUE TITLE
stems in whole note chords

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#120]
Basically, when there are chords of whole notes, stems appear:
![screen shot 2015-06-17 at 5 34 04 pm](https://cloud.githubusercontent.com/assets/11529868/8219304/10caf6c0-1517-11e5-8a38-3f00b3835807.png)
although, it doesn't happen if there are 2 notes in different layers.

**Comment by lpugin** [comment]
Fixed with b6aae1ac16cf49b258b20c4684598dd9d45f5d77
