### ISSUE TITLE
tie placement

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#121]
I'm sure this is something that's known, but tie placement still has some problems.
Especially problematic is when two tied notes have different stem directions:
![screen shot 2015-06-17 at 5 38 26 pm](https://cloud.githubusercontent.com/assets/11529868/8219384/acdd350a-1517-11e5-9e45-def65e054a75.png)
Also, ties don't seem to work in chordal situations:
![screen shot 2015-06-17 at 5 40 57 pm](https://cloud.githubusercontent.com/assets/11529868/8219427/06e1b5e4-1518-11e5-8690-236ce96bbc7a.png)

There are more examples [here](http://ddmal.github.io/mei-test-set/MEI-test-set/ties-slurs.html)

**Comment by lpugin** [comment]
This is fixed with 71495cd8dae4cfe7b9fbf1a6563d097fe28baad3. However, collision with stem might still occur with short ties depending on the context.

The chord issue seem to be a problem with the MEI encoding. See https://github.com/music-encoding/sibmei/issues/39
