### ISSUE TITLE
Support for mdiv selection

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#122]
In some pieces, like the [Beethoven](https://github.com/DDMAL/mei-test-set/blob/develop/complete-examples/MEI/Beethoven_op.18.mei), there multiple movements, but Verovio only displays the [first one](http://ddmal.github.io/mei-test-set/complete-examples/Beethoven_op.18.html).

**Comment by lpugin** [comment]
The limitation is actually that only the first ```mdiv``` is rendered. I am changing this issue to a feature request for having the ability to select which ```mdiv``` should be rendered. The limitation of displaying only one will remain.

**Comment by lpugin** [comment]
Added in 70acbf514b3b6917c7853922b224ecadca4672cb
