### ISSUE TITLE
How to display a staff on iOS

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1226]
Preliminaries:
1.Following the official tutorial, the mei format staff is displayed on the web page
2.Verovio can be compiled in Xcode

Questions:
Now my purpose is to use this Verovio framework to display mei files on iOS. I don't know how it is related to the above two content. any suggestions? Thank you.

**Comment by lpugin** [comment]
@Noroxs added the `./bindings/iOS/` and it would be good to have a hello-world example how to use it. @Noroxs could you add one?

**Comment by Noroxs** [comment]
I quickly created a small example app how to integrate and use Verovio in an iOS app.
I hope this will help you.
https://github.com/Noroxs/VerovioExample

**Comment by lpugin** [comment]
I added the link to the wiki

**Comment by yangyangnote** [comment]
thank you very much for your help 😊
