### ISSUE TITLE
Xcode 9.1 / Swift 3.0 compilation problem

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1233]
Thank you very much for writing this example. I successfully compiled in Xcode 11 / Swift 5.0 according to your method.
The problem now is that the compilation is not successful under the environment of Xcode 9.1 / Swift 3.0, is there any solution?
Because most of my code is now in this environment
Is there any compatible way?

Neither file can be opened
<img width="272" alt="屏幕快照 2019-12-13 下午3 21 22" src="https://user-images.githubusercontent.com/19338570/70783013-5596dd00-1dc3-11ea-9231-b50432216416.png">

**Comment by lpugin** [comment]
I seems that the example uses Swift 5.0. I am sorry, but this issue here is not relevant.
