### ISSUE TITLE
grace note alignment in layers

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#124]
In two parts, they align well rhythmically:
![screen shot 2015-06-19 at 10 25 54 am](https://cloud.githubusercontent.com/assets/11529868/8255375/957dce90-166d-11e5-8bf1-31a227012608.png)
but in layers:
![screen shot 2015-06-19 at 10 25 45 am](https://cloud.githubusercontent.com/assets/11529868/8255382/9f48ddc0-166d-11e5-947e-51c8c0ac6991.png)

**Comment by lpugin** [comment]
Fixed with 018d46e3b8ffc6acc300fc6bfa619dd8d552fdec
