### ISSUE TITLE
npm won't upgrade to 2.3.4-1

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-ch/verovio#1252]
It seems that the verovio version on npm tagged with `2.3.4-1` is not satisfied when using `yarn upgrade`/`npm update` with a usual version constraint like: 

```json
{
    "dependencies": {
        "verovio": "^2.3.3"
    }
}
```

To prevent this i suggest to not to use version tags with dashes (on npm). Check out https://semver.npmjs.com/, https://docs.npmjs.com/about-semantic-versioning.

For anyone experiencing the same problem that verovio is not upgraded to th lastest version. I fixed it with `"verovio": "^2.3.3||2.3.4-1"`.

**Comment by lpugin** [comment]
Thanks for the tip. We can make a new 2.3.5. Would this help?

**Comment by WolfgangDrescher** [comment]
Just for me not necessary at the moment, since npm allows you to also load a specific version (`"verovio": "2.3.4-1"`) thank you. But if you keep this in mind for the next release people can rely to automated upgrades in future.

**Comment by lpugin** [comment]
Fixed with https://github.com/rism-ch/verovio/releases/tag/version-2.3.5
