### ISSUE TITLE
Emit JavaScript events on a toolkit instance

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-ch/verovio#1253]
It would be useful if the verovio toolkit in JavaScript would emit some events to improve a better integration for developers within their apps. In my case i want to implement a simple loading message and catch an event (e.g. `onload`) as soon as verovio finished parsing a MEI file and rendering it into svg.

I know that im not the first one with this feature request since @craigsapp already had this idea in  #342 for better error handling.

I suggest events like the following could be useful:

* initialized / created (toolkit instance)
* load
* startLoading / startRendering
* endLoading / endRendering
* error
* fileParsed
* statusChanged
* pageChanged
* zoomChanged

An event system like @ahankinson is suggesting in https://github.com/rism-ch/verovio/issues/342#issuecomment-257626310 would be a good solution. Altough i never implemented a custom event system on JavaScript objects myself this StackOverflow answer seems to be a good resource for inspiration: https://stackoverflow.com/a/24216547

**Comment by WolfgangDrescher** [comment]
An alternative could be that the verovio toolkit returns promises on all methods so we can use `async` functions and `await` the promise.

I saw that @craigsapp built a wrapper interface around the toolkit for the humdrum viewer which wraps all verovio toolkit methods into promises: https://github.com/humdrum-tools/verovio-humdrum-viewer/blob/5d44d0771f92508b79b83b3c98145cdde27b9276/scripts/verovio-interface.js#L289.

Using something like this or an event system would help a lot to build nice JavaScript apps around the verovio toolkit:

```js
verovioToolkit.renderToSVG(1, {}).then(() => {
    console.log('Page rendered');
});
```

**Comment by lpugin** [comment]
Here are some thoughts about this idea. I am not too sure about the usefulness to have the JS toolkit emitting events since it is essentially synchronous. Basically, the browser will not do anything until Verovio has finished its task (e.g., render a page), so having an event triggered at the end does not bring much. 

(However, looking back at the JS toolkit, one possible improvement could be to make it a ES6 class. This would not bring further functionalities but maybe it would be good to change it.)

What would be more useful I think would be to wrap Verovio in a web worker. This is what it done for the App (https://www.verovio.org/editor). See the vida code for the worker stuff https://github.com/DDMAL/vida.js/blob/master/verovioWorker.js
One possibility would be to make this more generic and make all methods of the JS tookit having one single parameter being a JSON object and all returning a JSON object. Then this worker would call the method dynamically, with something like:
```
result = vrvToolkit[messageType](messageParam);
sendBack(messageType + "-ok", ticket, result);
```
This means that un-wrapping the parameters contained in the JSON object and wrapping the result would need to be done in the JS toolkit class (instead of doing it in the worker as in the vida code). Then, the message returned by the worker (including the JSON object containing the result, such as the SVG or anything else) would be the event in the application using the worker.

**Comment by lpugin** [comment]
Closing since there are no reactions

**Comment by WolfgangDrescher** [comment]
Sure if everything is synchronously there is not much point to emit an event at the end. Still to adopt to modern JS programming techniques it would be nice to use them in a "modern" way we write JavaScript today. So keeping a Promise based version in mind may be for a 3.0 release would be a good idea. Im not sure how good this is possible with the emscripten build you are currently using.

I think using a ES6 class could be a good first step. I even already tought to make a pull request for this. But since on https://www.verovio.org/javascript.xhtml there is a compatibility list with IE on it is was not sure what browser support verovio is guaranteeing (https://caniuse.com/#feat=es6-class). Sure we could then use webpack again to build a compatible JavaScript version of it, but since ES6 classes are only syntactic sugar for the prototype notation you are already using it would only be beneficial for setting up a modern an readable code base (which i think is good!).

Also i would consider a check if verovio is running in a JS or in a Node.js context before calling `module.exports` like i suggested in https://github.com/rism-ch/verovio/issues/1199#issuecomment-558570744.

The web worker approach i have seen before in your react example but i have not tested it myself but its sound like a good idea. I will check the vida.js verovioWorker since i did not completely understand your suggestion with the JSON object.

I think it would really help people out if in the official verovio documentation would have sections where it is explained how to import verovio in a modern setup with Vue.js oder React instead or additional to the jQuery examples. For example like my setup as a webpack external (altough with newer verovio versions it does not seem to work anymore): https://github.com/rism-ch/verovio/issues/1199#issuecomment-558579890

**Comment by WolfgangDrescher** [comment]
@lpugin I did some more research and came up with the following solution for the web workers. It is not perfect yet, but as a first draft i think it could help to show the direction where this feature can be going.

https://gist.github.com/WolfgangDrescher/63d24cd755e648afa998270dd3d7c283

The idea is that you can use an instance of VerovioToolkitProxy as kind of a reflection class that behaves exactly the same way as a toolkit instance itself. If a method is called a magic function `get` of the proxy will send a message to the worker with all relevant infos like method name and arguments. In the worker the verovio methods are handled and an event is emitted back to the proxy class where a listener then will resolve the asynchronous Promises.

E.g. with the toolkit you would use something like `toolkit.redoLayout()` with the proxy you can use `await toolkitProxy.redoLayout()`within an async function. I think especially catching the special onRuntimeInitialized event inside the worker should be improved.

At the end i sadly could not get it to work because a `[Message] Unsupported format` was thrown somewhere in the toolkit (i know that the used MEI file works in my normal verovio setup). I also had to remove the `module.exports` at the end of the toolkit (verovio-npm-end.js) because this command is not available in a worker.

I also tried to rewrite the verovio toolkit as a EM6 class and use the factory pattern to return and export the toolkit, but i could not get it to work. Somehow the `./buildToolkit -H` command will not add my changes in verovio-npm-start.js and verovio-npm-end.js to the build/verovio-toolkit.js file. Any ideas what i did wrong there? I was following https://github.com/rism-ch/verovio/wiki/Building-instructions.

I would like to contribute this with a pull request as soon as it is ready but i think the logic of the verovio-toolkis.js should be reorganized a bit to make this file flexible for a «js-only» usage, for node environments, webpack and with a worker.

**Comment by lpugin** [comment]
Looks promising. Two quick comments to your issues

MEI file not loading: make sure you fetch it is a string and not as XML. What you get depends on how it is served, to it is not impossible to have some code running on a server and not on another.

The npm version uses the webassembly version, so you need to pass `-w` to the buildToolkit call for it to trigger the npm start|end to used.

**Comment by WolfgangDrescher** [comment]
Hm, actually `const response = await fetch('file.mei'); const data = await response.text();` should return the file content as a string. Pasting the file content directly as a string I did also get the same error. I think there are other issues that fail when using verovio in a worker. I can setup a repo for this to make it easier to debug if needed.

Executing `./buildToolkit -H` i got `ERROR: BINARYEN_ROOT must be set up in .emscripten`. Can you give me your .emscripten config and where it is located? Is `which emscons` the correct command to get the binary root?

**Comment by lpugin** [comment]
Verovio works as a worker. For sure with `importScripts('https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js');` so the issue must be somewhere else. 

I have no specific `.emscripten` config. It points to the directory when I installed the emsdk
```
NODE_JS = '/Users/laurent/tools/emsdk/node/12.9.1_64bit/bin/node'
LLVM_ROOT = '/Users/laurent/tools/emsdk/upstream/bin'
BINARYEN_ROOT = '/Users/laurent/tools/emsdk/upstream'
EMSCRIPTEN_ROOT = '/Users/laurent/tools/emsdk/upstream/emscripten'
TEMP_DIR = '/var/folders/wd/7vt44b8n035_qp6k8mt55rdr0000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
To get the path setup, I do `source ~/tools/emsdk/emsdk_env.sh`. I currently have version 1.39.6 installed.

**Comment by musicEnfanthen** [comment]
@WolfgangDrescher  Not sure if this helps, but you can have a look at the Travis CI files for the emscripten logic ([./travis/ci_precache.sh](https://github.com/rism-ch/verovio/blob/develop/travis/ci_precache.sh) and [./travis/ci_build-toolkit.sh](https://github.com/rism-ch/verovio/blob/develop/travis/ci_build-toolkit.sh)).

Removing all other things going on there, it does the following:

(from `.travis.yml`)
```
# in travis.yml these guys are called EMSCRIPTEN_{...}, renamed here for clarification
const EMSDK_REPOSITORY = "https://github.com/emscripten-core/emsdk.git"
const EMSDK_DIRECTORY = "emsdk"
```

(from `../travis/ci_precache.sh`)
```
# be sure to be on the root of verovio repo
# Cloning emscripten to a new subdirectory ./emsdk (
# CAUTION: this will give you a nested ./emsdk/emsdk dir structure
git clone $EMSDK_REPOSITORY $EMSDK_DIRECTORY

# install emscripten to ./emsdk/emsdk
cd $EMSDK_DIRECTORY
./emsdk install latest

```

(from `../travis/ci_build-toolkit.sh`)
```
# activate and source emscripten tools
cd $EMSDK_DIRECTORY # not necessary if you are already in this directory from the previoius step
./emsdk activate latest
source ./emsdk_env.sh

# go back to root
cd ..

# go to verovios emcsripten(!) subdirectory (./emscripten from the root)
cd ./emscripten

# from here you can call the buildTookkit with options ( I leave them here for orientation)
# build toolkit depending on build target
if [[ "$BUILDTARGET" == nohumdrum ]]; then
    echo "Building toolkit without humdrum"
    ./buildToolkit -c -H
    # will create build/verovio-toolkit.js*

elif [[ "$BUILDTARGET" == light ]]; then
    echo "Building toolkit without humdrum as light version"
    ./buildToolkit -c -H -l
    # will create build/verovio-toolkit-light.js* 

elif [[ "$BUILDTARGET" == wasm ]]; then
    echo "Building toolkit without humdrum as wasm"
    ./buildToolkit -c -H -w
    # will create build/verovio*wasm*

elif [[ "$BUILDTARGET" == default ]]; then
    echo "Building default toolkit (with humdrum)"
    ./buildToolkit -c
    # will create build/*-hum.js*

else
  echo "No BUILDTARGET matched: $BUILDTARGET"
  exit 1
fi
```

**Comment by lpugin** [comment]
@WolfgangDrescher any progress on this?

**Comment by WolfgangDrescher** [comment]
Im still stuck getting verovio to work as a worker. But maybe im trying with the wrong build. Is it relevant to understand more how the different versions of verovio are built? As you wrote here before the npm version is built with WebAssembly. But in the emscripten of the main repository a saw that the `./buildToolkit` will also build a non npm version. Whats the difference?

I set up a repository to get some help about the error message in the JavaScript log.
https://github.com/WolfgangDrescher/verovio-worker

With `importScripts("verovio-toolkit-2.5.0.js");` (this is a copy of the npm version) i am getting a lot of unsupported options errors like`Unsupported option 'height'` and later a `function signature mismatch at wasm-function[59]:0x5916`.

With `importScripts('https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js')` i get also the unsupported options error plus `TypeError: Cannot read property 'ptr' of null`. It seems like the `this.ptr` is not available in

```
verovio.toolkit.prototype.setOptions = function (options) {
	verovio.vrvToolkit.setOptions(this.ptr, JSON.stringify(options));
};
```

Is it in your intention @lpugin that in best case the verovio npm package can be used in default mode or as a worker in the same file without using an additional file with the importScripts('verovio.js') command?

In anyway i think rewriting the wrapper logic for verovio file similar like i am using in `https://github.com/WolfgangDrescher/verovio-worker/blob/master/verovio-toolkit-proxy.js` would be a good idea. So we can export the toolkit, the module or proxy as a node module or assign them to the global variable scope.

I had problems using the `this` variable in https://github.com/WolfgangDrescher/verovio-worker/blob/master/verovio-worker.js for example with this.addEventLIstener() in the worker. I could solve it with removing `this` or replacing it with `self` i think. Using a factory we can pass the root object (window, this, self) dynamically.

**Comment by lpugin** [comment]
I can explain you the details about the various builds, but I am not sure it is necessary. Please have a try with this, which is quite minimal
https://gist.github.com/lpugin/62f93a4dec9a9dfa53baf8b843250216

It uses the WASM build. The NPM is the same build, but simply wrapped with `verovio-npm-start.js` and `verovio-npm-end.js`.  

We can see what to change, but we need to make sure there is not a problem somewhere else first. It seems to me that one advantageous side effect of the worker it that you do not need to have all the Verovio WASM code in the module. It would be nice to keep that if we make and NPM module work as a worker, so it might need to be a different module. But this is all beyond my knowledge of this....

**Comment by lpugin** [comment]
I updated the gist to make it even simpler and use `apply` as in your example. It passes the toolklit object, maybe this is what was missing in your code?

**Comment by WolfgangDrescher** [comment]
Ah yes, thank you! I missed to pass the verovioToolkit instance to the apply method. Fixed it in https://github.com/WolfgangDrescher/verovio-worker/ and it seems to work well now with 2.5.0 npm version and `https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js`.

Still getting the `Unsupported option 'height'` logs, but im pretty sure that this is an irrelevant problem for the worker.

So basically i think i could get this to work now. But im still not sure what the best design setup will because im really not into the whole WASM and emscripten thing.

What do you think, should i try to implement it into verovio-npm-end.js? Or maybe it would be cleaner to create an new verovio-proxy.js and verovio-worker.js and include them into the `buildToolkit` command?

`if (typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope)` seems to be pretty reliable to check if we are in a worker context or not. So maybe it could really be possible to create the worker itself in the npm package. But then in the worker context the toolkit will be initialized in the index.js file its self of the npm package and is not user controlled (which does not need to be bad). 

Alternatively the npm version could export additionally the VerovioToolkitProxy and we let the user write the worker themselves. But i would prefer to ship the worker as well since it must `postMessage` with the data so VerovioToolkitProxy can understand it.

What do you think to wrap all into a factory? Maybe even build the js package with webpack in the `buildToolkit` command to ensure backwards compatible browser support for EM6 classes and the Proxy class? Im not sure if it will work in IE 11 (I do not really care about that but maybe Verovio or RISM does).

Maybe i can open a WIP pull request.

**Comment by lpugin** [comment]
Following comments about the code size being problematic, my impression was that one advantage of having an worker (beside the fact that it would avoid the interface to freeze) would be that it would not necessary require the verovio (wasm) code to be in the npm package. However, this would mean a distinct npm package for the worker. One option would be to have it using the verovio code hosted on verovio.org (as in example), or to pass a custom url, or even use the verovio code from the npm package. But I do not not if any of these are actually possible.

Regarding the refactoring the toolkit into an ES6 class, I think this would be OK. I think backward compatibility with IE 11 is not really necessary at this stage.

**Comment by lpugin** [comment]
@WolfgangDrescher I looked at your code in https://github.com/WolfgangDrescher/verovio-worker This looks excellent. In runs for me, except on Safari. It says
```
[Error] Unhandled Promise Rejection: TypeError: Type error
	postMessage (verovio-worker.js:36)
	(anonymous function) (verovio-worker.js:36)
	promiseReactionJob
```
Any ideas?

**Comment by WolfgangDrescher** [comment]
I did not check Safari before but also get an error:

`failed to asynchronously prepare wasm: Error: WebAssembly.Module doesn't parse at byte 52: references are not enabled, in function at index 75`

But it does not seem to be worker specific since i get the same error in my index.html where i initialize verovio with the current default setup. I will have at closer look at this later this week.

I hope to find some time to rethink the js build process and split the worker, proxy, toolkit, module and WASM related things separated in different files that can be imported by each other. And then build it with webpack for example.

**Comment by lpugin** [comment]
This is another bug in Safari that was fixed recently. It no longer appears in the latest version (13.0.5). Which version of Safari are you using?
(At some point I tried to find a workaround with a684415b19e6a5d9af0694403ec57b460fbbd55f but maybe that did not work)

**Comment by WolfgangDrescher** [comment]
Im using Safari version 13.0.5 (macOS). Just be sure that im really using the lastest version from npm i did install verovio as a node module. Updated im my demo: https://github.com/WolfgangDrescher/verovio-worker
Did not change anything, still the same error message.

**Comment by WolfgangDrescher** [comment]
I am currently doing some refactoring for the JS related code. Is there a reason why in `~/emscripten/npm/` the node_modules folder is commited with some dependencies (fs, inherits, path, process, util)? Otherwise i would do my changes directly in the npm folder.
Since i do not know you deployment and CI/CD there will be some changes in your pipelines for sure.

**Comment by lpugin** [comment]
It seems that the change in a684415b19e6a5d9af0694403ec57b460fbbd55f is still necessary for the wasm build to work on Safari. It was made after the latest release (2.5.0), which is why it does not work with the node module, but only with the develop branch.

**Comment by WolfgangDrescher** [comment]
I opened a WIP pull request for this: https://github.com/rism-ch/verovio/pull/1315
