### ISSUE TITLE
"getTimeForElement" not working in iOS (2) 

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1255]
@lpugin Sorry, my description is not very accurate in #1248 , and my English is not good.
The problem is simple, it has nothing to do with the midi player

Is what I now pass the

vrvToolkit.getElementsAtTime (1200)

Cannot get

{
  "notes": [
    "d414233e89",
    "d414233e315"
  ],
  "page": 1
}
Similar data
Similar writing, I call other methods, and it is easy to get the data.

I call this method through Objective-C in iOS.
I suspect the problem is related to #261  ？

Thank you for your answer!

**Comment by yangyangnote** [comment]
This is the code call in Objective-C:
```
- (NSString *)getElementsAtTime:(int)time{
    std::string elements = self.toolkit->GetElementsAtTime(1250);
    return [NSString stringWithCString:elements.c_str() encoding:NSUTF8StringEncoding];
}

```

**Comment by lpugin** [comment]
What do you get when calling `renderToTimemap()`?

**Comment by yangyangnote** [comment]
when I calling renderToTimemap(), I returned 

```
[
	{
		"tstamp":	0,
		"qstamp":	0.000000,
		"tempo":	96,
		"on":	["note-0000000286731928"]
	},
	{
		"tstamp":	1250,
		"qstamp":	2.000000,
		"on":	["note-0000002001307050"],
		"off":	["note-0000000286731928"]
	},
	{
		"tstamp":	2500,
		"qstamp":	4.000000,
		"on":	["note-0000000426203559"],
		"off":	["note-0000002001307050"]
	},
	{
		"tstamp":	3750,
		"qstamp":	6.000000,
		"on":	["note-0000000324991579"],
		"off":	["note-0000000426203559"]
	},
	{
		"tstamp":	5000,
		"qstamp":	8.000000,
		"on":	["note-0000001910905006"],
		"off":	["note-0000000324991579"]
	},
	{
		"tstamp":	6250,
		"qstamp":	10.000000,
		"on":	["note-0000001594511777"],
		"off":	["note-0000001910905006"]
	},
	{
		"tstamp":	7500,
		"qstamp":	12.000000,
		"on":	["note-0000002070127806"],
		"off":	["note-0000001594511777"]
	},
	{
		"tstamp":	8750,
		"qstamp":	14.000000,
		"on":	["note-0000000690649569"],
		"off":	["note-0000002070127806"]
	},
	{
		"tstamp":	10000,
		"qstamp":	16.000000,
		"off":	["note-0000000690649569"]
	}
]

```

**Comment by yangyangnote** [comment]
I added the method based on this project https://github.com/Noroxs/VerovioExample

And mei File example:

[03爷爷的大钟.mei.zip](https://github.com/rism-ch/verovio/files/4051901/03.mei.zip)

**Comment by lpugin** [comment]
When testing with your file in the MEI viewer I get
```
{
  "notes": [
    "note-0000000286731928"
  ],
  "page": 1
}
```
with the latest version of Verovio. What version of Verovio do you link to? What does `getVersion()` return? It would be surprising for this to be an iOS specific issue since the timemap is correct.

**Comment by yangyangnote** [comment]
1.I got data through getVersion () as 2.3.3- [cocoapods]
2.I also modified 10d549c in my local project
3.I suspect the problem is related to # 261?

**Comment by lpugin** [comment]
Could you please rebuild Verovio with a fresh checkout of the develop branch? Thanks.

What do you mean related to #261? (This issue was closed a long time ago and was about the fact that some methods were available only in the JavaScript built.)

(It is still not clear what your problem is. What does `std::string elements = self.toolkit->GetElementsAtTime(1250);` return? Or does it crash?)

**Comment by yangyangnote** [comment]
When I call `std :: string elements = self.toolkit-> GetElementsAtTime (1250)`, only **{}** is returned, there is no data in it.That is the **problem**

I'm still trying to update the version, I don't know if it can solve this problem, this method is very important to me.

**Comment by lpugin** [comment]
I just tried with the develop branch and it works for me. I get 
```
{
	"notes": [
		"d414233e89",
		"d414233e110",
		"d414233e315",
		"d414233e333" 
	],
	"page": 1 
} 
```
Make sure you use the latest version from the develop branch of Verovio, that the file is properly loaded, and that there are some notes at the time being queried.

**Comment by yangyangnote** [comment]
@lpugin With the updated version, I have solved the problem, thanks!
