### ISSUE TITLE
How to display a staff on React-Native

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1256]
I think there are already examples of React at https://github.com/lpugin/verovio-app-react, but React-Native is still different from React
I am trying to port but it is a bit difficult
Is there a React-Native demo?
If I succeed, I will submit the demo.

Thank you !

**Comment by lpugin** [comment]
Thanks for submitting a demo.

**Comment by knoguchi** [comment]
Is there a React Native demo?
