### ISSUE TITLE
NPM build fails with "invalid opcode" in WebAssembly

### ISSUE THREAD

**Issue by pfefferniels** [rism-ch/verovio#1257]
I am not sure if this is actually a problem of verovio, but I'd like to report that on my machine as well as on an Amazon Beanstalk instance (Linux 4.12.0, Node 10.17.0), the NPM build is failing with a bunch of

`failed to asynchronously prepare wasm: CompileError: WebAssembly.compile(): Compiling wasm function "wasm-function[5814]" failed: Invalid opcode (enable with --experimental-wasm-sat_f2i_conversions) @+1781919
`

**Comment by lpugin** [comment]
Make sure you use Node 12 or newer
