### ISSUE TITLE
Problem with adding voices in one file/page

### ISSUE THREAD

**Issue by EvgenyM** [rism-ch/verovio#1260]
Hi Team,

We are experiencing a strange behavior of Verovio in case additional voice is added in the middle of the page. The number of voices increases from the third line. At the same time, the SVGs contain pre-allocated space on lines 1 and 2. One can also see the barline artifacts left.

**PDF content**
![image](https://user-images.githubusercontent.com/718183/72359239-38b93680-36ee-11ea-8983-a238b9d24a8f.png)

**SVG (rendered by Verovio from MEI)**
![image](https://user-images.githubusercontent.com/718183/72359287-4cfd3380-36ee-11ea-9e36-226c7d57c49b.png)

Please find the MEI  attached (zipped).
[haendel-deutsche-arien-p001.mei.zip](https://github.com/rism-ch/verovio/files/4060116/haendel-deutsche-arien-p001.mei.zip)

**Comment by ndubo** [comment]
I would suggest erasing the `@visible="false"` in staff 2 of your file. Verovio takes care of empty staves by itself. This would be more in sync with the principles of dynamic layout. The result could look like this:
![Händel_Arie](https://user-images.githubusercontent.com/33256891/72516416-eabd4380-3851-11ea-9ad8-82fe10557547.jpg)
You still have the staff for the soprano in the first system, but this makes sense anyway.
