### ISSUE TITLE
Color note with noteid  in iOS 

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1264]
@lpugin Now i have got noteid and now I want to make him red.

By https://www.verovio.org/tutorial.xhtml?id=topic09 ,I know this sentence needs to be executed

`$("#" + noteid).attr("fill", "#c00").attr("stroke", "#c00");`

In the iOS environment,I need to find a way to try to change elements of html using webkit?
Is there any other better way?

**Comment by lpugin** [comment]
What you can do is use `@color` on `<note>` before loading it into Verovio. Something like:
`<note color="red"/>`
For manipulating the SVG in iOS, this is unfortunately not the right place to ask. As you pointed out, this is an iOS / Webkit issue.
