### ISSUE TITLE
ignore nested beams

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#127]
when an MEI file uses nested beams (which is usually incorrect), ignore the inner beam

**Comment by lpugin** [comment]
It would not be difficult to have it handled properly. But since this is incorrect, do we really want this? Or should we make this valid?

**Comment by kepper** [comment]
it neither is nor should be valid; however, it could be useful if Verovio would break nicely and just ignore the inner beam (even though I wouldn't have spotted an encoding error then…)

**Comment by lpugin** [comment]
It should indeed be more polite.

**Comment by pe-ro** [comment]
Nested beams can't be ignored in all cases.  In particular, a beamed group of grace notes can fall under a beam that groups a set of "regular" notes, as exemplified in issue #147.

I've been thinking it would be useful to create a new element -- `gruppetto` -- for beamed grace notes. The name isn't technically correct, but may be close enough.  With this new element, it would be possible to allow `beam/gruppetto` and disallow `beam/beam`.

**Comment by donbyrd** [comment]
I don't think grupetto is a good name -- if I remember correctly, people used to call tuplets "grupettos" -- but otherwise I like pe-ro's idea.

**Comment by lpugin** [comment]
Allowing nested beams seems appropriate to me, unless we can find a better name. Alternatively, we could add a ```@grace``` on beam.

**Comment by pe-ro** [comment]
I have reservations about the name too.  Care to suggest a different one?



__________________________
Perry Roland
Music Library
University of Virginia
P. O. Box 400175
Charlottesville, VA 22904
434-982-2702 (w)
pdr4h (at) virginia (dot) edu
________________________________

**Comment by lpugin** [comment]
Sorry, I think I was not clear. I meant allowing nested beams without adding a new element with a different name seems fine to me. Why we would want another name? We do not have another one for grace notes anyway.

**Comment by rettinghaus** [comment]
Seems to me allowing ``@grace`` on ``beam`` would be the best approach here. 
Thus it still would help to spot encoding errors with verovio.

**Comment by pe-ro** [comment]
Creating a new element would make it easier to control the nested beam situation than `@grace` on `<beam>`.  Nested beams would be disallowed, but `beam/grupetto` (or whatever it's called) would be permitted, instantly stopping any encoding errors.  The one problem is with the interaction of `<beam>` and `<grupetto>` where either one crossed a measure boundary.  In that case, we're back to `<beamSpan>`, but that means we'd also need a `<grupettoSpan>`.  How likely is this to occur?

**Comment by lpugin** [comment]
One new element sounds already over the top to me, needless to say what I think of ```grupettoSpan``` ;-)

**Comment by pe-ro** [comment]
I don't think adding `@grace` to `<beam>` solves anything, so let's leave well enough alone.

**Comment by pe-ro** [comment]
But we have to be clear that nested beams ARE allowed, notwithstanding Jo's comments to the contrary.  ;-)
