### ISSUE TITLE
Explicit x position

### ISSUE THREAD

**Issue by davidrizo** [rism-ch/verovio#1274]
MEI allows the encoding of an explicit horizontal position using the @x attribute.
(e.g.
`<note dur="semibrevis" pname="d" oct="5" x="100"/>
<dot form="aug" x="120"/>
`
Is there any option in Verovio to use it?

Thanks

**Comment by rettinghaus** [comment]
Verovio doesn't support `@x` nor `@y` at the moment. But you could achieve this through SVG post processing. 

From your other issue connected with this one perhaps you are looking for some of these options:
* `--min-last-justification`
* `--min-measure-width `
* `--spacing-linear`
* `--spacing-non-linear`
* `--use-facsimile`

**Comment by lpugin** [comment]
This would be a good opportunity to finalize the page-based module. It is still a customization used internally in Verovio but would fit perfectly well use-cases such as OMR output. We should discuss this outside github issues.
