### ISSUE TITLE
-f and -t option long-form names

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1278]
The option `-f` has the long name `--format`, and the option `-t` has the long name `--type`.  

These are actually incorrect, and instead the long forms should be:

* `-f` &rarr; `--from`
* `-t` &rarr; `--to`

Either the correct long forms should be added as aliases for `--format` and `--type`, or they should be the new long forms for these options, and format/type versions should be deprecated (emit a warning when used for the next few years).

**Comment by lpugin** [comment]
I do not understand why travis is failing... https://travis-ci.org/rism-ch/verovio

**Comment by musicEnfanthen** [comment]
Seems that `main.cpp` in Travis is still referring to the old options. Since you have actually changed `main.cpp` acoordingly to `toolkit.h`, it could be some caching problem with Travis?

Maybe try to delete the cache in the Travis GUI (Burger Menu at the upper right: "More options": Cache).
