### ISSUE TITLE
consider @staff when calculating layers

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#128]
when a note is moved to an adjacent staff using the staff attribute, that staff doesn't consider the additional "layer" when calculating stem directions

**Comment by lpugin** [comment]
Do you have an example?

**Comment by kepper** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/2078563/8674894/1a4170aa-2a41-11e5-81f2-f95c8f930b24.png)
There are some of these notes in the existing beethoven prototype, included in variant g on page 17. Look for note@xml:id="e5bd15640-87a7-4fa7-a153-faf09112e727" in the encoding, for instance.

**Comment by lpugin** [comment]
This should be fixed once the @stem.dir for notes within beam is taken into
account

**Comment by lpugin** [comment]
Fixed for now with stem.dir?

**Comment by kepper** [comment]
yes, stem.dir seems to solve the problem. However, I wonder if verovio should handle the situation in the same way when no stem.dirs are provided. Could be done quite easily with a preprocessing xslt, but this can be discussed when the ticket gets reopened…
