### ISSUE TITLE
Compiling verovio on CentOS fails

### ISSUE THREAD

**Issue by frakel** [rism-ch/verovio#1285]
Hi, 
I am not able to successfully compile verovio (on branch develop) on a CentOS Linux 7.5.1804 (Core) machine. After `cmake .` the `make` failes immediately with the following error:
```
[  0%] Building CXX object CMakeFiles/verovio.dir/main.cpp.o
c++: error: unrecognized command line option '-std=c++17'
make[2]: *** [CMakeFiles/verovio.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/verovio.dir/all] Error 2
make: *** [all] Error 2
```
The first remedy I applied was updating the gcc compiler, which is now
```
# gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
```
But *make* produces still the same error. BTW verovio builds perfectly on my Windows machine where I have gcc 7.4.0 installed.

Has anyone successfully built verovio on Red Hat or CentOS?

Any help or comment is very much appreciated.

Thank you,
--franz

**Comment by craigsapp** [comment]
I had a similar problem when compiling for javascript:  the long-term solution is to update the compiler to a more recent version (but I do not know what version would be necessary).

The short-term solution would be to change from  c++17  to c++11 in the tool/CMakeList.txt file:

```
    add_definitions(-std=c++17)
```

to

```
    add_definitions(-std=c++11)
```

Then run `cmake .` again, and there should not be a problem.



c++17 seems mostly supported in GCC 8:
     https://en.cppreference.com/w/cpp/compiler_support
but maybe there is not yet a compile variable for using c++17 in that version of GCC.

Using c++11 should work until @lpugin merges the develop-beams branch that he is currently working on, which utilizes newer features of C++.

Here is the commit where c++17 was added:
      https://github.com/rism-ch/verovio/commit/71ccc0e65b6d304836959e44bca6f62544263f55
so you can see there where the 17 might need to be changed to 11 for various target platforms.

For the javascript build script, I added an option to the buildToolkit script to choose c++11 for compiling:
     https://github.com/rism-ch/verovio/commit/7cbc0989145446a0141171664be2d02ec6d66ee6
(this will work until the develop-beams branch is merged into develop, and then I will remove it).  I added that option because I am too lazy to update to a newer version of emscripten.  For updating on a linux-like operating system updating the GCC without updating the operating system would be dangerous.


-------------------------------

If that does not work, then there could be a variance in the name for the standard.  Have you compiled verovio on CentOS before?    Sometimes I have to change the standard name on linux computers (but I don't remember ever having to do it for verovio).  For example instead of `-std=c++17` maybe the compile flag `-std=gnu++17` might work (particularly if c++17 is not fully implemented, so they do not want to imply that it is completely c++17 compliant).


wikipedia page on c++17: https://en.wikipedia.org/wiki/C%2B%2B17
This page says:

>    GCC since version 7 has complete support for C++17.[48]

So it is strange that GCC 8 has problems (or even GCC 7).

**Comment by lpugin** [comment]
Is there any difference between using `gcc` versus `g++` ? Or are they the same?

**Comment by frakel** [comment]
Thank you Craig for your comment!
I tried very much to set up different devtool environments on our CentOS
server, unfortunately without any access.
The 

```
[  0%] Building CXX object CMakeFiles/verovio.dir/main.cpp.o
c++: error: unrecognized command line option ‘-std=c++17’
``` 
is always present even with the latest compilers from the Red Hat portage
(gcc 8.3.1) which apparently should be able to understand c++17.

The error messages are btw exact the same independently of using either
`c++17` or `gnu++17` as arguments.

Whe I change the option to `c++11` or `gnu++11` verovio does not compile
either, instead the following errors are thrown:
```
[root@dme-intern tools]# make
-- build verovio as executable
-- Configuring done
-- Generating done
-- Build files have been written to: /home1/kelnreiter/verovio/tools
Scanning dependencies of target verovio
[  0%] Building CXX object CMakeFiles/verovio.dir/main.cpp.o
/home1/kelnreiter/verovio/tools/main.cpp: In function ‘std::string fromCamelCase(const string&)’:
/home1/kelnreiter/verovio/tools/main.cpp:51:57: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [6])’
     result = std::regex_replace(result, regExp1, "$1-$2");
                                                         ^
/home1/kelnreiter/verovio/tools/main.cpp:51:57: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /home1/kelnreiter/verovio/tools/main.cpp:10:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
/home1/kelnreiter/verovio/tools/main.cpp:51:57: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
     result = std::regex_replace(result, regExp1, "$1-$2");
                                                         ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /home1/kelnreiter/verovio/tools/main.cpp:10:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
/home1/kelnreiter/verovio/tools/main.cpp:51:57: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [6]’
     result = std::regex_replace(result, regExp1, "$1-$2");
                                                         ^
/home1/kelnreiter/verovio/tools/main.cpp:52:57: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [6])’
     result = std::regex_replace(result, regExp2, "$1-$2");
                                                         ^
/home1/kelnreiter/verovio/tools/main.cpp:52:57: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /home1/kelnreiter/verovio/tools/main.cpp:10:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
/home1/kelnreiter/verovio/tools/main.cpp:52:57: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
     result = std::regex_replace(result, regExp2, "$1-$2");
                                                         ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /home1/kelnreiter/verovio/tools/main.cpp:10:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
/home1/kelnreiter/verovio/tools/main.cpp:52:57: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [6]’
     result = std::regex_replace(result, regExp2, "$1-$2");
                                                         ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-float-conversion" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-dollar-in-identifier-extension" [enabled by default]
make[2]: *** [CMakeFiles/verovio.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/verovio.dir/all] Error 2
make: *** [all] Error 2
```
But this is maybe not the right direction to go. The gcc man page expressly
mentions the `c++17` and `gnu++17` as correct values of the `-std` argument anyways.

So I am stuck at this point and it would be nice if someone else out there
could share their experience with compiling verovio on Red Hat or CentOS or
even other Linux flavours.

**Comment by frakel** [comment]
> 
> 
> Is there any difference between using `gcc` versus `g++` ? Or are they the same?

``````

**Comment by frakel** [comment]
... also same man page

**Comment by lpugin** [comment]
It works for me on CentOS 7.  Did you remove `CMakeCache` and `CMakeFiles.txt` after having upgraded gcc?

**Comment by frakel** [comment]
o yes, this worked. I did not remove the cache files :/
Thank you @lpugin for this hint!
