### ISSUE TITLE
Verovio 2.4 integration with vue.

### ISSUE THREAD

**Issue by jericho-music** [rism-ch/verovio#1292]
I cannot seem to instantiate verovio within a Vue component. I believe others (@WolfgangDrescher) have raised similar ideas but I have not seen a clear solution yet. I installed the verovio package by doing a yarn add. My package.json now has:

```
"dependencies": {
    "axios": "^0.19.1",
    "core-js": "^3.4.4",
    "verovio": "^2.4.0",
    "vue": "^2.6.10",
    "vue-axios": "^2.1.5",
    "vue-router": "^3.1.3",
    "vuejs-logger": "^1.5.3",
    "vuex": "^3.1.2"
  },
```

I created a very simple component to potentially display music sheets, but I am getting errors just trying to instantiate the toolkit. My code

```javascript
<template>
  <div class="music-sheet">
    <h1>Music Sheet</h1>
  </div>
</template>

<script>
import verovio from 'verovio';
import Vue from 'vue'

export default {
  name: 'music-sheet',

  data () {
    return {
      verovioToolkit: null,
    }
  },

  created() {
    Vue.$log.debug('Creating verovio toolkit...');
    this.verovioToolkit = new verovio.toolkit();
  },
}
</script>
```

The error I am getting in Firefox 72.0.2 (also in chrome) is along the lines of:

```
RuntimeError: abort(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -s ASSERTIONS=1 for more info.
TypeError: "Module.asm.B is undefined"
```

Any direction (preferably a working example) would be great.

Thanks.

**Comment by jericho-music** [comment]
I downloaded the 'verovio' code and started looking at it and realized that it is exporting 'module' and 'toolkit'. Tried to use them with similar message. Rebuilt verovio, by removing '-O3' and adding '-s ASSERTION=1' and get the following stack trace:

```
[Vue warn]: Error in created hook: "RuntimeError: abort(Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)) at jsStackTrace@webpack-internal:///./node_modules/verovio/index.js:4728:17
stackTrace@webpack-internal:///./node_modules/verovio/index.js:4745:16
abort@webpack-internal:///./node_modules/verovio/index.js:4500:44
assert@webpack-internal:///./node_modules/verovio/index.js:3572:10
Module._vrvToolkit_constructor@webpack-internal:///./node_modules/verovio/index.js:8846:9
ccall@webpack-internal:///./node_modules/verovio/index.js:3625:18
cwrap/<@webpack-internal:///./node_modules/verovio/index.js:3634:12
verovio.toolkit@webpack-internal:///./node_modules/verovio/index.js:9594:32
created@webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Sheet.vue?vue&type=script&lang=js&:22:27
invokeWithErrorHandling@webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:57
```

I also tried pre-defining a 'Module' with 'onRuntimeInitialized' function, but cannot get it to be called.

**Comment by lpugin** [comment]
you should have to do something like:
```JS
created() {
    Vue.$log.debug('Creating verovio toolkit...');
    /* Wait for verovio to load */
    verovio.module.onRuntimeInitialized = function ()
    {
        /* create the toolkit instance */
        this.vrvToolkit = new verovio.toolkit();
        console.log(this.vrvToolkit.getVersion());
    }
  },
```

**Comment by jericho-music** [comment]
Also tried what @lpugin recommended in the other thread:

```
var verovio = require( 'verovio' );

/* Wait for verovio to load */
verovio.module.onRuntimeInitialized = function ()
{
    /* create the toolkit instance */
    var vrvToolkit = new verovio.toolkit();
    console.log(vrvToolkit.getVersion());
}
```

but get this:

```
08:30:52.113 debug |  /node_modules/cache-loader/dist/cjs |  This is a test vue-logger.js:91
08:30:52.156 XHRGEThttp://localhost:8080/verovio.wasm
[HTTP/1.1 200 OK 2ms]

08:30:52.161 wasm streaming compile failed: TypeError: Response has unsupported MIME type index.js:3
08:30:52.162 falling back to ArrayBuffer instantiation index.js:3
08:30:52.205 XHRGEThttp://localhost:8080/verovio.wasm
[HTTP/1.1 304 Not Modified 1ms]

08:30:52.211 failed to asynchronously prepare wasm: CompileError: wasm validation error: at offset 4: failed to match magic number index.js:3
08:30:52.212 CompileError: wasm validation error: at offset 4: failed to match magic number index.js:3
08:30:52.212 CompileError: wasm validation error: at offset 4: failed to match magic number index.js:3
08:30:52.212 RuntimeError: abort(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -s ASSERTIONS=1 for more info. about.js line 1742 > eval:3:3116814
```

**Comment by jericho-music** [comment]
Hi Laurent,

  Afraid this gives the same message as above:

```
import verovio from 'verovio';
import Vue from 'vue'

export default {
  name: 'music-sheet',

  data () {
    return {
      verovioToolkit: null,
    }
  },

  created() {
    Vue.$log.debug('Creating verovio toolkit...');
    /* Wait for verovio to load */
    verovio.module.onRuntimeInitialized = function () {
      /* create the toolkit instance */
      this.vrvToolkit = new verovio.toolkit();
      Vue.$log.debug(this.vrvToolkit.getVersion());
    }
  }
}
```

**Comment by lpugin** [comment]
What version of node are you using? You need a recent version (at least 11 or 12, I cannot remember)

**Comment by jericho-music** [comment]
```
node -v
v13.6.0
```

**Comment by lpugin** [comment]
I looks like a server MIME type problem, doesn't it?

**Comment by jericho-music** [comment]
Sorry, I misread the result with your recommended change. The wasm validation error does not happen, but the onRuntimeInitialized function is never being called. I believe @WolfgangDrescher had pointed out something similar.

**Comment by jericho-music** [comment]
Hi Laurent,

  I have created a very small vue project which reflects what is going on. I have uploaded the code to https://github.com/jericho-music/vue-verovio. If you start the server with 'yarn serve' and then point the browser to localhost:8080 it should show the problem. I also have verovio locally so if you want me to run some test locally I can. Appreciate any help here.

**Comment by jericho-music** [comment]
Unbelievable!!! I needed to read the errors more carefully. Kept debugging and found out that verovio.wasm was being requested as ```http://localhost:8080/verovio.wasm```. That got redirected to the home page(html got back).

Just for quick fix I copied the verovio.wasm to the 'public' directory and got this:

``` debug |  /node_modules/verovio/index |  2.4.0-50c02de```

Apologies for all the hoopla and thanks for responding on a Sunday. I just have to figure out how to redirect when verovio.wasm is requested.

**Comment by WolfgangDrescher** [comment]
@jericho-music I had similar issues. To solve the problem I am copying verovio with CopyWebpackPlugin into the public folder. To avoid that webpack needs to pack the 10MB verovio file with the vue hot reload I am additionally adding it as a webpack externals and adding it as a resource manually in `public/index.html` with `<script src="<%= BASE_URL %>verovio/index.js"></script>` into the `<head>`. So when ever i use `import verovio from 'verovio';` in my components it will actually use the global verovio variable that `verovio/index.js` is defining. Although this method does not seems to work anymore with versions newer than verovio 2.3.3. I will debug for the verovio.wasm thanks for the advice.

```js
// vue.config.js
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    configureWebpack: {
        externals: {
            verovio: 'verovio',
        },
        plugins: [
            new CopyWebpackPlugin([{
                from: 'node_modules/verovio',
                to: 'verovio',
            }]),
        ],
    },
};
```

**Comment by lpugin** [comment]
@jericho-music this seems to do the job with your example (in vue.config.js):
```
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    configureWebpack: {
        plugins: [
            new CopyWebpackPlugin([{
                from: 'node_modules/verovio/verovio.wasm',
                to: '',
            }]),
        ],
    },
};
```

**Comment by WolfgangDrescher** [comment]
@jericho-music I did some debugging. It seems like verovio is now handled better with webpack than one year ago. So maybe in my new setup i will not copy it and use it as a webpack external anymore but instead use it with a normal `import verovio from 'verovio'`.

It looks like verovio is expecting verovio.wasm to be in the same directory where the verovio/index.js is called. So in a default vue setup webpack will bundle everything into `js/*`. The following config worked for me:

```js
// vue.config.js
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
    configureWebpack: {
        plugins: [
            new CopyWebpackPlugin([{
                from: 'node_modules/verovio/verovio.wasm',
                to: 'js/verovio.wasm',
            }]),
        ],
    },
};
```

**Comment by WolfgangDrescher** [comment]
Ah @lpugin was a bit faster ;-) . Thanks for the help. I think it would be good to have this documented anywhere (npm or verovio docs) how to use verovio with webpack. Altough im not a big fan of copying the wasm file manually to the build directory. Do you think there can be an easier solution where we have just have to think about importing verovio? I do not know WebAssembly and emscripten well so maybe it is a bad idea and surely there was a good reason to split verovio and wasm into two files.

**Comment by lpugin** [comment]
It was not a choice to have the wasm file separated from the JS glue code. I think there is now a new option with Emscripten to bundle them together. I will give a try and see if we can have it working.

**Comment by lpugin** [comment]
This issue should be solved with https://github.com/rism-ch/verovio/releases/tag/version-2.5.0 that builds wasm as a single file.

**Comment by jericho-music** [comment]
@lpugin, I just tested 2.5.0 and it works with the test application. We do not need the copy-webpack step.

Thanks a lot for the quick turnaround.
