### ISSUE TITLE
Feature request. An option to set number of systems per page.

### ISSUE THREAD

**Issue by vitalii-unicsoft** [rism-ch/verovio#1305]
Instead of defining a fixed line spacing this settings let the user define wether he wants less or more systems on one page (density of content). It still is logically connected to adjusting the system spacing but the logic behind this function is different;
As a user I want to be able to choose wether I want the page of my score to have as many systems as possible on it, or wether I prefer the page to look “lighter” with less systems on it by changing the “Systems per Page” settings from “Less - Default - More”
ATTENTION: for each setting the systems are distributed equally on the page, that means the top and bottom margins MUST be kept equal, as well as the spacIng between the systems. Obviously, if there is a higher density (Settings on “More” for more systems per page) the spacing is narrower between the systems than if there is less density (Settings on “Less”).
Acceptance criterias:
Rendering: Systems on first a regular page must distribute equally on the entire canvas (space between top menu and bottom menu). Therefore the spacing between systems is defined by the amount of systems that shall fit on the page. There MUST NOT be a situation where there is a big bottom margin from the last system to the bottom menu bar. In this case all systems shall redistribute on the page with equal spacing between them. 
ATTENTION: only on the last page, if there are less systems than on the previous oages, the system spacing of the previous page shall be kept and applied to last page, resulting in a larger bottom margin, if there is not enough systems to fill the page with.

**Comment by lpugin** [comment]
Please experiment and make a PR if you think it is satisfactory

**Comment by alexgnt** [comment]
hi @lpugin, I'm looking at this ticket and going to introduce one more option to specify 'maximum system per page' number. It will invalidate 'Spacing system' option in case new option value > 0. It looks like we just need to make appropriate offsets calculation when adding a new page to the document. Implementation looks straight forward at a first glance. 

Should we reopen this ticket for processing?

**Comment by lpugin** [comment]
@alexgnt setting a maximum number of systems page would be quite simple to implement. However, it is quite different from what was described in the initial comment of this issue. If your question is about implementing what you just described, then you can make a PR with an option system-max-per-page (with a default of 0)

(The implementation of "Less - Default - More" is another story, and it would require a much more significant modification of the vertical spacing algorithm. I am less sure about the relevance of that option.)

**Comment by alexgnt** [comment]
Hi @lpugin, according to latest information - gradation "Less - Default - More"  is not required and will be in responsibility of UI. So, we are talking only about system-max-per-page option, at least as for now.
