### ISSUE TITLE
Reference Error in JS toolkit

### ISSUE THREAD

**Issue by davidnalesnik** [rism-ch/verovio#1309]
Hi,

I'm using the Javascript build at https://www.verovio.org/javascript/develop/verovio-toolkit.js, and
a reference error has begun to appear.  Here's the log from Chrome:

verovio-toolkit.js:43 failed to asynchronously prepare wasm: ReferenceError: oa is not defined
(anonymous) @ verovio-toolkit.js:43
Promise.then (async)
instantiateArrayBuffer @ verovio-toolkit.js:43
instantiateAsync @ verovio-toolkit.js:43
createWasm @ verovio-toolkit.js:43
(anonymous) @ verovio-toolkit.js:43
verovio-toolkit.js:43 ReferenceError: oa is not defined
verovio-toolkit.js:43 ReferenceError: oa is not defined
abort @ verovio-toolkit.js:43
(anonymous) @ verovio-toolkit.js:43
Promise.then (async)
instantiateArrayBuffer @ verovio-toolkit.js:43
instantiateAsync @ verovio-toolkit.js:43
createWasm @ verovio-toolkit.js:43
(anonymous) @ verovio-toolkit.js:43
verovio-toolkit.js:43 Uncaught (in promise) Error: abort(ReferenceError: oa is not defined). Build with -s ASSERTIONS=1 for more info.
    at abort (verovio-toolkit.js:43)
    at verovio-toolkit.js:43
abort @ verovio-toolkit.js:43
(anonymous) @ verovio-toolkit.js:43
Promise.then (async)
instantiateArrayBuffer @ verovio-toolkit.js:43
instantiateAsync @ verovio-toolkit.js:43
createWasm @ verovio-toolkit.js:43
(anonymous) @ verovio-toolkit.js:43
verovio-toolkit.js:43 Uncaught TypeError: Cannot read property 'apply' of undefined
    at Object.Module._vrvToolkit_constructor [as constructor] (verovio-toolkit.js:43)
    at new verovio.toolkit (verovio-toolkit.js:135)
    at verovio.js:3
Module._vrvToolkit_constructor @ verovio-toolkit.js:43
verovio.toolkit @ verovio-toolkit.js:135
(anonymous) @ verovio.js:3

**Comment by lpugin** [comment]
I rebuilt develop with 1.39.7 and it works. This issue comes from the latest release of emscripten (1.39.8). As it stands, the Travis built will generate a corrupted file. I will investigate it.

**Comment by lpugin** [comment]
This is a problem in emscripten that is being looking at. Travis uses 1.39.7 for now. We can change it back to latest once this is fixed.

**Comment by lpugin** [comment]
Emscripten is fixed https://groups.google.com/forum/#!topic/emscripten-discuss/lEhUeQwlvGw
We can switch back when 1.39.9 is out.

**Comment by davidnalesnik** [comment]
Thank you for your help!
