### ISSUE TITLE
ending tie on first note

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#131]
when showing excerpts of a larger score, it's sometimes necessary to include a tie which ends on the first displayed note. I believe this is pretty close to page-based rendering, where you need to indicate a tie crossing the page. Is it possible already somehow?

**Comment by lpugin** [comment]
The way to do this is to include the measure preceding the page break with the appropriate notes/ties, and then to include the ```<pb>``` and ```<sb>``` for providing the layout information you want. Then you will need to display the second page.

Eventually, we should be able to have timestamp, but it does not really make sense for ties, does it?

**Comment by kepper** [comment]
yes, I already figured that solution. There really is no pb or sb preceding my intended "first" measure, but that's just a matter of adjusting the MEI that goes to Verovio. Since this isn't visible anywhere as MEI, I guess that's ok. It probably means that I always need to display the second page, but that'll be doable somehow, I guess�

Thanks :-)


Am 17.08.2015 um 11:05 schrieb Laurent Pugin <notifications@github.com>:

**Comment by lpugin** [comment]
OK, good. We will see if timestamps can solve it without adding another page.

**Comment by pe-ro** [comment]
The tstamp and tstamp2 attributes could be adjusted for a tie that starts/ends before/after the current fragment.  For example, a tie that ends in the first measure of p. 2 (that presumably began on a preceding page) could have its tstamp set to "0" (that is, the left edge of the first measure).  A tie that continues beyond the end of the page being displayed could likewise have its tstamp2 set to the numerator of the time signature + 1.  Both of these operations would require looking at the ties in the starting/ending measures within a fragment to determine their start/end points.
