### ISSUE TITLE
MusicXML Import: default staff forced to "1" in dir/dyn 

### ISSUE THREAD

**Issue by wergo** [rism-ch/verovio#1324]
In this commit, the MusicXML import of `<dyn>` and `<dir>` elements adds a default `@staff` value of "1" when no explicit staff information is given in the musicXML `<direction>` element. This causes most MusicXML files to have all `<dyn>` and `<dir>` elements located in `@staff="1"`, as in this Mahler symphony excerpt:

<img width="896" alt="grafik" src="https://user-images.githubusercontent.com/45632600/75544466-57685800-5a24-11ea-9fad-9f9f753b1d20.png">

The problem is introduced here (further down for `<dyn>`): https://github.com/rism-ch/verovio/blob/2a9cbee53420eaf2f969380c533a0cebd91c0274/src/iomusxml.cpp#L1546-L1549

This new bit imposes a default value for `@staff` as `"1"`, whenever no explicit staff information is provided in `<direction>`. It should be left undefined, so that in `MusicXmlInput::ReadMusicXmlNote` the staff information of the following note element can be applied.

**Comment by rettinghaus** [comment]
@wergo Sorry, I'll fix that.

**Comment by rettinghaus** [comment]
fixed with de919cd

**Comment by wergo** [comment]
Thanks a lot!! The import of dyn/dir works well again.
