### ISSUE TITLE
Feature request: Automatic system breaks with page breaks

### ISSUE THREAD

**Issue by palgranum** [rism-ch/verovio#1325]
Currently, if using 'breaks encoded', Verovio will layout according to page breaks and system breaks in mei file. If there are no system breaks, the music within a page is laid out with only one system (similar to 'breaks none').
I would like to have the feature of only specifying page breaks and then Verovio will lay out the music on the page and automatically put the system breaks as best fits the current settings for pageHeight, pageWidth, etc.

This is to deal with some specific requirements for keeping the same page content whilst changing page sizes, but hopefully this can be a useful feature more generally and so I would like to inquire the possibility of adding it as a feature.

Two images to illustrate :

Rendering with breaks encoded and only page breaks are specified, 1st page will look like this:
![ScreenShot2](https://user-images.githubusercontent.com/57617454/75563486-b8a32200-5a4a-11ea-9126-735a14c6ee3b.png)

Desired behavior, system breaks would be placed automatically:
![ScreenShot1](https://user-images.githubusercontent.com/57617454/75563481-b6d95e80-5a4a-11ea-8a28-066e2e193b36.png)

**Comment by lpugin** [comment]
This seems fairly specific, but it should not be too complicated. You can add a value "encoded-pages" to the option "breaks" and adjust the cast-off methods accordingly. Pls make a PR.
