### ISSUE TITLE
print version option for command line

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#133]
It would be useful to have a -v/--version option in the command line version of verovio.  This option flag would report only the version of verovio and then quit, such as:

```bash
$ verovio -v
Verovio 0.9.8-df2cd92
```

Currently I get a similar result by typing "verovio -v" but that is becuase it prints a help screen due to an unknown option.  But I have to scroll up to the top of the output to see the version.

Perhaps change "Verovio 0.9.8-df2cd92" to "verovio 0.9.8-df2cd92" since commands are case sensitive, and the program name is "verovio".

**Comment by lpugin** [comment]
-v/--version sounds like a good idea

**Comment by lpugin** [comment]
Added with 4c7b58c3e9d92f2fbab44438da94ea5e51c57da4
