### ISSUE TITLE
Compilining Python bindings (Debian Linux)

### ISSUE THREAD

**Issue by uliska** [rism-ch/verovio#1330]
I tried to install the Python bindings with `make` which started to compile and failed with

```
x-x86_64-2.7/../../src/vrv.o -DPYTHON_BINDING -std=c++17 -Wno-write-strings -Wno-overloaded-virtual
../../src/vrv.cpp:35:10: fatal error: git_commit.h: Datei oder Verzeichnis nicht gefunden
   35 | #include "git_commit.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [Makefile:19: compile] Fehler 1
```
Is there anything in that which indicates what might be wrong?

My system is Debian sid `Linux xxx 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux`, but this actually looks like something that is actually missing in the source repository?

**Comment by lpugin** [comment]
Normally, the file `git_commit.h.` is generated when running cmake. (I am not sure it does on Windows.) To get around this, you need to add manually a `./include/vrv/git_commit.h` file with simply `#define GIT_COMMIT "[unspecified]"`.

Any proposals to fix this would be welcome.

**Comment by lpugin** [comment]
PS Building the toolkit with cmake before woulding the Python toolkit should work too.

**Comment by cambiata** [comment]
This missing `git_commit.h` problem also occurs when compiling in an Linux Subsystem on Windows 10 (Utuntu 18.04 LTS in my case). Manually creating it, as described by Laurent above, solves the issue.

**Comment by Miking98** [comment]
When I first ran the build process for the CLI _before_ trying to build the Python part of this library, this error went away.

**Comment by lpugin** [comment]
It should be fixed (even though still not in a very elegant way) 6668ac5023d7e7d82a8103fafd2c03621ca3960b
