### ISSUE TITLE
Different rendered result using AdjustPageWidth in CLI and JS toolkit

### ISSUE THREAD

**Issue by cambiata** [rism-ch/verovio#1336]
The adjustPageWidth option doesn't seem to work correctly when used in the JS toolkit - at least not rendering the same result as when used in the CLI: The height is properly trimmed to the musical content, but the width is not.

In the rendered example below I use the following settings, expecting the rendered result to be the same:

### CLI
```
verovio -o tutorial4.svg --adjust-page-width --adjust-page-height -r data\ -s 50 tutorial1.mei
```
### Javascript
```
        var vrvToolkit = new verovio.toolkit();
        vrvToolkit.setOptions({
            scale: 50,
            adjustPageHeight: true,
            adjustPageWidth: true
        });
```
Am I missing something basic here, or is this expected behaviour?

Best! / Jonas

![verovio-adjust-width](https://user-images.githubusercontent.com/217074/76302531-74244b80-62c0-11ea-960e-6b5b738b4c97.png)

**Comment by cambiata** [comment]
Ah, I just realize that I get the following JS console error:
`[Error] Unsupported option 'adjustPageWidth'`

Is this not implemented in JS toolkit, or is it a version issue?
(Wouldn't expext that, as I'm testing JS using 
`<script src="http://www.verovio.org/javascript/latest/verovio-toolkit.js"></script>`.)

**Comment by lpugin** [comment]
It seems to be a version issue. This option is only available in the `develop` branch. (`latest` is the latest release. Please try with `http://www.verovio.org/javascript/develop/verovio-toolkit.js`

**Comment by cambiata** [comment]
Ah, thanks! Will try that!

**Comment by cambiata** [comment]
Yep, that did it. Thanks!
