### ISSUE TITLE
initial barline on single-staff systems

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#134]
When a system contains only a single staff, there should not be a system barline at the start of the staff.

For example, on the page http://www.verovio.org/pae-examples.xhtml, first example:

```pae
@clef:G-2
@keysig:xFCGD
@timesig:3/8
@data:'6B/{8B+(6B''E'B})({AFD})/{6.E3G},8B-/({6'EGF})({FAG})({GEB})/4F6-
```

Generates this graphical notation:

![screen shot 2015-08-04 at 3 58 33 pm](https://cloud.githubusercontent.com/assets/3487289/9074758/b27232fc-3ac1-11e5-87be-fe6b34ed9476.png)

The proper (default) style should be:

![noline](https://cloud.githubusercontent.com/assets/3487289/9074782/1832f4dc-3ac2-11e5-9eaf-c1cffebf4966.png)

I am not making this up, here are some examples in the wild:

http://javanese.imslp.info/files/imglnks/usimg/3/3c/IMSLP32089-PMLP72988-Kuhlau_3_Fantaisies_Solo_Flute_Op38.pdf

http://conquest.imslp.info/files/imglnks/usimg/c/c2/IMSLP98325-PMLP202072-Telemann-Gique-sans-Basse.pdf

http://petrucci.mus.auth.gr/imglnks/usimg/a/a8/IMSLP30505-PMLP68832-Paladilhe_-_Solo_pour_Hautbois__oboe_and_piano_.pdf

http://imslp.org/wiki/Horn_Sonata_(Hindemith,_Paul)

**Comment by lpugin** [comment]
Fixed with 860c3d46846b7943383d0c5d7dbb737f1c6f1906
