### ISSUE TITLE
midiplayer  Question

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1347]
1.I try to put topic09-midi on the local display
2.topic01-07 no problem
3.I have added wildwebmidi and midiplayer to the local folder
4.base64midi also has data
When I click p to start playing midi, the player cannot play,（ It just ended at the beginning）The error seems to be related to wildwebmidi.data, but I don't know what the problem is ？

**Comment by lpugin** [comment]
If the `wildwebmidi.data` is not located  in the root directory of you site, you should specify the path with the `locateFile` option.

**Comment by lpugin** [comment]
Please file further issues in the https://github.com/rism-ch/midi-player repo
