### ISSUE TITLE
Spacing between clef and key signature

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#135]
On the example page http://www.verovio.org/pae-examples.xhtml, the first example:

```pae
@clef:G-2
@keysig:xFCGD
@timesig:3/8
@data:'6B/{8B+(6B''E'B})({AFD})/{6.E3G},8B-/({6'EGF})({FAG})({GEB})/4F6-
```

The spacing between the clef and key signature is too large:

![spacing](https://cloud.githubusercontent.com/assets/3487289/9075218/27033c92-3ac7-11e5-9e3d-d2de1bceca37.png)

The spacing between the clef and the key signature should be in the range from 1.0 to 1.25 interline spaces (Behind Bars, p. 42).  The above example has 1.5 interline spaces.  I would prefer a default spacing of 1.0 interline spaces.

The spacing between the key and time signatures is 1.5.  This is in the recommended range of 1.0 to 1.5 (Behind Bars, p. 42), although I would prefer either 1.0 or 1.25.

The spacing between the time signature and the first note is correct at 2.0 :-)

Note the variable recommended distances before the first note from 1-2.5 in Behind Bars, p. 42, which depends on whether there is a key signature, time signature, and/or accidental before the first note.

**Comment by lpugin** [comment]
Fixed with cde33dd74e991f9d74eb4acf63d5c200e6d8aea2
