### ISSUE TITLE
Tempo text alignment with <mRest>

### ISSUE THREAD

**Issue by th-we** [rism-ch/verovio#1353]
The following MEI:

 ```
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title/>
            </titleStmt>
            <pubStmt/>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" lines="5" clef.shape="G" clef.line="2" meter.count="3"
                                meter.unit="4"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <pb/>
                        <measure n="1">
                            <staff n="1">
                                <layer n="1">
                                    <mRest xml:id="mrest"/>
                                </layer>
                            </staff>
                            <tempo staff="1" startid="#mrest">Adagio</tempo>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

currently renders as follows:

![grafik](https://user-images.githubusercontent.com/1147152/77196519-7023d500-6adb-11ea-88b8-3183b136fbb9.png)

**Comment by craigsapp** [comment]
I would think that it is more correct in such situations to connect a tempo marking to `@tstamp="0"` since the tempo marking should not be aligned with the rest but with the time signature:

<img width="420" alt="Screen Shot 2020-03-20 at 12 17 59" src="https://user-images.githubusercontent.com/3487289/77198755-db05e980-6aa4-11ea-8bf9-6bb9df6e9599.png">

If it is attached to the rest, then technically it is being displayed correctly.  There is also `@tstamp="1"` which displays the same as `@tstamp="0"`.  
```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
       <fileDesc>
           <titleStmt>
               <title/>
           </titleStmt>
           <pubStmt/>
       </fileDesc>
   </meiHead>
   <music>
       <body>
           <mdiv>
               <score>
                   <scoreDef>
                       <staffGrp>
                           <staffDef n="1" lines="5" clef.shape="G" clef.line="2" meter.count="3"
                               meter.unit="4"/>
                       </staffGrp>
                   </scoreDef>
                   <section>
                       <pb/>
                       <measure n="1">
                           <staff n="1">
                               <layer n="1">
                                   <mRest xml:id="mrest"/>
                               </layer>
                           </staff>
                           <tempo staff="1" tstamp="0">Adagio</tempo>
                       </measure>
                   </section>
               </score>
           </mdiv>
       </body>
   </music>
</mei>
```


Since the rest starts at tstamp 1, it might be reasonable to fix, but then there are cases such as fermatas where the fermata is attached to the rest, and it would not be good to move it to tstamp 1. Although for fermatas, then can be attached directly to the rest:

```xml
 <mRest  fermata="above" />
```

**Comment by th-we** [comment]
Then the MusicXML import should be changed, because at the moment, the following is converted to a `<tempo>` with `@startid`.

```
<score-partwise>
  <part-list>
    <score-part id="P1">
      <part-name>Flute</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>1</divisions>
        <time>
          <beats>3</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <direction>
        <direction-type>
          <words>Adagio</words>
        </direction-type>
        <sound tempo="30"/>
      </direction>
      <note>
        <rest/>
        <duration>3</duration>
        <voice>1</voice>
      </note>
    </measure>
  </part>
</score-partwise>
```

**Comment by rettinghaus** [comment]
Do you use the latest develop version? I‘ll have a look tomorrow.

**Comment by th-we** [comment]
Observed with d7b8eba. Should be up to date.

**Comment by rettinghaus** [comment]
@th-we As I thought, your branch is 1145 commits behind rism-ch:develop! Please update.

**Comment by th-we** [comment]
Ehm, no idea where I miscopied that commit hash. I did make sure I was up to date (ba370db).

**Comment by rettinghaus** [comment]
My tested showed the expected output. GitHub actually says on your develop branch: 

> This branch is 1145 commits behind rism-ch:develop.

**Comment by th-we** [comment]
I don't get it:

```
$ git rev-parse HEAD
ba370db4b2db10260a05c48e781b871b7376e513
$ git status
On branch develop
nothing to commit, working tree clean
$ make
[100%] Built target verovio
$ ./verovio --version
Verovio 2.7.0-dev-d7b8eba
$ date -r ./verovio 
Sa 21. Mär 09:50:21 CET 2020
```

**Comment by th-we** [comment]
To clarify: I was not compiling from the develop branch at the notengrafik repo.

**Comment by rettinghaus** [comment]
No, from this one: https://github.com/th-we/verovio
latest is `Verovio 2.7.0-dev-ba370db-dirty`

**Comment by th-we** [comment]
Yeah, as I wrote, that one is obsolete. I compiled ba370db (see bash output above). I don't understand why `verovio --version` would still show a different commit. If I change to a different branch, the SVG output definitely reflects the changes in that branch, but `verovio --version` will always report `Verovio 2.7.0-dev-d7b8eba`.

**Comment by th-we** [comment]
To assure myself I'm not totally crazy, here's a screenshot from the web viewer:

![grafik](https://user-images.githubusercontent.com/1147152/77223666-9fc3f300-6b56-11ea-9688-8f885933d0d1.png)

**Comment by rettinghaus** [comment]
But you are, because you use the MEI output. You have to use the original MusicXML to get this:
![screencapture-verovio-org-mei-viewer-xhtml-2020-03-21-10_33_54](https://user-images.githubusercontent.com/7693447/77223753-a145e900-6b5f-11ea-82d8-6889f58f5a19.png)

**Comment by th-we** [comment]
Ah, if we're talking about the MusicXML, you're of course right. (Turns out the verovio on my path was outdated and I used that one rather than the up-to-date one to convert the MusicXML to MEI.)
