### ISSUE TITLE
Staff line thickness

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#136]
The default thickness of staff lines on the example page:
     http://www.verovio.org/pae-examples.xhtml
is way way way too thick.  This causes the visual contrast of the notes and the staff to be about equal, lowering the readability of the notes.  The staff lines should be thinned and/or changed to a lighter color.

Vexflow does a good job at the relative contrast between staff and notes, so you can study its style on this point.

Here is a comparison of the first example on the above page to a SCORE-generated SVG image of the same music (with default staff line thickness and approximately the same size as the verovio example):

![screen shot 2015-08-04 at 5 28 08 pm](https://cloud.githubusercontent.com/assets/3487289/9075813/49ef37ae-3ace-11e5-90f4-ef4010f13ccc.png)

![screen shot 2015-08-04 at 5 28 37 pm](https://cloud.githubusercontent.com/assets/3487289/9075816/4cd44d92-3ace-11e5-919f-1265e8540fb6.png)

Also note that the thicker staff lines convey a somewhat childish or amateurish impression.

I am tempted to complain about several points related to the beams, but I will wait some more on those points :-).  But I will point out that the first beam in the example is required to be flat since the first and last notes are the same...

Also note the quite tight spacing of the clef and the key signature in the SCORE example (it looks like the spacing is defined as the distance between the top loop of the clef to the first sharp in the key signature).  The spacing from the key signature to the time signature in the SCORE example might look slightly better if it were increased by 0.25 interline spaces (so that the distance from the key signature to its neighbors would seem about equal).  In contrast the verovio example appears to have a gap between the clef and the key signature.

A minor complaint is that the tie ends are too close to the staff line (which might be fixed if the staff lines were thinner).  Probably the endpoints should be 1/2 of the distance from the top of the notehead to the bottom of the staff line above it.

**Comment by rettinghaus** [comment]
I do prefer heavier staff lines. So staff line thickness should be easily choosable.

**Comment by lpugin** [comment]
I think we can make it a little bit thinner by default, but not to much. Eventually, it should be configurable in a style. The best way to start this would be to see how this can be defined in MEI, and only then to implement it. Anybody willing to start to lay down ideas on this? In the meantime I'll create a new "style" label for this type of issues.

**Comment by ahankinson** [comment]
The more I think about it, the more I think that any style 'language' should be a project separate from MEI. I don't really care about the syntax, but I think it should be a separate effort from the MEI core development.

**Comment by lpugin** [comment]
I don't think it has to be a core development. But I also don't think we can make it completely separate from MEI. Otherwise it will be necessary to redefine all the MEI concepts and structures.

**Comment by lpugin** [comment]
Now the same at stem width.
