### ISSUE TITLE
Hand-coded example

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#137]
Hi Laurent,

It would be handy to transcribe the following musical composition into  raw Verovio code as a guideline for basic converter implementations (not too much sneaky stuff like hanging ties):

![screen shot 2015-08-17 at 4 53 14 pm](https://cloud.githubusercontent.com/assets/3487289/9319255/2f5187de-4501-11e5-808b-897ed35aa6dd.png)

For example the code for the first key signature might be:

```cpp
   int quantity = 2;
   data_ACCIDENTAL_EXPLICIT accid = ACCIDENTAL_EXPLICIT_s;	
   KeySig *k = new KeySig(quantity, accid);
   layer->AddLayerElement(k);
```

**Comment by lpugin** [comment]
Hi Craig,

I'll do it once the StaffDef/ScoreDef refactoring I am working on is done.

**Comment by lpugin** [comment]
Hi Craig,

Here is the basic. The code is not structured (just a long list) but very easy to follow. All the methods for adding attribute values are generated from the schema with LibMEI and the class names match the MEI element names.

https://github.com/rism-ch/verovio/blob/master/doc/importer.md

I'll update the example when you feature will become available.

**Comment by craigsapp** [comment]
Hi Laurent,

Thanks!  That is just what I need -- a top down overview of how to
construct the data.  I should be able to mostly figure out anything else by
reading the verovio code.

How do I output the MEI file from verovio?  That will be a good way of
writing a converter from Humdrum to MEI so that I don't have to write a
separate one.

I was in Los Angeles last weekend so not doing much, but I have been
thinking of more features for the minHumdrum library.  Yesterday I added a
CSV import/export of Humdrum data, such as:

standard TSV format:

**kern  **kern
*M3/4   *M3/4
8C      12d
.       12e
8B      .
.       12f
*       *^
4A      2g      4d
4G      .       4c
*       *v      *v
=       =
*-      *-

and the new CSV format:

**kern,**kern
*M4/4,*M4/4
8C,12d
.,12e
8B,.
.,12f
*,*^
4A,2g,4d
4G,.,4c
*,*v,*v
=,=
*-,*-

That will be useful for situations where tabs get munged, such as in the
case I most commonly come across when pasting/copying in email messages.


-=+Craig

**Comment by lpugin** [comment]
For getting the MEI into a string you should use the MeiOuput class (See the Toolkit class for a detail example). Something like

``` C++
MeiOutput meiOutput(doc, "");
meiOutput.SetScoreBasedMEI(true);
std::string mei = meiOutput.GetOutput();
```
