### ISSUE TITLE
emscripting compiling: missing libverovio.bc?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1371]
When I try to compile the latest `develop` branch version with emscripten, I am getting the following errors.

Perhaps there is a new file called `libverovio.bc` that was not committed to the repository?  Or is that file supposed to be autogenerated?

```
Compiled files will be written to build
Syncing SVG resources...
Creating commit version header file...
*************
Building makefile...
configure: cmake ../cmake -DBUILD_AS_WASM=ON -DEMSCRIPTEN_GENERATE_BITCODE_STATIC_LIBRARIES=ON -DCMAKE_CXX_FLAGS=-O3 -DNDEBUG --memory-init-file 0 -std=c++17 -s ASM_JS=1 -s INITIAL_MEMORY=256MB -s TOTAL_STACK=128MB -s WASM=0 -DCMAKE_TOOLCHAIN_FILE=/Users/craig/git-cloud/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/Users/craig/git-cloud/emsdk/node/12.9.1_64bit/bin/node"
-- build verovio as wasm bc
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/craig/git-cloud/verovio/cmake
*************
Compiling...
make: make -j 8
make: *** No targets specified and no makefile found.  Stop.
*************
Linking...
shared:ERROR: libverovio.bc: No such file or directory ("libverovio.bc" was expected to be an input file, based on the commandline arguments provided)
 Failed.
```

**Comment by lpugin** [comment]
The file is supposed to be generated. Try to remove ./tools/CMakeFiles and ./tools/CMakeCache.txt

**Comment by craigsapp** [comment]
It is working now: I removed `verovio/cmake/CmakeFiles`,  `verovio/cmake/CMakeCache.txt`, `verovio/cmake/cmake_install.cmake` and `verovio/cmake/Makefile` to get it to work.

I previously had compiled the command-line version from `verovio/cmake` (is that correct?), so perhaps the emscripten cmake settings and the command-line cmake settings are now overwriting each other?  Previously I did not have to re-run cmake for each of these targets.

I get a warning on MacOS Catalina that might be interesting:

```
shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning
[100%] Built target verovio
```

**Comment by lpugin** [comment]
emscripten and C++ build are now using the same makefile in ./cmake/CMakeLists.txt. To build, you now need to cmake ../cmake from ./tools. Leaving it in ./tools was yielding some conflicts I could not resolve, and moving it there was the only way I found to solve the issue.
(The instructions should be up-to-date https://github.com/rism-ch/verovio/wiki/Building-instructions)
