### ISSUE TITLE
PAE: Support chords

### ISSUE THREAD

**Issue by bretdabaker** [rism-ch/verovio#139]
As described [here](http://www.iaml.info/sites/default/files/pdf/plaine_easie_code.pdf):

__4.14. Chords__
The upper note is transcribed first; then follow the lower ones, each one separated by ‘^’.

**Comment by lpugin** [comment]
Added in commit bc5babe49c834fbf0f51c7cbb0a8604506c9d154 (to be pushed). However, chord support will remain limited with PAE. For example, with tuplets or with ties.
