### ISSUE TITLE
Verovio test files broken

### ISSUE THREAD

**Issue by th-we** [rism-ch/verovio#1396]
The test page:

https://www.verovio.org/test-frame.xhtml

does not work right now.  It displays no examples because all of them are "`display:none`", and all of them have the text "Verovio failed to render the MEI file".  If this is expected because the current development version is broken, then at least the messages should display.  (Probably a bad idea to hide failing tests.)

My suspicion is that in this line:

https://github.com/rism-ch/verovio/blob/gh-pages/_includes/test-version.html#L123

`cat` never becomes anything else but `null`.  I don't understand how the `localStorage` entries are meant to be set.

**Comment by lpugin** [comment]
The frames are used for the comparison of different version. The test-suite itself is accessible here http://www.verovio.org/test-suite.xhtml

**Comment by th-we** [comment]
Ok, then pardon my ignorance.
