### ISSUE TITLE
Build JS tookit for usage without browser?

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#1397]
Is it possible to build a JS toolkit without WASM and any web-dependent function calls and objects such as `console.log`, `setTimeout`, `document` etc. ?

I am trying to use it in a JS Engine that does not support any browser-specific functionality.

**Comment by lpugin** [comment]
It am sure it must be possible. You need to modify the C++ source code parts that call JS function in emscripten build in `vrv.cpp`, but this is basically it. (However, it does sound like a weird idea to go for a JS build without willing to target browsers.)

**Comment by sonovice** [comment]
Thanks for the quick answer. That's a great starting point. Embedding JS code in browser-less engines is not so uncommon in Java. It avoids handling stuff with JNI and keeps the code cross-platform.
