### ISSUE TITLE
Vertical and Horizontal Borders

### ISSUE THREAD

**Issue by bretdabaker** [rism-ch/verovio#140]
It would be great if we can decouple `border` into the `vertical-border` and `horizontal-border`. 

For instance, the example in the following page has an extra empty space on top. To remove it you will have to reduce `border` (vertical) which would result in clipping the the staff braces/brackets (horizontal).

http://www.verovio.org/features.xhtml?id=scoredef

**Comment by lpugin** [comment]
I would suggest to have actually four parameters (border-left, -right, -top, -bottom) in addition to border that would define all of them as now.

This is actually fairly simple to implement since it only requires to corresponding options to be added to the Toolkit class, to the main.cpp and JS interface. I'd be happy to integrate a PR if you add it, otherwise it will certainly be added eventually.

**Comment by craigsapp** [comment]
It would be very useful to have independent borders for each side of the image.  I notice a difficulty with system decoration when the border is set to zero:

![screen shot 2016-08-13 at 1 15 53 pm](https://cloud.githubusercontent.com/assets/3487289/17642883/3174d9c0-6158-11e6-93eb-07935c42d1ba.png)

Notice that the curly brace on the left is obscured when the border size is 0.  Here is what the same image looks like when the border is set to 40:

![screen shot 2016-08-13 at 1 17 50 pm](https://cloud.githubusercontent.com/assets/3487289/17642891/674687ce-6158-11e6-8b9f-1a00c1df8e78.png)


Ideally a `border` parameter would set the same border width on all sides, but the `border` options seems to add a border to the left and top sides of the image only, but not to the bottom (I didn't check the right, as the width might be from my css on the test page).  Also, the top border seems to increase more than the left border.  I am using `adjustPageHeight` for the example, so perhaps when that option is turned on, the border is eaten or not applied to the bottom of the image (you probably want to apply the border after `adjustPageHeight` has been processed).

But also consider the case of `border=0`.  It should not be set to the left edge of the system barline, but rather to the left-most part of the system decoration or instrument names at the start of the system (or whatever content is occurring before the system barline), like a bounding box in EPS files.

**Comment by lpugin** [comment]
Added in version 2.0
