### ISSUE TITLE
Cross-staff notes in empty staff

### ISSUE THREAD

**Issue by davidrizo** [rism-ch/verovio#1417]
When a layer from one staff is crossing to another staff that hadn't appear so far, a warning is reported and the note is not drawn in the correct staff.

For the input:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef key.mode="major" key.sig="2s" meter.sym="common">
                        <staffGrp>
                            <staffDef n="1" lines="5" clef.shape="G" clef.line="2"/>
                            <staffDef n="2" lines="5" clef.shape="F" clef.line="4"/>                            
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1">
                            <staff n="2">
                                <layer n="1">
                                    <beam>
                                        <note dur="8" oct="3" pname="g"/>
                                        <note dur="8" oct="3" pname="a"/>
                                        <note dur="8" oct="3" pname="b"/>
                                        <note dur="8" oct="4" pname="c"/>
                                        <note dur="8" oct="4" pname="d" staff="1"/>
                                        <note dur="8" oct="4" pname="e" staff="1"/>
                                        <note dur="8" oct="4" pname="f" accid.ges="s" staff="1"/>
                                        <note dur="8" oct="4" pname="g" staff="1"/>
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

the error is:
[Warning] Could not get the cross staff reference '1' for element 'note-0000001360571095'
[Warning] Could not get the cross staff reference '1' for element 'note-0000000712520409'
[Warning] Could not get the cross staff reference '1' for element 'note-0000000961698391'
[Warning] Could not get the cross staff reference '1' for element 'note-0000000457375046'

And the rendered score:
![image](https://user-images.githubusercontent.com/10772049/79251235-3054d100-7e80-11ea-9edd-2c3bd6739852.png)

However, if this target staff appears empty before it's used, there is no problem:
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef key.mode="major" key.sig="2s" meter.sym="common">
                        <staffGrp>
                            <staffDef n="1" lines="5" clef.shape="G" clef.line="2"/>
                            <staffDef n="2" lines="5" clef.shape="F" clef.line="4"/>                            
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1">
                            <staff n="1"> 
                                <layer></layer>  
                            </staff>
                            <staff n="2">
                                <layer n="1">
                                    <beam>
                                        <note dur="8" oct="3" pname="g"/>
                                        <note dur="8" oct="3" pname="a"/>
                                        <note dur="8" oct="3" pname="b"/>
                                        <note dur="8" oct="4" pname="c"/>
                                        <note dur="8" oct="4" pname="d" staff="1"/>
                                        <note dur="8" oct="4" pname="e" staff="1"/>
                                        <note dur="8" oct="4" pname="f" accid.ges="s" staff="1"/>
                                        <note dur="8" oct="4" pname="g" staff="1"/>
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>

...generating...

![image](https://user-images.githubusercontent.com/10772049/79251474-7873f380-7e80-11ea-834e-c2d6d9fdcc00.png)

**Comment by rettinghaus** [comment]
The encoding does not make much sense to me.

**Comment by davidrizo** [comment]
It's a minimal technical concept unit test ;)

**Comment by davidrizo** [comment]
I've sent just to raise a possible bug in more complex (and meaningful) music excerpts.
I think that either MEI should not allow this construction by forcing a hidden mRest (as VHV does) in the top staff, or Verovio should allow it. 
It seems that the data structure related to the staves are created when they are used in a `<section>` rather than when they are defined in the `staffDef`?

**Comment by craigsapp** [comment]
A core question is: If there is are two staves in the scoreDef:

```xml
                            <staffDef n="1" lines="5" clef.shape="G" clef.line="2"/>
                            <staffDef n="2" lines="5" clef.shape="F" clef.line="4"/> 
```

What should be the rendering behavior be when there is no `<staff n="1">` in a measure?

Here is an example where I comment out an empty measure in each staff.    The example below rendered as:

<img width="489" alt="Screen Shot 2020-04-14 at 11 00 21" src="https://user-images.githubusercontent.com/3487289/79257888-25c61780-7e3f-11ea-9326-cc4bf6a2d391.png">

This is not rendered correctly regardless, since the second measure of the system is showing the music for staff two on staff 1.  In other words, there is no music for staff 1, so all of the staves below it are popping up one staff.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-04-14T10:58:11" version="2.7.0-dev-9b84e3d">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000002103236101">
    <score xml:id="score-0000000497756152">
     <scoreDef xml:id="scoredef-0000000601724934" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000000127624332" symbol="brace" bar.thru="true">
       <staffDef xml:id="staffdef-0000001810741755" n="1" lines="5">
        <clef xml:id="clef-0000000745610398" shape="G" line="2" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001155771792" n="2" lines="5">
        <clef xml:id="clef-0000001652808161" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000798606366" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L3F2" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-0000001268174854" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dur="1" oct="3" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L4" n="2">
      <!--
       <staff xml:id="staff-L4F2N1" n="1">
        <layer xml:id="layer-L4F2N1" n="1">
         <space xml:id="space-L5F2" dur="1" />
        </layer>
       </staff>
      -->
       <staff xml:id="staff-L4F1N1" n="2">
        <layer xml:id="layer-L4F1N1" n="1">
         <note xml:id="note-L5F1" dur="1" oct="3" pname="d" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L6" n="3">
       <staff xml:id="staff-L6F2N1" n="1">
        <layer xml:id="layer-L6F2N1" n="1">
         <note xml:id="note-L7F2" dur="1" oct="4" pname="d" accid.ges="n" />
        </layer>
       </staff>
      <!--
       <staff xml:id="staff-L6F1N1" n="2">
        <layer xml:id="layer-L6F1N1" n="1">
         <space xml:id="space-L7F1" dur="1" />
        </layer>
       </staff>
      -->
      </measure>
      <measure xml:id="measure-L8" n="4">
       <staff xml:id="staff-L8F2N1" n="1">
        <layer xml:id="layer-L8F2N1" n="1">
         <note xml:id="note-L9F2" dur="1" oct="4" pname="e" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L8F1N1" n="2">
        <layer xml:id="layer-L8F1N1" n="1">
         <note xml:id="note-L9F1" dur="1" oct="3" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

I would expect it to render either as:

<img width="478" alt="Screen Shot 2020-04-14 at 11 01 40" src="https://user-images.githubusercontent.com/3487289/79258036-60c84b00-7e3f-11ea-9f2f-04b50249281a.png">


or as:

<img width="485" alt="example1" src="https://user-images.githubusercontent.com/3487289/79258209-a422b980-7e3f-11ea-8361-ce35f8d9cc78.png">

The second one is an interesting option, and could be one way of implementing ossia:

http://lilypond.org/doc/v2.18/Documentation/snippets/staff-notation

<img width="428" alt="Screen Shot 2020-04-14 at 11 07 22" src="https://user-images.githubusercontent.com/3487289/79258533-201d0180-7e40-11ea-8bb8-75ec6e914e6c.png">


Or for composers such as Stravinsky and other 20th century composers, there is a style to not display staff lines in measures that have a whole-measure rest:

<img width="709" alt="Screen Shot 2020-04-14 at 11 09 40" src="https://user-images.githubusercontent.com/3487289/79258732-71c58c00-7e40-11ea-9e56-87808a7103b7.png">

(Stravinsky _Sérénade en La_)

**Comment by lpugin** [comment]
You need to have `staff@visible='false'`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
	<meiHead>
		<fileDesc>
			<titleStmt>
				<title/>
			</titleStmt>
			<pubStmt/>
		</fileDesc>
		<encodingDesc>
			<appInfo>
				<application isodate="2020-04-14T10:58:11" version="2.7.0-dev-9b84e3d">
					<name>Verovio</name>
					<p>Transcoded from Humdrum</p>
				</application>
			</appInfo>
		</encodingDesc>
		<workList>
			<work>
				<title/>
			</work>
		</workList>
	</meiHead>
	<music>
		<body>
			<mdiv xml:id="mdiv-0000002103236101">
				<score xml:id="score-0000000497756152">
					<scoreDef xml:id="scoredef-0000000601724934" midi.bpm="400">
						<staffGrp xml:id="staffgrp-0000000127624332" symbol="brace" bar.thru="true">
							<staffDef xml:id="staffdef-0000001810741755" n="1" lines="5">
								<clef xml:id="clef-0000000745610398" shape="G" line="2"/>
							</staffDef>
							<staffDef xml:id="staffdef-0000001155771792" n="2" lines="5">
								<clef xml:id="clef-0000001652808161" shape="F" line="4"/>
							</staffDef>
						</staffGrp>
					</scoreDef>
					<section xml:id="section-L1F1">
						<measure xml:id="measure-L1" n="1">
							<staff xml:id="staff-0000000798606366" n="1">
								<layer xml:id="layer-L1F2N1" n="1">
									<note xml:id="note-L3F2" dur="1" oct="4" pname="c" accid.ges="n"/>
								</layer>
							</staff>
							<staff xml:id="staff-0000001268174854" n="2">
								<layer xml:id="layer-L1F1N1" n="1">
									<note xml:id="note-L3F1" dur="1" oct="3" pname="c" accid.ges="n"/>
								</layer>
							</staff>
						</measure>
						<measure xml:id="measure-L4" n="2">
							<staff xml:id="staff-L4F2N1" n="1" visible="false">
								<layer xml:id="layer-L4F2N1" n="1">
									<space xml:id="space-L5F2" dur="1"/>
								</layer>
							</staff>
							<staff xml:id="staff-L4F1N1" n="2">
								<layer xml:id="layer-L4F1N1" n="1">
									<note xml:id="note-L5F1" dur="1" oct="3" pname="d" accid.ges="n"/>
								</layer>
							</staff>
						</measure>
						<measure xml:id="measure-L6" n="3">
							<staff xml:id="staff-L6F2N1" n="1">
								<layer xml:id="layer-L6F2N1" n="1">
									<note xml:id="note-L7F2" dur="1" oct="4" pname="d" accid.ges="n"/>
								</layer>
							</staff>
							<staff xml:id="staff-L6F1N1" n="2" visible="false">
								<layer xml:id="layer-L6F1N1" n="1">
									<space xml:id="space-L7F1" dur="1"/>
								</layer>
							</staff>
						</measure>
						<measure xml:id="measure-L8" n="4">
							<staff xml:id="staff-L8F2N1" n="1">
								<layer xml:id="layer-L8F2N1" n="1">
									<note xml:id="note-L9F2" dur="1" oct="4" pname="e" accid.ges="n"/>
								</layer>
							</staff>
							<staff xml:id="staff-L8F1N1" n="2">
								<layer xml:id="layer-L8F1N1" n="1">
									<note xml:id="note-L9F1" dur="1" oct="3" pname="e" accid.ges="n"/>
								</layer>
							</staff>
						</measure>
					</section>
				</score>
			</mdiv>
		</body>
	</music>
</mei>
```
![image](https://user-images.githubusercontent.com/689412/79265606-a7955f80-7e96-11ea-80bf-78148dae80b7.png)
