### ISSUE TITLE
Position of fermata

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#142]
(Minor) A fermata touches the underlying note. See the score here:

http://neuma.huma-num.fr/scorelib/opus?id=timbres:cdc:0002

and Verovio (V. 0.9.9) here:

http://neuma.huma-num.fr/ajax/verovio?id=timbres:cdc:0002&matches=[]

Another example: measure 24.

http://neuma.huma-num.fr/scorelib/opus?id=timbres:cdc:0004
http://neuma.huma-num.fr/ajax/verovio?id=timbres:cdc:0004&matches=[]

The position of fermata should take the note/stems into account.

**Comment by lpugin** [comment]
Fixed
