### ISSUE TITLE
Feature request: Glissando

### ISSUE THREAD

**Issue by palgranum** [rism-ch/verovio#1421]
I see this has been mentioned before in https://github.com/rism-ch/verovio/issues/170 which was closed.

**Comment by lpugin** [comment]
Same as #1422. Slighly more complicated to implement because we need to deals with system breaks and calculate the appropriate angle / step of the glisando in such cases. But it is still a fairly standard feature to implement. Other MEI control events with `@tstamp2` would be examples to follow.

**Comment by EvgenyM** [comment]
Dear @lpugin ,

We are unsure of how to proceed in order to get Glissando supported. Could you please elaborate on your last answer?

**Comment by lpugin** [comment]
Basically, `<glissando>` is an MEI control event, and you can follow the implementation of similar MEI control events. This typically a control event that has a start (`@startid` or `@tstamp`) and an end (`endid` or `@tstamp2`). As I explain, looking a `<bracketSpan>` would be a good start. You can also look at the https://github.com/rism-ch/verovio/blob/master/doc/guidelines.md.
The main steps are:
- Adding the class (glissando.h/cpp)
- Add test files in the gh-pages branch in _tests/glissando/
- Reading and writing the object in iomei.cpp with MEIInput::ReadGlissando / MEIOutput::WriteGlissando
- Drawing in View with and new View::DrawGlissando method 
Does it make sense?
