### ISSUE TITLE
Note duration question

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1431]
Now,I have obtained the value of Pitch through the method 
` vrvToolkit.getMIDIValuesForElement(noteid);`
But can't get the value of duration

Can I use the callback method of midiplayer or the method of vrvToolkit library to export the duration of the note while the song is playing? Thank you!

@lpugin

**Comment by lpugin** [comment]
This is currently not possible. What would need to be modified is Toolkit::GetMIDIValuesForElement, and add the value to the JSON object. You probably want to have the values returned by Note::GetScoreTimeDuration() and Note::GetScoreTimeTiedDuration(). Please make a PR with this change.

**Comment by yangyangnote** [comment]
@lpugin  Ok I am trying to modify, Note::GetScoreTimeDuration() and Note::GetScoreTimeTiedDuration()  is there any difference? Which method is to get the duration of individual notes?

**Comment by yangyangnote** [comment]
@lpugin I have now tried to submit a PR to the developer branch, before the project update. How can I test my modified local code in a web environment?
My local path is like this

<img width="371" alt="屏幕快照 2020-05-05 下午3 53 08" src="https://user-images.githubusercontent.com/19338570/81045340-93b6a980-8ee8-11ea-8f8b-1b16ec230cc3.png">
