### ISSUE TITLE
Midi Playback Help

### ISSUE THREAD

**Issue by languageofmusic** [rism-ch/verovio#1442]
I'm trying to put musical examples on my site with playback. 

I tried following the Midi tutorial at https://www.verovio.org/tutorial.xhtml?id=topic09, with no luck. 

In an experiment, I tried simply copying the source code for this page: https://www.verovio.org/midi.xhtml and pasting it in my code editor. Without changing anything, and making sure all the files (scripts, stylesheets, etc.) are URLs and not file paths, I try to load the page locally. When I do this, everything is exactly the same except the playback doesn't work. I can also substitute my own MEI file and it displays properly, but doesn't play. 

When I upload my MEI file to https://www.verovio.org/mei-viewer.xhtml, it works properly.

Sorry if this is an easy issue to solve, I did look through past issues and couldn't find a solution.

**Comment by yangyangnote** [comment]
Is it a problem that the player can display, but it can not be played? I have encountered a similar problem, you can refer to my answer in midiplayer

https://github.com/rism-ch/midi-player/issues/16

**Comment by lpugin** [comment]
This is a midi player issue. Followup on https://github.com/rism-ch/midi-player if necessary
