### ISSUE TITLE
Problems tested in the web environment

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1447]
@lpugin I have now tried to submit a PR to the developer branch, before the project update. How can I test my modified local code in a web environment? Is it necessary to replace the verovio-toolkit.js file, it seems that there is no verovio-toolkit.js file in the verovio project.
My local path is like this

<img width="371" alt="屏幕快照 2020-05-05 下午3 53 08" src="https://user-images.githubusercontent.com/19338570/81045608-1d667700-8ee9-11ea-9297-272656613275.png">

**Comment by lpugin** [comment]
Your PS is now merged in the devlop branch. The branch is built automatically with travis, and you can download it. See https://www.verovio.org/download.xhtml

(Please make sure you use the issue tracker for reporting Verovio issues, and not programming problems specific to a project. For borderline cases, you can also use the music-encoding#verovio Slack channel. For documentation issues, it would be good to submit PRs to improves it.)

**Comment by yangyangnote** [comment]
@lpugin  Many questions are found through the use of the project, you mean that such questions about project integration / version testing can be asked in Slack, am I correct? Thank you !

**Comment by yangyangnote** [comment]
@lpugin Is it possible to send a Slack invitation, I can't get in now
