### ISSUE TITLE
Support for staffDef within measure without scoreDef

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#145]
Score:
http://scorelib.huma-num.fr/scorelib/opus?id=methodes:adampiano:204_1
As you can see there is a change of clef for staff 2 at the end of measure 3. This change is reported in the MEI, but seems to be ignored by Verovio (last release).
MEI: http://scorelib.huma-num.fr/rest/methodes/adampiano/204_1/mei.xml
Verovio: http:/scorelib.huma-num.fr/ajax/verovio?id=methodes:adampiano:204_1&matches=[]

**Comment by lpugin** [comment]
staffDef will be supported. However, in the reported cases it makes more sense to use a clef element. See https://github.com/music-encoding/encoding-tools/issues/11

**Comment by lpugin** [comment]
I will actually close this for now until it is clarified in MEI. See https://github.com/music-encoding/music-encoding/issues/324
