### ISSUE TITLE
What is the difference between TimeDuration () and TimeTiedDuration?

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1451]
@lpugin  (1)Note::GetScoreTimeDuration() and Note::GetScoreTimeTiedDuration() is there any difference? Which method is to get the duration of individual notes? (example: 500 ms)

(2)Now I can get the value of duration (4)by Note :: GetScoreTimeDuration () method, what does he mean?

**Comment by lpugin** [comment]
Tied duration it the duration of a group of tied notes on the first note. It will be -1.0 on subsequent notes of the groups. I don't think this is relevant for what you want to do.

Duration provided in not milliseconds. See d96df7d19a428660c0b1155079e7c6cf681d9554
