### ISSUE TITLE
Overlap slur / tuplet number + strange beam

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#146]
Score: http://neuma.huma-num.fr/scorelib/opus?id=methodes:adampiano:104_2
Measures 1 and 3: the '3' overlaps the slur.
http://neuma.huma-num.fr/ajax/verovio?id=methodes:adampiano:104_2&matches=[]

Also: the represent of the beam at measure 7 looks weird. Compare with the Lilypond version which seems more natural.

**Comment by rettinghaus** [comment]
The examples are no longer available (should be added to the issue).

**Comment by lpugin** [comment]
This was impoved
