### ISSUE TITLE
Support for bold text font in lyrics

### ISSUE THREAD

**Issue by Pryadka** [rism-ch/verovio#1460]
Sometimes rendering of text has different view and one of this representation looks like a bug. 
Wrong represantation:
![BigMei](https://user-images.githubusercontent.com/5373894/82040051-35d35000-96a6-11ea-8c9a-690d1113499c.png)
The same xml-snippet in another file
![SinipetFromBigMei](https://user-images.githubusercontent.com/5373894/82040125-5bf8f000-96a6-11ea-9b36-fd6370d4f98a.png)
It looks like a bug in `int Verse::AdjustSylSpacing(FunctorParams *functorParams)`

**Comment by lpugin** [comment]
Please post an MEI snippet with one single measure / staff with the problem

**Comment by Pryadka** [comment]
this is staff with a problem. **You can see wrong text in the middle of 9 page**
[scorecopy9.mei.txt](https://github.com/rism-ch/verovio/files/4634267/scorecopy9.mei.txt)

and this is corresponding snippet from this file put to empty .mei
[verse.mei.txt](https://github.com/rism-ch/verovio/files/4634271/verse.mei.txt)

Please remove .txt extension in order to use it.

**Comment by lpugin** [comment]
Thanks. Next time post the MEI snippet inline like https://github.com/rism-ch/verovio/issues/1455

The main issue is the use of `@fontweight="bold"`.  `DeviceContext::GetTextExtent` does not take into account the fontweight. To fix this, you need to modify the Resources class so it can load and use different fontweights / styles. Which means
* Have additional maps (same as  `Resources::m_textFont`) for `Times-italic`, `Times-italic-bold`, and `Times-bold` (see `./data/text`)
* Load the fonts following the normal text font model (call `InitTextFont("Times-italic")`, etc.)
* Add a `Resources::SelectTextFont(data_FONTWEIGHT fontWeight, data_FONTSTYLE fontStyle) method that can be called before GetTextExtent is call in order to select the appropriate font.

There might be some spacing issue to fix too, but you need to implement this first.

**Comment by Pryadka** [comment]
Hello @lpugin . I implemented text-font loading and using. It works but still doesn't fix the issue. Before creating pull request for this implementation I'd like to discuss one point. 
We have values FONTSTYLE_NONE and FONTWEIGHT_NONE in corresponding enumeration types. They indicate if style or weight were not specified in a .mei. But we apply always -normal value (or suppose some default value) for a text rendering. My proposal is to set this default value when style or weight are not specified. FONTSTYLE_NONE and FONTWEIGHT_NONE can be removed from enums in this case.

**Comment by lpugin** [comment]
FONTSTYLE_NONE (and similar) are generated from the MEI Schema (see https://music-encoding.org/guidelines/v4/data-types/data.fontstyle.html). As you pointed out, we need them to decide what to do when nothing is specified in the MEI. But you should never have to use them if you check if a value is set first – e.g., with `HasFontstyle()`.

**Comment by lpugin** [comment]
Implemented in #1478

**Comment by Pryadka** [comment]
Hello @lpugin . 
I still work on the issue. I added font style supporting for 'Syl' and it fix some cases. But I still have behavior like this
![no-syl-connector](https://user-images.githubusercontent.com/5373894/84120939-c5b2b280-aa36-11ea-8237-ba6b90169b32.png)
Corresponding mdiv snippet has this definition:
[snipet.txt](https://github.com/rism-ch/verovio/files/4750683/snipet.txt)

Whole svg

[scorecopy9_008.svg.txt](https://github.com/rism-ch/verovio/files/4750694/scorecopy9_008.svg.txt)

**Comment by Pryadka** [comment]
@lpugin . Finally I figured out the reason of this issue. Sometimes a width of a system is wider than path width. In this case all items on the page shift to left by multiplying by m_justifiableRatio :
```
m_justifiableRatioSetXRel(ceil((((double)this->m_xRel - (double)params->m_leftBarLineX) * params->m_justifiableRatio)
            + params->m_leftBarLineX));
```
The X coordinates of all elements become smaller and the image more dense. Syllables go to new positions and as result spaces between them also become smaller, because the width of the syllable stays the same as before coordinate scaling. In the method `void View::DrawSylConnectorLines(DeviceContext *dc, int x1, int x2, int y, Syl *syl, Staff *staff)` we check if space is enough for drawing connector 
`if (dist < dashLength) {
            LogDebug("Hyphen space under the limit");
            nbDashes = 0;
        }`
and it is not drawn.
As a solution I can offer to scale syllable text in both direction or only by X axe (I implemented this possibility in brace support task and corresponding pull request will be provided after tests is finished).
What do you think about it?
