### ISSUE TITLE
How to get the corresponding noteid when clicking on any note？

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1462]
@lpugin  @craigsapp 
1.Through https://www.verovio.org/gh-tutorial/topic07-choice.html this example I can only click on the selected element
like:
```
 $(".orig, .reg, .unclear").each(function() {
                    $(this).click(function(event) {
                        });
});
```

2.But how do I click on any note and to get the corresponding noteid?
 So that I can get the pitch information I want through noteid.

**Comment by lpugin** [comment]
You should follow the tutorial step by step. See https://www.verovio.org/tutorial.xhtml?id=topic05

**Comment by yangyangnote** [comment]
OK,Thank you !

**Comment by yangyangnote** [comment]
I use https://www.verovio.org/tutorial.xhtml?id=topic09 function
```
$(".note").click(function() {
                    var id = $(this).attr("id");
});
```
You can also get the value of noteid
