### ISSUE TITLE
How to get channel information through the method in verovio 

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1469]
@lpugin  
by https://github.com/rism-ch/verovio/issues/1456

I know to get the concept of channel from staffDef  --->instrDef --->  @midi.channel

I still don't quite understand which method can get the channel (such as 0,1) in the verovio. Like I can get the pitch value by id. This way I can control the piano to play only the left or right hand function

Can you give me a simple example, thank you very much!

**Comment by lpugin** [comment]
There is no way to do this in Verovio. However, I assume this to be trivial with xPath on the MEI data. Basically looking at the staff@n of the parent staff of a note and get the matching staffDef@n/instrDef@midi.channel.

**Comment by yangyangnote** [comment]
Ok i'm doing research
