### ISSUE TITLE
Warnings with rendering of file from MEI Sample Encodings repository

### ISSUE THREAD

**Issue by kseniaosipova** [rism-ch/verovio#1470]
After the rendering of the file from The MEI Sample Encodings repository
(https://github.com/music-encoding/sample-encodings/blob/master/MEI_4.0/Music/Complete_examples/Aguado_Walzer_G-major.mei)
there are warnings (with not supported elements) and debugs appearing

![image](https://user-images.githubusercontent.com/60135178/82825328-5459f800-9eab-11ea-8b63-e20903fdf4a9.png)

**Comment by lpugin** [comment]
This is intended. Verovio does not support everything possible in MEI and shows a warning for elements not supported. 
If you do not want to see the debug messages, then you should not build it in debug mode. Closing since is it not reporting an issue.
