### ISSUE TITLE
How to get staff or channel through note

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1475]
@lpugin @craigsapp 
Sorry, forgive my ignorance, now only through similar
`$(".measure .staff ~ .staff " ).attr("fill", "#00e").attr("stroke", "#00e");`
 method makes the staff change color, like
<img width="600" alt="屏幕快照 2020-05-27 下午3 42 01" src="https://user-images.githubusercontent.com/19338570/82991690-a6785600-a030-11ea-94cb-dbf6c8949dca.png">
but I don't know how to get staff or channel through note

I still don't understand how to execute with code
"Verovio can't do this. However, I don't think it matters with the xPath on the MEI data. Basically, look at the staff @ n of the parent staff of the note and get the matching staffDef @ n / instrDef @ midi.channel."

Can you give me a simple code example, Or just a simple code hint.thank you very much

**Comment by lpugin** [comment]
The MEI is your input file (if you use another input format, you can get the MEI with the `getMEI` method of the toolkit.) Then look on the web for a tutorial on XPath or a place where you can ask for help how to learn this - this is not Verovio related.
