### ISSUE TITLE
complete support for att.staffLoc and att.staffLoc.pitched

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1492]
Only some elements have support for `@loc` or `@oloc` and `@ploc`. Support should be completed at least for all layer elements.

**Comment by lpugin** [comment]
Do you mean to have it on `LayerElement`? This would not make sense? Or on MEI elements that support it? Which are they?

**Comment by rettinghaus** [comment]
I meant those that support it. Currently it doesn't work on `accid`, `dot`, and `multiRest`.

**Comment by lpugin** [comment]
OK, makes sense. Closing the issue since there is none here.
