### ISSUE TITLE
Incorrect calculation of systems height - (footer overlapping by system body)

### ISSUE THREAD

**Issue by alexgnt** [rism-ch/verovio#1503]
In some cases system height incorrectly calculated during layout. This is causing footer overlapping (in some cases systems  only partly printed on the page).

Please take a look at attached samples.

![image](https://user-images.githubusercontent.com/11978860/84404788-943d1100-ac07-11ea-9647-a1318aabcc0d.png)

[shub_system_overlaping.mei.zip](https://github.com/rism-ch/verovio/files/4765739/shub_system_overlaping.mei.zip)

**Comment by rettinghaus** [comment]
corresponds to #831

**Comment by lpugin** [comment]
@alexgnt you need to give more information when opening an issue like this. We need to know:
- the version of Verovio you are using,
- the parameters passed to it.

**Comment by alexgnt** [comment]
- The latest version pulled yesterday.
- command line:
 -a   -r C:\verovio\data    C:\verovio\samples\shub_system_overlaping.mei

**Comment by alexgnt** [comment]
@lpugin, did you had a chance to reproduce the issue? Any tip regarding this one?

**Comment by lpugin** [comment]
Yes, I can reproduce it. No clue where the problem is at this stage.

**Comment by lpugin** [comment]
Fixed. It was a problem with an x value for tstamp attributes not reset during cast off, which would yield an different vertical height. 
(I took the opportunity to add Doc::m_drawingPageContentHeight/Width members that hold corresponding values without margin. This makes calculation clearer.)
