### ISSUE TITLE
"Segno" and "Coda

### ISSUE THREAD

**Issue by GBogdahn** [rism-ch/verovio#1512]
Neither "Segno" nor "Coda" seem to be supported by Verovio.

This is a screenshot from Finale:
![Repetition symbols](https://user-images.githubusercontent.com/64458816/85375218-447b1580-b536-11ea-94a7-46a534ab53e2.png)

Here its rendering by Verovio:
![No repetition symbols](https://user-images.githubusercontent.com/64458816/85375324-6bd1e280-b536-11ea-8848-ca242abc28b0.png)

**Comment by lpugin** [comment]
It does. Use `<dir>&#x1D10B;</dir>` and `<dir>&#x1D10C;</dir>` respectively
