### ISSUE TITLE
A --spacing-staff option affects spacing between header/footer and first/last staff

### ISSUE THREAD

**Issue by alexgnt** [rism-ch/verovio#1517]
The value of spacing-staff option affects spacing between header and fist staff and footer and last staff. Which is barely looks correct and usable, as alternative it could be a good idea to introduce a new option for header(footer) and content spacing.

Tested on latest develop and reproducible on any test files.

Used the following commands to obtain result on the picture below:
`-a --spacing-staff 15 -r C:\work\verovio\data C:\work\Samples\Grieg_op.43_butterfly.mei`
`-a --spacing-staff   0 -r C:\work\verovio\data C:\work\Samples\Grieg_op.43_butterfly.mei`

![image](https://user-images.githubusercontent.com/11978860/85576287-91dfab80-b638-11ea-9a9d-ec0d6c2e08ab.png)

**Comment by rettinghaus** [comment]
There's more to that. It affects the space between two systems. 
The guidelines clearly state, that it
> Specifies the minimum amount of space between adjacent staves in the same system
