### ISSUE TITLE
[QUESTION] Alternative noteheads support

### ISSUE THREAD

**Issue by Monceber** [rism-ch/verovio#1525]
From the looks of it, Verovio has already build foundation for support of alternative noteheads.

![noteheads](https://user-images.githubusercontent.com/1819669/86442647-c9281980-bd16-11ea-8c80-04a97ea285c8.png)

However, I don't think full support is implemented yet. All that I can see in the code are the stubs for the future changes like this:

_// Here we should get the notehead value_
**wchar_t code = SMUFL_E0A4_noteheadBlack;**

Is there any plans on adding support for this in the near future?

**Comment by rettinghaus** [comment]
Funny, as all those glyphs are not available in Verovio. Where'd you get this image? 
And please, add always a test file.

**Comment by Monceber** [comment]
This is image is not from Verovio, but generated by Musescore. My bad, should have clarified it in the initial post.
As for the test file, basically any musicxml with any <notehead> attribute would do (e.g. **<notehead>diamond</notehead>**) - Verovio clearly doesn't have the glyphs needed, but it does have all the required shapes in the code
https://github.com/rism-ch/verovio/blob/58c99e49c66ab749b9bbc1da58071adff1930323/libmei/atttypes.h#L680-L699

Hence my initial question regarding support of these noteheads.

**Comment by lpugin** [comment]
From the current status (3.2.0-dev-9dd2c3f) of the test suite
![image](https://user-images.githubusercontent.com/689412/105056339-5f821980-5a74-11eb-89f7-3a4f6a46d491.png)
