### ISSUE TITLE
GABC support

### ISSUE THREAD

**Issue by adunning** [rism-ch/verovio#1527]
Have you considered adding GABC to your supported formats? There is a large body of square-note notation written in this format, and it would be useful to have a way to get it into MEI.

http://gregorio-project.github.io

There are existing parsers for it, such as this (with links to further examples):

https://crates.io/crates/gabc-parser

**Comment by rettinghaus** [comment]
Just had a look at GABC and it shouldn't be too complicated. Would you volunteer?

**Comment by lpugin** [comment]
@rettinghaus do you think it should be done by extending ABCInput? Or through completely new GABCInput class?

**Comment by rettinghaus** [comment]
@lpugin as the input is quite different (and the output even more) it should be a new class.

**Comment by lpugin** [comment]
@adunning please ask if you need any help to implement this. Closing the issue since at this stage it is still a generic feature request
