### ISSUE TITLE
Extended ornament support

### ISSUE THREAD

**Issue by Monceber** [rism-ch/verovio#1531]
It would be great to have extended support for the ornaments like trills and mordents.
There are,a lot of different variations for this type of ornaments. E.g.
![image](https://user-images.githubusercontent.com/1819669/86571587-54551980-bf7a-11ea-9e84-b00399bc948a.png)

Currently there are only 3 different types of mordent that are supported: normal, inverted, and long.
Here's MEI data for example:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title>Example</title>
   </titleStmt>
   <pubStmt/>
  </fileDesc>
  <encodingDesc xml:id="encodingdesc-0000000707086629">
   <appInfo xml:id="appinfo-0000000645338505">
    <application xml:id="application-0000001260849453" isodate="2020-07-06T10:32:25" version="3.0.0-dev-5706f96-dirty">
     <name >Verovio</name>
     <p>...</p>
    </application>
   </appInfo>
  </encodingDesc>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001150083862">
    <score xml:id="score-0000000349406986">
     <scoreDef xml:id="scoredef-0000001527545709">
      <staffGrp xml:id="staffgrp-0000000056438675">
       <staffGrp xml:id="staffgrp-0000001463845395">
        <staffDef xml:id="staffdef-0000002003966291" n="1" lines="5" ppq="16" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4">
         <label xml:id="label-0000000346988744">Piano</label>
        </staffDef>
       </staffGrp>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-0000000631718026">
      <pb xml:id="pb-0000001055314533" />
      <measure xml:id="measure-0000001477853898" n="1">
       <staff xml:id="staff-0000001261022864" n="1">
        <layer xml:id="layer-0000001364464289" n="1">
         <note xml:id="note-01" dur.ppq="16" dur="4" oct="5" pname="c" stem.dir="down" accid.ges="s" />
         <note xml:id="note-02" dur.ppq="16" dur="4" oct="5" pname="d" stem.dir="down" accid.ges="s" />
         <note xml:id="note-03" dur.ppq="16" dur="4" oct="5" pname="e" stem.dir="down" accid.ges="s" />
         <note xml:id="note-04" dur.ppq="16" dur="4" oct="5" pname="f" stem.dir="down" accid.ges="s" />
        </layer>
       </staff>
       <mordent staff="1" startid="#note-01" form="lower"/>
       <mordent staff="1" startid="#note-02" form="upper"/>
       <mordent staff="1" startid="#note-03" form="lower" long="true"/>
       <mordent staff="1" startid="#note-04" form="upper" long="true"/>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>

```

And it generates this:
![image](https://user-images.githubusercontent.com/1819669/86571151-a9446000-bf79-11ea-992e-87764d15bfde.png)

MusicXML has better support for this by providing attributes like **approach** and **departure**, which allows for additional a vast combinations of mordents. MEI doesn't have such attributes, but this probably could be implemented by using altsym, glyph.name, or glyph.num attributes, as suggested by MEI documentation for mordent.

**Comment by th-we** [comment]
It makes sense to implement this relying on `@glyph.name` and/or `@glyph.num` and SMuFL. Would it be a requirement that any glyphs that can be referenced by those attributes have to be in the Leipzig font? A general approach could just work with what the font in question has.

**Comment by rettinghaus** [comment]
Basicallly no need to have them supported globally, but you'd still have to "switch on" those glyphs in `supported.xsl`.

**Comment by lpugin** [comment]
> Basicallly no need to have them supported globally

What do you mean by this?

**Comment by rettinghaus** [comment]
@lpugin Once `@glyph.num` is available, theoretically you may address any (SMuFL) glyph, but that shouldn't mean, we have to make all the glyphs available …

**Comment by lpugin** [comment]
I am not sure I understand want you mean, but as long as we do not start adding glyphs (e.g., uncomment glyphs in `supported.xsl`) without adding them to the Leipzig font I am OK.

**Comment by th-we** [comment]
If `@glyph.num` is found in the MEI, should we always assume SMuFL?  We could at least check if `@glyph.auth` is present – and if it is, make sure it's `smufl`. If it is not, then we should not render the glyph as SMuFL.

**Comment by ramagottfried** [comment]
would be great to be able to access the entire set of glyphs in Bravura, http://www.unicode.org/charts/PDF/U1D100.pdf -- or is it already possible?

this is a real limitation that is keeping me from using verovio at the moment, I've been trying with `@glyph.name` but no luck so far.

see also #910

**Comment by rettinghaus** [comment]
@ramagottfried This is about ornaments, where Verovio uses `@glyph.num` for alternative glyphs. Perhaps you should open a new issue for your specific problem.

**Comment by rettinghaus** [comment]
@lpugin This can be closed now, I presume.

**Comment by ramagottfried** [comment]
@rettinghaus ok great thanks for the hint, I'll try `@glyph.num` again, and will make a new issue if I'm still having issues.
