### ISSUE TITLE
Which MEI version does Verovio support?

### ISSUE THREAD

**Issue by valeriyvan** [rism-ch/verovio#1539]
It isn't stated clearly anywhere which version of MEI does Verovio support and what's scope of that support.
Would be nice to see that clearly stated in README.

**Comment by lpugin** [comment]
Added here https://github.com/rism-ch/verovio/commit/f521e21ff5c8adcc53d276a9a6da5b73c18643cc

See also https://github.com/music-encoding/music-encoding/issues/675

The scope of the support is another story. We had this at the begining https://www.verovio.org/supported-mei.xhtml. Then there was the idea to provide an MEI customization for this but it was never finalized. Contributions are welcome, but we need something that can be maintained. Any thoughts?

**Comment by lpugin** [comment]
The development version of the MEI Schema is now "5.0.0-dev". It can be used when working with MEI files that include features added or changed since MEI 4.0.

**Comment by craigsapp** [comment]
There is also a question about the other end: I see some automatic converters from MEI 3 in the source code, so there is some automatic handling of version 3 as well?

**Comment by lpugin** [comment]
Yes. Basically all features Verovio supported before MEI 4 came out are converted to MEI 4. (For example, a `staffDef@label` is converted to `staffDef/label`.) The same is planned in the future, as long as it possible.
