### ISSUE TITLE
Support for several <mdiv> 

### ISSUE THREAD

**Issue by shino-funayama** [rism-ch/verovio#154]
In order to encode some harmonic studies from Max Reger.Alltogether there are six different (mdiv) for six different groups of tonalities, namely C-major, C sharp-major, a-minor, C flat-major, d flat-minor and a sharp-minor. Each (mdiv) has a (score) and multiple (section) as modulation examples.
In Verivio is only shown the first (mdiv). That means that we can see in Verovio only examples of C-major. Has someone an idea about how to show several (mdiv) in Verovio?

**Comment by lpugin** [comment]
Support for mdiv selection was added in 70acbf514b3b6917c7853922b224ecadca4672cb
