### ISSUE TITLE
Support for choice element

### ISSUE THREAD

**Issue by shino-funayama** [rism-ch/verovio#155]
This is about major and minor cadence in one example. We have taken (choice) here and two different variations as input. But in Verovio (choice) is not displayed. Does anyone have ideas?

![frage2](https://cloud.githubusercontent.com/assets/16317856/11866026/942f0f8a-a4a8-11e5-9944-31e810ea7f4b.JPG)

**Comment by lpugin** [comment]
Added with 70eebfb723903093b3101272f16ca7130c2ad597
