### ISSUE TITLE
Dash length is not used anywhere in View::DrawSylConnector method

### ISSUE THREAD

**Issue by valeriyvan** [rism-ch/verovio#1551]
`dashLength` is not used in View::DrawSylConnector method
https://github.com/rism-ch/verovio/blob/11b04bc98cc64163bcba026443d16240c9761c8c/src/view_control.cpp#L1203
That's probably a bug.

**Comment by rettinghaus** [comment]
removed in 4b0f7cd6123287a748a63fa47062c6ca901d2b38

**Comment by valeriyvan** [comment]
I see. It's part of PR  #1548 which is not merged yet.

**Comment by valeriyvan** [comment]
Closed with #1548
