### ISSUE TITLE
Support for SMuFL's engravingDefaults as Verovio options

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1555]
Many of Verovios styling options resemble those from SMuFL's engravingDefaults. The main difference is that SMuFL specifies "all measurements expressed in staff spaces", while Verovio uses MEI's virtual units. 

Wouldn't it make sense to follow the SMuFL specifications (as long as the options do not correspond to MEI attributes)?

https://w3c.github.io/smufl/gitbook/specification/engravingdefaults.html

**Comment by rettinghaus** [comment]
(Basically, we somewhat agreed on that already in #368.)

**Comment by lpugin** [comment]
It would be good to support SMuFL options. At the same time we need to keep the door open for additional styling features in MEI that will be using MEI units. For this reason, and for ensuring consistency, it is preferable to keep Verovio options in MEI units. What about adding a single option (e.g., --smuflEngraving) that takes a JSON object (or file in the command line?) and that converts them to Verovio / MEI values?

**Comment by rettinghaus** [comment]
Taking a JSON object sounds good. But I think it would be confusing to keep all the options around then. For full SMuFL compatibility we would have to add even more, as right now many values are hard coded, e.g. `beamSpacing`, `beamThickness`, `legerLineThickness`, and `thickBarlineThickness`. 
Perhaps we should keep direct options to a minimum instead and deprecate things like `--lyric-line-thickness`.

**Comment by lpugin** [comment]
We can leave existing options for now. We do not want to force people to use SMuFL engraving options. Once we have a better styling structure in MEI we can clean them up.

**Comment by lpugin** [comment]
The issue should have been closed already.
