### ISSUE TITLE
Avoid collision with unison or second intervals

### ISSUE THREAD

**Issue by shino-funayama** [rism-ch/verovio#156]
It's about two different note duration of two different voices which, however, have the same pitch. They appear to overlap in verovio. Is it somehow possible to display two notes side by side?

![frage3](https://cloud.githubusercontent.com/assets/16317856/11866100/180b4c42-a4a9-11e5-8d3a-236e7ae9b7d9.JPG)

**Comment by lpugin** [comment]
Actually already provided by #96

**Comment by shino-funayama** [comment]
Ok! Thank you.
