### ISSUE TITLE
Shrink to fit page

### ISSUE THREAD

**Issue by th-we** [rism-ch/verovio#1572]
If a system/page is too high to fit in the specified page height, the rendering should be scaled down to fit the page instead of cutting it off.

Suggested handling: An option `--shrink-to-fit` is introduced. If that option is active and the bounding box of the image is higher than the page, scale down the image to fit the height precisely. Center the page horizontally.

Technically, the only thing that should be necessary to achieve this is setting the last value of the viewBox attribute of the inner SVG element to the bounding box height + top margin + bottom margin.

**Comment by rettinghaus** [comment]
@th-we Is this connected to #1533?

**Comment by th-we** [comment]
@rettinghaus I see them as separate. This issue is mostly independent of the used page size, units etc.  But my suggested solution is very SVG specific, so that might be a problem.

**Comment by lpugin** [comment]
Looks like this was implemented....
