### ISSUE TITLE
Support for enclose on accid

### ISSUE THREAD

**Issue by shino-funayama** [rism-ch/verovio#158]
How can I encode a clip without (choice)?

![frage5](https://cloud.githubusercontent.com/assets/16317856/11866302/6f9f7342-a4aa-11e5-8d42-d085108660a2.JPG)

**Comment by lpugin** [comment]
att.enclose for accid is now supported on single notes but not for chords. Closing the issue for now

**Comment by lpugin** [comment]
`@enclose` is now also supported on chord accidentals

![image](https://cloud.githubusercontent.com/assets/689412/24927299/e0406bae-1efe-11e7-998d-b5bfcc32dfd7.png)
