### ISSUE TITLE
Support for multiple accid values (e.g., "ns")

### ISSUE THREAD

**Issue by shino-funayama** [rism-ch/verovio#159]
How can at a note  a  natural and a sharp side by side be encoded? In Verovio this is not displayed correctly.

![frage6](https://cloud.githubusercontent.com/assets/16317856/11866324/b3bc4474-a4aa-11e5-8535-ed0353aa8ba9.JPG)

**Comment by ahwitz** [comment]
Part of #181.

**Comment by lpugin** [comment]
This is now supported
