### ISSUE TITLE
F major with two flats in white mensural notation

### ISSUE THREAD

**Issue by davidrizo** [rism-ch/verovio#1599]
In many mensural manuscripts, F major is notated by duplicating the flat in the two possible positions of the B in the staff. E.g.:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/10772049/89673997-a675bb80-d8e7-11ea-80e6-be281a728607.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/10772049/89674058-c60ce400-d8e7-11ea-8196-8d2f7b1d1d03.png">

<img width="446" alt="image" src="https://user-images.githubusercontent.com/10772049/89674157-fc4a6380-d8e7-11ea-99c3-a716ac906fe4.png">

The last example key signature could be encoded with the following MEI code:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title>Example</title>
   </titleStmt>
   <pubStmt/>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application>
     <name>MuRET</name>
    </application>
   </appInfo>
  </encodingDesc>
 </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
     <scoreDef>
      <staffGrp>
       <staffDef n="1" lines="5" notationtype="mensural.white">
        <clef line="1" shape="C"/>
        <keySig>
         <keyAccid pname="b" accid="f" oct="3"/>
         <keyAccid pname="b" accid="f" oct="4"/>
        </keySig>
        <mensur sign="C" modusmaior="2" modusminor="2" tempus="2" prolatio="2"/>
       </staffDef>       
      </staffGrp>
     </scoreDef>
     <section>
      <staff n="1">
       <layer n="1">
        <note dur="minima" oct="3" pname="b" accid.ges="f"></note>
        <note dur="minima" oct="4" pname="b" accid.ges="f"></note>
       </layer>
      </staff>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

However, Verovio ignores the `@oct` `keySig`:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/10772049/89674791-06209680-d8e9-11ea-9ee3-649c1a8a0dbe.png">

**Comment by craigsapp** [comment]
Same as issue https://github.com/rism-ch/verovio/issues/1144

**Comment by davidrizo** [comment]
Thank you @craigsapp, they I close this issue

**Comment by craigsapp** [comment]
As long as @lpugin notices it :-).  Has this been clarified in MEI?  What do you guys do in ODD meetings? 🦗
