### ISSUE TITLE
Support for meter change in MusicXML import

### ISSUE THREAD

**Issue by lmarcon** [rism-ch/verovio#160]
Hi,
I have the following sheet in MuseScore:

![schermata 2015-12-28 alle 17 57 25](https://cloud.githubusercontent.com/assets/3500986/12022100/f33bcfb2-ad8c-11e5-8246-73f893364881.png)

I exported it in MusicXML, then used the online interface to convert it to .mei (and then svg), and I get the following:

![schermata 2015-12-28 alle 17 57 14](https://cloud.githubusercontent.com/assets/3500986/12022122/182381c6-ad8d-11e5-9d46-4c61061bfeed.png)

As you can see, the meter change information is lost, but the note length is correct for each note/pause. By opening the converted .mei file with a text editor, I can see that there's only one `<section>` with the meter information (the first one, 4/4), and no evidence of the meter change.

I did another test: I manually edited the .mei file, adding another `<section>` with the changed tempo information (and manually changing the id attributes to avoid dups).

Loading the edited .mei in the online svg editor (http://www.verovio.org/mei-viewer.xhtml) the rendering works as expected, the sheet looks the same as the original one in MuseScore.

Is it possible that the meter change is a bug / unsupported feature in the xml to mei conversion?

Attached you find all the xml and mei I used: [test xml and mei.zip](https://github.com/rism-ch/verovio/files/73392/test.xml.and.mei.zip)

**Comment by ahankinson** [comment]
Which Music XML to MEI tool did you use specifically?

**Comment by pe-ro** [comment]
I just made a change to musicxml2mei-3.0 that should fix the capture of the time signature change.  Even so, this area of the conversion is still incomplete and the whole style sheet will have to be re-examined with regard to the new release.

**Comment by lmarcon** [comment]
I used the online tool here: http://www.verovio.org/musicxml.html
Il 29/dic/2015 00:25, "Andrew Hankinson" <notifications@github.com> ha
scritto:

**Comment by lpugin** [comment]
I'll try to fix it in the next update.

**Comment by rettinghaus** [comment]
this can be closed now
