### ISSUE TITLE
Ledger vs leger

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1625]
Naming is inconsistent with leger lines, mostly "ledger" is used, at some points it's "leger". 
As SMuFL prefers the British spelling we should have "leger" used everywhere.

**Comment by craigsapp** [comment]
Behind Bars uses "ledger", such as p. 32:

<img width="458" alt="Screen Shot 2020-10-16 at 9 08 20 PM" src="https://user-images.githubusercontent.com/3487289/96328036-be5a7180-0ff3-11eb-9d89-f1c8c491231f.png">

(Behind Bars was published in England).

**Comment by rettinghaus** [comment]
Just to add: MusicXML and SMuFL use leger. 
See: https://github.com/w3c/smufl/issues/113

**Comment by craigsapp** [comment]
SMuFL is British 😉 . I pronounce the `d` (as in the German word `Dschungel`), so it looks weird without it.  Without it, I would pronounce the `g` halfway towards the `s` in leisure (i.e., a slightly more voiced `j` sound as in manager, geriatric or geranium).  But English speakers are not known for their spelling abilities, so enything goez 😛 

Leger is a variant spelling derived from Ledger in the late 19th century:

<img width="387" alt="Screen Shot 2021-01-27 at 8 54 15 AM" src="https://user-images.githubusercontent.com/3487289/106025187-5a792780-607d-11eb-88dd-8a40c356ab36.png">

(Google dictionary based on Oxford dictionary https://languages.oup.com/google-dictionary-en)

With ledger line being the primary spelling according to OUP:

<img width="668" alt="Screen Shot 2021-01-27 at 8 51 15 AM" src="https://user-images.githubusercontent.com/3487289/106024916-184fe600-607d-11eb-9d32-e596d292ff57.png">

Here is a counter-example of Michael Good using the spelling "Ledger" in a W3C post:
https://www.w3.org/community/music-notation/2017/05/01/musicxml-3-1-beta-test-begins


Search for "leger line" or "ledger line" in Google to see the dictionary entry.  A fun thing is to look at the name of the term in various languages.   

Spanish has a nice one: línea suplementaria (supplemental line)

Polish is "linea księgi" which literally translated is "book line" (i.e., a Ledger book), so similar to the English term's origin.

German Hilfslinie is similar to Spanish, literally translated as "auxiliary line" or more literally as a "help line".
