### ISSUE TITLE
Beams sometimes incorrectly rendered

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#163]
Hello,
The beam:

                                <beam>
                                    <rest dur="16"/>
                                    <note dur="16" …/>
                                    <rest dur="8"/>
                                </beam>
(two bars on the eight rest)
is incorrectly rendered whereas the inverse one:

                                <beam>
                                    <rest dur="8"/>
                                    <note dur="16" …/>
                                    <rest dur="16"/>
                                </beam>
is. (one bar on the eight rest)
Thank you

**Comment by lpugin** [comment]
Fixed
