### ISSUE TITLE
Beam on 16th wrongly rendered 

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#164]
Hello,

The 16th beam is wrongly rendered on:

![wrongbeamon16th](https://cloud.githubusercontent.com/assets/16109195/12565609/81e02626-c3b5-11e5-9c1e-0d9c74de98d1.png)

Thank you

**Comment by lpugin** [comment]
Fixed with dca1fd914607d2dd09a1f0c19dde82fe30521a28
