### ISSUE TITLE
Develop branch: bug in int LayerElement::GetDrawingRadius for rests

### ISSUE THREAD

**Issue by palgranum** [rism-ch/verovio#1647]
It seems like in this function (LayerElement::GetDrawingRadius) whenever this->Is(REST), and it proceeds to call doc->GetGlyphWidth with code = 0, it will cause assertion failure in GetGlyphWidth

**Comment by lpugin** [comment]
Please always provide a minimal MEI test file when reporting such an issue. Thanks.

**Comment by lpugin** [comment]
@Monceber it was broken there https://github.com/rism-ch/verovio/pull/1630 Could you fix it? Thanks

**Comment by lpugin** [comment]
Fixed with #1650
