### ISSUE TITLE
Chord beams may be incorrectly rendered

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#165]
Hello,

The beam:

                                <beam >
                                    <chord dots="1" dur="8" dur.ges="192p" stem.dir="down">
                                        <note dots="1" dur="8" dur.ges="192p" layer="1" oct="4" pname="g" pnum="68" staff="3">
                                            <accid  accid="s"/>
                                        </note>
                                        <note dots="1" dur="8" dur.ges="192p" layer="1" oct="5" pname="g" pnum="80" staff="3">
                                            <accid  accid="s"/>
                                        </note>
                                    </chord>
                                    <chord dur="16" dur.ges="64p" stem.dir="down">
                                        <note dur="16" dur.ges="64p" layer="1" oct="4" pname="a" pnum="70" staff="3">
                                            <accid  accid="s"/>
                                        </note>
                                        <note  dur="16" dur.ges="64p" layer="1" oct="5" pname="a" pnum="82" staff="3">
                                            <accid  accid="s"/>
                                        </note>
                                    </chord>
                                </beam>

is rendered with a missing 16th beam on the second chord.
It's correctly rendered with single notes, the problem only occurs with chords.

Thank you

**Comment by lpugin** [comment]
Fixed
