### ISSUE TITLE
Support request for new elements and attributes

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#167]
Hello,

I think the verovio should support the following elements (in order of priority in my opinion):

1.  <gliss>
2.  <hairpin>
3.  <dynam>
4. element <note>
 - support for artic="stacc" , artic="acc" or a combination of both
 - support for head.shape="cross" (for rythmics)
5.  <beamSpan>
6. element <slur>
- support for lform="dashed"
7. element <measure>
- support for label attribute

That would be the ideal world :-)

Thank you

**Comment by lpugin** [comment]
Thanks. I reorganized them as separated issues.
