### ISSUE TITLE
Support for beams with stems up and down

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#168]
Hello,

The beam:

                                <beam >
                                    <rest dur="8" dur.ges="128p"/>
                                    <note artic="stacc" dur="16" dur.ges="64p" layer="1" oct="3" pname="g" pnum="56" staff="4" stem.dir="up">
                                        <accid  accid="s" func="caution"/>
                                    </note>
                                    <chord artic="stacc acc" dur="16" dur.ges="64p" stem.dir="down">
                                        <note dur="16" dur.ges="64p" layer="1" oct="4" pname="f" pnum="65" staff="3" stem.dir="down"/>
                                        <note dur="16" dur.ges="64p" layer="1" oct="4" pname="b" pnum="71" staff="3" stem.dir="down"/>
                                    </chord>
                                </beam>

is rendered as:

![beamupdown](https://cloud.githubusercontent.com/assets/16109195/12596739/b5795e68-c481-11e5-8dbc-7eb755c95641.png)

whereas it should be rendered as:

![beamupdownok](https://cloud.githubusercontent.com/assets/16109195/12596814/109a4280-c482-11e5-83c6-37c0c07968f6.png)

Thank you

**Comment by lpugin** [comment]
Duplicates with #98
