### ISSUE TITLE
Tuplets not supported in ABC, background info

### ISSUE THREAD

**Issue by khausam** [rism-ch/verovio#1680]
I noticed in ioabc.cpp that the AddTuplet method call is commented out.  I'm assuming it's commented out because it didn't work correctly. Is there any background information available to read (commits, issues, etc.) as to the history of this and what the problems are? I may be interested in trying to help. Also, I only need simple eighth note and quarter note triplet support. Hoping maybe the issues are associated with ABC's more extensive duplet and quadruplet and generic p:q:r notation and the existing code will be sufficient for my needs. Thanks for your time.

**Comment by khausam** [comment]
I spent a little time with the code today and I think I can answer my own question at this point. 

I very quickly hacked together some changes to the ABCInput class this evening to support a very simple version of ABC triplets. The code is not yet worthy of a pull request, but if you're interested in looking at what I threw together, let me know and I will try to clean it up a bit. In particular, I had to disable a couple of assertions related to adding the Note() children to both the Beam() and Tuplet().

My changes only support the very simplistic form of (n and not the more generic (p:q:r format. Still, maybe it is better than nothing. Below is my test abc content:

X:1
T:Beams
L:1
M:4/4
K:C
(3C/8C/8C/8C/2  |]

This triplet is beamed, but if I replace the 8's (eighth notes) with 4's (quarter notes), the quarter note triplet correctly does not beam.

**Comment by lpugin** [comment]
Thanks for looking at this. Have you committed the changes to your own repository? Maybe @rettinghaus could have a look at them before you make a PR. If the changes you had to do are in Beam and Tuplet classes, then there is probably something not right.

**Comment by rettinghaus** [comment]
@khausam If I remember correctly, the tuplets support was left out originally, because it can be tricky to correctly stack beams and tuplets in the correct order. 
The logic in filling up the layer is very simple and should be improved. I'd be happy to have a look at your code.

**Comment by craigsapp** [comment]
>  because it can be tricky to correctly stack beams and tuplets in the correct order.

It is. See https://github.com/rism-ch/verovio/blob/develop/src/iohumdrum.cpp#L13981-L14487

You could try to model after that code, or easier would be to convert first to Humdrum and then use that code to convert to MEI.

For example

```
X:1
T:Beams
L:1
M:4/4
K:C
(3C/8C/8C/8C/2 |]
```

Would convert to Humdrum as

```
!!!OTL: Beams
**kern
*k[]
*C:
*M4/4
=1
12cL
12c
12cJ
2c
==
*-
```

Rendering this file:

```bash
verovio file.krn
```

produces:

<img width="295" alt="Screen Shot 2020-09-14 at 3 34 36 AM" src="https://user-images.githubusercontent.com/3487289/93075849-40452c80-f63b-11ea-9d2c-b4eca6f73a82.png">

and converting to MEI:

```bash
verovio -atmei file.krn
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title>Beams</title>
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-09-14T03:35:46" version="3.0.0-dev-774540b-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title xml:id="title-L1" analog="humdrum:OTL" type="main">Beams</title>
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="0" token="!!!OTL: Beams" xml:id="L1">
     <frameInfo>
      <startTime float="0" />
      <frameType>reference</frameType>
      <referenceKey>OTL</referenceKey>
      <referenceValue>Beams</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000964605363">
    <score xml:id="score-0000001455227819">
     <scoreDef xml:id="scoredef-0000002092512658">
      <staffGrp xml:id="staffgrp-0000000846746190">
       <staffDef xml:id="staffdef-0000000663538302" n="1" lines="5">
        <clef xml:id="clef-0000002107339156" shape="G" line="2" />
        <keySig xml:id="keysig-L3F1" pname="c" mode="major" sig="0" />
        <meterSig xml:id="metersig-L5F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
      <pgHead xml:id="pghead-0000000564071653">
       <rend xml:id="rend-0000000879095938" halign="center" valign="middle">
        <rend xml:id="rend-0000002034783247" fontsize="large">Beams</rend>
        <lb xml:id="lb-0000001581377593" /> 
<lb xml:id="lb-0000000172214330" /> </rend>
      </pgHead>
     </scoreDef>
     <section xml:id="section-L2F1">
      <measure xml:id="measure-L1" right="end" n="1">
       <staff xml:id="staff-0000000748059784" n="1">
        <layer xml:id="layer-L2F1N1" n="1">
         <tuplet xml:id="tuplet-L7F1-L9F1" num="3" numbase="2" bracket.visible="false" num.format="count">
          <beam xml:id="beam-L7F1-L9F1">
           <note xml:id="note-L7F1" dur="8" oct="4" pname="c" accid.ges="n" />
           <note xml:id="note-L8F1" dur="8" oct="4" pname="c" accid.ges="n" />
           <note xml:id="note-L9F1" dur="8" oct="4" pname="c" accid.ges="n" />
          </beam>
         </tuplet>
         <note xml:id="note-L10F1" dur="2" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

Also, I have a converter from [Humdrum to ABC](https://github.com/humdrum-tools/humextra/blob/master/src-programs/hum2abc.cpp), with

```
!!!OTL: Beams
**kern
*k[]
*C:
*M4/4
=1
12cL
12c
12cJ
2c
==
*-
```

converting back into ABC-plus as:

```
X: 1
T: Beams
%%abc-version 2.0
%%abcx-abcm2ps-target-version 5.9.1 (29 Sep 2008)
%%abc-creator hum2abc beta
%%abcx-conversion-date 2020/09/14 03:37:50
%%humdrum-veritas 3341445561
%%humdrum-veritas-data 1921946292
%%continueall 1
%%barnumbers 0
L: 1/8
M: 4/4
K: C
(3CCCC4 |]  
```

**Comment by khausam** [comment]
I forked the project and pushed my changes here: https://github.com/khausam/verovio/commit/44af32265f9a2ce3d6e047813890389eaacfaf9d 

My use case and requirements for tuplets is very constrained: I only need to support eighth note and quarter note triplets and I am in control of how they will be notated in ABC. Given these restrictions, do you see any glaring errors or problems with what I've thrown together?

**Comment by khausam** [comment]
Thanks to all for the comments and suggestions. I don't have the time (or likely the skill) to do a proper job of supporting tuplets in ABC right now. I'm able to move forward on my project using Humdrum (Kern) instead. Regards.
