### ISSUE TITLE
spacingStaff option not working

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1693]
The `spacingStaff` and `spacingSystem` option defaults and behaviors have changed recently.  It would be useful to post issues about these sorts of changes, describing the what and why of the changes.

The default for `spacingStaff` has changed from 8 to 12, with a range of 0-24 changed to 0-36.

The default for `spacingSystem` has changed from 3 to 12 with a range of 0-12 change to 0-48.

Why are the option ranges for `spacingStaff` and `spacingSystem` different?  Obviously because the original ranges were not identical, but the new system treats the spacings as equivalent, so it is better to make the ranges for each option the same.

In addition, see issue #1295 for suggested changes in ranges from 0 to 100.

---------------

Previously the `spacingStaff` value was placed below every staff, and `spacingStaff` was placed below every system.  This means that the previous behavior was that the true spacing between each system was `spacingStaff` + `spacingSystem`.

The new system does not add `spacingStaff` below the bottom staff of the system, so the new `spacingSystem` is what was previously `spacingStaff` + `spacingSystem`.   This of course makes sense and is easier to understand that the previous system.

| Option | Old meaning | New meaning |
| ------- | ------------ | -------------- |
| `spacingStaff` |    Place this amount of space below every staff.      | Place this amount of space between every staff within a system.           |
| `spacingSystem` |  Place this amount of space below every system.  Total space between systems includes `spacingStaff`.          |  Place this amount of space below every system.            |

------------

However, there is some sort of regression in the `spacingStaff` option as it is not working at all.   This also indicates that changes in the code were not tested for regressions, but it would be preferrable to do so at the time of a pull request.  This would be facilitated with example renderings before and after code changes affecting an option or rendering behavior being worked on, and such examples should be provided with pull requests.

With the test file at the bottom of this post, here are some examples:

The default spacings of `spacingStaff` = 12 and `spacingSystem` = 12 is working:

<img width="697" alt="Screen Shot 2020-09-19 at 10 43 10 PM" src="https://user-images.githubusercontent.com/3487289/93695236-81b95a00-fac9-11ea-9f94-a1bceef52c9e.png">

However, setting `spacingStaff` to its maximum does not change anything in the example:

<img width="697" alt="Screen Shot 2020-09-19 at 10 42 55 PM" src="https://user-images.githubusercontent.com/3487289/93695234-782ff200-fac9-11ea-9818-b9db71efb86e.png">

Setting `spacingStaff` = 0, the minimum value also does nothing:

<img width="697" alt="Screen Shot 2020-09-19 at 10 44 13 PM" src="https://user-images.githubusercontent.com/3487289/93695270-a4e40980-fac9-11ea-9ec1-6873f1c54a16.png">

Compare this to `spacingSystem` which can be changed:

Setting `spacingSystem` = 48 (maximum value):

<img width="697" alt="Screen Shot 2020-09-19 at 10 45 04 PM" src="https://user-images.githubusercontent.com/3487289/93695283-c3e29b80-fac9-11ea-9f58-19fe06e840e5.png">

Setting `spacingSystem` = 0 (minimum value):

<img width="697" alt="Screen Shot 2020-09-19 at 10 46 11 PM" src="https://user-images.githubusercontent.com/3487289/93695765-ebd1ff00-fac9-11ea-8614-65d9df6557d5.png">

This spacing is a bit odd and behaves differently from the previous minimum spacing, but it is a synthetic example so the difference is not important.

----------------------

Here is the test HTML file for the above examples:

```html
<html>
<head>
<title>Spacing test</title>
</head>
<body>

<div style="color:blue; font-size:2rem;" id="parameters"></div>
<div id="example"></div>

<script>
var vrvToolkit;
var Module = {
	onRuntimeInitialized: function() {
		vrvToolkit = new verovio.toolkit();
		prepareExample("example");
	}
};
</script>

<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit-wasm.js"></script>

<script>

var vrvOptions = {
	scale: 40,
	header: "none",
	pageHeight: 6000,
	adjustPageHeight: 1,
	pageWidth: 2100,
	spacingStaff: 12,
	spacingSystem: 12
}

function prepareExample(targetid) {
	var delement = document.querySelector("#humdrum-data");
	var data = delement.textContent;
	var svg = vrvToolkit.renderData(data, vrvOptions);
	var element = document.querySelector("#" + targetid);
	element.innerHTML = svg;
	var pelement = document.querySelector("#parameters");
	var output = "";
	var staff = vrvOptions.spacingStaff;
	staff = typeof staff === 'undefined' ? 12 : staff;
	var system = vrvOptions.spacingSystem;
	system = typeof system === 'undefined' ? 12 : system;
	output += "spacingStaff: " + staff + ", ";
	output += "spacingSystem: " + system;
	pelement.innerHTML = output;
}

</script>

<script type="text/x-humdrum" id="humdrum-data">**kern	**kern	**kern
*staff2	*staff1	*staff1
*clefF4	*clefG2	*clefG2
*k[]	*k[]	*k[]
*M4/4	*M4/4	*M4/4
*a:	*a:	*a:
*MM72	*MM72	*MM72
=1	=1	=1
4r	1r	1r
4e	.	.
4c	.	.
4f	.	.
=2	=2	=2
4G#	1r	1r
4r	.	.
8r	.	.
8d	.	.
8BL	.	.
8eJ	.	.
=3	=3	=3
8cL	4r	1r
8AJ	.	.
8F#L	4a	.
8d#J	.	.
8EL	4g	.
32e	.	.
32dn	.	.
32c	.	.
32BJ	.	.
8AL	4cc	.
32c	.	.
32B	.	.
32A	.	.
32GJ	.	.
=4	=4	=4
32F#L	4d#	1r
32G	.	.
[16A	.	.
32A]	.	.
32G	.	.
32F#	.	.
32EJ	.	.
32D#L	4r	.
32E	.	.
[16F#	.	.
32F#]	.	.
32E	.	.
32D#	.	.
32C#J	.	.
8.BBL	8r	.
.	8a	.
32C#	.	.
32D#J	.	.
8.D#TL	8f#L	.
.	8bJ	.
32C#	.	.
32D#J	.	.
=5	=5	=5
8EL	8gL	1r
32r	8eJ	.
32E	.	.
32Fn	.	.
32GJ	.	.
8AL	8c#L	.
32r	8aJ	.
32G	.	.
32F	.	.
32EJ	.	.
8DL	8fnL	.
32r	8dJ	.
32D	.	.
32E	.	.
32FJ	.	.
8GL	8BL	.
32r	8gJ	.
32F	.	.
32E	.	.
32DJ	.	.
=6	=6	=6
*	*strophe	*
*	*^	*
*	*S/sic	*S/ossia	*
8.CL	8e	8eL	4r
.	4axx	8cxxJ	.
16DJ	.	.	.
16EL	.	8Bxx	4ee
32F	.	.	.
32E	.	.	.
*	*v	*v	*
*	*Xstrophe	*
16D	8g#	.
16EJ	.	.
4F	8AL	4cc
.	32a	.
.	32gn	.
.	32f	.
.	32eJ	.
4r	8dL	4ff
.	32f	.
.	32e	.
.	32d	.
.	32cJ	.
=7	=7	=7
8r	32BL	4g#
.	32c	.
.	[16d	.
8F	32d]	.
.	32c	.
.	32B	.
.	32AJ	.
8BBL	32G#L	4r
.	32A	.
.	[16B	.
8DJ	32B]	.
.	32A	.
.	32G#	.
.	32F#J	.
8GG#L	8.EL	8r
8BBJ	.	8dd
.	32F#	.
.	32G#J	.
4E	8.G#TL	8bL
.	.	8eeJ
.	32F#	.
.	32G#J	.
=8	=8	=8
8AA	8AL	8ccL
8r	32r	8aJ
.	32A	.
.	32B	.
.	32cJ	.
8r	8dL	8f#L
8F#	32r	8ddJ
.	32c	.
.	32B	.
.	32AJ	.
8G	8GL	8bL
8r	32r	8gJ
.	32G	.
.	32A	.
.	32BJ	.
8r	8cL	8eL
8E	32r	8ccJ
.	32B-	.
.	32A	.
.	32GJ	.
=9	=9	=9
8FL	16FL	8aL
.	8f	.
8GJ	.	8bJ
.	[16fJ	.
8AL	32f]L	[4cc
.	32e	.
.	32f	.
.	32g	.
8GJ	32a	.
.	32g	.
.	32f	.
.	32eJ	.
8FL	[4d	32cc]L
.	.	32cc
.	.	32dd
.	.	32ee
8DJ	.	32ff
.	.	32ee
.	.	32dd
.	.	32ccJ
8GL	32d]L	4b
.	32d	.
.	32e	.
.	32f	.
8FJ	32g	.
.	32f	.
.	32e	.
.	32dJ	.
=	=	=
*-	*-	*-
</script>

</body>
</html>
```

**Comment by alexgnt** [comment]
@craigsapp, mentioned changes were introduced as part of implementation of feature https://github.com/rism-ch/verovio/issues/1526

The spacingStaff option has no effect here since all spacings actually a bracket group spacings, i.e. here is in play --spacing-bracket-group values.

**Comment by rettinghaus** [comment]
But shouldn't `--spacing-brace-group` and `--spacing-bracket-group` simply overrule `--spacing-staff`?

**Comment by alexgnt** [comment]
@rettinghaus, that is not stated explicitly in the ticket. There is stated:

> --spacing-bracket-group: Overrides --spacing-staff when we're within a <staffGrp> with @symbol='bracket' or 'bracketsq'.

Also, there were no possibility to check is the option is set or not. But I believe it was implemented recently and not a problem anymore.

In such case we can inherit --spacing-staff by --spacing-brace-group and --spacing-bracket-group in case they are not set. But from other side it is not hard to set them explicitly to the same value.

**Comment by rettinghaus** [comment]
Also, there is a problem with `staffDef@spacing`. The guidelines state, that this holds "the absolute distance" to the previous staff, but it's not exactly the value given in the file.
