### ISSUE TITLE
An error occurred in the “make” link when Linux installed verovio-version-1.1.6

### ISSUE THREAD

**Issue by yuanyifeng** [rism-ch/verovio#1713]
When I execute the “make" command in the "verovio-version-1.1.6/tools" folder，there have some error，i hope you can give me solution to this problem.

[ 84%] Building CXX object CMakeFiles/verovio.dir/usr/local/verovio-version-1.1.6/src/hum/MxmlMeasure.cpp.o
[ 85%] Building CXX object CMakeFiles/verovio.dir/usr/local/verovio-version-1.1.6/src/hum/MxmlPart.cpp.o
[ 86%] Building CXX object CMakeFiles/verovio.dir/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp.o
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp: In member function ‘bool hum::HumRegex::getGlobal()’:
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp:4748:9: error: no match for ‘operator!’ (operand type is ‘std::bitset<11ul>’)
  return !(m_searchflags & std::regex_constants::format_first_only);
         ^
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp:4748:9: note: candidate is:
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp:4748:9: note: operator!(bool) <built-in>
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp:4748:9: note:   no known conversion for argument 1 from ‘std::bitset<11ul>’ to ‘bool’
/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp:4749:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [CMakeFiles/verovio.dir/usr/local/verovio-version-1.1.6/src/hum/humlib.cpp.o] Error 1
make[1]: *** [CMakeFiles/verovio.dir/all] Error 2

**Comment by lpugin** [comment]
Why don't you want to use a more recent version? Updating to the latest release would be my first recommendation.

**Comment by yuanyifeng** [comment]
I must use this version1.1.6,because  our product environment is using this version， and different version of Verovio transfer different version mei file from musicXml. Please tell me the version of Gcc about the make the verovio 1.1.6 Or other solution to solute this problem. I beg your help!Thank you!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Laurent&amp;nbsp;Pugin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月30日(星期三) 下午5:37
收件人:&nbsp;&quot;rism-ch/verovio&quot;<verovio@noreply.github.com&gt;;
抄送:&nbsp;&quot;yuanyifeng&quot;<296213076@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rism-ch/verovio] An error occurred in the “make” link when Linux installed verovio-version-1.1.6 (#1713)

**Comment by rettinghaus** [comment]
@yuanyifeng Did you try `cmake . -DNO_PAE_SUPPORT=ON -DNO_HUMDRUM_SUPPORT=ON`

**Comment by craigsapp** [comment]
> @yuanyifeng Did you try cmake . -DNO_PAE_SUPPORT=ON -DNO_HUMDRUM_SUPPORT=ON

That will work.

What version of gcc are you using?  

> ‘std::bitset<11ul>’ to ‘bool’

The problem is converting a bitset into a bool, which may be compiler version related.
