### ISSUE TITLE
dur ignored in single note beams

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#173]
Hello,
If a beam contains a single note - probably incorrect, but in that case, the beam is hopefully ignored -  the duration is not taken into account. The note is always rendered as a quarter note.
Thank you

**Comment by lpugin** [comment]
I am not sure about this. I would rather suggest we try to add a schematron rule for this in the MEI schema. Other opinions?

**Comment by kepper** [comment]
there is a schematron rule for this in MEI…

**Comment by lpugin** [comment]
OK, thanks. The file is not valid.

**Comment by ahankinson** [comment]
Just to follow up -- If the single note beam is a result of a nasty bug in the Sibelius to MEI exporter, this has been fixed in version 2.0. You can download the beta version of it here which fixes it: https://github.com/music-encoding/sibmei/releases/tag/2.0.0-beta3

**Comment by efreja** [comment]
Yes, indeed it comes from the Sibelius to MEI exporter, but in version 2.0.0 beta3.
Maybe the correction is not complete as it remained some occurrences of this pattern.
All the best.

**Comment by ahankinson** [comment]
Can you send me the Sibelius file? I would like to have a look at it to see where the problem might be. You can e-mail it to me, andrew.hankinson(at)mail.mcgill.ca

**Comment by efreja** [comment]
I can't. I'm not the owner of that score... Sorry...

**Comment by ahankinson** [comment]
Ok, no worries.

**Comment by ahankinson** [comment]
One thing you might check is the beaming and flagging on the number pad for the notes in question. Sibelius lets you set notes as 'beamed' but will not draw them as beamed if there is only one of them. In other words, you could have an eighth note set as beamed, but if it is followed by a quarter note it will draw it with a flag.

**Comment by efreja** [comment]
OK , I'll try to check, otherwise I'll try to provide an excerpt...

**Comment by efreja** [comment]
OK, here's the original bar under Sibelius:
![capture d ecran 2016-02-02 a 19 39 02](https://cloud.githubusercontent.com/assets/16109195/12760051/c5754c6a-c9e4-11e5-9abf-48ca2422a9e4.png)

The mei excerpt proving the Sibelius to MEI exporter:

    <encodingDesc xml:id="m-18">
        <appInfo xml:id="m-19">
            <application xml:id="sibelius" isodate="2015-12-2T00:28:29Z" version="8010">
                <name xml:id="m-21" type="operating-system">Windows 8</name>
            </application>
            <application xml:id="sibmei" type="plugin" version="2.0.0b3">
                <name xml:id="m-23">Sibelius to MEI Exporter (2.0.0b3)</name>
            </application>
        </appInfo>

and the result:

                        <staff xml:id="m-2575" n="4">
                            <layer xml:id="m-2576" n="1">
                                <beam xml:id="m-2580">
                                    <note xml:id="m-2578" dur="8" dur.ges="128p" layer="1" oct="2" pname="d" pnum="39" staff="4" stem.dir="up">
                                        <accid xml:id="m-2579" accid="s" func="caution"/>
                                    </note>
                                </beam>
                                <note xml:id="m-2581" dur="4" dur.ges="256p" layer="1" oct="2" pname="d" pnum="38" staff="4" stem.dir="up">
                                    <accid xml:id="m-2582" accid="n" func="caution"/>
                                </note>
                                <beam xml:id="m-2585">
                                    <note xml:id="m-2583" dur="16" dur.ges="64p" layer="1" oct="2" pname="e" pnum="40" staff="4" stem.dir="up">
                                        <accid xml:id="m-2584" accid="n" func="caution"/>
                                    </note>
                                    <note xml:id="m-2586" artic="acc" dur="16" dur.ges="64p" layer="1" oct="2" pname="c" pnum="37" staff="4" stem.dir="up">
                                        <accid xml:id="m-2587" accid="s"/>
                                    </note>
                                </beam>
                                <beam xml:id="m-2591">
                                    <note xml:id="m-2589" dur="8" dur.ges="128p" layer="1" oct="2" pname="c" pnum="37" staff="4" stem.dir="up">
                                        <accid xml:id="m-2590" accid.ges="s"/>
                                    </note>
                                </beam>
                                <note xml:id="m-2592" dots="1" dur="4" dur.ges="384p" layer="1" oct="2" pname="d" pnum="39" staff="4" stem.dir="up">
                                    <accid xml:id="m-2593" accid="s"/>
                                </note>
                            </layer>
                        </staff>

There are 3 beams in the MEI and one in the score..

All the best and Thanks to the Verovio team :-)

**Comment by ahankinson** [comment]
If you get a moment, let me know what the beam settings look like for these notes...

**Comment by efreja** [comment]
I've checked, the notes in question aren't beamed. Cheers
