### ISSUE TITLE
highlight the first staff in blue

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1737]
Now I can use $(".measure.staff~.staff").attr("fill", "#00e"). attr("stroke", "#00e"); command to highlight the second staff of every measure

I try to use $(".measure.staff").attr("fill", "#00e"). attr ("stroke", "#00e"); command to highlight the first staff of each bar, but not working?

Is there any way to change the color of the first staff in each measure?

**Comment by craigsapp** [comment]
I could do it with two selectors:

var staves1 = document.querySelectorAll("svg svg g.measure g:not(.staff) + .staff");
var staves2 = document.querySelectorAll("svg svg g.measure g.staff:first-child");

staves1 are red and staves2 are green in the following example:


<img width="947" alt="Screen Shot 2020-10-12 at 1 13 48 AM" src="https://user-images.githubusercontent.com/3487289/95721979-31e13500-0c28-11eb-8833-2ca566d84e00.png">

**Comment by yangyangnote** [comment]
Thanks @craigsapp   ，I found another way. When I want to make the first track gray, I need to use two sentences
Although a bit counterintuitive
$(".measure .staff" ).attr("fill", "#ccc").attr("stroke", "#ccc");
$(".measure .staff ~ .staff " ).attr("fill", "#000").attr("stroke", "#000");
