### ISSUE TITLE
Ligature test crashing on Doc::GetGlyphWidth

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#1752]
https://github.com/rism-ch/verovio.org/blob/gh-pages/_tests/ligature/ligature-001.mei

Introduced in #1630

**Comment by rettinghaus** [comment]
Something is wrong here: 
https://github.com/rism-ch/verovio/blob/f1ba46ddebec6053ba42261e2422ca1310ba5f3c/src/layerelement.cpp#L452

In all cases the boolean should be true in this example, but at some point it is false, causing https://github.com/rism-ch/verovio/blob/f1ba46ddebec6053ba42261e2422ca1310ba5f3c/src/layerelement.cpp#L467 to fail.

**Comment by lpugin** [comment]
@rettinghaus are you trying to fix it?

**Comment by rettinghaus** [comment]
Not really. Was just curious why it happens.

**Comment by lpugin** [comment]
OK. It is not very clear. Do you think it is better to revert the PR for now?

**Comment by lpugin** [comment]
Hopefully fixed with 3b59f01956754fb06c5fda92833cca12a079fe2b 
* All tests build now successfully. 
* Example for the original PR shows
<img width="627" alt="image" src="https://user-images.githubusercontent.com/689412/96842857-d98f0c00-144d-11eb-87ca-ef9b5c62def9.png">

* Waiting for https://github.com/MeasuringPolyphony/mp_editor/issues/71 to be checked before closing since this regression it probably its caused.
