### ISSUE TITLE
only deploy on main repo

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1758]
@musicEnfanthen is there a way in GitHub Actions to call the deploying only on the main repo? It's a bit annoying, that forks always fail here.

**Comment by musicEnfanthen** [comment]
See #1757

**Comment by musicEnfanthen** [comment]
But probably, it will fail nonetheless. You may need to set a deploy key on your `verovio.org` fork to communicate with your `verovio` fork.

**Comment by rettinghaus** [comment]
You shouldn't need to fork `verovio.org` too.

**Comment by musicEnfanthen** [comment]
Ok, will try to add a flag to skip deploy steps if needed. Is this a way to go?(@rettinghaus @lpugin )
