### ISSUE TITLE
Configuration of visibility of bar numbers.

### ISSUE THREAD

**Issue by nikobeer** [rism-ch/verovio#177]
In some circumstances it would be nice to have the possibility to configure whether bar numbers are rendered or not (e.g. „no bar numbers“, „only on system/page breaks“, „every nth bar“, „every bar number“ …).

**Comment by rettinghaus** [comment]
At first we should react to the `@mnum.visible` on `<scoreDef>` to easily switch off numbering.

**Comment by rettinghaus** [comment]
Now, that measure numbers are sub elements of measure, we could add them to every measure in SVG output by default, making them invisible. Then making them visible would be very easy with CSS.

**Comment by lpugin** [comment]
I would suggest to revised `<scoreDef>` attributes first and then we can implement this accordingly
