### ISSUE TITLE
gh-actions: compiler on macos uses default AppleClang instead of specified compilers

### ISSUE THREAD

**Issue by musicEnfanthen** [rism-ch/verovio#1772]
Compiler step in build workflow uses default AppleClang on macOs runner. 

Seems to be a known issue: 
https://github.com/OpenTimer/OpenTimer/issues/19
https://github.com/conan-io/cmake-conan/issues/159
https://github.com/conan-io/cmake-conan/pull/226/files
https://github.com/sergeyklay/ytc/commit/84c46f4dd3f8d958e9c9c478c45499e24d977fe1

**Comment by musicEnfanthen** [comment]
Ok, managed to set up macos-latest with gcc-9 and with XCode-12.1 (uses XCodeDefault clang/AppleClang 12).

Could someone have a look, if that's what's needed: https://github.com/musicEnfanthen/verovio/runs/1288567386?check_suite_focus=true

**Comment by musicEnfanthen** [comment]
BTW, while digging into this issue, I just recognized that CMAKE default version on Ubuntu runner is 3.17.0, while on macOs runner it is 3.18.4

Is this an issue, or fine, given that we build the JS Toolkit with Ubuntu runner...?

**Comment by lpugin** [comment]
Looks all good to me. Please re-open if not. Thanks!
