### ISSUE TITLE
Enable build without glyph count check

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1779]
Would it be possible to introduce a build parameter to turn off the check for the number of SMuFL glyphs?

**Comment by lpugin** [comment]
Yes. Having a runtime option (e.g., `--no-glyph-count-check`) would also be a valid solution for me. Would that work?

**Comment by rettinghaus** [comment]
I don't think that a runtime option would make too much sense, as it basically always should work. Perhaps it would be good to only check in debug mode, or just throw a debug message if there is something wrong.

**Comment by lpugin** [comment]
> I don't think that a runtime option would make too much sense, as it basically always should work

What do you mean? I don't think it would. If the font glyphs are missing it should not work. This was basically added to make sure users would not install the command line version of Verovio, and then run a newer version without installing the new font, which would crash. So it is not so much a debug thing. 

What is the use case where this is problematic for you?

**Comment by rettinghaus** [comment]
What I originally had in mind will not be possible without greater refactoring of some code. Closing this for now.
