### ISSUE TITLE
better feedback for rejected files in MEI Viewer

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#178]
when Verovio doesn't accept a file in the Verovio viewer, it would be good to get some kind of feedback why it was rejected. No need for a full-blown analysis, even a simple indication _that_ it has been rejected would be good.

**Comment by ahankinson** [comment]
Seems to me that the fact that it isn't showing up is a pretty good indication that it has been rejected. :smile:

(kidding! kidding!)

**Comment by kepper** [comment]
well, but sometimes you make subtle changes to a file, and Verovio just shows the old one – and you spend quite some time to recognize that nothing has changed ;-)

**Comment by lpugin** [comment]
What helps is to do a try and catch in JavaScript. See the mei-viewer.xhtml for this, which does:

```
        try {
            vrvToolkit.loadData(data);
        }
        catch(err) {
            $('#err').html(err);
            $('#errorDialog').modal();
        }
```

**Comment by kepper** [comment]
yes, but I'd like to see this in the "official" MEI Viewer – sometimes this tool is very handy to get a first impression of the quality of a file, without having to set up something on my own… Pretty pretty please, with cream on top ;-)

**Comment by ahankinson** [comment]
It may be that your file doesn't actually raise an error to catch...

**Comment by lpugin** [comment]
It seems to work only if you have not selected a local file first. That is, if you go there
http://www.verovio.org/mei-viewer.xhtml
And then select a file that Verovio cannot handle, then it shows an error. If you have selected and loaded a file that works before, it does not. I do not understand why.

**Comment by lpugin** [comment]
@kepper could you have a try?

**Comment by kepper** [comment]
I get an error after a fresh reload in Safari, but not in Firefox…

**Comment by lpugin** [comment]
I get the error on Firefox too, version 44

**Comment by lpugin** [comment]
It depends ;-) Actually not so easily because Verovio fails on assert, which are intended but not designed to passed a message back.

**Comment by kepper** [comment]
both Maja and I tried – doesn't work. The pre-selected "Am Brunnen vor dem Tore" gets rendered, and then after loading the iffy file, nothing happens – no error message. We both use FF 44.0.2…

**Comment by lpugin** [comment]
Could you send me the two files?

**Comment by lpugin** [comment]
PS I am now running FF 45.0.1

**Comment by lpugin** [comment]
PS Verovio is now showing the logs in the browser console
