### ISSUE TITLE
Add option to skip CI build on some commits

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#1784]
In some cases it can be reasonable not to rebuild everything on a commit. For example, when fixing a typo or when updating the changelog. Appending something like no-ci-build to the commit message could be used to skip CI.

**Comment by musicEnfanthen** [comment]
There seems to be no built-in skip option in GH actions yet, but it is possible with a workaround:

https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf

Markdown files (and others?) can be excluded from within the workflow yml with `paths-ignore`.
