### ISSUE TITLE
Coverage of accidentals in 3.0.0

### ISSUE THREAD

**Issue by ahwitz** [rism-ch/verovio#181]
Checkboxes reflect status on github.com/ahwitz/verovio, devel_ahwitz branch.

List currently ignores positioning and overlap, solely for glyph coverage.
- [x] s: Sharp.
- [x] f: Flat.
- [x] ss: Double sharp (written as 2 sharps).
- [x] x: Double sharp (written using croix).
- [x] ff: Double flat.
- [x] xs: Triple sharp (written as a croix followed by a sharp).
- [x] sx: Triple sharp (written as a sharp followed by a croix). - **Waiting on #183** 
- [x] ts: Triple sharp (written as 3 sharps).
- [x] tf: Triple flat.
- [x] n: Natural.
- [x] nf: Natural + flat; used to cancel preceding double flat.
- [x] ns: Natural + sharp; used to cancel preceding double sharp.

The following glyphs need to have the XML font snippets added (#182):
- [x] su: Sharp note raised by quarter tone (sharp modified by arrow).
- [x] sd: Sharp note lowered by quarter tone (sharp modified by arrow).
- [x] fu: Flat note raised by quarter tone (flat modified by arrow).
- [x] fd: Flat note lowered by quarter tone (flat modified by arrow).
- [x] nu: Natural note raised by quarter tone (natural modified by arrow).
- [x] nd: Natural note lowered by quarter tone (natural modified by arrow).
- [x] 1qf: 1/4-tone flat accidental.
- [x] 3qf: 3/4-tone flat accidental.
- [x] 1qs: 1/4-tone sharp accidental.
- [x] 3qs: 3/4-tone sharp accidental.

**Comment by ahwitz** [comment]
Still todo: moving vector assembly from DrawAccid to Accid, manipulated by CalculateAccidX

**Comment by lpugin** [comment]
I am actually not sure you need a vector. Wouldn't be enough to have a wstring? See Dynam::GetSymbolStr()
Then you can use DC::GetSmuflTextExtent() to get the width / height.
The only advantage I can see with a vector would be to add margin, but I don't think we need this.

**Comment by craigsapp** [comment]
Double flats are showing, but a bit too close to the notehead.  Double sharps are displayed as naturals:

<img width="396" alt="screen shot 2017-01-09 at 08 17 54" src="https://cloud.githubusercontent.com/assets/3487289/21773506/394cf126-d644-11e6-81cd-4084b04b3263.png">

MEI data

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-09 08:15:42</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-8c6bcc9</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000065863104">
                        <staffGrp xml:id="m-000000018263069">
                            <staffDef xml:id="staffdef-000000070982242" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000136006695">
                        <measure xml:id="measure-L1" n="0" right="end">
                            <staff xml:id="staff-000000083240011" n="1">
                                <layer xml:id="layer-L1F1" n="1">
                                    <note xml:id="note-L2F1" dur="4" accid="ff" oct="4" pname="f" />
                                    <note xml:id="note-L3F1" dur="4" accid="f" oct="4" pname="f" />
                                    <note xml:id="note-L4F1" dur="4" accid="n" oct="4" pname="f" />
                                    <note xml:id="note-L5F1" dur="4" accid="s" oct="4" pname="f" />
                                    <note xml:id="note-L6F1" dur="4" accid="x" oct="4" pname="f" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by ahwitz** [comment]
For what it's worth, https://github.com/ahwitz/verovio/commit/1a81aace7aa2919c1e96094aa645474eb417a836 accommodates for that by acknowledging that it's two glyphs wide.

**Comment by craigsapp** [comment]
Here is an accidental layout case that would be nice to clean up:

<img width="136" alt="screen shot 2017-01-24 at 03 32 50" src="https://cloud.githubusercontent.com/assets/3487289/22245709/3f7c5f0c-e1e6-11e6-90ff-1df8ed10d139.png">

It would be preferable if the natural sign were closer to the A2 pitch.

This is from a real musical example, but not quite the same situation:

<img width="107" alt="screen shot 2017-01-24 at 03 36 49" src="https://cloud.githubusercontent.com/assets/3487289/22245720/5d6f1950-e1e6-11e6-9d4d-7594fe45f0f4.png">

MEI data:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-24 03:32:26</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-a6ca10a</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000033975413">
                        <staffGrp xml:id="m-000000147660315">
                            <staffDef xml:id="staffdef-000000106185885" clef.shape="F" clef.line="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000101811016">
                        <measure xml:id="measure-L3" n="1" right="end">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <chord xml:id="chord-L4F1" dur="4">
                                        <note xml:id="note-L4F1S1" oct="2" pname="a" accid.ges="n">
                                            <accid xml:id="accid-000000128731336" accid="n" func="caution" />
                                        </note>
                                        <note xml:id="note-L4F1S2" accid="f" oct="4" pname="c" />
                                        <note xml:id="note-L4F1S3" oct="4" pname="d" accid.ges="n">
                                            <accid xml:id="accid-000000097681480" accid="n" func="caution" />
                                        </note>
                                    </chord>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
@pe-ro: how should 1qf, 3qf, 1qs and 3qs look like?

**Comment by craigsapp** [comment]
I like the French system:

<img width="512" alt="screen shot 2017-01-25 at 04 35 46" src="https://cloud.githubusercontent.com/assets/3487289/22290823/e7a93520-e2b7-11e6-8467-5cb8c7b3abe5.png">

take from this page:

https://en.wikipedia.org/wiki/Quarter_tone

**Comment by rettinghaus** [comment]
according to the guidelines 
> 1qf, 3qf, 1qs, 3qs represent fixed symbols (Gould, p. 96)

In SMuFL-speak:
[Stein-Zimmermann accidentals](https://w3c.github.io/smufl/gitbook/tables/stein-zimmermann-accidentals-24-edo.html)

**Comment by pe-ro** [comment]
@rettinghaus got it.
