### ISSUE TITLE
Add XML snippets for new single accid glyphs

### ISSUE THREAD

**Issue by ahwitz** [rism-ch/verovio#182]
Glyphs needed:
//    SMUFL_E270_accidentalQuarterFlatArrowUp = 0xE270,
//    SMUFL_E271_accidentalThreeQuartersFlatArrowDown = 0xE271,
//    SMUFL_E272_accidentalQuarterSharpNaturalArrowUp = 0xE272,
//    SMUFL_E273_accidentalQuarterFlatNaturalArrowDown = 0xE273,
//    SMUFL_E274_accidentalThreeQuartersSharpArrowUp = 0xE274,
//    SMUFL_E275_accidentalQuarterSharpArrowDown = 0xE275,
//    SMUFL_E280_accidentalQuarterToneFlatStein = 0xE280,
//    SMUFL_E281_accidentalThreeQuarterTonesFlatZimmermann = 0xE281,
//    SMUFL_E282_accidentalQuarterToneSharpStein = 0xE282,
//    SMUFL_E283_accidentalThreeQuarterTonesSharpStein = 0xE283,

**Comment by ahwitz** [comment]
Following will not be necessary once new implementation is complete:
    SMUFL_E263_accidentalDoubleSharp = 0xE263,
    SMUFL_E264_accidentalDoubleFlat = 0xE264,
    SMUFL_E265_accidentalTripleSharp = 0xE265,
    SMUFL_E266_accidentalTripleFlat = 0xE266,
    SMUFL_E267_accidentalNaturalFlat = 0xE267,
    SMUFL_E268_accidentalNaturalSharp = 0xE268,
    SMUFL_E269_accidentalSharpSharp = 0xE269,

**Comment by lpugin** [comment]
I would actually leave them and use them whenever possible. See also Dynam::GetSymbolStr() that does about the same for dynamics
