### ISSUE TITLE
Time Signature

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1822]
I can already load the staff in the js environment. Is there any way I can get the meter.count/meter.unit data in the Time Signature after the loading is complete?

@lpugin @craigsapp

**Comment by lpugin** [comment]
Please provide a complete description of the issue (not of what you are trying to achieve for your project) AND an minimal MEI example. Thanks.

**Comment by yangyangnote** [comment]
Sorry, I may not be clear enough, and the examples are not detailed enough, but I think the application of real projects can better test the framework. I will pay attention to preparing detailed examples related to the framework when I raise questions, rather than simply questioning. Hope you can understand


<img width="814" alt="屏幕快照 2020-11-13 下午2 35 53" src="https://user-images.githubusercontent.com/19338570/99037056-e8d12780-25bd-11eb-8e62-e9f145288f07.png">

![IMG_0067](https://user-images.githubusercontent.com/19338570/99037420-9a705880-25be-11eb-9d20-9d5789a0ccf9.PNG)

As shown in the figure, is there any way to get the numerator and denominator of the time signature? thanks for your help！！

**Comment by craigsapp** [comment]
To extract the meter information from the MEI data within webpage using javascript, the general technique will be to use xpath:

https://www.w3schools.com/xml/xpath_syntax.asp
https://www.w3schools.com/xml/xpath_intro.asp

Look specifically at this page for xpath use in javascript:
https://www.w3schools.com/xml/xpath_examples.asp

This is similar to CSS and built-in javascript functions such as `document.querySelecotr()`, but specifically for XML data.

More advanced processing of XML data can be done with XSLT:
https://www.w3schools.com/xml/xsl_intro.asp
but this should not be necessary for your current case of extracting the meter information.

**Comment by yangyangnote** [comment]
@craigsapp   Thank you for your guidance. To know that your help is of great help to me, let me try to study it carefully in this direction.
