### ISSUE TITLE
Left and right hand function

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/verovio#1827]
@craigsapp 
1. I now want to make a left and right hand function, similar to this
When I select the right hand, the player only plays the first staff of each song
When I choose the left hand, the player only plays the second staff of each song

2.Now I can drive the staff to play and color the notes, and I can also get the noteid of each note, but I can't get the staff number of each note.
Do you know there are other ways to achieve this function?
I found that every measure / staff has a corresponding n = "1", n = "2", is it helpful to solve this problem?

`<measure xml:id="measure-0000000289787772" n="10">
                            <staff xml:id="staff-0000000265812789" n="1">
                           ......
                            </staff>
                            <staff xml:id="staff-0000000616516140" n="2">
                             ....
                            </staff>
                        </measure>`
Thank you for your help！

**Comment by ahankinson** [comment]
Hi @yangyangnote -- if you're looking for support, it's probably better to use the Music Encoding slack channel. The GitHub issue tracker is used primarily for working on bugs and features in the software. 

Details of how to join are here: https://music-encoding.org/community/community-contacts.html

Once you've joined there is a `#verovio` channel.

**Comment by yangyangnote** [comment]
OK thank you! @ahankinson
