### ISSUE TITLE
Lost documentation?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#186]
The webpage:

http://www.verovio.org/command-line.xhtml

Says: "Building and installing instructions are available on the download page."

The current download page: http://www.verovio.org/download.xhtml

No longer contains the instructions, and instead they can be found here:

https://github.com/rism-ch/verovio/wiki/Building-instructions

Formerly the download page had these instructions:

![screen shot 2016-06-06 at 2 58 05 pm](https://cloud.githubusercontent.com/assets/3487289/15839238/2198a66c-2bf7-11e6-8f1b-f0ae38c6babe.png)

The building-instructions wiki page is pretty much the same:

![screen shot 2016-06-06 at 2 58 53 pm](https://cloud.githubusercontent.com/assets/3487289/15839258/43d178bc-2bf7-11e6-97e1-463918f8e43d.png)

but does seem to have new information about PAE compiling, so apparently it is newer.  If the building-instructions wikipage is to replace the information on the download page, then a link from the command-line page directly to the building-instructions wikipage would be useful, as the building instructions are no longer available on the download page.

**Comment by lpugin** [comment]
This was moved to the wiki
https://github.com/rism-ch/verovio/wiki
I'll update the the command-line page, thanks.
