### ISSUE TITLE
text for version rendering display

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1878]
In this pull-request comment:

https://github.com/rism-ch/verovio/pull/1869#issuecomment-742425833

It is noted that the order of the before and after renderings in this display:

<img width="521" alt="Screen Shot 2020-12-10 at 2 51 56 AM" src="https://user-images.githubusercontent.com/3487289/101762778-b3233f80-3a92-11eb-87bb-a9312ff3b86e.png">

Are the "after" version first, and then the "before" version underneath.

However, the text says "Show before/after" which implies the other way around.

Either the order of the images for before and after should be adjusted to be "before" first and then "after" or the text should change to "Show after/before".

**Comment by lpugin** [comment]
It should now be OK. We will see it with the next PR that yield changes and can re-open the issue if necessary.
