### ISSUE TITLE
@n="0" for measures

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#188]
When I try to set @n="0" with SetN(0) on measures, the attribute is not added to the MEI data:

```xml
             <measure xml:id="measure-000000007900448" />
             <measure xml:id="measure-000000169519888" n="1" />
             <measure xml:id="measure-000000119438290" n="2" />
             <measure xml:id="measure-000000153391916" n="3" />
             <measure xml:id="measure-000000174811136" n="4" />
```

A zero seems to be permitted when setting the value of @n:

https://github.com/rism-ch/verovio/blob/master/libmei/atts_shared.h#L913

```cpp
    void SetN(int n_) { m_n = n_; };
```

But HasN() uses 0 as meaning the value is not set:

https://github.com/rism-ch/verovio/blob/master/libmei/atts_shared.cpp#L1154-L1157

```cpp
bool AttCommon::HasN() const
{
    return (m_n != 0);
}
```

According to the MEI 2.1.1 (MEI 2013) documentation (also MEI 2.0.0/2012), @n is an xsd:NMTOKEN:

http://music-encoding.org/documentation/2.1.1/att.common

&lt;&lt;The type xsd:NMTOKEN represents a single string token. xsd:NMTOKEN values may consist of letters, digits, periods (.), hyphens (-), underscores (_), and colons (:). They may start with any of these characters. xsd:NMTOKEN has a whiteSpace facet value of collapse, so any leading or trailing whitespace will be removed. However, no whitespace may appear within the value itself.&gt;&gt;

So is there a reason @n is limited to an integer?  And if so, why is "0" excluded?  I want to use that for measure "0" which represents a pickup measure (incomplete measure at the start of a piece).

**Comment by pe-ro** [comment]
There's no reason `"0"` should be excluded as a label; however, using `@n="0"` to indicate an incomplete measure is an abuse of `@n`.  `@metcon` should be used instead.

**Comment by craigsapp** [comment]
I am using @n="0" as the measure number, not to indicate and incomplete measure.

**Comment by lpugin** [comment]
I fixed this. @n="0 is now not excluded anymore.

**Comment by craigsapp** [comment]
Hi Laurent,

> I fixed this. @n <https://github.com/n>="0" is now not excluded anymore.
>
How do i get fixes such as this one and the extra-padding fix into the
develop-humdrum branch?

-=+Craig

**Comment by lpugin** [comment]
You need to merge develop into develop-humdrum

**Comment by craigsapp** [comment]
Hi Laurent,

That was easy:
    git pull origin develop
I thought that was going to download the develop branch and then I would
have to figure out how to merge, but it does the merging into the current
branch automatically.

The spacing in the first measure of the systems looks good now:

[image: Inline images 1]

The proper thing to do will be to repeat the measure number on the second
half of an incomplete barline, since no bar number is printed if @n is not
given:

[image: Inline images 4]


Here is where I repeat the @n="7" for the second half of the measure after
the repeat sign:

[image: Inline images 3]


I notice that the top example is not right-justified on the last system.
How can I indicate to verovio that the last line of music should be right
justified?

-=+Craig

**Comment by pe-ro** [comment]
I don't see the images.

**Comment by craigsapp** [comment]
They did not pass through the mail system properly...  They should be available on the webpage for the issue now:
    https://github.com/rism-ch/verovio/issues/188

**Comment by lpugin** [comment]
I would expect the ```@n``` to be repeated, so I think it is all good.

Justification: we need to add an option for this. I will keep it unjustified by default since with automatic layout with the algorithm we have now we can often have a last system with only one or a few measures, and justifying this does not look great.

**Comment by craigsapp** [comment]
Hi Laurent,

Yes, stretching a whole measure to justify would not look good.

You will have to recursively acquire measures from previous systems to fill
in space on the last line, and the previous systems may need to acquire
measures from more previous systems, and so on in theory to the beginning
of the piece.

Some sort of waterfilling algorithm would probably be needed.  Here is a
random paper about the general technique (but not in music):
     http://publik.tuwien.ac.at/files/PubDat_208166.pdf


-=+Craig

**Comment by lpugin** [comment]
Thanks for the tip. However, it would take me longer to understand the paper than to come up with something appropriate for music... ;-)

**Comment by lpugin** [comment]
```@n="0"``` is now supported. We can improve this once MEI has distinct attribute definitions between ```@n``` in measure and in staff or layer
