### ISSUE TITLE
Ability to turn off condensing for MusicXML scores

### ISSUE THREAD

**Issue by matangover** [rism-ch/verovio#1883]
I looked for a way to turn off condensing (hiding empty staves) for MusicXML scores but it seems impossible. For MEI scores, we can use `optimize="false"`, but I don't see an equivalent in MusicXML.  Also, `--condense-encoded` works only for `--breaks encoded` IIUC. If I missed a valid way to do this, please advise.

**Comment by rettinghaus** [comment]
This is connected to #1667 and will be addressed when condense option is improved.

**Comment by matangover** [comment]
Great. Your fix to #1667 has already improved the default heuristics in my case, thank you.

**Comment by rettinghaus** [comment]
@matangover The improvements have been merged, so now you could use `--condense none`. Please test and close this ticket eventually.

**Comment by matangover** [comment]
Thank you.
