### ISSUE TITLE
DEFINITON_FACTOR -> DEFINITION_FACTOR?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#191]
On line 202 of include/vrv/vrvdef.h:

https://github.com/rism-ch/verovio/blob/master/include/vrv/vrvdef.h#L202

there is a define called "DEFINITON_FACTOR".  What does this mean, as "definiton" is not an English word?  Maybe it is Swissglish?  I am thinking that it should perhaps be DEFINITION_FACTOR, with an extra "I" added.  Note that the define is used in several files as well, which would have to change if you alter the spelling:

```
include/vrv/vrvdef.h
src/aligner.cpp
src/doc.cpp
src/iomei.cpp
src/style.cpp
src/svgdevicecontext.cpp
src/view_floating.cpp
src/view_tuplet.cpp
```

**Comment by lpugin** [comment]
Obviously a typo... Fixed with 49c819cf47472e9af916e42225dd36e9e8d83dce
