### ISSUE TITLE
Make all importers optional

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#192]
It would be good to allow for all data importers (other than MEI import) to be optional, and have an official standard way of handling it (described on the wikipage for converters). 

For example, there is a preprocessor define for NO_PAE_SUPPORT.   I added one for NO_HUMDRUM_SUPPORT, but it does not behave exactly the same way as NO_PAE_SUPPORT, and I suppose I should adjust it.  I just blank out the entire code with the option turned on for the Humdrum importer (so the importer class is undefined), but perhaps you want me to just blank out the protected/private data (other than m_filename perhaps), and keep the class and the public interface functions visible.

It would also be useful to add optional support for MusicXML and DARMS importers.

Perhaps an optional suppression of non-MEI or SVG output, such as MIDI?

**Comment by lpugin** [comment]
What would be the advantage of this? the NO_PAE_SUPPORT was introduced because of some compilation issues on some Windows version (and the dependency on regex).

**Comment by craigsapp** [comment]
Mostly I am thinking that this would allow a smaller footprint of the
executable for web applications (it is not a problem for the command-line
version).  What is the size difference of the emscripten file when The PAE
support is or is not included?

Currently I am not using C++11 regular-expressions in the Humlib library or
the Humdrum importer, but I really want to :-), so if I break down, the
Humdrum importer would need to be excludable for the same reason.

**Comment by lpugin** [comment]
> What is the size difference of the emscripten file when The PAE
support is or is not included?

I haven't check this. I will see if it makes a difference that is significant enough

**Comment by lpugin** [comment]
PS I think NO_PAE_SUPPORT was introduced before we enabled to C++11.

**Comment by craigsapp** [comment]
C++11 regular expressions are implemented in the current versions of clang,
but not in GCC before version 5.1, so compiling on most linux machines
(which usually still have gcc 4.9) might currently be as tricky as in
Windoze.

**Comment by craigsapp** [comment]
I have correctly implemented NO_HUMDRUM_SUPPORT.  When that is turned on, the emscripten-compiled toolkit compiles 412 kB smaller, which is 9.6% of the total size of the javascript executable.  When Humdrum support is disabled, a Humdrum file can be loaded, but the SVG output will be blank.

The emscripten build.sh script is not linked to cmake Makefile generation?  I had to manually activate the define variable (temporarily defined it in iohumdrum.h).  So alternate instructions for how to turn on/off importers with emscripten would be good.

Note that on the page:
    https://github.com/rism-ch/verovio/wiki/Building-instructions
The instructions say:

```bash
 cmake . -DNO_PAE_SUPPORT=OFF
```

but you almost certainly mean:

```bash
 cmake . -DNO_PAE_SUPPORT=ON
```

Since that will turn on the NO_PAE_SUPPORT feature (which then turns off PAE :-)

**Comment by lpugin** [comment]
Correct, fixed.

**Comment by lpugin** [comment]
This was added in https://github.com/rism-ch/verovio/commit/99c402a10036a0511e19a585d11aea350f2596cd
