### ISSUE TITLE
consistent attibute order printing

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#193]
When printing MEI output from verovio, attributes are printed in a random order.  In order for the data to be easier to read, the attributes should be output in a consistent order.  Probably the best thing to do is to sort alphabetically, but as long as it is consistent some other ordering system would also work.

Here is an example:

```xml
<layer xml:id="layer-000000101307397" n="1">
   <note xml:id="note-000000148392760" dur="4" oct="4" pname="c" accid.ges="s" />
   <note xml:id="note-000000164361420" dur="4" accid="s" oct="4" pname="c" accid.ges="s" />
   <note xml:id="note-000000114175846" dur="4" accid="n" oct="4" pname="c" />
   <note xml:id="note-000000176805127" dur="4" oct="4" pname="c" accid.ges="n" />
</layer>        
```

Compare to a consistent ordering (not alphabetical, though), which is easier to read:

```xml
<layer xml:id="layer-000000101307397" n="1">
   <note xml:id="note-000000148392760" dur="4" oct="4" pname="c" accid.ges="s" />
   <note xml:id="note-000000164361420" dur="4" oct="4" pname="c" accid="s" accid.ges="s" />
   <note xml:id="note-000000114175846" dur="4" oct="4" pname="c" accid="n" />
   <note xml:id="note-000000176805127" dur="4" oct="4" pname="c" accid.ges="n" />
</layer>        
```

**Comment by lpugin** [comment]
The output is generate by pugixml. It seems that we cannot control this.

**Comment by ahankinson** [comment]
Perhaps xmldiff would help here?

https://pypi.python.org/pypi/xmldiff
