### ISSUE TITLE
Uninterpreted stroke in articulation

### ISSUE THREAD

**Issue by jacekiwaszko1** [rism-ch/verovio#1934]
In 17<sup>th</sup>-19<sup>th</sup> century manuscripts there's you can find different type of articulation marks notated as stroke. Few examples:

In Organo stroke usually means _tasto solo_:

![stroke-org](https://user-images.githubusercontent.com/29225574/103992384-50f25300-5194-11eb-8665-854b216c7cc9.png)

In violins it can be either _détaché_ or _staccatissimo_:

![stroke-vl1](https://user-images.githubusercontent.com/29225574/103992560-94e55800-5194-11eb-8dc0-7259d1063842.png)

![stroke-vl2](https://user-images.githubusercontent.com/29225574/103992573-99aa0c00-5194-11eb-8fc2-a513e7aacd6e.png)

In [MEI guidelines](https://music-encoding.org/guidelines/v4/data-types/data.articulation.html) stroke is listed as one of available articulation encoding. 

Would it be possible to render it in Verovio?

**Comment by jacekiwaszko1** [comment]
I checked SMuFL documentation, and I think there's one good character there, that can be used from [Other baroque ornaments](https://w3c.github.io/smufl/gitbook/tables/other-baroque-ornaments.html) palette - **U+E583** = _ornamentVerticalLine_:

![stroke](https://user-images.githubusercontent.com/29225574/105473543-853e3700-5c9d-11eb-92a5-0802435d6ec7.png)

There's also staccatissimo stroke in articulation (**U+E4AA** = _articStaccatissimoStrokeAbove_, **U+E4AB** = _articStaccatissimoStrokeBelow_), but I think it should not be used in any other context, then staccatissimo.

**Comment by craigsapp** [comment]
Yes, I think that is the one that gives the best representation.  Is there a way of representing that in MEI as an articulation @rettinghaus?  Or would there be some explicit font encoding method to chose that glyph?

**Comment by rettinghaus** [comment]
You could probably use `<artic glyph.num>` for this, but I don't think it's implemented yet.

**Comment by lpugin** [comment]
@jacekiwaszko1 only to double check. These are different from articStaccatissimoStrokeAbove/Below in SMuFL https://w3c.github.io/smufl/gitbook/tables/articulation.html. Correct?

**Comment by jacekiwaszko1** [comment]
> @jacekiwaszko1 only to double check. These are different from articStaccatissimoStrokeAbove/Below in SMuFL https://w3c.github.io/smufl/gitbook/tables/articulation.html. Correct?

I would say so. Only the last example from my first comment could be encoded as staccatissimo, but it can be also _détaché_, as far as I'm concerned. Uninterpreted stroke (from Other baroque ornaments) is - in my opinion - the best solution there.

![_staccatissimo_ / _détaché_](https://user-images.githubusercontent.com/29225574/103992573-99aa0c00-5194-11eb-8fc2-a513e7aacd6e.png)

**Comment by jacekiwaszko1** [comment]
@craigsapp 

> Yes, I think that is the one that gives the best representation. Is there a way of representing that in MEI as an articulation @rettinghaus? Or would there be some explicit font encoding method to chose that glyph?

I think it can be matched with **stroke** mentioned at the end of the _Allowed Values_ section in [data.ARTICULATION](https://music-encoding.org/guidelines/v4/data-types/data.articulation.html):

|||
|---:|:---|
|**stroke**|Uninterpreted stroke.|

Am I right?

**Comment by lpugin** [comment]
![image](https://user-images.githubusercontent.com/689412/106170985-58a08880-6191-11eb-8d14-e705ced080e5.png)

**Comment by craigsapp** [comment]
Is is possible to set the glyph.num of an artic?  I see `Att::setGlyphnum()`

I see this line in `libmei/atts_externalsymbols.cpp`

```cpp
this->SetGlyphNum(StrToHexnum(element.attribute("glyph.num").value()));
```
in `AttExtSym`, so perhaps that class needs to be inherited by `Artic`?  Or I have to access it though an interface class for `Artic`?

Also, is it necessary to specify the glyph for a stroke?  Otherwise it seems to be rendered as nothing so it might as well be assigned the `#E583` glyph by default.

**Comment by lpugin** [comment]
I think you don't have the latest commits https://github.com/rism-ch/verovio/commit/0a3abb6dfe2a64d9099fb7c589d748b88f808a5b
