### ISSUE TITLE
Separate Leipzig in extra repository 

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1941]
For easier development, redistribution, and licensing it would be good to have a separate repo for Leipzig.

**Comment by lpugin** [comment]
Where is this problematic for you, and how do you want this to be organized? We would still need to have the SVG font(s) in the Verovio repo.

**Comment by craigsapp** [comment]
Here is a model repository for the Leipzig font:

https://github.com/MuseScoreFonts/Leland

I would say that you would not need to then include the font as a subrepository in verovio, but having it also as https://github.com/rism-ch/Lepzig might be interesting.

**Comment by rettinghaus** [comment]
Instead of having a separate branch in Verovio which is always a bit complicated to keep track of, it would be much easier. Also there is missing some font and licensing information.

**Comment by lpugin** [comment]
I am trying to understand how it would work. I imaging we would like to have a repository with:
* Leipzig-5.2.sfd
* README.md
* FONTLOG.txt
* LICENSE.txt

When a glyph is added, then the sfd file is copied to the verovio repos, where the SVG file of the new font is generated as well as the metadata.json file and the other files embedded in verovio. This would be more or less equally simple as what we currently have, but it does gives the font a better visibility. That is good.

**Comment by rettinghaus** [comment]
That's the plan. I think we could even have a GitHub Action to generate the font on every push, to provide a release of the OTF version, and deploy the SVG to Verovio.

**Comment by lpugin** [comment]
I'll create the repo. As I understand you are volunteering to write the GH action ;-) Thanks!

**Comment by lpugin** [comment]
Here we go https://github.com/rism-digital/leipzig
