### ISSUE TITLE
CamelCase inconsistency in method names

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#195]
Just to be picky ;-), I will point out that the CamelCase names for SetStartid() and SetEndid()  (and probably similar) are not consistent with CamelCase.

In the following example code:

```cpp
// keep the id as end id for the tie
endid = note->GetUuid();
layer->AddLayerElement(note);

// create the tie with appropriate start and end ids
tie = new Tie();
tie->SetStartid(startid);
tie->SetEndid(endid);
```

GetUuid() is correct, because this stands for "get UUID", where "get" is a word and "UUID" is a word (specifically an abbreviation).

SetStartid() is not correct, because this stands for "set start ID", which should more logically be CamelCased to "SetStartId".

Of course it does not matter if you change it as the compiler will point out if it is spelled differently from the definition.  You could always have an alias which is CamelCased correctly...

**Comment by lpugin** [comment]
The inconsistency comes from the MEI schema. The method name is generated by LibMEI
