### ISSUE TITLE
chord/note attachment of fermata?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#197]
In the sample converter encoding:

https://github.com/rism-ch/verovio/blob/master/doc/importer.md

There is a fermata on the last chord:

![screen shot 2016-06-20 at 7 58 22 pm](https://cloud.githubusercontent.com/assets/3487289/16216685/b4de2d36-3721-11e6-8a0e-fb11dd0bd24e.png)

I am wondering why you attach the fermata to a note in the chord rather than on the chord itself:

``` cpp
chord = new Chord();
chord->SetDur(DURATION_4);
note = new Note();
note->SetPname(PITCHNAME_c);
note->SetAccidGes(ACCIDENTAL_IMPLICIT_s);
note->SetOct(5);
chord->AddLayerElement(note);
note = new Note();
note->SetPname(PITCHNAME_e);
note->SetOct(4);
note->SetFermata(PLACE_below);
chord->AddLayerElement(note);
layer->AddLayerElement(chord);
```

As chord elements may also posses @fermata.

Getting ahead of myself, can MEI/verovio encode/display signum congruentiae in CMN mode?  For example:

http://josquin.stanford.edu/data?a=notation&f=Duf3017

![screen shot 2016-06-20 at 8 07 50 pm](https://cloud.githubusercontent.com/assets/3487289/16216841/06bc0208-3723-11e6-9d91-3bb0ee7e22fd.png)

These function similar to fermatas as graphical objects, so that is why I am wondering here.

**Comment by lpugin** [comment]
Actually it is probably best to use fermata elements, which will be added soon in Verovio.

For signum congruentiae we need to look first at the situation in MEI

**Comment by pe-ro** [comment]
The `<fermata>` element is a specialized form of `<dir>`.  We can follow that pattern with signum congruentiae or they can be handled with `<dir>`.  A special element is called for if signum congruentiae need special attributes / content.  The danger is that even if we create specific elements, folks might 'abuse' `<dir>` anyway. So, what attributes do sig. con. need that `<dir>` doesn't provide?

**Comment by lpugin** [comment]
`fermata` element support was added
