### ISSUE TITLE
Sb missing in ABC and MusicXML import

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#1971]
When importing an ABC or a MusicXML file and saving it to MEI with `-a -t mei` there are no `sb` elements showing up while conversion of page breaks to `pb` still works. 

This is new since PR #1944.

**Comment by lpugin** [comment]
I tried with this file https://github.com/rism-ch/verovio.org/blob/gh-pages/examples/musicxml/Bach_Invention_No_1_BVW.772.xml with add default options. This is what I get

with `--breaks encoded`

![image](https://user-images.githubusercontent.com/689412/105179912-345a0180-5b2a-11eb-9395-c0ff8c00f58c.png)

with `--breaks auto`

![image](https://user-images.githubusercontent.com/689412/105179934-39b74c00-5b2a-11eb-8154-002d115c6094.png)

The layout is different, so it seems that `sb` are showing and more elaborated description of the issue would be helpful.

**Comment by rettinghaus** [comment]
Look at the ticket. It says converting to MEI. So when I use `-a -t Mei` the resulting MEI file has no `sb`.

**Comment by lpugin** [comment]
Look at the ticket: it says "they're missing in renderings."

**Comment by rettinghaus** [comment]
Yeah, sorry! This should have meant: Converting to MEI and then rendering it. Obviously this is clear. I'll update my crappy ticket.

**Comment by lpugin** [comment]
> Obviously this is clear.

I must be stupid then ;-) Sorry, I was only trying to help

**Comment by rettinghaus** [comment]
No, me stupid. What I meant was: when sb is missing in MEI it is clear that breaks won't work in rendering.

**Comment by lpugin** [comment]
It looks like this has been fixed with 601abae7e2df35e5fc110eb81fdb0691d6ae57b0 @rettinghaus could you confirm?

**Comment by rettinghaus** [comment]
Yes, seems to work again.
