### ISSUE TITLE
temporary last system justification algorithm

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#198]
It would be handy to have a temporary justification method for the last system: if the last system is at least 80% full (or some other cut-off), then justify the last system.

Example usage:

![screen shot 2016-06-20 at 9 03 24 pm](https://cloud.githubusercontent.com/assets/3487289/16217728/f7a78712-372a-11e6-947d-a2f263cbe2fb.png)

**Comment by lpugin** [comment]
This was added to d8be65507c7a8cfebc2d997dedd036c8317e728e

However, at this stage there is no option to change the limit which is currently set at 80%

**Comment by craigsapp** [comment]
That will be nice even with the hard-coded cut-off until a more sophisticated measure layout system is implemented.


Two systems, using spacing factor 0.48:

![screen shot 2016-07-14 at 6 05 58 pm](https://cloud.githubusercontent.com/assets/3487289/16860516/c4ba195c-49ed-11e6-912d-69176b17ec6c.png)

Three systems using spacing factor 0.58:

![screen shot 2016-07-14 at 6 08 10 pm](https://cloud.githubusercontent.com/assets/3487289/16860539/fb11ee62-49ed-11e6-92a2-8e59e4ce6214.png)

**Comment by earboxer** [comment]
It would be nice to have this as an option (or at least an option to always justify the last system).
