### ISSUE TITLE
System justification

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#1985]
This issue can be used to store notes about improving system justification.

Here is a first example:

<img width="599" alt="Screen Shot 2021-01-21 at 11 56 28 PM" src="https://user-images.githubusercontent.com/3487289/105463267-a3c41400-5c44-11eb-9fa5-caa495f28f4e.png">

<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-21T23:56:35" version="3.2.0-dev-80879e0-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000295306766">
    <score xml:id="score-0000001340746153">
     <scoreDef xml:id="scoredef-0000001452809114" midi.bpm="138">
      <staffGrp xml:id="staffgrp-0000000245507865" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-0000001883259253" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="F" line="4" />
        <keySig xml:id="keysig-L3F2" sig="2s" />
        <meterSig xml:id="metersig-L4F2" count="4" sym="common" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000001324761847" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <keySig xml:id="keysig-L3F1" sig="2s" />
        <meterSig xml:id="metersig-L4F1" count="4" sym="common" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <pb xml:id="pb-0000000613529903" />
      <measure xml:id="measure-L1" n="25">
       <staff xml:id="staff-0000001238504562" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <beam xml:id="beam-L8F2-L11F2">
          <note xml:id="note-L8F2" dur="8" oct="3" pname="f" accid.ges="s">
           <artic xml:id="artic-L8F2" artic="stacc" />
          </note>
          <note xml:id="note-L9F2" dur="8" oct="3" pname="d" accid.ges="n">
           <artic xml:id="artic-L9F2" artic="stacc" />
          </note>
          <note xml:id="note-L10F2" dur="8" oct="3" pname="f" accid.ges="s">
           <artic xml:id="artic-L10F2" artic="stacc" />
          </note>
          <note xml:id="note-L11F2" dur="8" oct="3" pname="b" accid.ges="n">
           <artic xml:id="artic-L11F2" artic="stacc" />
          </note>
         </beam>
         <note xml:id="note-L12F2" dur="2" oct="2" pname="b" accid.ges="n">
          <artic xml:id="artic-L12F2" artic="acc" />
         </note>
         <clef xml:id="clef-L14F2" shape="G" line="2" />
        </layer>
       </staff>
       <staff xml:id="staff-0000001837883900" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L8F1" dur="4" oct="1" pname="f" accid.ges="s">
          <artic xml:id="artic-L8F1" artic="stacc" />
         </note>
         <note xml:id="note-L10F1" dur="4" oct="1" pname="e" accid.ges="n">
          <artic xml:id="artic-L10F1" artic="stacc" />
         </note>
         <note xml:id="note-L12F1" dur="4" oct="1" pname="d" accid.ges="n">
          <artic xml:id="artic-L12F1" artic="stacc" />
         </note>
         <note xml:id="note-L13F1" dur="4" oct="1" pname="c" accid.ges="s">
          <artic xml:id="artic-L13F1" artic="stacc" />
         </note>
        </layer>
       </staff>
      </measure>
      <sb xml:id="sb-L16F1" type="z" />
      <measure xml:id="measure-L16" n="26">
       <staff xml:id="staff-L16F2N1" n="1">
        <layer xml:id="layer-L16F2N1" n="1">
         <beam xml:id="beam-L17F2-L21F2">
          <note xml:id="note-L17F2" dur="8" oct="3" pname="b" accid.ges="n" />
          <note xml:id="note-L18F2" dur="8" oct="4" pname="c" accid.ges="s">
           <artic xml:id="artic-L18F2" artic="stacc" />
          </note>
          <chord xml:id="chord-L19F2" dur="8">
           <note xml:id="note-L19F2S1" oct="3" pname="f" accid.ges="s" />
           <note xml:id="note-L19F2S2" oct="4" pname="d" accid.ges="n" />
           <artic xml:id="artic-L19F2" artic="stacc" />
          </chord>
          <note xml:id="note-L21F2" dur="8" oct="4" pname="e" accid.ges="n">
           <artic xml:id="artic-L21F2" artic="stacc" />
          </note>
         </beam>
         <beam xml:id="beam-L22F2-L23F2">
          <note xml:id="note-L22F2" dur="8" oct="4" pname="f" accid.ges="s">
           <artic xml:id="artic-0000000119257473" />
           <artic xml:id="artic-L22F2" artic="stacc acc" />
          </note>
          <note xml:id="note-L23F2" dur="8" oct="4" pname="d" accid.ges="n">
           <artic xml:id="artic-L23F2" artic="stacc" />
          </note>
         </beam>
         <chord xml:id="chord-L24F2" dur="4">
          <note xml:id="note-L24F2S1" oct="3" pname="f" accid.ges="s" />
          <note xml:id="note-L24F2S2" oct="4" pname="f" accid.ges="s" />
          <artic xml:id="artic-L24F2" artic="stacc" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-L16F1N1" n="2">
        <layer xml:id="layer-L16F1N1" n="1">
         <note xml:id="note-L17F1" dur="4" oct="0" pname="b" accid.ges="n">
          <artic xml:id="artic-L17F1" artic="stacc" />
         </note>
         <beam xml:id="beam-L19F1-L21F1">
          <chord xml:id="chord-L19F1" dur="16">
           <note xml:id="note-L19F1S1" oct="2" pname="f" accid.ges="s" />
           <note xml:id="note-L19F1S2" oct="3" pname="d" accid.ges="n" />
          </chord>
          <note xml:id="note-L20F1" dur="16" oct="2" pname="e" accid="s" />
          <note xml:id="note-L21F1" dur="8" oct="2" pname="f" accid.ges="s" />
         </beam>
         <note xml:id="note-L22F1" dur="4" oct="1" pname="b" accid.ges="n">
          <artic xml:id="artic-L22F1" artic="stacc" />
         </note>
         <beam xml:id="beam-L24F1-L26F1">
          <chord xml:id="chord-L24F1" dur="16">
           <note xml:id="note-L24F1S1" oct="2" pname="f" accid.ges="s" />
           <note xml:id="note-L24F1S2" oct="3" pname="d" accid.ges="n" />
          </chord>
          <note xml:id="note-L25F1" dur="16" oct="2" pname="e" accid.ges="s" />
          <note xml:id="note-L26F1" dur="8" oct="2" pname="f" accid.ges="s" />
         </beam>
        </layer>
       </staff>
       <dynam xml:id="dynam-L17F3" staff="1" tstamp="1.000000" vgrp="100">p</dynam>
       <slur xml:id="slur-L19F1-L21F1" staff="2" startid="#chord-L19F1" endid="#note-L21F1" />
       <slur xml:id="slur-L24F1-L26F1" staff="2" startid="#chord-L24F1" endid="#note-L26F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

In this layout, no justification is applied to the second measure, and the layout is optimized to the most compact form that is the result of the pre-castoff procedure.  Of interest is the spacing of the pairs of sixteenth notes.  The first pair of sixteenth notes are spaced wider than the second because of the accidental in front of the note.

Here is an example of what the same measure looks like after justification:

<img width="592" alt="Screen Shot 2021-01-21 at 11 56 56 PM" src="https://user-images.githubusercontent.com/3487289/105463252-9eff6000-5c44-11eb-9de0-a869253eebe7.png">

The current basic justification algorithm does a linear interpolation of the spacings between the noteheads to stretch out the music.  This causes a visual disruption in the music that decreases its readability: The spacings between the pairs of sixteenth notes are still unequal do to the original layout spacing.

A more readable justification would first expand the spacing between the last two sixteenth notes first until they match the distance between the first two sixteenth notes.  Once there is enough space to allow justifying them to have the same spacing, they should expand at the same rate at wider spacings.

A final algorithm would probably be more complicated, which is also useful to think about with this example.   Even spacings of notes is desirable for maximizing sight-readability.   At compact justifications, it may be useful to steal space from the longer notes on the system.  This might end up being a verovio option dealing with how aggressive verovio is allowed to steal space from longer durations in order to try to even out the spacing of shorter notes.   This is somewhat built into the current `spacingLinear` and `spacingNonLinear` options. [as a side note, the `spacingNonLinear` option should probably be renamed to `spacingNonlinear`, since `nonlinear` is a word (rather than `non linear` or `non-linear`)].

There may be counter-examples where it is not desirable for the spacings to not become uniform, but the general rule would be to try to make the rhythmic spacings for each rhythmic level uniform.  One particular complication will be spacing tuplets.

One possible way to view the music for justification is to collapse rhythms on all staves into a single composite rhythm (when not dealing with tuplets).  And also not considering things like accidentals in particular, and probably other elements such as flags (i.e., just consider the noteheads as points).  The composite rhythm for this example:

<img width="896" alt="Screen Shot 2021-01-22 at 12 32 30 AM" src="https://user-images.githubusercontent.com/3487289/105466620-59916180-5c49-11eb-98cd-92d16de8d4c0.png">

The goal would be to ensure that every rhythmic level in the composite rhythm is given the same amount of space.  Once this happens, then extra space could be allocated according to the `spacingNonLinear` option.  After even spacing of the composite rhythm is achieved further padding of the music should only be done based on the `spacingNonLinear` option.  In particular the `spacingLinear` option should not be used at this point, as well as any linear interpolation to expand the music (which is basically the same as `spacingLinear`).  This is related to @napulen's recent comments about readability: if music is widely spaced, then it is harder to read.  Any expansion after an equally spaced composite rhythm should be focused on padding the longer rhythmic units and not the smaller units.  Widening of the smaller rhythmic units causes a shift in the reading strategy of a musician from interval contours into an isolated pitch method.  Reading interval contours is very efficient since you are grouping multiple notes together to read as a single unit.  Reading by isolated pitch takes longer since each note has to be considered separately.  Placing more space between longer rhythms is better since there is more time to read longer notes and they are probably already spaced far enough apart to already be causing the isolated pitch reading strategy to be used by the musician.  When shorter notes are expanded far enough that they cross over the boundary between contour and absolute position reading, the musician suddenly will take longer to read the same musical content.

There may be  other factors or styles of justification to consider.  One thought is that once the composite rhythm is evenly spaced, extra space could be inserted giving priority to making the rhythm levels on each individual staff even out, giving priority to the shortest rhythmic units before the longer ones.  This may not work out too well without refinement since this would disrupt the even-spacing of the composite rhythm (which may still have priority for readability).

------------------

Here is the same music typeset in SCORE using various widths to examine how it adds space as the system is stretched:

Width 50:
<img width="343" alt="Screen Shot 2021-01-22 at 1 29 16 AM" src="https://user-images.githubusercontent.com/3487289/105472921-57330580-5c51-11eb-9952-35bf811cb066.png">

<details>
<summary>
Click to view SCORE data for Width 50 example.
</summary>

```
8 1 0 0 0 50
14 1 0 2
14 1 0 2 8
3 1 0.438 0 1
17 1 6.377 0 2 1
1 1 13.115 -9 10 0 1 10 0 0 7
1 1 21.592 2 10 0 0.25 5
1 1 21.592 7 0 0 0.25
6 1 21.592 7 4.5 29.87 11 0 0 11 21.59 26.93
5 1 21.592 0 0 29.87 -1.5 -1
1 1 26.931 1 12 0 0.25 4.39
1 1 29.869 2 10 0 0.5 2.5
1 1 32.808 -2 10 0 1 2 0 0 7
1 1 38.685 2 10 0 0.25 5
1 1 38.685 7 0 0 0.25
6 1 38.685 7 4.5 44.56 11 0 0 11 38.68 41.62
5 1 38.685 0 0 44.56 -1.5 -1
1 1 41.623 1 10 0 0.25 4.75
1 1 44.562 2 10 0 0.5 2.5
14 1 50 2
8 2 0 5.18 0 50
3 2 0.438
17 2 6.377 0 2
1 2 13.115 0 10 0 0.5
6 2 13.115 0 3 29.87 11
9 2 13.115 -4.5 53
1 2 17.354 1 10 0 0.5 -0.24 0 0 7
1 2 21.592 -3 10 0 0.5 4.52 0 0 7
1 2 21.592 2 0 0 0.5
1 2 29.869 3 10 0 0.5 0 0 0 7
1 2 32.808 4 10 0 0.5 0 0 0 5.05
6 2 32.808 4 2.5 35.75 11
1 2 35.746 2 10 0 0.5 0.5 0 0 7
1 2 38.685 -3 10 0 1 7 0 0 7
1 2 38.685 4 0 0 1
```

</details>

Width 75:
<img width="479" alt="Screen Shot 2021-01-22 at 1 29 20 AM" src="https://user-images.githubusercontent.com/3487289/105472931-5b5f2300-5c51-11eb-8077-a0cb4c9e927e.png">

<details>
<summary>
Click to view SCORE data for Width 75 example.
</summary>

```
8 4 0 21.73 0 75
3 4 2
17 4 9.694 0 2
1 4 17.994 0 10 0 0.5
6 4 17.994 0 3 42.15 11
9 4 17.994 -4.5 53
1 4 24.318 1 10 0 0.5 -0.24 0 0 7
1 4 30.643 -3 10 0 0.5 4.52 0 0 7
1 4 30.643 2 0 0 0.5
1 4 42.147 3 10 0 0.5 0 0 0 7
1 4 47.675 4 10 0 0.5 0 0 0 5.05
6 4 47.675 4 2.5 53.2 11
1 4 53.204 2 10 0 0.5 0.5 0 0 7
1 4 58.732 -3 10 0 1 7 0 0 7
1 4 58.732 4 0 0 1
8 5 0 33.1 0 100
14 5 0 2
14 5 0 2 8
3 5 2 0 1
17 5 9.922 0 2 1
1 5 18.222 -9 10 0 1 10 0 0 7
1 5 36.973 2 10 0 0.25 5
1 5 36.973 7 0 0 0.25
6 5 36.973 7 4.5 50.22 11 0 0 11 36.97 43.87
5 5 36.973 0 0 50.22 -1.5 -1
1 5 43.873 1 12 0 0.25 4.39
1 5 50.222 2 10 0 0.5 2.5
1 5 59.394 -2 10 0 1 2 0 0 7
1 5 77.738 2 10 0 0.25 5
1 5 77.738 7 0 0 0.25
6 5 77.738 7 4.5 90.44 11 0 0 11 77.74 84.09
5 5 77.738 0 0 90.44 -1.5 -1
1 5 84.087 1 10 0 0.25 4.75
1 5 90.437 2 10 0 0.5 2.5
14 5 100 2
```

</details>

Width 100:
<img width="546" alt="Screen Shot 2021-01-22 at 1 29 25 AM" src="https://user-images.githubusercontent.com/3487289/105472943-5dc17d00-5c51-11eb-9b35-b572a9303115.png">

<details>
<summary>
Click to view SCORE data for Width 100 example.
</summary>

```
8 5 0 33.1 0 100
14 5 0 2
14 5 0 2 8
3 5 2 0 1
17 5 9.922 0 2 1
1 5 18.222 -9 10 0 1 10 0 0 7
1 5 36.973 2 10 0 0.25 5
1 5 36.973 7 0 0 0.25
6 5 36.973 7 4.5 50.22 11 0 0 11 36.97 43.87
5 5 36.973 0 0 50.22 -1.5 -1
1 5 43.873 1 12 0 0.25 4.39
1 5 50.222 2 10 0 0.5 2.5
1 5 59.394 -2 10 0 1 2 0 0 7
1 5 77.738 2 10 0 0.25 5
1 5 77.738 7 0 0 0.25
6 5 77.738 7 4.5 90.44 11 0 0 11 77.74 84.09
5 5 77.738 0 0 90.44 -1.5 -1
1 5 84.087 1 10 0 0.25 4.75
1 5 90.437 2 10 0 0.5 2.5
14 5 100 2
8 6 0 38.27 0 100
3 6 2
17 6 9.922 0 2
1 6 18.222 0 10 0 0.5
6 6 18.222 0 3 50.22 11
9 6 18.222 -4.5 53
1 6 27.597 1 10 0 0.5 -0.24 0 0 7
1 6 36.973 -3 10 0 0.5 4.52 0 0 7
1 6 36.973 2 0 0 0.5
1 6 50.222 3 10 0 0.5 0 0 0 7
1 6 59.394 4 10 0 0.5 0 0 0 5.05
6 6 59.394 4 2.5 68.57 11
1 6 68.566 2 10 0 0.5 0.5 0 0 7
1 6 77.738 -3 10 0 1 7 0 0 7
1 6 77.738 4 0 0 1
```

</details>

Width 125:
<img width="678" alt="Screen Shot 2021-01-22 at 1 29 31 AM" src="https://user-images.githubusercontent.com/3487289/105472950-6023d700-5c51-11eb-8e58-c86e2e1bafcf.png">

<details>
<summary>
Click to view SCORE data for Width 125 example.
</summary>

```
8 7 0 49.65 0 125
14 7 0 2
14 7 0 2 8
3 7 2 0 1
17 7 9.956 0 2 1
1 7 18.256 -9 10 0 1 10 0 0 7
1 7 42.844 2 10 0 0.25 5
1 7 42.844 7 0 0 0.25
6 7 42.844 7 4.5 59.56 11 0 0 11 42.84 51.31
5 7 42.844 0 0 59.56 -1.5 -1
1 7 51.307 1 12 0 0.25 4.39
1 7 59.559 2 10 0 0.5 2.5
1 7 71.738 -2 10 0 1 2 0 0 7
1 7 96.096 2 10 0 0.25 5
1 7 96.096 7 0 0 0.25
6 7 96.096 7 4.5 112.6 11 0 0 11 96.1 104.35
5 7 96.096 0 0 112.6 -1.5 -1
1 7 104.348 1 10 0 0.25 4.75
1 7 112.6 2 10 0 0.5 2.5
14 7 125 2
8 8 0 54.82 0 125
3 8 2
17 8 9.956 0 2
1 8 18.256 0 10 0 0.5
6 8 18.256 0 3 59.56 11
9 8 18.256 -4.5 53
1 8 30.55 1 10 0 0.5 -0.24 0 0 7
1 8 42.844 -3 10 0 0.5 4.52 0 0 7
1 8 42.844 2 0 0 0.5
1 8 59.559 3 10 0 0.5 0 0 0 7
1 8 71.738 4 10 0 0.5 0 0 0 5.05
6 8 71.738 4 2.5 83.92 11
1 8 83.917 2 10 0 0.5 0.5 0 0 7
1 8 96.096 -3 10 0 1 7 0 0 7
1 8 96.096 4 0 0 1
```

</details>

Width 75 is about the most compact reasonable spacing, with the pairs of 16th notes not equally spaced because a accidental is placed inside one of the pairs.  Notice that by width 100, equal spacing of the sixteenth note pairs is (nearly) achieved.

Underneath each example is the SCORE data for that example.  The first number on each line is the object type (1 = notes, 2 = rests, 3 = clefs, 6 = beam, 8 = staff lines, 9 = musical font object (`p` dynamic in this case) 14 = bar lines, 17 = key signature.   

The second number on a line is the staff number to which the object belongs.   The data was split up from a full page of 8 staves, so the numbers will be different in each example.  The smaller number means the lower staff. 

Then in the third column is the interesting data: this is the absolute horizontal position of the object between the page margins, with 0.0 being the far left, and 200.0 being the far right.  These values can be examined and compared to various justification algorithms.  (The name "width 50" , as an example, means that the maximum horizontal position is 50, or 1/4 of the way across the page).

For notes, the fourth number on a line gives the pitch (vertical position), with the bottom staff line being `3` (probably so that middle C on a treble clef was `1`).

**Comment by craigsapp** [comment]
Clef changes should be considered as a object with width rather than a point when compressing the justification:

<img width="123" alt="Screen Shot 2021-01-31 at 11 47 49 AM" src="https://user-images.githubusercontent.com/3487289/106396003-2faf0c00-63ba-11eb-8b9d-7e9a143a2142.png">

<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-31T11:46:12" version="3.2.0-dev-751456e-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001511615002">
    <score xml:id="score-0000001518310879">
     <scoreDef xml:id="scoredef-0000001859975118">
      <staffGrp xml:id="staffgrp-0000001923143718">
       <staffDef xml:id="staffdef-0000000112542811" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000001533019273" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="4" oct="4" pname="e" accid.ges="n" />
         <clef xml:id="clef-L5F1" shape="F" line="4" />
         <note xml:id="note-L6F1" dur="4" oct="3" pname="b" accid.ges="n">
          <artic xml:id="artic-L6F1" artic="stacc" />
         </note>
         <note xml:id="note-L7F1" dur="4" oct="3" pname="e" accid.ges="n">
          <artic xml:id="artic-L7F1" artic="stacc" />
         </note>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>




The spacing can get closer than a diatonic step to stems if the clef does not start with a vertical line (C clefs would be an exception):

<img width="136" alt="Screen Shot 2021-01-31 at 11 44 22 AM" src="https://user-images.githubusercontent.com/3487289/106395914-ab5c8900-63b9-11eb-85fb-801c10a1aa90.png">

Also in tight justifications, clef changes close to a barline can get closer since they do not have vertical elements (such as stems) that would be confused with the vertical line of the barline (or the repeat dots of a barline).  This also would apply to notes where the stems are not near the vertical lines of the barline in tight justifications:

<img width="95" alt="Screen Shot 2021-01-31 at 11 51 01 AM" src="https://user-images.githubusercontent.com/3487289/106396078-992f1a80-63ba-11eb-974b-bd8da0dbde2e.png">

**Comment by rettinghaus** [comment]
Why not change `--left-margin-clef` and `---right-margin-clef`? (Overlapping should not be allowed anyway, of course.)

**Comment by craigsapp** [comment]
Overlapping is currently allows since only a simple justification algorithm is currently being used.  This is a backburner issue, so I am not trying to fix any particular example *per se*, but rather noting problems that should be addressed in the future for general cases.  Tight justification is desirable for music notation in particular for performance since allows the eye to see more music in a single glance, thus increasing the readability of the music.  Musicologists on the other hand want clarity, which allows for a less compressed justification.

Here is where the clef-change example comes from:
https://verovio.humdrum.org/?file=haydn/sonatas/sonata12-2.krn#mh16

When there is lots of space it is OK (when the width of the music is wide when the system breaks are as encoded, or if system breaks are auto):
<img width="1672" alt="Screen Shot 2021-01-31 at 2 29 18 PM" src="https://user-images.githubusercontent.com/3487289/106399995-b4a52000-63d0-11eb-9b5d-7a0eb2ecb0f3.png">

When trying to duplicate the justfication of the original edition (type `alt-p` on the above page to view the PDF):
<img width="1668" alt="Screen Shot 2021-01-31 at 2 30 39 PM" src="https://user-images.githubusercontent.com/3487289/106400030-e6b68200-63d0-11eb-8458-4d271e496c9e.png">

verovio cannot handle very much compression in the layout because there is no code yet to deal with justification compression other than a simple model which fails quickly as the justification is compressed:

<img width="1026" alt="Screen Shot 2021-01-31 at 2 33 14 PM" src="https://user-images.githubusercontent.com/3487289/106400104-5a588f00-63d1-11eb-9d1f-ebd9c4b703de.png">

(note also the grace-note accidental which touches the barline, gracenote notehead touching the barline, natural sign which touches the stem, slurs that touch notes which I am not complaining about yet :-).  Note in the analog typesetting, extra space is stolen from the larger composite rhythm regions to avoid these collisions, which will be the basis for allowing a tighter justification that remains readable.
