### ISSUE TITLE
Python pip not working on ARM64

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#2017]
I tried to install the Verovio Python package on Rapsberry Pi (3 and 4) with Raspbian and Ubuntu. 
The first problem was that `swig` was missing on the system. 
Now it looks better but still fails. I searched for a solution and installed several other packages, but without any luck. Perhaps somebody has a good idea?

Here's the output:
[verovio.log](https://github.com/rism-ch/verovio/files/5898484/verovio.log)

**Comment by ahankinson** [comment]
` ./include/vrv/view.h:11:20: fatal error: optional: Datei oder Verzeichnis nicht gefunden
     #include <optional>`

looks like a header is not found on your platform. Does Verovio compile normally on arm64?

**Comment by lpugin** [comment]
I suspect this is a c++17 issue. Does the command-line version build?

**Comment by rettinghaus** [comment]
Indeed it was a compiler problem because of C++17. I updated the system and now it builds (which takes hours).
