### ISSUE TITLE
about multi voice beam connect

### ISSUE THREAD

**Issue by mleozhang** [rism-ch/verovio#2021]
Hello, I found out that other software can connect different sound stem, why not Verovio, I'm using MusicXML

**Comment by lpugin** [comment]
You can use the other software then.

**Comment by mleozhang** [comment]
Because my project is based on Verovio, I would like to ask whether Verovio supports connect different sound stem？
thanks！

**Comment by lpugin** [comment]
No, it does not since its focus is on music notation and not on audio.

**Comment by mleozhang** [comment]
I mean one measure has two voices,voice= 1,beam= begin,voice=2,beam=end, and then can those two notes be connected
