### ISSUE TITLE
Inserted elements in toolkit not drawn in SVG

### ISSUE THREAD

**Issue by wergo** [rism-ch/verovio#2036]
When inserting a slur element through `vrvToolkit.edit()` the MEI returned by `Toolkit::getMEI()` correctly contains the new slur with both `@startid` and `@endid` attributes, but the returned SVG `Toolkit::renderToSVG()` looks like this: `<g id="slur-1" class="slur" />`. Thus, it lacks a `path` element.

The js code I used looks essentially like:

``` js
editorAction = {
            action: 'insert', param: { elementType: 'slur', startid: 'note-1', endid: 'note-2' }
};
vrvToolkit.edit(editorAction);
vrvToolkit.redoLayout();
editor.setText(vrvToolkit.getMEI()); 
// returned MEI correctly contains <slur xml:id="slur-1" startid="#note-1" endid="#note-2" />

verovioPanel.innerHTML = vrvToolkit.renderToSVG(currentPage); 
// this contains only the un-drawn slur element without a path element
```
What command inside Verovio needs to be called to draw the slur and generate the `path` element in the SVG?

**Comment by lpugin** [comment]
I think you need to call `{ action: 'commit' }` before redoing the layout. We can look into it.

Please follow-up on Slack (also for such questions) so we don't overload the issue tracker. Thanks

**Comment by wergo** [comment]
Yes, that solves it. Thanks a lot.
