### ISSUE TITLE
Tempo::SetStaff enhancement

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#204]
When adding a tempo element, it will not show in the rendering unless there is a `@staff` number.  

When I try this code:

```cpp
Tempo *tempo = new Tempo;
tempo->SetStaff(1);
```

I get a type error because SetStaff requires a `vector<int>` typedefed to xsd_posIntList.  Then I have to do all of this:

```cpp
Tempo *tempo = new Tempo;
xsd_posIntList stafflist;
stafflist.push_back(1);
tempo->SetStaff(stafflist);
```

It would be more convenient to be able to do just `tempo->SetStaff(int)` when there is only a single staff.

Also, perhaps if there is no `@staff` for a tempo element, it should default to "1".  

Sub-issue: There should be a list of default values for all attributes in all elements somewhere in the code/documentation, along with notes about when defaults are ever changed...

**Comment by lpugin** [comment]
We could add a AddStaff(int) to the TimePointInterface that would add it to the vector (if not there already).

Not sure about the default values. This is maybe something people will agree to have for the MEI-Lite version, but certainly not for MEI in general.

**Comment by lpugin** [comment]
Added in f0ee79e646a6bcde847fd19078da93e57ff606ca

**Comment by craigsapp** [comment]
Default attribute values would be useful in the MEI guidelines; otherwise, different software implementations will behave differently from each other.  Can not default values be specified in XML schemas?

http://www.w3schools.com/xml/schema_simple_attributes.asp

**Comment by lpugin** [comment]
Apparently yes... You should raise the question on the MEI repository or on MEI-L

**Comment by craigsapp** [comment]
And then libmei should be transferring those defaults into verovio somehow (if it is not doing so already).

**Comment by ahankinson** [comment]
I don't have any plans for including any provision for default values in libmei.

**Comment by craigsapp** [comment]
Are there defaults in the MEI ODD document?

> otherwise, different software implementations will behave differently from each other.

**Comment by craigsapp** [comment]
`AddStaff(int)` works.  Is there a reason not to do `SetStaff(int)`?  That would remove any previous staves, and set to a single one.

**Comment by ahankinson** [comment]
I don't think so. There are acceptable string values (in the case of a closed list) and datatypes (usually a regex).

I don't think there is any way to declare what to do in the case of an absent attribute, since validation doesn't really care about the behaviour of software implementations.

**Comment by lpugin** [comment]
You can do ```ResetStaffident()``` before

**Comment by craigsapp** [comment]
Of course defaults are tricky: suppose `@staff="1"` is the default for the tempo element, but there is no staff "1".  Ideally the default in this case would be "display the tempo on the top staff in the system".

**Comment by lpugin** [comment]
Exactly. So the best is still to expect a ```@staff```. I think it should actually be required by the schema, but maybe there is a reason why it is not.

**Comment by craigsapp** [comment]
`ResetStaffident()`:  How I am going to remember CamElCasEs of meilib functions @ahankinson ? :-)

@lpugin: I notice that `@placement` has a default value of "above" and `@tstamp` has a default value of "1" for tempo elements in verovio, so why is `@staff` different?  (i.e., the schema should require `@staff` for tempo elements in MEI 3.0.1)

**Comment by lpugin** [comment]
Where can you see this? This is an example where default values are set for ```place```
https://github.com/rism-ch/verovio/blob/master/src/floatingelement.cpp#L100-L126

**Comment by craigsapp** [comment]
Yes, I meant `@place`.  I was reverse engineering from the MEIviewer data files:

```xml
                            <tempo staff="1" place="above" tstamp="1">Mässig.</tempo>
```

First I did
```
                            <tempo>Mässig.</tempo>
```
but nothing showed, then I did
```
                            <tempo staff="1">Mässig.</tempo>
```
And at it showed, I was done (I will be complaining that the tempo mark is too low in my test case).

From:  http://music-encoding.org/documentation/3.0.0/tempo
> `@staff` (optional) Signifies the staff on which a notated event occurs or to which a control event applies. Mandatory when applicable. One or more values of datatype positiveInteger, separated by spaces. att.staffident 

So `@staff` is a manditory optional attribute :-)

Here is the documentation for `@place` on the same page:
> @place (optional) Captures the placement of the item with respect to the staff with which it is associated. Value conforms to data.STAFFREL . att.placement 

This one is optional optional.

It might be useful for the MEI guidelines to have a list of "suggested" defaults for various element/attribute contexts when it makes sense.   For example, a list like: 

```
    tempo@place="above"
    dynam@place="below"
    dir@place="below"
```

@lpugin can provide the list used in verovio :-)

**Comment by ahankinson** [comment]
```
src|develop⚡ ⇒ pwd
/Users/ahankins/Documents/code/git/libmei/src
src|develop⚡ ⇒ grep -R "ResetStaffident" *
src|develop⚡ ⇒
```
I think it's a Verovio problem.

**Comment by lpugin** [comment]
The CamelCase in Staffident is a MEI issue

**Comment by pe-ro** [comment]
Let's compile a list of attribute class names that need modification.  Andrew has already suggested changing `att.staffgroupingsym` and `att.staffident` to `att.staffGroupingSym` and `att.staffIdent` in https://github.com/music-encoding/music-encoding/issues/309.  Other suggestions?

**Comment by lpugin** [comment]
Attribute class names might be changed, but this will not change anything for Verovio members since all attribute names are lowercase.

**Comment by ahankinson** [comment]
Won't `Staffident` become `StaffIdent` if the attribute class names are changed?

**Comment by pe-ro** [comment]
No!  The name of the attribute class and the name of the attribute are independent of each other.  Changing the name of the class to `att.staffIdent` has no effective on the name of the attributes in that class.
```
<classSpec ident="att.staffident" module="MEI.shared" type="atts">
  <desc>Attributes for identifying the staff associated with the current feature.</desc>
  <attList>
    <attDef ident="staff" usage="opt">
      <desc>Signifies the staff on which a notated event occurs or to which a control event
        applies. Mandatory when applicable.</desc>
      <datatype maxOccurs="unbounded">
        <rng:data type="positiveInteger"/>
      </datatype>
    </attDef>
  </attList>
</classSpec>
```

**Comment by pe-ro** [comment]
There is no attribute called `staffident`.

**Comment by pe-ro** [comment]
Attribute default values are a bad idea.  See Harold, Effective XML, p. 105 -- 

"For maximum portability and robustness, include all necessary information in the instance document itself."

This would seem to make a case for requiring any attribute for which a default value is necessary.  However, other circumstances, argue against that.  For instance, there would be high degree of redundancy in a file if every event or even every control event had to have `@staff`.  Requiring `@staff` would also essentially dictate a certain processing model, violating our principle of remaining software agnostic.  The best approach is for a processor to adopt its own constraints and enforce them either with another schema or with schematron.
