### ISSUE TITLE
Inserting UTF8

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#205]
It would also be handy to make the UTF16 conversion of strings more transparent for TextElements:

If I try to do this:

```cpp
            Text *text = new Text;
            tempo->AddTextElement(text);
            string value = "Allegro";
            text->SetText(value);
```

I get a type error since the input to SetText must a wide character string.  I have to convert manually:

```cpp
            Text *text = new Text;
            tempo->AddTextElement(text);
            string value = "Allegro";
            text->SetText(UTF8to16(value));
```

Can `SetText` be overloaded so that UTF-8 is automatically converted to UTF-16?

**Comment by lpugin** [comment]
try
```
std::wstring value = L"Allegro";
text->SetText(value);
```

**Comment by craigsapp** [comment]
```
std::wstring value = L"Allegro";
text->SetText(value);
```

Ick.  In any case I am not creating a static tempo marker :-)

**Comment by lpugin** [comment]
Then you need to use UTF8to16()
