### ISSUE TITLE
Verovio Python Toolkits are not equivalent across platforms (Mac, Linux)

### ISSUE THREAD

**Issue by apacha** [rism-ch/verovio#2058]
I've installed the Python Verovio package, version 3.2.0 on an Ubuntu machine and on a Mac and unfortunately it seems like in the two binaries some methods have different signatures, which causes problems when calling it from the other platform.

### Mac
<img width="459" alt="Screen Shot 2021-02-18 at 15 00 33" src="https://user-images.githubusercontent.com/594497/108368385-aa6d8900-71fa-11eb-9f59-9c997a3cd72e.png">
<img width="819" alt="Screen Shot 2021-02-18 at 15 00 49" src="https://user-images.githubusercontent.com/594497/108368384-a9d4f280-71fa-11eb-9b97-65438f4efed3.png">
<img width="813" alt="Screen Shot 2021-02-18 at 15 01 01" src="https://user-images.githubusercontent.com/594497/108368383-a9d4f280-71fa-11eb-9205-3df519679f12.png">

### Ubuntu
<img width="466" alt="Screen Shot 2021-02-18 at 15 00 10" src="https://user-images.githubusercontent.com/594497/108368386-aa6d8900-71fa-11eb-97b7-3fad984708a4.png">
<img width="1042" alt="Screen Shot 2021-02-18 at 15 01 24" src="https://user-images.githubusercontent.com/594497/108368378-a8a3c580-71fa-11eb-9b6d-2c0d74873d4b.png">
<img width="1047" alt="Screen Shot 2021-02-18 at 15 01 34" src="https://user-images.githubusercontent.com/594497/108368373-a6da0200-71fa-11eb-902e-dab950688b71.png">

I've installed Verovio on both machines using `pip install verovio==3.2.0`

**Comment by rettinghaus** [comment]
Is there a reason we use Ubuntu 18.04 for building the Python package?

**Comment by lpugin** [comment]
What does `getVersion` return on both platforms?

**Comment by apacha** [comment]
### Mac
```
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
import verovio
toolkit = verovio.toolkit()
toolkit.getVersion()
'3.2.0-d7189a9'
```

### Ubuntu
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
import verovio
toolkit = verovio.toolkit()
toolkit.getVersion()
'3.2.0-d7189a9'
```

**Comment by musicEnfanthen** [comment]
> 
> 
> Is there a reason we use Ubuntu 18.04 for building the Python package?

@rettinghaus When we created the GH action, Ubuntu 18.04 was more stable in GH environment.

**Comment by lpugin** [comment]
Looking at the `getVersion` output it seems like the same codebase. What do you mean by not equivalent?

**Comment by musicEnfanthen** [comment]
> Looking at the `getVersion` output it seems like the same codebase

One could argue, that the version shown with `getVersion` is only the string provided via `git_commit.sh`. It does not necessarily have to be the same codebase?

From the screenshots above, the signature of the method differs: `(self, *args)` vs. `(self, jsonOptions)`

@apacha Do you have an issue when using the option on Ubuntu with the same inputs as on Mac? Is it giving an error?

**Comment by ahankinson** [comment]
Every commit has a unique sha identifier that is computed from the code itself, so the commit used to generate the code indicates that it’s the same codebase. A change in code would be a different hash and thus a different identifier. 

The Mac version of swig is 4.0.2; the Linux version is 2.0.10. Since the interfaces are automatically generated i am guessing that’s where the difference in signature comes in?

**Comment by rettinghaus** [comment]
Yeah, I think it's just because of the outdated version of SWIG that was used in Ubuntu. So #2060 should resolve this, @musicEnfanthen?

**Comment by musicEnfanthen** [comment]
Just learned that SWIG 4.x is now preinstalled with manylinux2014 (which is great). 

So probably the following line could be removed: https://github.com/rism-ch/verovio/blob/f5287d9a609d77bfbb76c01491c12ef86b27183a/.github/workflows/python-ci-wheel.yml#L95

**Comment by musicEnfanthen** [comment]
@ahankinson Thanks for the clarification!

**Comment by musicEnfanthen** [comment]
Hmm, but it seems to be not included in the latest ciduildwheel version 🤔 Test failed: https://github.com/musicEnfanthen/verovio/runs/1930266433?check_suite_focus=true#step:6:100

Cibuildwheel 1.9.0 still pulls an "older" image from 24 January 2021 where this change is not included yet

**Comment by apacha** [comment]
@lpugin I have to clarify - the code base is the same, but the signatures of some functions are different. And yes, this causes an exception when trying to call `setOptions(jsonOptions=...)` on Linux, as that parameter does not exist there.

**Comment by lpugin** [comment]
What are you passing as parameter and what's the exception?

**Comment by apacha** [comment]
The code is something like:
```
import verovio
import json

verovio_options = {"footer": "none", "breaks": "encoded", "minLastJustification": 0.1}
verovio_toolkit = verovio.toolkit()
verovio_toolkit.setOptions(jsonOptions=json.dumps(verovio_options))
```

The exception:
```
TypeError: setOptions() got an unexpected keyword argument 'jsonOptions'
```

**Comment by lpugin** [comment]
OK, now I understand. Related to swig and not to the verovio codebase. I assume this works on both Mac and Linux:
```
verovio_toolkit.setOptions(json.dumps(verovio_options))
```
Could you try?

**Comment by apacha** [comment]
Yes, that works.

**Comment by musicEnfanthen** [comment]
Perfect!

Meanwhile, I got a nice and quick answer from the cibuildwheel team (https://github.com/joerick/cibuildwheel/issues/603) that the image name can be specified. Tested it once more with a newer image, and it works perfectly with inbuilt SWIG (of course, upload to PyPi fails in the end expectedly). 

@apacha Could you test with the build artifacts here: https://github.com/musicEnfanthen/verovio/actions/runs/580996237 if you see the correct signature on Ubuntu?

@rettinghaus In case everything works out, and you want to include it in your PR, the changes I've made are here: https://github.com/rism-ch/verovio/compare/develop...musicEnfanthen:swig-test  (change in [line 6](https://github.com/rism-ch/verovio/compare/develop...musicEnfanthen:swig-test#diff-3cef39af4d669734eb2d466e7deeeec6df9cc0fb76ae50a8118c3518313be842R6) is not needed for the PR)

**Comment by apacha** [comment]
@musicEnfanthen Yes, I can confirm that I'm getting the correct signatures now on Linux and Mac.

**Comment by musicEnfanthen** [comment]
Great! 😃

**Comment by rettinghaus** [comment]
@musicEnfanthen Thanks for solving this. Would you have another look at #2060?
