### ISSUE TITLE
Enum Options in Python toolkit are lowercased

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/verovio#2065]
Currently, the enum options for Verovio are appearing as lowercased:

`verovio.pAE`, `verovio.mEI`, etc.

Looking at the Swig header file for Java I noticed that it's slightly different, and has the option to keep enum values uppercase:

```
// Change method names to lowerCamelCase
%rename("%(lowercamelcase)s") "";
// Ignore enum items (e.g., for fileFormat.PAE)
%rename("%(upper)s", %$isenumitem) "";
```

This change should be ported to the Python toolkit. It will probably break any existing code, though, so this change should be flagged.

**Comment by lpugin** [comment]
Yes, this should be changed. It is not impossible that this will break code even though probably very unlikely because users probably use options to set the format.
