### ISSUE TITLE
Verovio Python Toolkit: Naming of Artifacts

### ISSUE THREAD

**Issue by musicEnfanthen** [rism-ch/verovio#2069]
There seems to be an issue with the naming of the artifacts of a python build. All the dev versions are named in the following way, no matter what Python version they are built with:

`verovio-<major>.<minor>.<patch>.dev39` (cf. https://github.com/rism-ch/verovio/runs/1955260055?check_suite_focus=true#step:6:28, L28-78)

Where is the `39` coming from (`setup.py`?) Assuming that this position should indicate the Python version, it does not get reflected properly.

**Comment by lpugin** [comment]
I would remove the `strategy.matrix` for the source distribution. It does not matter which version of python we use to generate it, does it?

**Comment by lpugin** [comment]
(`dev39` is simply the revision number commit from the commit - it has nothing to do with the python version. The artifcat naming is correct.)

**Comment by musicEnfanthen** [comment]
> 
> 
> I would remove the `strategy.matrix` for the source distribution. It does not matter which version of python we use to generate it, does it?

You are right. And since it builds tar archives with the same (auto-generated) name, there is no benefit in having it multiple times.




> 
> 
> (`dev39` is simply the revision number commit from the commit - it has nothing to do with the python version. The artifcat naming is correct.)

Sorry for the false alert (`39` was perfect to be misunderstood as the underlying python version). So this revision number is generated here: https://github.com/rism-ch/verovio/blob/develop/setup.py#L65 ?
