### ISSUE TITLE
Setting color of notes/rests?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#215]
How do I color notes?

When I try this:

```cpp
    Note *note = new Note;
    note->SetColor(COLORNAMES_red);
```

I get the error:

```
error: no member named 'SetColor' in 'vrv::Note'
```

I see AttColor::SetColor(string) in libmei/atts_shared.h

The AttColor is not listed as a parent class of Note, but if I add it, I can use:

```cpp
    Note *note = new Note;
    note->SetColor("red");
    cerr << "NOTE COLOR IS " << note->getColor() << endl;
```
But the output SVG and MEI files do not have color attributes.

**Comment by lpugin** [comment]
Yes, you would still need to change the color before drawing it. 

Actually the best would be to add the interface to LayerElement directly so we have it for all of them. Then in View::DrawLayerElement check if the color is given and change the m_currentColor before drawing and reset it at the end.  Something like

```
if (element == m_currentElement) {
    m_currentColour = AxRED; // legacy editor code that can sill be useful
}
else if (element->HasColor()) {
    m_currentColour = element->GetColor(); // some conversion will be needed there
else {
   m_currentColour = AxBLACK;
}
```

You would still need to read / write the color (in iomei.cpp) in ReadLayerElement and WriteLayerElement.
