### ISSUE TITLE
Accidental kerning case to consider for offset noteheads

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#217]
For this MEI data:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-06-26 20:38:38</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Encoded with Verovio version 0.9.12-dev-3f108ee</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000123390218">
                        <staffGrp xml:id="m-000000014796490">
                            <staffDef xml:id="staffdef-000000006004468" clef.shape="F" clef.line="4" key.sig="4f" meter.count="4" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure xml:id="measure-000000200124077" n="1" right="end">
                            <staff xml:id="staff-000000005970874" n="1">
                                <!-- kern: =1-  4r  4c 4B- 4G 4En  2r  == -->
                                <layer xml:id="layer-000000064999725" n="1">
                                    <rest xml:id="rest-000000025461972" dur="4" />
                                    <chord xml:id="chord-000000160627644" dur="4">
                                        <note xml:id="note-000000067126787" oct="4" pname="c" accid.ges="n" />
                                        <note xml:id="note-000000126751020" oct="3" pname="b" accid.ges="f" />
                                        <note xml:id="note-000000000625400" oct="3" pname="g" accid.ges="n" />
                                        <note xml:id="note-000000203179655" accid="n" oct="3" pname="e" />
                                    </chord>
                                    <rest xml:id="rest-000000126727935" dur="2" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Verovio renders as:

![screen shot 2016-06-26 at 8 38 55 pm](https://cloud.githubusercontent.com/assets/3487289/16367958/084906c4-3bde-11e6-8bed-c242c1d52dcc.png)

The space between the natural sign and the chord is a bit wide.

Here are sample typesettings of this chord from various publishers:

![screen shot 2016-06-26 at 8 37 34 pm](https://cloud.githubusercontent.com/assets/3487289/16367971/22ae2d28-3bde-11e6-8a88-83c159bfb0ce.png)

![screen shot 2016-06-26 at 8 40 40 pm](https://cloud.githubusercontent.com/assets/3487289/16367987/465d0834-3bde-11e6-90ad-26b1b6ff94c1.png)

![screen shot 2016-06-26 at 8 41 45 pm](https://cloud.githubusercontent.com/assets/3487289/16368002/6cf77236-3bde-11e6-8939-c58dccc3e9c4.png)

![screen shot 2016-06-26 at 8 42 24 pm](https://cloud.githubusercontent.com/assets/3487289/16368014/846d9904-3bde-11e6-8a3c-356172316e83.png)

![screen shot 2016-06-26 at 8 43 04 pm](https://cloud.githubusercontent.com/assets/3487289/16368022/9986608c-3bde-11e6-9885-1735f2df9b32.png)

![screen shot 2016-06-26 at 8 43 40 pm](https://cloud.githubusercontent.com/assets/3487289/16368035/b204e35e-3bde-11e6-9d0c-a5c4d693fe51.png)

![screen shot 2016-06-26 at 8 44 25 pm](https://cloud.githubusercontent.com/assets/3487289/16368046/cc11f502-3bde-11e6-85bd-c4d4fe131312.png)

![screen shot 2016-06-26 at 8 45 37 pm](https://cloud.githubusercontent.com/assets/3487289/16368062/f68b478e-3bde-11e6-852b-b0616a0c6e7d.png)

![screen shot 2016-06-26 at 8 46 27 pm](https://cloud.githubusercontent.com/assets/3487289/16368081/152a430c-3bdf-11e6-8d4c-b2ab4f8b755b.png)

![screen shot 2016-06-26 at 8 47 08 pm](https://cloud.githubusercontent.com/assets/3487289/16368092/2e91a18c-3bdf-11e6-8ca5-d7631fd18ee6.png)

**Comment by lpugin** [comment]
This is fixed in the develop-layer branch.

With Leipzig
![image](https://cloud.githubusercontent.com/assets/689412/24926796/198437ee-1efd-11e7-9d87-53ef04d46d93.png)

With Bravura
![image](https://cloud.githubusercontent.com/assets/689412/24926750/f66e3bba-1efc-11e7-8bce-54b2bfb1183a.png)

**Comment by donbyrd** [comment]
It's good that Verovio kerns accidentals now, but why is the kerning so different in Leipzig and Bravura? FWIW, I'd say the natural is still a bit too far to the left with Leipzig; with Bravura, it's too far to the right. Nearly all of Craig's many samples are in between.

**Comment by lpugin** [comment]
The difference in placement is due to the glyph height. The natural sign in Leipzig is higher than in Bravura and has to be moved to the left no to touch the note head above. The minimal distance will eventually be made a styling parameter.

**Comment by donbyrd** [comment]
OK.
