### ISSUE TITLE
spacing of accidentals to noteheads

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#220]
In general, natural signs appear to be further spaced from notes than sharps in verovio:

![screen shot 2016-06-27 at 11 56 38 am](https://cloud.githubusercontent.com/assets/3487289/16391934/4263c21a-3c5e-11e6-844c-dbb2d8e9f3ce.png)

It is more noticeable at smaller scales (see next message, as this was printed with Bravura):

![screen shot 2016-06-27 at 12 19 10 pm](https://cloud.githubusercontent.com/assets/3487289/16392659/e5474a80-3c61-11e6-88bd-7fefc3f9589a.png)

As a comparison, here is how they are spaced by default in SCORE:

![screen shot 2016-06-27 at 11 51 21 am](https://cloud.githubusercontent.com/assets/3487289/16391948/51364024-3c5e-11e6-8004-001d17f2b4a8.png)

In verovio, the right vertical lines of the sharp and natural signs line up (and the left bounding-box edges align):

![screen shot 2016-06-27 at 11 40 58 am](https://cloud.githubusercontent.com/assets/3487289/16391965/6a069b08-3c5e-11e6-9801-eb25dff755ef.png)

This is perhaps good when there is a mixture of accidentals in a chord; however, the visual effect is to make the natural sign appear to be further from the notehead than the sharp when a single accidental is displayed before a note.

In SCORE, the natural sign's right vertical line retraces about 1/2 of the width of the right horizontal extension in the sharp (and the left vertical lines of the accidentals nearly align):

![screen shot 2016-06-27 at 12 06 34 pm](https://cloud.githubusercontent.com/assets/3487289/16392245/cb1c62dc-3c5f-11e6-8ac5-017a5e922790.png)

This makes the spacing of the accidentals closer to perceptually equal in distance to the notehead, which increases the legibility and aesthetics of the musical layout.

**Comment by craigsapp** [comment]
Maybe this issue is really caused by the use of different fonts.

Here is some music in Leipzig, with naturals spaced correctly:

![screen shot 2016-06-27 at 12 52 50 pm](https://cloud.githubusercontent.com/assets/3487289/16393552/33298ef8-3c66-11e6-93f7-30b15187a16b.png)

Here is the same music using Bravura, with naturals too far from their noteheads:

![screen shot 2016-06-27 at 12 52 39 pm](https://cloud.githubusercontent.com/assets/3487289/16393620/560d977a-3c66-11e6-9258-742ec59557c0.png)

**Comment by donbyrd** [comment]
When you say it's "really caused by the use of different fonts", I thought at first you meant it's because the Bravura natural is narrower than the Leipzig one. The Bravura natural _is_ narrower, and that's clearly the main problem, but there are also differences in the horizontal spacing of the notes in the two samples -- well, at least one difference: the 3rd and 4th notes (F3 and E3) are slightly further apart in the Bravura sample, despite the natural requiring _less_ space.

**Comment by lpugin** [comment]
@donbyrd I think this is due to the fact that Bravura's note head is slightly wider.

**Comment by donbyrd** [comment]
Yes, I guess that could be the cause. Anyway, I intended to say but forgot: Craig, a great job of analyzing and displaying the accidental-to-notehead spacing issue in Bravura!

**Comment by lpugin** [comment]
Chords are still limited to sharp, flat and natural
