### ISSUE TITLE
Fix options for MEI

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#222]
The "-t mei" option for verovio outputs the post cast-off version of the MEI data that is segmented into pages.  It would be useful to have a way of outputing the MEI data from importers _before_ being cast-off.

Sample music:

![screen shot 2016-06-27 at 3 16 35 pm](https://cloud.githubusercontent.com/assets/3487289/16397569/2ea51f3c-3c7a-11e6-89b1-1e6f2775fa85.png)

Current output from MEI:

``` xml
<?xml version="1.0"?>
<pages>
    <page xml:id="page-000000032232614">
        <system xml:id="system-000000141017732" system.leftmar="0" system.rightmar="0">
            <measure xml:id="measure-000000056326900" n="1" right="end">
                <staff xml:id="staff-000000125130088" n="1">
                    <!-- kern: =1-  1c  == -->
                    <layer xml:id="layer-000000030665273" n="1">
                        <note xml:id="note-000000209929841" dur="1" oct="4" pname="c" accid.ges="n" />
                    </layer>
                </staff>
            </measure>
        </system>
    </page>
</pages>
```

Desired additional output from MEI in more canonoical form:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-06-27 14:53:09</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Encoded with Verovio version 0.9.12-dev-3f108ee</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000170223647">
                        <staffGrp xml:id="m-000000061433248">
                            <staffDef xml:id="staffdef-000000213221788" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure xml:id="measure-000000112629167" n="1" right="end">
                            <staff xml:id="staff-000000016966363" n="1">
                                <!-- kern: =1-  1c  == -->
                                <layer xml:id="layer-000000182593068" n="1">
                                    <note xml:id="note-000000087567355" dur="1" oct="4" pname="c" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
You can already do this. You need to set the ```--all-pages``` option. (If you also set ```--no-layout``` as well no layout will be performed, so it will be faster but the output will be the same anyway). However, this will not work with standard output, only with a file output.

**Comment by craigsapp** [comment]
Yes... that is very obvious.  Your story checks out.  Perhaps add an additional option called `--raw-mei` or `-t raw-mei` which would turn on both `--all-pages` and `--no-layout` to make that functionality more obscure?

For the option `--all-pages`, what does "Output all pages with one output file per page" mean with respect to `-t mei`?  The program is 30% faster when `--no-layout` is also given (on a smallish test file), so having it included automatically in a meta-option would be useful.

**Comment by craigsapp** [comment]
And it would be useful to allow `--raw-mei` to output to standard output, as there is only one file ever output.

**Comment by lpugin** [comment]
Yes, we need to rethink this. Actually the default with ```-t mei``` should be all pages, in score-based MEI and without doing the layout. Then if a page number is provided (```--page 1```) then it should output the page-based MEI for the corresponding page. File and standard output should be supported in any case. OK?

**Comment by craigsapp** [comment]
Yes, I like that.

**Comment by craigsapp** [comment]
> Yes, we need to rethink this. Actually the default with -t mei should be all pages, in score-based MEI and without doing the layout. Then if a page number is provided (--page 1) then it should output the page-based MEI for the corresponding page. File and standard output should be supported in any case. OK?

I have thought of a problem with this system.  Basically it is OK:

(1) -t mei outputs the non-paged MEI data (or whatever the input/converted MEI data is before it is paged).
(2) --page # would trigger the layout process, and return a single page.

The problem is that there will be cases where all pages of paged MEI data will be wanted.  The current system would require re-layout of the entire file to extract the next page.  For large works, the time wasted would increase greatly.

It would be useful to have an option setting which outputs all MEI pages as well as the single page output.  Perhaps --page 0 or similar could trigger all pages to be output?

**Comment by lpugin** [comment]
It think we could add a --page-based-mei option for this. Even though I am not sure people are interested to have page-based MEI.

**Comment by lpugin** [comment]
I have renamed the issue

**Comment by craigsapp** [comment]
See https://github.com/rism-ch/verovio/wiki/Backburner-Issues for possibly implementing this feature later.
