### ISSUE TITLE
Strange space after grace notes in certain conditions

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#223]
Here are two views of m16 of Der Lindenbaum in the Verovio viewer:

![screen shot 2016-06-30 at 6 27 43 am](https://cloud.githubusercontent.com/assets/3487289/16489897/5725cb5a-3e8c-11e6-861f-b222da8e1e69.png)
![screen shot 2016-06-30 at 6 29 11 am](https://cloud.githubusercontent.com/assets/3487289/16489900/5a63443c-3e8c-11e6-9af6-bd00360e2854.png)

The grace notes in m16 are spaced correctly when not in the first measure of the system, but when at the start of the system, extra space is added after the grace notes (which should be removed).

**Comment by lpugin** [comment]
Fixed in d8be65507c7a8cfebc2d997dedd036c8317e728e

**Comment by craigsapp** [comment]
Looks great:

![screen shot 2016-07-14 at 6 02 02 pm](https://cloud.githubusercontent.com/assets/3487289/16860439/1d1b1476-49ed-11e6-9be1-0d15fb325b3a.png)
![screen shot 2016-07-14 at 6 01 16 pm](https://cloud.githubusercontent.com/assets/3487289/16860440/1fbcf064-49ed-11e6-9917-7111def018df.png)
