### ISSUE TITLE
interesting offset note accidental case

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#226]
Here is an interesting case of accidental placement.

Verovio rendering:

![screen shot 2016-07-04 at 8 01 11 am](https://cloud.githubusercontent.com/assets/3487289/16564713/e36bbffa-41bd-11e6-8012-b95c7187bbaa.png)

This is following the rule that the top accidental is placed closest to the chord notes.

But in manually typeset music, the lower accidental is placed closer to the  noteheads since it can slip in underneath the offset note into a more compact configuration:

![screen shot 2016-07-04 at 8 01 01 am](https://cloud.githubusercontent.com/assets/3487289/16564686/b62b77ec-41bd-11e6-9c36-5b775ede528b.png)

Sample of other manual typesettings:

Cheating:

![screen shot 2016-07-04 at 8 07 42 am](https://cloud.githubusercontent.com/assets/3487289/16564804/697bc3ba-41be-11e6-81e3-e9417d334fb6.png)

![screen shot 2016-07-04 at 8 09 21 am](https://cloud.githubusercontent.com/assets/3487289/16564856/a71c479e-41be-11e6-860a-c246fe0db2b9.png)

![screen shot 2016-07-04 at 8 10 40 am](https://cloud.githubusercontent.com/assets/3487289/16564893/d17ddebc-41be-11e6-800a-021485828e6b.png)

![screen shot 2016-07-04 at 8 11 46 am](https://cloud.githubusercontent.com/assets/3487289/16564914/f9729e8a-41be-11e6-9eb6-59c9c41b336f.png)

![screen shot 2016-07-04 at 8 12 45 am](https://cloud.githubusercontent.com/assets/3487289/16564961/1cea72c0-41bf-11e6-838a-169ec07acfe1.png)

![screen shot 2016-07-04 at 8 13 53 am](https://cloud.githubusercontent.com/assets/3487289/16564985/441895c0-41bf-11e6-886b-b254c8ace7c6.png)

![screen shot 2016-07-04 at 8 14 41 am](https://cloud.githubusercontent.com/assets/3487289/16565007/6175c714-41bf-11e6-84a1-e3093d06989d.png)

![screen shot 2016-07-04 at 8 15 33 am](https://cloud.githubusercontent.com/assets/3487289/16565021/836c8fb0-41bf-11e6-8613-22f8734c52e5.png)

![screen shot 2016-07-04 at 8 16 29 am](https://cloud.githubusercontent.com/assets/3487289/16565041/a1f574a6-41bf-11e6-9b3a-814a3eb0c8e4.png)

From digitally typeset editions (which bulldoze over the problem with the same algorithm used in verovio):

![screen shot 2016-07-04 at 8 17 34 am](https://cloud.githubusercontent.com/assets/3487289/16565069/cc4fc5c6-41bf-11e6-9e5e-83986b0599d5.png)

![screen shot 2016-07-04 at 8 18 25 am](https://cloud.githubusercontent.com/assets/3487289/16565098/e6db1c9c-41bf-11e6-95a0-fe1d960dff9b.png)

![screen shot 2016-07-04 at 8 20 40 am](https://cloud.githubusercontent.com/assets/3487289/16565147/39cbc6b8-41c0-11e6-888e-b93babcea6c6.png)

**Comment by lpugin** [comment]
![image](https://cloud.githubusercontent.com/assets/689412/24929600/cb70a4c0-1f06-11e7-9f58-42789c6d8e44.png)
