### ISSUE TITLE
Slurs on tips vs. side of stems

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#228]
Sometimes having slurs attached to stem sides is nicer than attaching to the stem tips, but it is less common in real music compared to verovio renderings.

Here is a case where it is bad:

![screen shot 2016-07-04 at 8 58 48 am](https://cloud.githubusercontent.com/assets/3487289/16565968/c9a34c52-41c5-11e6-9bc8-bc388b8d033c.png)

The manual typesetting version:

![screen shot 2016-07-04 at 8 58 39 am](https://cloud.githubusercontent.com/assets/3487289/16565978/d6c4beca-41c5-11e6-954f-56e9f34dd125.png)

The curvature is exaggerated due to needing to allow space for the intervening stems.  This decreases readability of the music.

Perhaps one of these two rules could be implemented:

(1) If stem-attached slurs causes an increase in the slur curvature, then select the tip-attached slurs instead.
(2) alternatively, only use stem-side slurs when there are no notes between the two endpoints (i.e., only two notes in the slur).

(1) is probably a better rule and might work in the general case.

**Comment by lpugin** [comment]
Maximum curvature was reduced. We can eventually make it a paramter
