### ISSUE TITLE
Don't allocate extra space for clef change on other staves

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#231]
In the MEI viewer samples, Chopin Etude Op. 10 No. 9, m65, there is a clef change in the bottom staff:

![screen shot 2016-07-04 at 8 04 38 pm](https://cloud.githubusercontent.com/assets/3487289/16572926/0d1816f4-4223-11e6-9d24-e0798661e713.png)

The notes in the top staff are moved to accommodate the clef, but they should not.   Here is a sample hand typesetting of these measures:

![screen shot 2016-07-04 at 8 09 58 pm](https://cloud.githubusercontent.com/assets/3487289/16572947/57f99b3e-4223-11e6-87c2-4290e77df17f.png)

The extra space does not seem to be related to the *legerissimo* text, as the gap is still there when it is removed:

![screen shot 2016-07-04 at 8 11 38 pm](https://cloud.githubusercontent.com/assets/3487289/16572992/a8d3d63c-4223-11e6-8587-48e970f47c39.png)

**Comment by lpugin** [comment]
Fixed in d8be65507c7a8cfebc2d997dedd036c8317e728e

**Comment by craigsapp** [comment]
That is great!  Although I will be extra picky and point out that the spacing is a bit wide on each side of the clef.  This causes the clef to push the music on the top staff out a little:

![screen shot 2016-07-14 at 5 30 29 pm](https://cloud.githubusercontent.com/assets/3487289/16860236/db075a56-49ea-11e6-8168-244c28c28348.png)

The maximum margin around the clef should be about 1 staff space (2 diatonic steps).  This would not include the ledger lines (which might be included at the moment).

Probably a secondary rule would be to decrease the space down to 1/2 staff space (1 diatonic step) if the clef causes music to be spread out on other staves.

Here is the default spacing behavior in SCORE for this example:

![screen shot 2016-07-14 at 5 44 47 pm](https://cloud.githubusercontent.com/assets/3487289/16860264/218c3604-49eb-11e6-972c-e29b56649b66.png)

There is a tiny bit of spreading in the music on the top staff, but not very much.

**Comment by lpugin** [comment]
Yes, I am aware of this. There is also an issue with clef change with measures with mRests. However, fixing these will require some significant changes in the way clefs are aligned, so I'll leave them for now.
