### ISSUE TITLE
Toolkit::GetMEI() naming convention

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#243]
The function `Toolkit::GetMEI()` does not exactly match the CamelCase pattern libmei, and should perhaps better be spelled `Toolkit::GetMei()`. MEI is an abbreviation treated as a word, so should just capitalize the first letter.  Compare to libmei functions: GetMm(), SetMmUnit(), SetMmDots(), SetVuHeight() (although not all libmei functions strictly follow this pattern).

Also `MeiOutput::SetScoreBasedMEI()` (you can keep `m_scoreBasedMEI` since it is a private variable :-)

Also `Doc::ExportMIDI()`

**Comment by lpugin** [comment]
Not sure about this. I am fine with MEI all in capital letters in the same way MIDI is.
