### ISSUE TITLE
Directives in mensural notation aren't drawn

### ISSUE THREAD

**Issue by donbyrd** [rism-ch/verovio#248]
In mensural notation (i.e., on staves with a mensural notation.type), <dir> directives aren't drawn. See the attached file.
[AllMensuralDurs.txt](https://github.com/rism-ch/verovio/files/371416/AllMensuralDurs.txt)

**Comment by lpugin** [comment]
This is indeed not supported. I changed the label to feature request.

**Comment by donbyrd** [comment]
You're' the boss, but it seems to me it obviously _should_ work, and even the experts were surprised it didn't; therefore it's a bug. I'd be interested in hearing why you disagree, but it's really no big deal.

**Comment by lpugin** [comment]
```dir``` within ```layer``` is not implemented, so I don't think it is a bug. What is a bug is the additional staff that is shown when reading mensural data with ```dir``` within ```section```, but the example you attached is a former one.

**Comment by donbyrd** [comment]
OK, I see. But fixing bug seems like it'd accomplish very little. Giving an error message for the illegal placement of the dir would be more helpful. Though I suppose validating the MEI file would do that?

**Comment by lpugin** [comment]
Yes indeed, the MEI is actually not valid, so there is no bug at all.

**Comment by pe-ro** [comment]
Don's example file validates against 3.0.0 (http://www.music-encoding.org/schema/current/mei-Mensural.rng).

**Comment by pe-ro** [comment]
Don's question raises an interesting issue -- Currently, some control events are allowed within `<layer>` when the mensural module is turned on.  But, I'm wondering if this is really desirable.  Perhaps it would be better to allow these control events (dir, dynam, ornam, phrase, and tempo) within `<staff>` instead. The presence/values of `@staff` and `@layer` can be disallowed/controlled via Schematron (but this probably ought to be the case anyway).

The side effect of this change would be that these control events would also be legal in `<staff>` when the MEI-all schema is used.  (They are, in fact, allowed now in `<layer>` under MEI-all.)  We just have to encourage people to be very, very cautious about using MEI-all. :-)  It really is "the kitchen sink" and everything else, too.

I wanted to put this on the table before any work is done on implementing `<dir>` in `<layer>`.

**Comment by donbyrd** [comment]
I assume you mean my example file with your correction? Or does my original file (improperly) validate?

**Comment by pe-ro** [comment]
I meant the file I corrected.  Your original file did not validate.

**Comment by donbyrd** [comment]
Glad to hear that :-) .

**Comment by lpugin** [comment]
Yes, what I meant was that Don's original file did not validate, so it is not a bug in Verovio to create a third staff. No big deal anyway.

Regarding the placement of control events, having them within ```staff``` instead of ```layer``` would be more similar to CMN in the sense that they would be place after the music content and have their placement encoded with a reference to an id or a timestamp. 

```
<staff>
    <layer>
        <note pname="d" dur="longa" oct="5"/>
        <note pname="c" dur="brevis" oct="5"/>
        <note xml:id="n1" pname="b" dur="semibrevis" oct="4"/>
        <note pname="c" dur="minima" oct="5"/>
        <note pname="g" dur="minima" oct="4"/>
        <barLine />
        <note pname="f" dur="maxima" oct="4"/>
        <note xml:id="note-67" pname="g" dur="longa" oct="4"/>
    </layer>
    <dir place="above" startid="#n1">testing</dir>
</staff>
```

I must say that for me it does not make much sense to have them in ```layer``` with a ```@staff``` attribute but also have a placement indication. I would expect them to occur where they are when encoded in ```layer```. Something like:
```
<layer>
    <note pname="d" dur="longa" oct="5"/>
    <note pname="c" dur="brevis" oct="5"/>
    <note pname="b" dur="semibrevis" oct="4"/>
    <dir place="above">testing</dir>
    <note pname="c" dur="minima" oct="5"/>
    <note pname="g" dur="minima" oct="4"/>
    <barLine />
    <note pname="f" dur="maxima" oct="4"/>
    <note xml:id="note-67" pname="g" dur="longa" oct="4"/>
</layer>
```

A related important question is how to encode positioning. ```@tstamp``` will not work well with mensural notation, so I have the feeling they should be discarded completely in mensural (only). 

Maybe the discussion should be moved to the mensural-ig mailing list or to MEI-L?

**Comment by pe-ro** [comment]
@lpugin, I think you're right -- it makes more sense to put control events within `<staff>` than within `<layer>` in mensural notation.  I'll work out how to get them there without allowing them in CMN.

I'll rely on you and/or Don to bring this up on MEI-L.

**Comment by donbyrd** [comment]
Laurent, I agree with all your comments about placement of <dir>s and control of positioning.

Perry, I agree this discussion should be moved. Offhand, I'd say the mensural-ig mailing list makes more sense than MEI-L, but I don't feel strongly. I feel more strongly that Laurent should be the person to do it :-) . I doubt I could do a good job because I don't understand MEI's assumptions/preferences/rules about e.g. what can be nested in what very well.

**Comment by lpugin** [comment]
General feature request
