### ISSUE TITLE
--max-systems-per-page option

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#249]
It would be useful to have an option called `--max-systems-per-page` (`maxSystemsPerPage`).  This would allow in particular generating incipits based on the first system of a work, and would otherwise allow extracting separate SVG images for each system (which I can imagine would be useful as well).

Is there currently otherwise a robust way of extracting an incipit?  If I make the page height too short, no music will be output.  The `--spacing-system` option is limited to "12", so I cannot force a large distance to the next system, effectively preventing two systems on a page.

**Comment by lpugin** [comment]
It makes sense to have this option.

**Comment by rettinghaus** [comment]
For rendering incipits it would be nice to have an option just taking the encoded incipit from the MEI file, so you don’t have to fiddle with an XSLT.

**Comment by craigsapp** [comment]
That would be good too.  Something like

```bash
    verovio --incipit
```

A nice enhancement for `--incipit` is that if there were not an incipit encoded in the data, the program would set maxSystemPerPage to 1 and page to 1 in order to output the first system of music.

Is there a way of using `--appXPathQuery` to extract an explicitly encoded incipit?  Perhaps too complicated as this would probably require re-arranging the tree structure of the document.

Of course, I am way too lazy to separately encode an incipit in the header, so I would do:

```bash
    verovio --max-systems-per-page 1 --page 1
```

**Comment by craigsapp** [comment]
https://github.com/rism-ch/verovio/wiki/Backburner-Issues
