### ISSUE TITLE
Document the vrvToolkit.getMEI() options

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#260]
It would be useful if the vrvToolkit had a `getRawMEI()` or similar function which would return the input MEI data before layout is applied to the data, so that importer's direct output can be extracted in JavaScript.  This would function similar to `vrvToolkit.getMEI()` which returns the post-layout MEI data organized by `<pages>`.

Also, the page:
    http://www.verovio.org/javascript.xhtml
does not list vrvToolkit.getMEI().  Perhaps the page needs updating, as the official list of vrvToolkit  functions is found in the emscripten build.sh script:

https://github.com/rism-ch/verovio/blob/master/emscripten/build.sh#L190-L206

```
		'_vrvToolkit_constructor',\
		'_vrvToolkit_destructor',\
		'_vrvToolkit_getElementsAtTime',\
		'_vrvToolkit_getLog',\
		'_vrvToolkit_getVersion',\
		'_vrvToolkit_getMEI',\
		'_vrvToolkit_getPageCount',\
		'_vrvToolkit_getPageWithElement',\
		'_vrvToolkit_getTimeForElement',\
		'_vrvToolkit_loadData',\
		'_vrvToolkit_redoLayout',\
		'_vrvToolkit_renderData',\
		'_vrvToolkit_renderPage',\
		'_vrvToolkit_renderToMidi',\
		'_vrvToolkit_setOptions',\
		'_vrvToolkit_edit',\
		'_vrvToolkit_getElementAttr']" \
```

**Comment by lpugin** [comment]
The documentation indeed needs to be updated.

The ```getMEI``` method is the same of the ```Toolkit``` class. You can do ```vrvToolkit.getMEI(0, 1)``` in order to get the score-based MEI. If you set a page number, only the ```score``` element will be outputted (and not the entire file with the header).

**Comment by craigsapp** [comment]
Thanks!  How will I remember that the third time? :-).  VRV now shows the score-based MEI for the "m" command.
