### ISSUE TITLE
"getTimeForElement" and "getElementsAtTime" not working in Python

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#261]
The two functions `getTimeForElement(xmlId)` and `getElementsAtTime(millisec)` are not working in Python (at least on Windows, don't know about POSIX).
First one always returns `0.0`, the result of the second one is empty.

**Comment by raygray** [comment]
Both functions work only if Verovio is compiled with the USE_EMSCRIPTEN preprocessor definition set.

**Comment by sonovice** [comment]
> Both functions work only if Verovio is compiled with the USE_EMSCRIPTEN preprocessor definition set.
Thanks for clarifying. Is there a particual reason for not having it always included?

**Comment by lpugin** [comment]
The reason not to have it included is that it also requires the JSON lib for the output, which was meant to be included only in the JavaScript version. We can also include them in the Python binding if this is desirable.

**Comment by sonovice** [comment]
> We can also include them in the Python binding if this is desirable.

That would be a really great, I would appreciate it.

**Comment by lpugin** [comment]
It is now included in https://github.com/rism-ch/verovio/tree/develop-python-win32

**Comment by sonovice** [comment]
Thanks a lot!
