### ISSUE TITLE
Partial-layer layout analysis

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#262]
In piano music it is common to have _partial layers_ where a voice pops in or out as needed.   I am presuming that the `<space>` element is used to fill out the layer to complete it, since there are no partial layers in MEI.

Here is an example of a partial layer in the first measure, bottom staff:

![screen shot 2016-07-31 at 3 06 23 pm](https://cloud.githubusercontent.com/assets/3487289/17279737/3486a30e-5731-11e6-98b6-2262ae42431f.png)

The first beat has two voices, while the second and third beats have one voice.  

Here is how I encode that measure/staff in MEI:

``` xml
<staff xml:id="staff-000000151325027" n="2">
   <layer xml:id="layer-000000184270552" n="1">
       <note xml:id="note-000000149006848" dur="4" oct="4" pname="c" accid.ges="n" stem.dir="up" />
       <space xml:id="space-000000177415250" dur="2" />
   </layer>
   <layer xml:id="layer-000000037062890" n="2">
       <beam xml:id="beam-000000145743003">
           <note xml:id="note-000000082812056" dur="8" oct="3" pname="e" accid.ges="n" stem.dir="down" />
           <note xml:id="note-000000038078613" dur="8" oct="3" pname="f" accid.ges="n" stem.dir="down" />
       </beam>
       <beam xml:id="beam-000000037128607">
           <tuplet xml:id="tuplet-000000176511841" num="3" numbase="2" num.visible="false" bracket.visible="false" num.format="count">
               <note xml:id="note-000000100603401" dur="8" oct="3" pname="g" accid.ges="n" stem.dir="down" />
               <note xml:id="note-000000127500450" dur="8" oct="4" pname="c" accid.ges="n" stem.dir="down" />
               <note xml:id="note-000000140883534" dur="8" oct="4" pname="e" accid.ges="n" stem.dir="down" />
           </tuplet>
       </beam>
       <beam xml:id="beam-000000114638665">
           <tuplet xml:id="tuplet-000000009726331" num="3" numbase="2" num.visible="false" bracket.visible="false" num.format="count">
               <note xml:id="note-000000046947983" dur="8" oct="3" pname="g" accid.ges="n" stem.dir="down" />
               <note xml:id="note-000000069271818" dur="8" oct="4" pname="d" accid.ges="n" stem.dir="down" />
               <note xml:id="note-000000100573532" dur="8" oct="4" pname="f" accid.ges="n" stem.dir="down" />
           </tuplet>
       </beam>
   </layer>
</staff>
<slur xml:id="slur-000000014100201" staff="2" startid="#note-000000100603401" endid="#note-000000140883534" />
<slur xml:id="slur-000000054988896" staff="2" startid="#note-000000046947983" endid="#note-000000100573532" />
```

Here is the verovio rendering:

![screen shot 2016-07-31 at 3 41 01 pm](https://cloud.githubusercontent.com/assets/3487289/17279869/4108496c-5735-11e6-8a2a-701bf438d7ec.png)

Notice that the slurs are shown underneath the notes as if the music were in the second layer on the staff (as it _is_ encoded in the second layer).  If the `<space>` element is removed from layer 1 to make an implicit space at the end of the measure, the same rendering will be given.  However, there is only one real layer for the second and third beats of this measure.  And the slurs should ideally be placed as if there were only one layer, despite being in the `@n="2"` layer.

If these notes are moved to the first layer and the `<space>` element is added to the second layer, the music is arranged properly:

![screen shot 2016-07-31 at 3 50 35 pm](https://cloud.githubusercontent.com/assets/3487289/17279911/a250c072-5736-11e6-9bff-84311a9ed3dc.png)

Full sample measure/staff example encoding:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-07-31 15:47:04</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.12-dev-a018b75-dirty</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000022849767">
                        <staffGrp xml:id="m-000000071336861">
                            <staffDef xml:id="staffdef-000000018514471" clef.shape="F" clef.line="4" key.sig="1f" meter.count="3" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure xml:id="measure-000000199783650" n="16">
                            <staff xml:id="staff-000000136487161" n="1">
                                <!-- kern: =16-  *Xtuplet  *^  4c/  (12G\L  12c\  12e\J)  (12G\L  12d\  12f\J)  *v  = -->
                                <layer xml:id="layer-000000212445011" n="1">
                                    <note xml:id="note-000000157003501" dur="4" oct="4" pname="c" accid.ges="n" stem.dir="up" />
                                    <beam xml:id="beam-000000144685918">
                                        <tuplet xml:id="tuplet-000000140503773" num="3" numbase="2" num.visible="false" bracket.visible="false" num.format="count">
                                            <note xml:id="note-000000073902973" dur="8" oct="3" pname="g" accid.ges="n" stem.dir="down" />
                                            <note xml:id="note-000000197479193" dur="8" oct="4" pname="c" accid.ges="n" stem.dir="down" />
                                            <note xml:id="note-000000096820312" dur="8" oct="4" pname="e" accid.ges="n" stem.dir="down" />
                                        </tuplet>
                                    </beam>
                                    <beam xml:id="beam-000000115062496">
                                        <tuplet xml:id="tuplet-000000046356232" num="3" numbase="2" num.visible="false" bracket.visible="false" num.format="count">
                                            <note xml:id="note-000000002135857" dur="8" oct="3" pname="g" accid.ges="n" stem.dir="down" />
                                            <note xml:id="note-000000034376736" dur="8" oct="4" pname="d" accid.ges="n" stem.dir="down" />
                                            <note xml:id="note-000000096704270" dur="8" oct="4" pname="f" accid.ges="n" stem.dir="down" />
                                        </tuplet>
                                    </beam>
                                </layer>
                                <!-- kern: 8E\L  8F\J  2ryy  *v -->
                                <layer xml:id="layer-000000069609957" n="2">
                                    <beam xml:id="beam-000000200204778">
                                        <note xml:id="note-000000164327407" dur="8" oct="3" pname="e" accid.ges="n" stem.dir="down" />
                                        <note xml:id="note-000000186761087" dur="8" oct="3" pname="f" accid.ges="n" stem.dir="down" />
                                    </beam>
                                    <space xml:id="space-000000131502518" dur="2" />
                                </layer>
                            </staff>
                            <slur xml:id="slur-000000110632855" staff="1" startid="#note-000000073902973" endid="#note-000000096820312" />
                            <slur xml:id="slur-000000093048563" staff="1" startid="#note-000000002135857" endid="#note-000000096704270" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

The second encoding is not as elegant, as the bottom voice clearly continues through the whole measure rather than the top voice.  This is also of concern for cases where a slur might otherwise cross a layer when it would otherwise be better to encoded the vocal line in the same layer.

So to get finally to the feature request:

It would be useful if verovio monitored layers for `<space>`, and if it finds a region where only one layer has a space while the other(s) does/do not, then treat the music in that layer as if it were a single-layer case for layout purposes.

**Comment by craigsapp** [comment]
Don't forget this one.  Partial layers are needed for proper automatic layout of piano music.

For example here is sample music with two complete layers in the first staff:

<img width="475" alt="screen shot 2017-01-27 at 09 34 26" src="https://cloud.githubusercontent.com/assets/3487289/22380854/f20c30ae-e473-11e6-88ae-90cb7f37548b.png">

The musical elements are laid out correctly (stem directions, staccato and slur placement).

However, when the `rest` is turned into a `space`:

<img width="490" alt="screen shot 2017-01-27 at 09 34 18" src="https://cloud.githubusercontent.com/assets/3487289/22380897/1be89fe8-e474-11e6-92d6-98529689c311.png">

The staccato and slur on the beamed notes are no longer in the correct position, which should be above the notes (the stem directions can be affected, but not in this case).

What should happen is the staff layers should be mapped into regions of partial layers.  In this case the first half of the measure should be treated as a single layer (orange highlight below), and the second half as two layers:

<img width="522" alt="screen shot 2017-01-27 at 09 34 40" src="https://cloud.githubusercontent.com/assets/3487289/22380990/82d8e3fc-e474-11e6-9384-673770a432d2.png">

Autodetection of partial layers is most useful for two-layer cases since three and more layers may be too complicated to manipulate automatically.  But the two-layer cases is straight-forward.  The basic algorithm would be to segment by regions containing spaces, but with a complication is that the segmentation cannot cut through a beam group.

**Comment by donbyrd** [comment]
@craigsapp says what Verovio should do is "if it finds a region where only one layer has a space while the other(s) does/do not, then treat the music in that layer as if it were a single-layer case for layout purposes." I'm pretty sure he means a region where every layer _but_ one has a space! A much more difficult question is the definition of a region. I agree that "the segmentation cannot cut through a beam group". But if one of two voices drops out in the middle of the measure for only a note or two, two-voice notation shouldn't be suspended. Also, if a voice drops and comes back in repeatedly in a measure, switching back and forth between one-voice and two-voice notation is going to look silly. But that's rare enough that it might not be worth worrying about.

**Comment by craigsapp** [comment]
>  'if it finds a region where only one layer has a space while the other(s) does/do not, then treat the music in that layer as if it were a single-layer case for layout purposes." I'm pretty sure he means a region where every layer but one has a space! 

Yes, if all layers except one have a space at a given tstamp, then treat that  layer as if it were the only layer.  For now I would only worry about identifying partial layers for two-layer staves.  If there are more than two layers, automatic layout might not do too well and would require manually assigned layout that is not necessary in one or two layers.  Otherwise, three-layer staves could be analyzed for being partially one, two or three layers.  Music in the one-layer regions would be processed with the one-layer layout algorithm; two-layer regions with the two-layer layout algorithm; and good luck for the three-layer (or more) regions doing automatic layout.

> But if one of two voices drops out in the middle of the measure for only a note or two, two-voice notation shouldn't be suspended. Also, if a voice drops and comes back in repeatedly in a measure, switching back and forth between one-voice and two-voice notation is going to look silly. But that's rare enough that it might not be worth worrying about.

Just provided exceptions to the basic algorithm I propose, and I will believe it :-) I am mostly looking at the piano music of Mozart, Beethoven, and Chopin.  Baroque harpsichord music might have some exceptions.  Alternatively there could be two types of spaces in MEI: one which allows partial layer analysis, and one that does not.  Or there could be an attribute added to the current space element which controls that.

The purpose of this feature is to minimize encoding of explicit layout information when it could be properly calculated 99% of the time.  The 1% leftovers can be explicitly encoded contrary to the general rule rather than the other way around.  Other than for encoding efficiency, this feature would be useful for transposing piano music.

Here is the only case that I have found where a space does not activate a single-layer layout region:

<img width="697" alt="spaces2" src="https://cloud.githubusercontent.com/assets/3487289/22392167/5d21f2d4-e4ab-11e6-90c1-bc6cf6afc546.png">

There green regions show where spaces are added to the music in order to fill in a layer.  In this case there are two spaces encoded in each measure within the second layer.  The first one in each measure is within a beam group as well as occurring completely within a beam group in another layer, so it does not trigger a segmentation boundary.  However, the second space in each layer does trigger a partial-layer region so that the second half of each measure is treated as if it were in a measure with a single layer for layout purposes (and it should perferrably not matter which layer the notes in the non-space layer are in).

The two staccatos, slur and tie highlighted in red have to be given explicitly layout directions when not using the partial-layer layout algorithm; otherwise, these elements would be positioned above the notes rather than below.  As there are 15 notes in the measure, that is about an intervention rate of 25% rather than the 0% needed in the case of the partial-layer layout algorithm.

**Comment by pe-ro** [comment]
@craigsapp, +1 for switching into "single layer mode" when all but one voice has space(s).

**Comment by donbyrd** [comment]
I'll have to be more careful; I shot from the hip on this, after shooting from the hip on the mensural-IG list the day before. Sorry, Craig! I was thinking yesterday, and should have said, I like your idea. I'm sure there are few if any cases it can't handle in Mozart and  Beethoven. Once Bach died, and with him music notated as if strictly linear regardless of whether it is, died away, it's not until the time of Chopin that this became at all common. But even in Chopin, after looking around, I found that most of the nasty cases I was thinking of either have explicit rests for the 2nd voice -- it doesn't just disappear -- and most of the others have more than two voices. The best example of what I was talking about is this, from the Chopin F-minor Ballade (no. 4):
![chopin_ballade4_voiceisin out](https://cloud.githubusercontent.com/assets/1672175/22401180/8f8eb0ca-e598-11e6-8b57-b66eb73cc03e.png)
And there are many places in the Bach solo-violin Chaconne where a second voice appears and disappears twice in a measure -- but (in the old Gesellschaft edition) the slurs are positioned as if the other voice isn't there!:
![bach_chaconne_voiceisin out](https://cloud.githubusercontent.com/assets/1672175/22401191/a1ae940a-e598-11e6-8aa3-f2d4caaba2af.png)
Finally, you mention "the only case that I have found where a space does not activate a single-layer layout region", where one voice has three triplet 8ths and the other has two eighths, sharing noteheads with the first and third notes of the triplet. I'm not sure what you mean by "the only case", but (thanks to Jay Hook, a theorist here at IU) I know of at least a dozen pieces with notation essentially the same feature. Here's one from Brahms' Variations on an Original Theme, Op. 21 no. 1:
![brahms_op21no1_impossiblerhythm](https://cloud.githubusercontent.com/assets/1672175/22401195/ac9db9ae-e598-11e6-94ee-ed09655de955.png)

**Comment by craigsapp** [comment]
This is a good example:

<img width="460" alt="screen shot 2017-01-28 at 17 38 09" src="https://cloud.githubusercontent.com/assets/3487289/22401237/e3b0f0fe-e580-11e6-90b1-994a166f1a38.png">

In this case the single-layer mode will not be activated since all spaces are spanned by beams in the other voice.   The slurs will be placed incorrectly by the automatic layout algorithm, which will  place the slurs below the 16th notes.  So in this case an explicit `@curvedur="above"` would be needed for the slurs.  But no `note@stem.dir` parameters would be needed, so only three explicit layout parameters are needed for the example.

Here is a similar breaking of the basic algorithm in the first edition of Beethoven's first piano sonata (1796):

<img width="431" alt="screen shot 2017-01-28 at 17 50 24" src="https://cloud.githubusercontent.com/assets/3487289/22401282/5a81803a-e582-11e6-8091-7ba5a65773a4.png">

http://hz.imslp.info/files/imglnks/usimg/6/60/IMSLP51970-PMLP01446-Beethoven_-_Piano_Sonata_No.1__Artaria_.pdf

The staccatos are on the "wrong" side of the notes, since they are in the first layer and should be placed above the stems in the two-layer layout algorithm.   So, again, the layout should be encoded explicitly as opposed to trying to complicate the layout algorithm to compensate for this case.  Most later editions do move the staccato's to the other side of the note:

Peters' edition *c*1920:

<img width="594" alt="screen shot 2017-01-28 at 17 54 03" src="https://cloud.githubusercontent.com/assets/3487289/22401304/d7d5ffb6-e582-11e6-978a-f76fe2f683bd.png">

http://ks.petruccimusiclibrary.org/files/imglnks/usimg/1/13/IMSLP66390-PMLP01446-Sonata_F_minor_Opus_2_no_1.pdf


Here is a case of the stem directions violating the two-layer layout algorithm (Chopin mazurka 30/4, G. Schirmer/Mikuli edition *c*1912):

<img width="430" alt="screen shot 2017-01-28 at 18 01 18" src="https://cloud.githubusercontent.com/assets/3487289/22401338/d7c1075e-e583-11e6-9f63-3a6d2ddc09c8.png">

In this case both layers in the second staff have stems down.   The F#3 should be placed in the first layer with `@stem.dir="below"` rather than putting it in the second layer which then requires more `@stem.dir="below"` for the chords that would then be placed in the first layer.

-------------

> I'm not sure what you mean by "the only case"

I was meaning the only case that I have come across while testing conversions from Humdrum to MEI/verovio :-)

**Comment by donbyrd** [comment]
To clarify (for me, anyway; it may be obvious to everyone else), when you say "The slurs will be placed incorrectly by the automatic layout algorithm, which will place the slurs below the 16th notes", you mean _incorrectly_ for anything like a diplomatic transcription, attempting to reproduce the style of the original formatting. But in terms of standard practice, the automatic layout algorithm will place the slurs _correctly_. Am I not correct?  :-)

**Comment by craigsapp** [comment]
Yes, I am mostly meaning *incorrectly* in terms of a diplomatic transcription.  But I am not completely saying that the basic two-layer algorithm is standard practice, and it could have exceptions.   For example, I don't see either of these two being preferrable as "standard practice":

<img width="763" alt="screen shot 2017-01-29 at 09 20 57" src="https://cloud.githubusercontent.com/assets/3487289/22406266/ef790c44-e604-11e6-8955-ba1d870af896.png">

<img width="771" alt="screen shot 2017-01-29 at 09 22 59" src="https://cloud.githubusercontent.com/assets/3487289/22406267/f0b62a1a-e604-11e6-9080-a6a8f51c458e.png">

However I am a pianist, and therefore used to doing more vertical scanning of the music.  A violinist may have more difficulty in reading the second example, preferring the slurs to be more centrally located. 

Also the first example has a more concise and clean look to it which the second one does not (partially due to issue #225).

**Comment by donbyrd** [comment]
I actually like the second example better, but more on principle than because I find it more readable. But I'm also a pianist, and, as you say, violinists might have more difficulty with it.

**Comment by lpugin** [comment]
This should now be done

**Comment by craigsapp** [comment]
Yeah!!!!! I was noticing it being implemented last week, but didn't have time to try it out.

Sample:

<img width="467" alt="screen shot 2017-07-14 at 9 30 40 pm" src="https://user-images.githubusercontent.com/3487289/28228245-f53af23a-68dd-11e7-81e7-61e8465c8169.png">


```
**kern
*clefF4
*M3/4
=16
*^
4c	8EL
.	8FJ
*v	*v
*Xtuplet
(12GL
12c
12eJ)
(12GL
12d
12fJ)
=
*-
```

**Comment by rettinghaus** [comment]
It would be good to implement support for `@layerscheme` (`att.staffDef.vis`) to control (stem) behavior.

**Comment by craigsapp** [comment]
How is `staffDef@layerscheme="3o"` used to determine stem directions?  for `2o` it is reasonable to assume that layer 1 has stems up and layer 2 has stems down, but the mapping of up and down stems for 3 voices is not as straight-forward.

Also, it would be useful to add an attribute to `<layer>` which specifies the direction of stems for notes in the layer.  This would particularly be useful for layers 3 and higher.

And what happens when the number of voices change, would a `staffDef` need to be given to update the number of layers at each change in layer counts on the staff?

What if someone wants to reverse the direction of stems for layer 1 and 2 so that layer 1 stems are down, and layer 2 notes are stem up?  This might be particularly useful for 3+ layers where the layer enumeration can be more flexible.

**Comment by rettinghaus** [comment]
All legitimate questions, but they're not to be solved by Verovio. I like the new default rendering, but I would like to have the ability to force stem directions without using `@stem.dir`. And AFAICS `layerscheme` is the only way MEI offers so far.

**Comment by pe-ro** [comment]
> the mapping of up and down stems for 3 voices is not as straight-forward

The assumption (borrowed from Mup) is that "3o" is just like "2o" with an additional voice; that is, the first 2 voices are assigned stems up and stems down, respectively, and the 3rd voice must specify the direction of stems on every note.

**Comment by craigsapp** [comment]
>  and the 3rd voice must specify the direction of stems on every note.

That is what I am doing for 3-layer staves now, but it would be useful to be able to specify a global `staffDef` or local `layer` control of layer-3 stem directions to avoid having to specifiy stem directions on all notes in such a layer.  This might also be useful for manipulating music, since the stem directions could be controlled outside of the note depending on which layer the music is moved to.

This would be useful to further generalize the mup system for MEI, such as `3oa`/`3fa` for three voices with the 3rd voice having stems up (above), and `3ob`/`3ob` for 3rd voice having stems down (unless overridden by `staff@stem.dir`).

Although more though would have to be given to how to generalize this to more voices or to change the defaults of the stem directions for first two voices.

**Comment by craigsapp** [comment]
Another useful parameter to indicate somewhere is what the preferred stem direction of notes on the middle line should be.  This would be useful to include in `<staffDef>` since it can be dependent on the instrument.  Voice parts often use stem up for the middle note on the staff so that the stem does not collide or get too close to the lyrics.  Also this parameter could be used to indicate the stem direction of beams notes that are symmetrically placed around the middle line:

<img width="1006" alt="screen shot 2017-07-20 at 10 34 55 pm" src="https://user-images.githubusercontent.com/3487289/28437644-afa40b36-6d9b-11e7-8e9f-1d4d16bb1bab.png">

**Comment by craigsapp** [comment]
Here is some crazy stuff from BWV 1001, which might be nice to control stems at the layer level within staves:


<img width="1134" alt="screen shot 2017-07-20 at 10 46 51 pm" src="https://user-images.githubusercontent.com/3487289/28438193-97805972-6d9d-11e7-9d0f-b10e2703b877.png">

a little later:

<img width="1127" alt="screen shot 2017-07-20 at 10 48 09 pm" src="https://user-images.githubusercontent.com/3487289/28438216-a753048a-6d9d-11e7-93e6-0c6a40f13801.png">

http://hz.imslp.info/files/imglnks/usimg/4/4f/IMSLP01304-BWV1001.pdf

**Comment by pe-ro** [comment]
> more though[t] would have to be given to how to generalize this to more voices or to change the defaults of the stem directions for first two voices.

I agree. 😁
