### ISSUE TITLE
Note durations in chords not rendered correctly

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#266]
Here is an excerpt of my mei file (one chord from the upper system, one from the lower):
```xml
<mei>
    <chord xml:id="A_mov9_measure135_s5l1_e1"
           stem.dir="down"
           dur="8"
           tstamp="1">
        <note xml:id="A_mov9_measure135_s5l1_e2"
              pname="b"
              oct="4"
              accid.ges="f"/>
        <note xml:id="A_mov9_measure135_s5l1_e3"
              pname="a"
              oct="5"
              accid.ges="f"/>
    </chord>
    [...]
    <chord xml:id="A_mov9_measure135_s6l1_e1" stem.dir="up">
        <note xml:id="A_mov9_measure135_s6l1_e2"
              dur="8"
              tstamp="1"
              pname="f"
              oct="4"/>
        <note xml:id="A_mov9_measure135_s6l1_e3"
              dur="8"
              tstamp="1"
              pname="d"
              oct="5"/>
    </chord>
</mei>
```
Verovio output:
![Output](https://cloud.githubusercontent.com/assets/8217108/17364105/99f404da-597e-11e6-8b7c-2d782847aada.PNG)

The durations are correctly shown if they are an attribute of the chord element (upper staff). Placing 'dur' directly in the note elements confuses Verovio.

**Comment by lpugin** [comment]
I don't think it is a good practice not to have the ```@dur``` on the ```chord```. 

Even for chords with multiple durations (very rare) I would still expect to have the longest duration on ```chord``` and then the shorter one on the ```note``` where appropriate.

**Comment by sonovice** [comment]
Agreed. Unfortunately I don't write these mei files on my own, so I have no influence on the style of coding. I just thought that it might be useful to pass up the note duration to the chord element if not explicitly provided.

**Comment by craigsapp** [comment]
Perhaps the rule should be: if there is no @dur on `<chord>` then go to the first child `<note>` element and read the @dur of that note.

**Comment by craigsapp** [comment]
How were these files created?  You could also filter the data with a not
very difficult XLST transform to add the dur data to the chord level.  I
don't see the need to limit the duration to the chord level if the children
elements could be searched for the desired duration.

**Comment by lpugin** [comment]
I would strongly recommend to have the duration moved to the chord level. I am closing the issue and this will be reconsider later for chords with different duration values.
