### ISSUE TITLE
DrawPolygon() always fills the polygon

### ISSUE THREAD

**Issue by donbyrd** [rism-ch/verovio#271]
Minimas  in black mensural notation, colored, should appear as hollow diamonds. Instead they're drawn as solid diamonds. This is because DrawPolygon() _always_ fills the polygon (and always in black), regardless of the pen and brush settings. A test MEI file is attached.

[AllMensuralDurs.txt](https://github.com/rism-ch/verovio/files/407474/AllMensuralDurs.txt)

**Comment by lpugin** [comment]
Fixed in 484044b339ddcb4364f906eb0ebe9b713b222c14
