### ISSUE TITLE
Creating xml:id values

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#274]
In the Humdrum Importer, every time I convert the score from Humdrum to MEI, the `xml:id`s are different.  It would be nice if the `xml:id`s could be produced the same way when the same data file (without any changes) is reconverted.  

(1) Is there a way, such as with a random seed, to produce the same `xml:id`s every time?  This would perhaps allow me to use the checksum for the file as a seed to randomly generated id numbers.

and/or

(2) Can I supply my own `xml:id` values?

An example verovio `xml:id`:  `note-000000189093144`.  If I can create my own xml ids, should the "note-" prefix (and similar for other classes) be maintained?  In other words, is this prefix for human readability, or does it have an additional function (such as MIDI playback)?

The C++ function names used to deal with xml ids imply that these are UUIDs (`GetUuid()`, `SetUuid()`), but technically they are not UUIDs  (https://en.wikipedia.org/wiki/Universally_unique_identifier).

I tracked down the id generator, which I see is a random-number generation using `rand()` from the C standard library:

https://github.com/rism-ch/verovio/blob/5637d0bd87dd0adde5b9210fdb48819234a381e3/src/object.cpp#L481-L489

But now I am wondering why they are different every time, since I cannot find a call to `srand()` which would initialize different sequences...

The ability to seed the random number generation would be useful, but also allowing user-supplied xml ids (or the part after the class name at least) would also be useful.

There are also C++ 11 ways to generate random numbers: http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution
The C++ ways might be able to fill in the leading zero in the current ids.

**Comment by lpugin** [comment]
> (2) Can I supply my own xml:id values?

It think this is already be possible. You only need to call SetUuid in your importer.

> If I can create my own xml ids, should the "note-" prefix (and similar for other classes) be maintained?

No, the prefix has no meaning and is there only for readability. (I am not sure it actually helps.)

> The C++ function names used to deal with xml ids imply that these are UUIDs (GetUuid(), SetUuid()), but technically they are not UUIDs 

I am aware of this. They were actually UUIDs at some point, but I changed them to something shorter because it was making reading the MEI very difficult.

> But now I am wondering why they are different every time, since I cannot find a call to srand() which would initialize different sequences...

https://github.com/rism-ch/verovio/blob/master/tools/main.cpp#L150-L151
and
https://github.com/rism-ch/verovio/blob/master/emscripten/emscripten_main.cpp#L35-L36

This is probably not the right place to have this. It should probably be in Object with a static member to check if it was initialized or not. Also, they are probably the same with the Python toolkit.

> The ability to seed the random number generation would be useful, but also allowing user-supplied xml ids (or the part after the class name at least) would also be useful.

Would you make it an option to the toolkit?

**Comment by craigsapp** [comment]
> Would you make it an option to the toolkit?

I can do that.  Moving it out of the interfaces and putting it in the object class should make things cleaner.  Which branch should it be done on and/or should it be done as a pull request?

And do you want to keep the C standard library rand(), or use C++11 random numbers (probably whichever is faster).

**Comment by lpugin** [comment]
> I can do that. Moving it out of the interfaces and putting it in the object class should make things cleaner. 

Great! Yes, it would be cleaner. The check for initialization can then happen directly in Object::GenerateUuid.

> Which branch should it be done on and/or should it be done as a pull request?

You create a develop-uuids branch in this repository.

> And do you want to keep the C standard library rand(), or use C++11 random numbers (probably whichever is faster).

I have no particular opinion on this. We can go for C++11 as long as it is not slower.

**Comment by craigsapp** [comment]
Standard C library function `rand()` is 12 times faster than the equivalent in C++11 random library, so we can stick with that:

C implementation:
```cpp
#include <stdlib.h>
#define maxval 123456789

int main(void) {
   double sum = 0.0;
   for (int i=0; i<maxval; i++) {
      sum += rand();
   }
   return 0;
}
```

This takes about one second to run:

```bash
$ time ./test1
real	0m0.994s
user	0m0.968s
sys   	0m0.005s
```

C++11 uniform random numbers:

```cpp
#include <random>
#include <climits>
#define maxval 123456789

int main(void) {
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_int_distribution<> dis(0, INT_MAX);

   double sum = 0.0;
   for (int i=0; i<maxval; i++) {
      sum += dis(gen);
   }
   return 0;
}
```

Which takes 12 seconds to run:

```bash
$ time ./test2
real	0m12.227s
user	0m12.128s
sys	0m0.034s
```

**Comment by lpugin** [comment]
Definitely

**Comment by craigsapp** [comment]
The only downside is that srand() and rand() are global and cannot be hidden within the Object class, so the seeding will affect all rand() uses, but there is only one use at the moment: generating xml:id values, so there is currently no problem.

**Comment by craigsapp** [comment]
I implemented the user-controlled seeding of Object in commit 868d3b023a6f945f8ead3cfd24f79cab2f63d5a2.

I checked the command-line interface at it works (using `--xml-id-seed #`.

The emscripten version compiled, but I did not test it yet.  The python interface is the same (from src/toolkit.cpp).

**Comment by lpugin** [comment]
What would you typicallly pass as parameter to --xml-id-seed? The file checksum?

**Comment by craigsapp** [comment]
Yes, that is what I am thinking.  But for the most part, I do not care about having IDs match across different files, so I myself may be lazy and just use a constant value (other than 0) for now.  

However, I might switch to XML IDs which are addresses to locations in the original file (such as primarily the line and column).  This could also be added to `@class`, but the addresses should be unique (for a particular file).  I might also add the checksum to the ID to make the addresses unique across multiple files.

**Comment by lpugin** [comment]
OK. Do I understand correctly that the ```@class``` would be added by your importer using the new SVGClass stuff and has nothing to do with the IDs generation?

**Comment by craigsapp** [comment]
Yes.  In the current importer I have lost access to `@class` because I want to process `<app>`.  To do so I convert to MEI (which would lose the `@class` information, and then re-import as an MEI file with the standard importer.

**Comment by lpugin** [comment]
@craigsapp this is done, isn't it?
