### ISSUE TITLE
Lower case IDs

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#275]
The `MeiOutput::UuidToMeiStr()` function forces `xml:id`s to always be lower case.  Is there a reason for that?   I don't see a reason, so I moved the `tolower` processing of `m_classid` into `Object::GenerateUuid()`; otherwise, `Object::SetUuid()` values will automatically be set to all lower case when writing `xml:id`s in `MeiOutput`.  See commit c606027c984bace5da2542fa9dc18e8991beaf14 in the `develop-uuids` branch.

**Comment by lpugin** [comment]
This is fine. I cannot remember the reason for the conversion to lower case when writing the data.
