### ISSUE TITLE
Support for harm elements to be displayed on top of chords

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#280]
Would be nice if chord-symbols like Am7, Gmaj7 etc could be shown in the score.

**Comment by lpugin** [comment]
How would they be represented in MEI?

**Comment by pe-ro** [comment]
Textual chord labels can be represented using:
```
<harm>Am7</harm>
etc.
```
Since they're text, one may use `<rend>` for special formatting:
```
<harm>Am<rend rend="sup">7</rend></harm>
```

**Comment by sannedubois** [comment]
HEllo LAurent,

The problem is that I have to convert ten thousands of music-xml files,
using sibmei. So it would be nice that the chords could be converted the
same way as the lyrics. Graig told me about this possibility to add it
manually, but that's not doable for me, would take me years.

In music xml for Fm7 it would be:

<harmony default-y="24">
        <root>
          <root-step>F</root-step>
        </root>
        <kind halign="center" text="m7">minor-seventh</kind>
 </harmony>

But I'm not sure if the sollution lies in the mei-viewer or in sibmei.
Sibmei should be able to convert and the mei-viewer should be able to
interpret/read?

Kind regards,
Derk













2016-08-22 23:43 GMT+02:00 pe-ro <notifications@github.com>:

**Comment by lpugin** [comment]
They are indeed two different issues. If the chord labels are displayed in Sibelius, then there is probably a way to have them converted to ```harm``` by Sibmei.

Another option is to add ```harm``` support to the musicxml importer in Verovio, but since this importer has much less features than Sibmei I assume it would create other issues for you to convert your data.

**Comment by lpugin** [comment]
Third option: have you tried the musicxml2mei stylesheet? https://github.com/music-encoding/encoding-tools

**Comment by ahankinson** [comment]
Can you send me one of your files with chord symbols? I can see about adding support for it in sibmei.

**Comment by sannedubois** [comment]
Thanks. I will contact Sibmei about it.

2016-08-23 8:42 GMT+02:00 Laurent Pugin <notifications@github.com>:

**Comment by sannedubois** [comment]
Hi Andrew,

That would be absolutely great!

I added an attachment with a music xml 3.0 file and a jpeg.

Kind regards,
Derk

2016-08-23 9:31 GMT+02:00 Andrew Hankinson <notifications@github.com>:

**Comment by ahankinson** [comment]
I think you have to send it to me directly; GitHub strips off attachments for e-mail replies.

**Comment by ahankinson** [comment]
I'll post this here since everyone seems to be watching it.

I've taken a stab at exporting `<harm>` from Sibelius. The test file is here:

https://www.dropbox.com/s/hcwguxvq16cc408/rigaudon.mei?dl=0

At the moment it's pretty bare-bones. I've placed the `<harm>` elements as a child of `<measure>` with `@tstamp` values for their placement. Let me know if anyone sees a problem with this.

**Comment by pe-ro** [comment]
@ahankinson :  Looks great.  Works better.  :-)

**Comment by pe-ro** [comment]
@ahankinson : The labels in the test file are all "simple" ones: C, Dm, G/B, etc. Are you also able to deal with more complex labels; that is, those with augmented or diminished intervals?

**Comment by sannedubois** [comment]
Do you want a file with more complex chord-symbols? I can do that, no
problem.

2016-08-23 15:00 GMT+02:00 pe-ro <notifications@github.com>:

**Comment by ahankinson** [comment]
If you can do more complex chord symbols that would be great. I can see what it will do and adjust if necessary.

**Comment by sannedubois** [comment]
I've been thinking about it and it seems in fact to be very simple, because
as you can see via the link below, as long as one uses the 'long' chord
symbol, it always stays 'text'. So you wouldn't have to add anything at all.

If you want to convert all special signs which are used, it will become
more complex.  Wikipedia shows very nicely that all chords have a long and
a short version.

Here it is:

https://en.wikipedia.org/wiki/Chord_names_and_symbols_(popular_music).

I'm a guitar player myself, but I wouldn't need the 'short' chord symbols,
with triangles, circles, +, -  etc.



2016-08-23 18:06 GMT+02:00 Andrew Hankinson <notifications@github.com>:

**Comment by lpugin** [comment]
Added in 3498019a3a49a00cae65d5e6dcb5778021036580
