### ISSUE TITLE
break is missing

### ISSUE THREAD

**Issue by cute** [rism-ch/verovio#284]
https://github.com/rism-ch/verovio/blob/1324a0d46b6ad6688e63e511fdf9c5627198edfd/src/view_element.cpp#L214

```
        case ACCIDENTAL_EXPLICIT_s: symc = SMUFL_E262_accidentalSharp; break;
        case ACCIDENTAL_EXPLICIT_ff: symc = SMUFL_E264_accidentalDoubleFlat;
        case ACCIDENTAL_EXPLICIT_f: symc = SMUFL_E260_accidentalFlat; break;
```

**Comment by craigsapp** [comment]
A ha.  That is why I get a flat when I want a double-flat, and adding the break should fix issue #200.  And I see from the same switch statement that there is no case for `ACCIDENTAL_EXPLICIT_x`.  Adding this case should fix issue #199 (currently a double sharp is displayed as a natural-sign).

Here are "explicit accidentals" defined in [libmei/atttypes.h](https://github.com/rism-ch/verovio/blob/master/libmei/atttypes.h#L25-L48) that should eventually have entries in this switch statement:

```cpp
enum data_ACCIDENTAL_EXPLICIT {
    ACCIDENTAL_EXPLICIT_NONE = 0,
    ACCIDENTAL_EXPLICIT_s,
    ACCIDENTAL_EXPLICIT_f,
    ACCIDENTAL_EXPLICIT_ss,
    ACCIDENTAL_EXPLICIT_x,
    ACCIDENTAL_EXPLICIT_ff,
    ACCIDENTAL_EXPLICIT_xs,
    ACCIDENTAL_EXPLICIT_ts,
    ACCIDENTAL_EXPLICIT_tf,
    ACCIDENTAL_EXPLICIT_n,
    ACCIDENTAL_EXPLICIT_nf,
    ACCIDENTAL_EXPLICIT_ns,
    ACCIDENTAL_EXPLICIT_su,
    ACCIDENTAL_EXPLICIT_sd,
    ACCIDENTAL_EXPLICIT_fu,
    ACCIDENTAL_EXPLICIT_fd,
    ACCIDENTAL_EXPLICIT_nu,
    ACCIDENTAL_EXPLICIT_nd,
    ACCIDENTAL_EXPLICIT_1qf,
    ACCIDENTAL_EXPLICIT_3qf,
    ACCIDENTAL_EXPLICIT_1qs,
    ACCIDENTAL_EXPLICIT_3qs,
};
```

**Comment by ahwitz** [comment]
@craigsapp: FWIW, the last few commits in https://github.com/ahwitz/verovio/commits/ahwitz-devel were to help that, but I didn't get the chance to finish it at (or since) the MEC hack day.

**Comment by craigsapp** [comment]
@ahwitz: That is ok.  I hunted down the double sharp/flat bug in the MIDI conversion because it was so irritating to hear the wrong notes.  Wrong accidentals in the notation have not been a problem since I haven't tried playing directly from them.
