### ISSUE TITLE
Chords missing dots in Plain and Easy conversion

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#285]
Example 8.{'G^D^,B6'D}6.3{EGFA}{GDEF}{GDAD}/{BD''C'D}{3.''D5C3'BAGFED}

**Comment by rettinghaus** [comment]
@lpugin my commit fixes this import problem. 
However: 
In the generated MEI all notes within chords carry duration attributes, which isn't good style. Is this intended, or should I open another issue to address this?

**Comment by rettinghaus** [comment]
this may be closed now
