### ISSUE TITLE
pass by reference in importer function ImportString()

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#287]
The definitions of ImportString() in data importers are:

```cpp
    virtual bool ImportString(std::string mei);
    virtual bool ImportString(std::string musicxml);
    virtual bool ImportString(std::string pae);
```

These should instead be passed by const reference rather than by copy:

```cpp
    virtual bool ImportString(const std::string& mei);
    virtual bool ImportString(const std::string& musicxml);
    virtual bool ImportString(const std::string& pae);
```

**Comment by lpugin** [comment]
Yes, you are right

**Comment by craigsapp** [comment]
An interesting possibility is to allow passing a non-const string for `ImportString()`.  Pugixml allows for three ways of loading data: (1) immutable (pugixml will not mess with the original string, and instead it allocates extra memory for the text used in the nodes), (2) a mutable string managed externally to pugixml, which it will destructively use for data storage, and (3) a mutable string managed internally to pugixml:

http://pugixml.org/docs/quickstart.html

> There are different functions for loading document from memory; they treat the passed buffer as either an immutable one (load_buffer), a mutable buffer which is owned by the caller (load_buffer_inplace), or a mutable buffer which ownership belongs to pugixml (load_buffer_inplace_own). There is also a simple helper function, xml_document::load, for cases when you want to load the XML document from null-terminated character string.

The mutable options would allow for avoiding an extra temporary copy of the XML string in memory while pugixml copies it.  This would be useful for very large files, and allow the memory requirements in emscripten to be approximately halved for a given MEI file size.  There also might be some speed advantage as well.

**Comment by lpugin** [comment]
Since it has to be a non const buffer I am not sure we can avoid a copy step if we have a std::string in the toolkit object. Or maybe only when we load from a file directly? But this would not change anything in the JS toolkit. Am I overlooking something?

**Comment by craigsapp** [comment]
I would have to research more carefully how the mutable import could work.  The problem is that the string class manages memory on its own.  For example when it needs to grow, it will reallocate new storage space, copy the old contents to the new larger location and delete the old location behind the scenes.  In theory as long as the string is not appended to, the storage will remain where it is (this is a requirement on the mutable imports of pugixml).  I have tried in the past to use a const char* from `String::str()`, but I will get junk on certain operating systems and it will be fine on others (I had to fix a bug related to that a few weeks ago).  So at the moment, I would only use plain char* to manage the input contents if doing a mutable import.

Also to store data in a character array, you will have to know the size of the storage in which to store it.  But if you don't know the size beforehand, you can only guess as to what the size should be, and possibly need to overestimate.  Reading from a file is not a problem, as you can ask the operating system what the size of the file is.  But in JavaScript it would be more difficult.

JavaScript has static memory management capabilities, although I have never used it before.  This would probably end up how using the mutable pugixml import would work: you store the MEI data in a static location in heap memory within JavaScript, then pass the memory pointer to vervio toolkit which would then use it for text storage when parsing the file.  This could potentially greatly minimize the need of memory pre-allocation for the toolkit's use, as the main requirement for memory would be stored outside the toolkit.

http://www.html5rocks.com/en/tutorials/speed/static-mem-pools

**Comment by lpugin** [comment]
I have changed it to a string passed by reference. This will already reduce the memory  alloc by roughly a third (2 times instead of 3 times in memory). We can then see if we want to do more optimization. The amount of memory that has to be pre-allocate by the toolkit will remain difficult to predict anyway.
