### ISSUE TITLE
Mensural-mei isn't rendered in Verovio anymore

### ISSUE THREAD

**Issue by martha-thomae** [rism-ch/verovio#291]
I have some mensural-mei files that I rendered a few weeks ago in Verovio, and it actually displayed all of them. Now, with the new version, I can't visualize any of them; the Verovio webpage is blank when I try to render them.

Here I am attaching two example files: [MensuralMEI.zip](https://github.com/rism-ch/verovio/files/473253/MensuralMEI.zip)

**Comment by craigsapp** [comment]
When I try to convert them into notation on the command-line, I see the message:

```
[Warning] Unsupported '<staff>' within <section>
```

And an empty SVG is generated:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="visible">
	<svg id="definition-scale" viewBox="0 0 21000 29700">
		<g class="page-margin" transform="translate(500, 500)" style="stroke: #000; stroke-opacity: 1.0; fill: #000; fill-opacity: 1.0">
			<g class="system" id="system-000000029896430">
				<g class="section boundaryStart" id="m-40" />
				<g class="boundaryEnd m-40" id="bdend000000056322215" />
			</g>
		</g>
	</svg>
</svg>
```

Perhaps a problem where staff is directly a child of section, and perhaps the new code is expecting a measure element between them.

![screen shot 2016-09-14 at 9 14 01 pm](https://cloud.githubusercontent.com/assets/3487289/18526288/49cbc14c-7ac0-11e6-9012-5f7fcbfbba3d.png)

**Comment by lpugin** [comment]
I noticed this. I am fixing it.

**Comment by lpugin** [comment]
It should be ok now

**Comment by craigsapp** [comment]
Note that the change is in the develop branch rather than the master.

I get these warnings when compiling the file into notation:

```
[Warning] No @n on <staff> might yield unpredictable results
[Warning] No @n on <layer> might yield unpredictable results
[Warning] No @n on <staff> might yield unpredictable results
[Warning] No @n on <layer> might yield unpredictable results
[Warning] No @n on <staff> might yield unpredictable results
[Warning] No @n on <layer> might yield unpredictable results
[Message] triplum
[Message] motetus
[Message] tenor
[Message] triplum
[Message] motetus
[Message] tenor
[Message] triplum
[Message] motetus
[Message] tenor
[Warning] Justification stop because of a ratio smaller than 0.8
Output written to bona_output.svg.
```

And the graphical rendering (at least for me with the command-line version not giving any options):

![screen shot 2016-09-14 at 9 45 52 pm](https://cloud.githubusercontent.com/assets/3487289/18527339/a93864c4-7ac4-11e6-975e-4976bd0a70c0.png)

**Comment by lpugin** [comment]
> Note that the change is in the develop branch rather than the master.

This was intended. 0.9.12 will remain broken for mensural...

> [Warning] No @n on <staff> might yield unpredictable results

Indeed safer to have ```@n``` on staves. But I think it still works.

> [Message] triplum

A debug message left somewhere.

> And the graphical rendering

Cast-off is not implemented with un-measured music. You should use --no-layout

**Comment by martha-thomae** [comment]
Thank you @lpugin for fixing it. It works now, it does display the mensural-mei file.

@craigsapp thanks for the feedback. You are totally right, the lack of @n on the <staff> elements is messing up some of my files, to be specific, it is rendering incorrectly the mensural-mei files that have different mensurations for the different voices (like the one I sent you: "bona_output.mei"); and in all the files it isn't applying the right 'label' value (triplum, motetus or tenor) to the staves. In the previous version of Verovio the presence/absence of the @n on the staves didn't make a difference; but I totally agree that @n should be included in the <staff> elements and I will edit my files in order to include it.

Here I am sending you again the "bona_output.mei" file that I sent the last time and that looks just like @craigsapp showed; and also "bona_output2.mei", in which I actually included the @n attribute for all the staves (and layers), and now the piece do line-up and has all its labels correctly assigned, it looks like this:
![screen shot 2016-09-14 at 5 50 52 pm](https://cloud.githubusercontent.com/assets/13948831/18531366/fe6a00f4-7aa3-11e6-9ea5-9759c37346cb.png)
[MensuralMei_bona.zip](https://github.com/rism-ch/verovio/files/473529/MensuralMei_bona.zip)

Again, thank you both.

**Comment by pe-ro** [comment]
This issue raises the question, Should `@n` or `@def` be required on `<staff>` (via Schematron)?

**Comment by lpugin** [comment]
I would say yes (at least for ```@n``` since it is required on ```staffDef```)

**Comment by pe-ro** [comment]
I think we'd have to require **one** of either `@n` or `@def`.
