### ISSUE TITLE
Compilation fails due to missing "humlib.h"

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#293]
Python compilation fails under Linux and Windows with the following msg:

```
[...]
In file included from ../src/iohumdrum.cpp:20:0:
../include/vrv/iohumdrum.h:24:20: fatal error: humlib.h: No such file or directory
```

**Comment by craigsapp** [comment]
I fixed it by adding the humlib files to the python setup script: https://github.com/rism-ch/verovio/commit/fa91f1a6392edd29fbabbb70a125333798ebcc4b

This is on the `develop` branch (I'll let @lpugin put it on the master).

**Comment by sonovice** [comment]
Thanks for the quick fix!

**Comment by rettinghaus** [comment]
@craigsapp could you fix the "implicit conversion" warning in humlib.cpp (lines 1837 and 5585)?
