### ISSUE TITLE
building JavaScript toolkit fails

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#295]
On trying to build the js toolkit (master branch) I get the error 
> ../src/floatingelement.cpp: No such file or directory ("../src/floatingelement.cpp" was expected to be an input file, based on the commandline arguments provided)

**Comment by lpugin** [comment]
I can see the the ./emscripten/build.sh script was not removed. There is now a new script ./emscripten/buildToolkit which is the one to use.

**Comment by rettinghaus** [comment]
Yeah, this works. 
Please update the wiki!
