### ISSUE TITLE
Support for MEI files with only a music element

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#297]
Verovio ignores MEI files that contain only music (i.e. no `<mei>` but `<music>`).

**Comment by lpugin** [comment]
Are they valid MEI files?

**Comment by sonovice** [comment]
Should be valid, as long as the namespace is correctly included:
`<music xmlns="http://www.music-encoding.org/ns/mei">`

**Comment by rettinghaus** [comment]
I tried it with the Doc_starts_with_music.mei from the sample collection and ideed, there were validation errors. I fixed them but still no rendering.

**Comment by lpugin** [comment]
Correct, they are valid. I was not aware of this options

**Comment by lpugin** [comment]
Added 20305a2b08bd92480af95b182ce26513724929c7
Outputting MEI will still produce a file with an `mei` root.
