### ISSUE TITLE
build resource directory

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#302]
There is a lot of clutter from various building environments in the root directory of the verovio source code.  It would be nice to place them all in a subdirectory.  Perhaps call the subdirectory `builds` or `environments` or something similar.

Files/directories that should go into that subdirectory:

```
Verovio.xcodeproj
appveyor.yml
emscripten
java
python
```

`tools` should in theory go there too, but it seems to be privileged as it contains the cmake makefile.

The build script for enscripten would probably have to be adjusted if moved into a subdirectory; likewise for `python`, etc.

**Comment by lpugin** [comment]
Why not. Maybe this should go first in a develop-dir branch?

**Comment by craigsapp** [comment]
That is good.  I'll adjust the emscripten build script.

Perhaps `fonts` and `data` should go into a `resources` subdirectory (you should think about that at the same time instead of later). Cmakefile would also have to be adjusted in that case for the `make install` action.

Another thing to think about is the images directory, which is bloating the source-code repository.  Ideally this could go in the gh-pages branch, and the `README.md` file would use a URL to the website to get the example images (there is a way of including an image link in the README file which I have done before and will figure out how to do again if that is an interesting adjustment to the repository).

**Comment by ahankinson** [comment]
I suspect appveyor.yml (and .travis.yml) need to be in the root directory for the GitHub trigger system to work on them.

**Comment by craigsapp** [comment]
That does seem to be so:

> To store versioned project configuration along with your sources download appveyor.yml and commit it to the root of your code repository.

![screen shot 2016-09-22 at 12 58 53 pm](https://cloud.githubusercontent.com/assets/3487289/18763989/7129a204-80c4-11e6-85b0-d9ac21eb8b44.png)

**Comment by craigsapp** [comment]
Although I also find that you can specify the location in Settings &rarr; General under "Custom Configuration `.yml` file name:

![screen shot 2016-09-22 at 1 04 31 pm](https://cloud.githubusercontent.com/assets/3487289/18764222/4abe46d2-80c5-11e6-8a39-cad0163ad3e4.png)


http://help.appveyor.com/discussions/problems/2463-can-a-custom-configuration-yml-file-name-exist-in-a-sub-directory

**Comment by lpugin** [comment]
I removed the images directory. For now I think it is not too bad with ten directories. If we change this we will need to change all the web-pages with build instructions, etc.

**Comment by craigsapp** [comment]
There is now a directory called `bindings` which contains `java`, `python`, and `qt`.  Should `emscripten` go in there as well?  And what about `appveyor.yml` and `Verovio.xcodeproj`?  Or do those get to be privileged to stay in the root directory?
