### ISSUE TITLE
strip command-line executable

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#305]
By default, the compiling process leaves debugging information in the executable program.  It would be useful to remove this by default when compiling verovio for the command line, or make it easier to remove for users who don't know that.

For example, verovio compiles to 3.7 MB in OS X, and after removing the extra information from the executable with strip:

```bash
    strip verovio
```

The size of the file is reduced to 2.3 MB.  The smaller size file will in theory be faster to load and take up less space in memory.  In Fedora Linux the unstripped executable size is a mind-numbing 26.5 MB, and the stripped version is 2.5 MB.  Emscripting does not require stripping.

Adding  the `-s` option to the GNU compiler is equivalent to the `strip` stand-alone command.

Info about strip:
    https://en.wikipedia.org/wiki/Strip_(Unix)

**Comment by lpugin** [comment]
@craigsapp what do you want to do with this? Can you look at it?

**Comment by craigsapp** [comment]
In other words, you want me to add it to the makefile and submit as a patch?

For general users, it would be best to strip debugging information when compiling the command-line version of verovio.  I occasionally need it for debugging, but not very often, so I would have to figure out how to prevent stripping.

Alternatively in the instructions for compiling the command-line program, we could add a note that you should strip the compiled program if you are not going to debug and/or the "make install" process could strip it when it copies it to /usr/local/bin (this is perhaps the best thing to do).

**Comment by lpugin** [comment]
I think you are the only general user...

I looked and apparently you can do `make install/strip` and it does the job. It works for me so I updated the wiki

**Comment by craigsapp** [comment]
`make install/strip` worked for me.

**Comment by lpugin** [comment]
great!
