### ISSUE TITLE
<harm> ID

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#319]
Is it possible to add an ID to each <harm> tag? This makes it possible to dynamically transpose etc them. Very convenient fo when you want to make the chords also usable when accompanying transposing instruments.

**Comment by lpugin** [comment]
This is quite likely a SibMEI issue.

**Comment by sannedubois** [comment]
Sorry, you are - ofcourse - completely right. I'll ask Andrew about it.

Kind regards,
Derk

2016-09-29 21:14 GMT+02:00 Laurent Pugin <notifications@github.com>:
