### ISSUE TITLE
Need to allow plainchant/early mensural clefs

### ISSUE THREAD

**Issue by donbyrd** [rism-ch/verovio#326]
The only mensural clefs among the SMuFL characters Verovio knows about are the so-called "Petrucci" clefs, but for a lot of mensural notation, the "plainchant" clefs -- at least C clef = U+E906, F clef = U+E902 -- are much better.

**Comment by lpugin** [comment]
Added

**Comment by donbyrd** [comment]
Thanks very much, Laurent -- but did you change this in the develop-mensural branch? SourceTree isn't showing anything to pull.

**Comment by donbyrd** [comment]
Looking at the GitHub repository directly, I see you added these clefs in _develop_ (commit 780b99d) but not _develop-mensural_. I might be able to figure out how to make the same changes in _develop-mensural_, but I'd be much more comfortable if you did it!

**Comment by lpugin** [comment]
I merged it to develop-mensural
