### ISSUE TITLE
SVG Tiny support

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#332]
Verovio outputs SVG 1.1. Many frameworks (for example Qt & Android) only support SVG Tiny. It would be great to have the option to output SVG Tiny files in Verovio.

**Comment by lpugin** [comment]
What is used in Verovio that is missing in Tiny SVG?

**Comment by rettinghaus** [comment]
As far I see it Verovio basically generates SVG Tiny already. The root just should carry an additional `baseProfile="tiny"`.
See: 
https://www.w3.org/TR/SVGTiny12/

**Comment by sonovice** [comment]
> What is used in Verovio that is missing in Tiny SVG?

`<symbol>` and `<tspan>` are not valid elements. `<g>` elements have no attribute `class`. These are the most severe ones, I guess.

To get a more complete overview, just try validating a Verovio SVG file with the [W3C Markup Validator](https://validator.w3.org/) and choose "SVG 1.1 Tiny" as Doctype.

**Comment by rettinghaus** [comment]
Try SVG Tiny 1.2. Here `@class` *is* a common attribute.

https://www.w3.org/TR/SVGMobile12/struct.html#Core.attrib

**Comment by lpugin** [comment]
If `tspan` and `symbol` are missing then it is going to be quite difficult. `symbol` is used to include the SMuFL font. There is certainly other ways to include a font with Tiny SVG but this is going to yield other issues. Including an external font used to be the solution inf Verovio a while ago but this used to be create many cross-browser problems. I am closing the issue. We can re-open it if you work on it and find a possible solution.

**Comment by sonovice** [comment]
Okay, here is a (very quick'n'dirty) python script that allows me to load Verovio output into Qt:

```python
from lxml import etree
from copy import copy

svg_xml = etree.parse('score.svg')

# get all <use> elements and their defined height and weight combinations
uses = set()
for elem in svg_xml.xpath('//*[local-name()="use"]'):
    old_href = elem.get('{http://www.w3.org/1999/xlink}href').split('#')[-1]
    new_href = old_href + '-' + str(elem.get('height')) + '-' + str(elem.get('width'))
    elem.set('{http://www.w3.org/1999/xlink}href', '#' + new_href)  # set href to new link
    del elem.attrib['height']  # attribute is obsolete
    del elem.attrib['width']   # attribute is obsolete
    uses.add(new_href)

# generate new definitions for all combinations
new_defs = etree.Element('defs')
for elem in svg_xml.xpath('//*[local-name()="symbol"]'):
    identifier = elem.get('id')
    viewbox = elem.get('viewBox')
    width = int(viewbox.split(' ')[2])
    height = int(viewbox.split(' ')[3])

    for symbol in [e for e in uses if identifier in e]:
        g = copy(elem[0])
        new_width = int(symbol.split('-')[1].split('px')[0])
        new_height = int(symbol.split('-')[2].split('px')[0])
        g.set('id', symbol)
        g.set('transform', 'scale(' + str(new_width / width) + ', ' + str(-new_height / height) + ')')
        new_defs.append(g)

# transform SVG
root = svg_xml.getroot()
del root[0]                       # delete defs
viewbox = root[0].get('viewBox')  # get viewBox of SVG
root.set('viewBox', viewbox)      # write viewBox to root SVG element
g = root[0][0]                    # temporarily save SVG content
del root[0]                       # ... and delete it
root.insert(0, new_defs)          # write new defs
root.insert(1, g)                 # insert back SVG content to correct position

with open('score.svg', 'wb') as f:
    svg_xml.write(f)

```

It basically changes 2 things:
### Calculate `<g>` elements for all `<symbol>` elements.
The various used `width` and `height` attributes are considered individually.
For example:
```xml
<symbol id="E0A4" viewBox="0 0 1000 1000" overflow="inherit">
	<g transform="scale(1,-1)">
		<path d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
	</g>
</symbol>
```
gets transformed to 2 elements: regular notes (720px) and grace notes (514px):
```xml
<g transform="scale(0.514, -0.514)" id="E0A4-514px-514px">
    <path d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z"/>
</g>
<g transform="scale(0.72, -0.72)" id="E0A4-720px-720px">
    <path d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z"/>
</g>
```

### Change structure of SVG
Regular Verovio SVGs have an additional `<svg>` element after the definitions:
```xml
</defs>
<svg id="definition-scale" viewBox="0 0 326700 4810">
```
Since I could not get the exact purpose, I just moved the `@viewBox` to the root svg element and deleted the second one.

Now at least Qt is happy and loads the SVGs flawlessly. This is just a workaround, but it shows the most important steps on the way to SVG Tiny compatibility. I guess it would be somewhat easier to do this as an XSLT, but I'm not very proficiant with XSL...

**Comment by sonovice** [comment]
Quick update: `<tspan>` is defined in SVG Tiny 1.2 (but not 1.1), so the output of my script should produce valid SVG Tiny 1.2 files.

**Comment by lpugin** [comment]
OK, 1.2 seems possible then. Dropping `tspan` would mean drop editorial markup for all textual elements, I think.

**Comment by lpugin** [comment]
Even simpler than an XSLT would quite likely to make it an option and redefine the DrawMusicText accordingly
https://github.com/rism-ch/verovio/blob/master/src/svgdevicecontext.cpp#L599-#L637
I can provide you with more information if you are willing to do it there.

**Comment by sonovice** [comment]
Right now I simply don't have the time to implement this on my one. I will use my own script for now, but will look into this when I find some free time.
