### ISSUE TITLE
Wrap staff label in g

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#335]
All `<staffDef>` (`<staffGrp>`) atrributes which can be represented as elements (e.g. key and meter signatures) get modeled as their respective elements in SVG (i.e. `<g class="meterSig">` etc.). 
Same should be done with the staff label (`@label`) for common sense and better reachability through CSS. 

(Keeping in mind that Bootstrap uses a label class too, gh-pages will have to be adjusted as it would get printed bold.)

**Comment by lpugin** [comment]
I am not so sure about this. I was actually thinking of doing the reverse. That is removing `g` for `staffDef` attributes.

**Comment by rettinghaus** [comment]
So will there be no support for the child elements of `staffDef` or would that help differentiate (MEI) attributes and elements in the SVG?

**Comment by lpugin** [comment]
There will be support for `staffDef` child elements and `g` only for them. This would indeed help to differentiate attributes and elements in the SVG.

**Comment by kepper** [comment]
> Am 12.10.2016 um 08:01 schrieb Laurent Pugin <notifications@github.com>:
> 
> But maybe we can think of another way to differentiate them. For example by adding an extra class. Something like
> 
> <g class="stattDef">
>     <g class="clef attr"/>
> </g>
> 
> Or class="attr-clef"? Or `class="@clef" ? Any opinion on this?

definitely the first option (two separate classes). Not sure if an @-sign is allowed at all, and if you combine both into one single class name, you're forced to look for both even when you really don't care about whether it's an attribute or not…

**Comment by lpugin** [comment]
`@` is allowed but probably not a good idea. I agree that two classes is probably the best because you can get them all in one go.
