### ISSUE TITLE
fixing beginning of the first staff when zooming

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#338]
Wouldn't it be a nice feature to have the left side of the upper line of the first staff stay at the same position when zooming in/out by default?

**Comment by lpugin** [comment]
I don't think this will work because at high zoom levels then notes or symbols above the staff will be truncated or hidden.

**Comment by lpugin** [comment]
Also, I think this is a Verovio use issue and not directly a Verovio issue

**Comment by sannedubois** [comment]
Hello Laurent,

O.K. You are completely right.

Thanks,
Derk

2016-10-24 12:10 GMT+02:00 Laurent Pugin <notifications@github.com>:
