### ISSUE TITLE
Enable secure connections on www.verovio.org

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#353]
Otherwise secured websites can't rely on the latest versions there, but have to keep a local copy up to date.

**Comment by lpugin** [comment]
Unfortunately it seems that it is not possible.
https://help.github.com/articles/securing-your-github-pages-site-with-https/

> HTTPS is not supported for GitHub Pages using custom domains

**Comment by crantila** [comment]
Now it is!
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
