### ISSUE TITLE
Command line option to place output in different directory from input data

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#355]
When converting files with the command-line interface to verovio, the output data is saved to the same directory as the input data.  This can be changed by specifying the output file with the `-o` option, but it would be convenient to have an option to specify the directory to save the output to that is independent of `-o`.  For example `-d .` or `--output-directory .` to save the output in the current directory, with the same filename base (direcotory/file.mei output would be saved to ./file.svg).

The current way of doing this:
 
```bash
verovio directory1/file.mei -o directory2/file
```

or more generalized:

```bash
FILE = directory1/file.mei
verovio $FILE -o directory2/`basename $FILE .mei`
```

The new option would look like this:

```bash
verovio directory1/file.mei -d directory2
```

with the generalized version being equivalent.

**Comment by lpugin** [comment]
If you need this do add it, it can be useful.

**Comment by craigsapp** [comment]
OK, I will add it.

**Comment by rettinghaus** [comment]
Lilypond uses one command for both: if you give it a directory it puts all
output files there. Seems to me more logical.

**Comment by craigsapp** [comment]
So like this?:

```bash
verovio directory1/file.mei -o directory2
```

That will be more concise.  If the output is a directory, then remove the old directory from the input file, and replace it with the output directory name to build the output filename base.

I'll implement it that way.

**Comment by lpugin** [comment]
Detecting if it is a directory or a file can be tricky to have in a robust and cross platform manner. I would suggest to add a long option --directory for this. But if you are willing to do it the way you mentioned above, I am fine as long as it is tested on OS X, Linux and Windows ;-)

**Comment by craigsapp** [comment]
Would anyone using Windows use the command-line version of the tool :-).  I'll check how to do directory manipulation in Windows.  OS X and Linux will both be the same.

**Comment by rettinghaus** [comment]
@craigsapp any progress with this?

**Comment by lpugin** [comment]
@rettinghaus are you interested to have this? Otherwise we can forget it for me.

**Comment by rettinghaus** [comment]
I think it would be a valuable feature. Although for most use cases it is probably not needed. 
Anyway, as @craigsapp volunteered to implement this (and as long it is not too difficult to get running) I'd like to see it.

**Comment by rettinghaus** [comment]
Reminder for @craigsapp
