### ISSUE TITLE
Find single staff for @tstamp

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#363]
When using `@tstamp` in a control element Verovio complains about missing `@staff` even if there is only a single staff. In such cases to me it seems obvious where it was meant to be drawn (as `@staff` *is* an optional attribute).

**Comment by lpugin** [comment]
Yes, this makes sense.

**Comment by lpugin** [comment]
Changed here f112cb8ccffcd55fd1a19490dbb147d9cad90807
This will work only if `@n` in staffDef == 1
