### ISSUE TITLE
using SMuFL engravingDefaults

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#368]
When we use SMuFL code points/names for glyphs, shouldn't we also follow the naming of the engravingDefaults?
https://w3c.github.io/smufl/gitbook/specification/engravingdefaults.html

**Comment by rettinghaus** [comment]
I meant that as naming convention for the variables in `style.h`

**Comment by lpugin** [comment]
Yes, this is a good idea for when we refactor the Style class

**Comment by pe-ro** [comment]
Should this find its way into MEI attributes, say in `att.scoreDef.vis`, `att.staffDef.vis`, etc.?  If so, should actual default values be provided or should we continue leaving this to software?  Are there additional, similar features found in other software, such as MuseScore, that it would be prudent to accommodate?

**Comment by lpugin** [comment]
I don't think we should have default values in MEI for this

**Comment by pe-ro** [comment]
Ok, no default values then.  But, seeing as how there are several "style" attributes already in MEI, should we add more?  One argument for it is that encodings could be more visually/stylistically specified.  Another is that since we've already started down that road, we should continue.
