### ISSUE TITLE
Visual Studio Project

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#373]
It would be great if there was a Visual Studio project to be able to compile it on Windows, or at least some instructions to set it up.

I found this thread #323 where there was a discussion about Visual Studio.

//K

**Comment by cambiata** [comment]
+1

**Comment by lpugin** [comment]
I think this is being used, but I am not sure what the exact procedure is. @sonovice ?
https://github.com/rism-ch/verovio/issues/296#issuecomment-248791448

**Comment by sonovice** [comment]
Generating a Visual Studio Project is pretty straightforward:

1. Install [cmake](https://cmake.org/)
2. Go into the `tools` folder of Verovio
3. Execute `cmake -DNO_PAE_SUPPORT=ON .` (add `-DCMAKE_GENERATOR_PLATFORM=x64` for a x64 solution)
4. Use the resulting `Verovio.sln` with Visual Studio

**Comment by lpugin** [comment]
Thanks, I added it.

**Comment by craigsapp** [comment]
@sonovice, @k-ljung, @cambiata: Do you use the command-line version of verovio?  This is related to adding a directory option for issue #355.  @sonovice uses the python interface, so that accesses verovio through the C++ library rather than the command-line interface I am presuming.

**Comment by k-ljung** [comment]
I executed `cmake . -DNO_PAE_SUPPORT=ON` opened the solution file in Visual Studio but run into problem. Visual Studio complained about missing the file `#include <getopt.h>`, i found this solution https://github.com/skandhurkat/Getopt-for-Visual-Studio but then get lots of errors when compiling the project in Visual Studio.

My goal is to compile a dll file I can reference from any .NET C#  project.

**Comment by craigsapp** [comment]
You might need to use the develop branch of verovio.  There is a newly added file related to this problem:

https://github.com/rism-ch/verovio/blob/develop/include/win32/win_getopt.h

The master branch does not yet have these updates for Visual Studio compiling of verovio:

https://github.com/rism-ch/verovio/blob/master/include/win32/win_getopt.h

**Comment by k-ljung** [comment]
I'm using the develop branch and can now compile the project, I needed to add `#include <ciso646>` in the `iomusxml.cpp` to be able to compile the project.

When I run the application I get the following error message and then it crashes.
![capture](https://cloud.githubusercontent.com/assets/9248053/20862368/ad0368ce-b9a8-11e6-9559-ff572c6be79e.PNG)

**Comment by rettinghaus** [comment]
Did you run it with a specific file?

**Comment by k-ljung** [comment]
@rettinghaus yes, I did try two different files, one of them was this Beethoven_StringQuartet_Op18_No2.mei used in this example http://www.verovio.org/tutorial.xhtml?id=topic00

**Comment by lpugin** [comment]
What version of Visual Studio are you using?

**Comment by k-ljung** [comment]
I'm using Visual Studio 2015

**Comment by lpugin** [comment]
I pushed a change in Object::ClearRelinquishedChildren to the develop branch. Does it fix it?

**Comment by k-ljung** [comment]
I think I came a step forward, but now I get errors in the method: Object::GetListFirstBackward

Expression: list iterator not decrementable

**Comment by lpugin** [comment]
What line?

**Comment by k-ljung** [comment]
@lpugin std::advance(it, GetListIndex(startFrom));

**Comment by lpugin** [comment]
OK. In the meantime I tested it and it runs if you build it as Release (and not Debug) because the assert where it stops have no effect in Release mode. I'll have a closer look, though

**Comment by lpugin** [comment]
It should be fixed now. Keep me posted

**Comment by k-ljung** [comment]
Yes, the Release mode works.
However, I get lots of warnings, this applies to both the Debug and Release mode.

```
C:\_Projects\verovio\tools\Release>verovio -f mei -o output.svg Hummel_Concerto_for_trumpet.mei
[Warning] Unsupported '<pgHead>' within <scoreDef>
[Warning] Unsupported '<pgFoot>' within <scoreDef>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<staffDef>' within <section>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<trill>' within <measure>
[Warning] Unsupported '<reh>' within <measure>
[Warning] Justification stop because of a ratio smaller than 0.8
Output written to output.svg.
```

**Comment by ahankinson** [comment]
Those are normal. It's just warning that there's an unsupported notation figure in the encoding.

**Comment by bobra** [comment]
There are some code wich doesnt follow standart
an array was initialising with non constant value, 
either `const int temp argc` or `char** tempargv = new char* [tempargc + 1]; delete[] tempargv;` should be used here
`
//tools-musicxml2hum.cpp

void Tool_musicxml2hum::setOptions(const vector<string>& argvlist) {
	int tempargc = (int)argvlist.size();
	char** tempargv = new char* [tempargc + 1]; 
        // before was char* tempargv[tempargc + 1];
	tempargv[tempargc] = NULL;

	int i;
	for (i=0; i<tempargc; i++) {
		tempargv[i] = new char[argvlist[i].size() + 1];
		strcpy(tempargv[i], argvlist[i].c_str());
	}

	setOptions(tempargc, tempargv);

	for (i=0; i<tempargc; i++) {
		if (tempargv[i] != NULL) {
			delete [] tempargv[i];
		}
	}
	delete[] tempargv; // this line should be added too
}
`

othervise it will not even build on Visual studio

**Comment by craigsapp** [comment]
Fixed in commit https://github.com/rism-ch/verovio/commit/60b005666ba6aab13285f3f32d256bdbb8c9b946

However it should probably be merged from `develop-humdrum` into `develop`.

The function was simplified to:

```cpp 
void Tool_musicxml2hum::setOptions(const vector<string>& argvlist) {
     m_options.process(argvlist);
}
```

I didn't need to unpack the the string array into a c-string array, since there was a `vector<string>` version of the process function.
