### ISSUE TITLE
Error Message Guidelines

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#377]
I noticed that warnings and errors are not very consistent. On some you'll get very detailed information where the problem is, on others you're only noticed that something may not work. So my question: shouldn't we have some *Error Message Guidelines*?

**Comment by lpugin** [comment]
Yes, this can be useful. Any proposal welcome

**Comment by pe-ro** [comment]
You might want to look at https://msdn.microsoft.com/en-us/library/windows/desktop/ms679325(v=vs.85).aspx or https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowAlerts.html#//apple_ref/doc/uid/20000957-CH44-SW1 for models.

**Comment by lpugin** [comment]
To be solved together with #180
