### ISSUE TITLE
Barline padding too small

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#38]
Spacing of notes after a barline is too small.  The the padding to the right of a barline should be one "line-space" or two MEI "virtual units".  Currently the padding is 0.5 linespaces or 1 VU.  Perhaps confusion between those units is the cause of the problem?  In any case, the 0.5 line-space/1 VU padding does not look good and is non-standard.  See pp. 42-43 of Beyond Bars for more details and exceptions.  Here is an illustration showing the problem and the desired solution:

![screen shot 2014-11-12 at 3 59 03 pm](https://cloud.githubusercontent.com/assets/3487289/5021139/fe7401ec-6a85-11e4-988b-2b7841776451.png)

**Comment by lpugin** [comment]
Fixed
