### ISSUE TITLE
Sudden endings of unfinished bars

### ISSUE THREAD

**Issue by vonvlaho** [rism-ch/verovio#381]
Is it possible to influence the space following the last note of an unfinished bar? In our case of PAE-Incipits the endings of the lines seem to be very sudden sometimes. I would be very thankful for any recommendation for getting a smoother alignment in these cases. Thanks a lot for your help!

![screenshotincipits](https://cloud.githubusercontent.com/assets/23097270/21005227/3c76c1a2-bd34-11e6-8ceb-4f78c97fe6f1.jpg)

Options we use:

```javascript
var options = JSON.stringify({
                inputFormat: 'pae',
                pageHeight: 500,
                pageWidth: 2000,
                ignoreLayout: 1,
                border: 0,
                scale: 40,
                adjustPageHeight: 1
            })
```

[Some example](http://www.gluck-gesamtausgabe.de/gwv/werkregister/eintrag/antigono.html) (navigate to "Werkteile" on the right)

**Comment by lpugin** [comment]
This should have been fixed in the develop branch. See here how to use it http://www.verovio.org/download.xhtml
