### ISSUE TITLE
percussion parts

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#385]
Can verovio render percussion parts?

For example, notes can be made stemless to represent parts with pitches but without rhythm, but I also want to display notes  with rhythms but without pitches:

<img width="856" alt="screen shot 2016-12-16 at 22 34 14" src="https://cloud.githubusercontent.com/assets/3487289/21284947/cabb7c62-c3df-11e6-954f-814129387213.png">

**Comment by lpugin** [comment]
@pe-ro? How would you encode them?

**Comment by kepper** [comment]
`<staffDef lines="1"/>`, and then each note could have a `@loc` instead of `@pname`. However, since this is always the same value, one could argue that it's not necessary in the case of one staff line…

**Comment by pe-ro** [comment]
Percussion notation, even on one line, is a little more complex than @kepper suggests. With a single line, there are 3 positions that a "note" can occupy -- above the line, "on" the line, and below the line.  A single-line staff therefore can have the `@ontheline` attribute: "A value of 'true' places all notes on the line, while a value of 'false' places stems-up notes above the line and stems-down notes below the line."

In any case, as Jo points out, `@loc` and such aren't necessary for a single-line staff. The following should all end up "on" the line when `@ontheline` is either "true" or absent --
```
<note dur="2"/>
<note dur="4"/
<note dur="8"/>
<note dur="8"/>
```
The addition of stem directions (still with `@ontheline` "true" or absent) --
```
<note dur="2" stem.dir="down"/>
<note dur="4" stem.dir="down"/>
<note dur="8" stem.dir="up"/>
<note dur="8"stem.dir="up"/>
```
should result in the notes all still on the line, but with stems pointing in the specified direction.

When `@ontheline` is "false", then the example above should result in the first 2 notes rendered below the line (with stems down) and the last 2 above the line (with stems up).

**Comment by rettinghaus** [comment]
With `@loc` support on `<note>` now I think this is fixed.

**Comment by lpugin** [comment]
Indeed. Thanks
