### ISSUE TITLE
Standard input

### ISSUE THREAD

**Issue by ghost** [rism-ch/verovio#39]
The command-line version of verovio should (must) accept standard input and be able to write to standard output.  This is necessary in order to avoid the need for temporary files.

This could be done in several ways.  Here is an example possibility for standard input/output processing, using the most common convention for standard input/output behavior:
     `cat file.xml | verovio -f mei | less`

Currently output is tied to the input filename, so the -o option could take "-" as a filename, which is a usual convention for standard output:
     `cat file.xml | verovio -f mei -o - | less`
or equivalently:
     `cat file.xml | verovio -f mei -o- | less`

It is possible to use a similar convention for indicating standard input if you do not want to allow zero arguments:
     `cat file.xml | verovio -f mei -o -  - | less`
The second dash is the filename "-" which would indicate that standard input is being expected.

The last example is similar to processing with ps2pdf (manpage: http://man.he.net/man1/ps2pdf).

```
     ps2pdf file.ps
     ps2pdf file.ps file2.pdf
     cat file3.ps | ps2pdf - - > file4.pdf
```

The first example is similar to verovio, and the output will automatically be called file.pdf.  The second example is similar to "-o file2.svg" option of verovio.  The last example would be similar to the proposed "verovio -f mei -o- -" for standard input and output.

<hr noshade>

Standard output should be easy to implement.  Standard input can be implemented by adding Toolkit::LoadFile(std::istream &in) or Toolkit::LoadFile(std::ifstream &in).  The Toolkit::LoadFile(std::string &filename) function would open the file, and then call one of the previous LoadFile functions with the opened file stream, so not much extra code would be needed.  The only complication will be how to calculate the byte size of standard input to preallocate the stored string size (I could look up how to do that if you like).

**Comment by craigsapp** [comment]
Standard input/output style selectected:
```bash
    cat file.xml | verovio -f mei -o - - | less
```
works, although a bit more wordy than:
```bash
    cat file.xml | verovio -f mei | less
```
:-)

**Comment by lpugin** [comment]
Not so much more... But I would be happy to integrate a pull request for this ;-)
