### ISSUE TITLE
fprintf to stderr in LogError producing wrong integer formatting

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#392]
vrv::LogError is now redirected to the stderr via fprintf. However, this seems to produce wrong formatting with integers. For example, call from `Resources::InitFonts` produces
```
Expected 1606404576 default SMUFL glyphs but could load only -286459368.
```
Changing to stdout produces the same. However, using printf works correctly

**Comment by craigsapp** [comment]
This code in`vrv.cpp: Resources::InitFonts()` seems to have an integer overflow

```
    if (m_font.size() < SMUFL_COUNT) {
        LogError("Expected %d default SMUFL glyphs but could load only %d.", SMUFL_COUNT, m_font.size());
        return false;
    }
```

Since the size cannot be negative, `%d` should probably be changed to `%lu` (unsigned long rather than int).

**Comment by craigsapp** [comment]
Hmmm, but `SMUFL_COUNT` should be 187 rather than 1606404576:

```
../include/vrv/smufl.h:#define SMUFL_COUNT 187
```

**Comment by lpugin** [comment]
Indeed. I tried casting to int to the issue must be somewhere else

**Comment by craigsapp** [comment]
It could potentially be a mixing of floats and integers.  When I set a floating point value to 187.0, and then pretend the floating point storage is an integer, I get the value 1127940096.   This is not 1606404576, but something like this could be involved.

```cpp
#include <iostream>

union janus {
        std::int32_t i;
        float f;
};

int main(void) {
        janus num;
        num.f = 187;
        std::cout << "VALUE = " << num.i << std::endl;
        return 0;
}
```

**Comment by donbyrd** [comment]
I tried using %ld; that gave me different but equally nonsensical numbers. So printf works but fprintf doesn't!?  Bizarre. Mixing of floats and integers is an interesting theory, but what fprintf-specific code could it be?

**Comment by craigsapp** [comment]
The inputs going into LogError are correct.  The problem is that you have to use `vfprintf` rather than `fprintf` whenever there are variable args.  I ran across the problem a while ago on the Humdrum develop branch:

https://github.com/rism-ch/verovio/blob/develop-humdrum/src/vrv.cpp#L270-L288

```cpp
void LogError(const char *fmt, ...)
{
    if (noLog) return;
#ifdef EMSCRIPTEN
    std::string s;
    va_list args;
    va_start(args, fmt);
    s = "[Error] " + StringFormatVariable(fmt, args) + "\n";
    AppendLogBuffer(true, s, CONSOLE_ERROR);
    va_end(args);
#else
    fprintf(stderr, "[Error] ");
    va_list args;
    va_start(args, fmt);
    vfprintf(stderr, fmt, args);
    fprintf(stderr, "\n");
    va_end(args);
#endif
}
```

Current develop version, which is not using `vfprintf`:

```cpp
void LogError(const char *fmt, ...)
{
    if (noLog) return;
#ifdef EMSCRIPTEN
    std::string s;
    va_list args;
    va_start(args, fmt);
    s = "[Error] " + StringFormatVariable(fmt, args) + "\n";
    AppendLogBuffer(true, s, CONSOLE_ERROR);
    va_end(args);
#else
    va_list args;
    va_start(args, fmt);
    fprintf(stderr, "[Error] ");
    fprintf(stderr, fmt, args);
    fprintf(stderr, "\n");
    va_end(args);
#endif
}
```

Changing to `vfprintf` give the correct values in the error message:
```
[Error] Expected 196 default SMUFL glyphs but could load only 187.
The music font could not be loaded; please check the contents of the resource directory.
```

**Comment by lpugin** [comment]
Fixed in 5a6123dd1922c16b71a926ced5aae82e56cca047 with vfprintf

**Comment by donbyrd** [comment]
Bravo!  :-)  This seemed like such a low-level thing, I was afraid the problem was going to be in a library we couldn't touch. But then Verovio _is_ self-contained, which avoids precisely such situations.

**Comment by donbyrd** [comment]
Please merge this into develop-mensural when you have a chance.
