### ISSUE TITLE
editorial accidentals

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#394]
Is this the correct way to encode editorial accidentals:

<img width="452" alt="screen shot 2016-12-24 at 19 38 30" src="https://cloud.githubusercontent.com/assets/3487289/21469610/aa2d2a4a-ca10-11e6-8c00-fa65bab0d6b0.png">

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
	<meiHead>
		<fileDesc>
			<titleStmt>
				<title />
			</titleStmt>
			<pubStmt>
				<date>2016-12-24 19:32:49</date>
			</pubStmt>
		</fileDesc>
		<encodingDesc>
			<projectDesc>
				<p>Transcoded from Humdrum with Verovio version 0.9.13-dev-ebcf862-dirty</p>
			</projectDesc>
		</encodingDesc>
	</meiHead>
	<music>
		<body>
			<mdiv>
				<score>
					<scoreDef xml:id="scoredef-000000149552179">
						<staffGrp xml:id="m-000000168167451">
							<staffDef xml:id="staffdef-000000087132905" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
						</staffGrp>
					</scoreDef>
					<section xml:id="section-000000120333998">
						<measure xml:id="measure-L3" n="1" right="end">
							<staff xml:id="staff-L3F1" n="1">
								<layer xml:id="layer-L3F1" n="1">
									<note xml:id="note-L4F1" dur="4" oct="4" pname="g" accid.ges="n" />
									<note xml:id="note-L5F1" dur="4" oct="4" pname="f" >
									     <accid accid="s" func="edit" fontsize="small" />
									</note>
									<note xml:id="note-L6F1" dur="2" oct="4" pname="g" accid.ges="n" />
								</layer>
							</staff>
						</measure>
					</section>
				</score>
			</mdiv>
		</body>
	</music>
</mei>
```
I would also like to make the accidental cue-sized, but trying `@fontsize="75%"` does not work.  Is there another way? or is this a feature request ? :-)

Should the `@accid="s"` be removed from the `<note>` element (as I did), since it is now found in `note/accid@accid`?

Where would `@accid.ges` go if it is needed?  In `<note>`  or `<accid>`?

**Comment by pe-ro** [comment]
I'm having second thoughts about `@func` on `<accid>`, at least the "edit" value.  I think the best way to encode editorial accidentals is to used editorial markup.  (What a surprise!)  For example, 
```
<note>
  <supplied><accid accid="s" place="above"/></supplied>
</note>
```
The fact that the accidental is inside `<supplied>` is the only indicator needed for its "editorial-ness".

**Comment by pe-ro** [comment]
>Should the `@accid="s"` be removed from the <note> element (as I did), since it is now found in `note/accid@accid`?

Yes. Right now, `@accid` captures a written accidental.

>Where would `@accid.ges` go if it is needed? In `<note>` or `<accid>`?

It depends. 😀 In this case, I think it should go on `<accid>`.  This binds together the supplied accidental and its performed value. `note/@accid.ges` would indicate the performed value of an accidental written on/for the note.

**Comment by pe-ro** [comment]
> The smaller size could be triggered by presence of `@place="above"` (or `@place="below"`) within `supplied/accid`.

This can be the default behavior, but it should be overridden when `accid/@fontsize` is provided.

> Perhaps `@place="above"` without accid being inside supplied would render a regular-sized accidental above the note.
>
> If `@place` is not given then it would be displayed as a regular accidental, I think.

If `@place` is not given or if `@place` is "within", then a regular-sized accidental should be displayed before the note.

>If `@enclose` is given without `@place`, then it would visually appear as a regular-sized editorial accidental in front of the note, but enclosed in () or []. XSLT processing could easily switch between the two styles of editorial accidentals.

Sounds good to me.

**Comment by lpugin** [comment]
You will get this with `@func="edit"`
![image](https://cloud.githubusercontent.com/assets/689412/24929821/a30d0e5a-1f07-11e7-97c1-7f801ccddd46.png)

**Comment by davidrizo** [comment]
In the page 83 / section "Placing cautionary accidentals" of Behind Bars book by E. Gould, she states:
> ... where horizontal space is limited , to place cautionary accidentals directly above notes....
In the example in the book, she places those cautionary accidentals above the notes, exactly as the example above by @lpugin. 

![image](https://user-images.githubusercontent.com/10772049/80148420-50d60700-85b5-11ea-9832-214a09d2fe59.png)

Then, if the function of the sharp in the example above is not editorial, but cautionary, the encoding should be:
```xml
<note dur="4" oct="4" pname="c">
   <accid accid="s" func="caution" place="above" />
</note>
```
I've tested it in Verovio (actually with an natural instead of a sharp), and it does not paint the accidental above the note.

Other question is that if there can be cautionary accidentals placed above the notes, is it correct to use just the attribute func="edit" in order to place the accidental placed above the note. Should not be better to encode the example as?:

```xml
<note dur="4" oct="4" pname="c">
   <accid accid="s" func="edit" place="above" />
</note>
```

**Comment by craigsapp** [comment]
One thought: Would a cautionary accidental above a note be smaller than a regular accidental?  I can imagine if there were no space for the cautionary accidental, then moving it above would probably make it not shrink, since its intended location is in front of the note, and it is moved only for space considerations.  This would be a convenient way of giving different default visual definition to the two functions. 

Editorial accidentals that come before the note are placed in parentheses or brackets and are large (so they would be visually identical to cautionary accidentals in cases when in front of notes).

**Comment by davidrizo** [comment]
(I think I cannot upload here a scan of the page for copyright reasons) 

The book states this sequence:
1: In the traditional practice is to show cautionary accidentals are placed in brackets (in the example they are parentheses). They are in normal size.
2: It there are too many bracketed accidentals the overall legibility is reduced and then they can be printed without the brackets. Again, they are in normal size.
3: (What I sent about placing it above): If there is the horizontal space is limited, put it above. In this case the examples given print those accidentals smaller.
