### ISSUE TITLE
selecting whole/half notes in UI

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#397]
Not directly a verovio toolkit problem, but perhaps you notice that selecting whole/half notes within the verovio editor is more difficult than a quarter note?  In other words, clicking on the background of an SVG image will not select anything, and whole/half notes contain background in their middles with only an thin ring of selectable content.

One possibility is to add transparent rectangle overlays to the SVG.   It need not be an overlay as long as it is grouped in the <g> content for a note element for example.

A fancy solution would be to somehow define voronoi regions for each notational object:
     http://www.visualcinnamon.com/2015/07/voronoi.html

**Comment by lpugin** [comment]
Yes, I am aware of this. One solution is to change the `pointer-events` attribute to `bounding-box`. 
https://www.w3.org/TR/pointerevents/

See it here
http://www.verovio.org/tutorial.xhtml?id=topic07
https://github.com/rism-ch/verovio-tutorial/blob/gh-pages/topic07-choice.html#L92

However, this does not work with all browser, I think

**Comment by craigsapp** [comment]
Thanks!  I will play around with that.
