### ISSUE TITLE
implement @sameas for <clef> (& keySig/meterSig)

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#401]
libmei contains `@sameas` accessor functions in the `AttCommonAnl`class .  Perhaps add that class as a parent for the Clef class, which is currently:

```cpp
class Clef : 
      public LayerElement, 
      public AttClefshape, 
      public AttLineloc, 
      public AttOctavedisplacement
```

Related to issue #400

**Comment by lpugin** [comment]
Implemented
