### ISSUE TITLE
ending styling

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#404]
Here is an example of `<ending>`:

<img width="953" alt="screen shot 2016-12-29 at 17 04 22" src="https://cloud.githubusercontent.com/assets/3487289/21558055/4a922342-cde9-11e6-8251-02888f448b9b.png">

Is there a way of specifying that the 2nd ending is "open"?:

<img width="953" alt="ending2" src="https://cloud.githubusercontent.com/assets/3487289/21558059/55adef9a-cde9-11e6-98be-9f5f33e44ea2.png">

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt>
        <date>2016-12-29 17:01:31</date>
      </pubStmt>
    </fileDesc>
    <encodingDesc>
      <projectDesc>
        <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-0cd2987</p>
      </projectDesc>
    </encodingDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef xml:id="scoredef-000000199179094">
            <staffGrp xml:id="m-000000211799737">
              <staffDef xml:id="staffdef-000000049291533" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section xml:id="section-000000046675363">
            <measure xml:id="measure-000000093869274" n="1">
              <staff xml:id="staff-000000142499449" n="1">
                <layer xml:id="layer-000000114486292" n="1">
                  <note xml:id="note-L5F1" dur="1" oct="4" pname="c" accid.ges="n"/>
                </layer>
              </staff>
            </measure>
            <ending n="1">
              <measure xml:id="measure-000000059319723" n="2" right="rptend">
                <staff xml:id="staff-000000014163269" n="1">
                  <layer xml:id="layer-000000100879037" n="1">
                    <note xml:id="note-L7F1" dur="1" oct="4" pname="d" accid.ges="n"/>
                  </layer>
                </staff>
              </measure>
            </ending>
            <ending n="2">
              <measure xml:id="measure-000000134779343" n="3">
                <staff xml:id="staff-000000007031406" n="1">
                  <layer xml:id="layer-000000065253502" n="1">
                    <note xml:id="note-L9F1" dur="1" oct="4" pname="e" accid.ges="n"/>
                  </layer>
                </staff>
              </measure>
            </ending>
            <measure xml:id="measure-000000001284941" n="4" right="end">
              <staff xml:id="staff-000000185688557" n="1">
                <layer xml:id="layer-000000144343359" n="1">
                  <note xml:id="note-L11F1" dur="1" oct="4" pname="f" accid.ges="n"/>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by pe-ro** [comment]
An "open" ending can be specified using --
```
<ending n="2" lendsym="none"/>
```
but not until the next revision.

**Comment by craigsapp** [comment]
Here is the initial implementation of endings for the Humdrum-to-MEI converter: 
https://github.com/rism-ch/verovio/commit/2779c105c5b1be1de0b0e0862992fda4b27dca6a

> `<ending n="2" lendsym="none"/>`

What does the `l` in `lendsym` mean?

Another question: How should music before the endings be arranged?  Such as for being able to render MIDI files correctly  would the music be arranged in `<section>`s?:

```
<section>
    <measures>
    <ending n="1">
         <measures>
     </ending>
    <ending n="2">
         <measures>
    <ending>
</section>
```

The first `<measures>` is the music to play for both repeats.

**Comment by pe-ro** [comment]
@craigsapp 

> What does the 'l' in 'lendsym' mean?

l (el) = "line"

N.B. On the `<line>` element itself, the attribute names drop the initial "l" (el).

> Another question: How should music before the endings be arranged? Such as for being able to render MIDI files correctly would the music be arranged in `<section>`s?

MEI borrows the idea of an expansion list from Humdrum.  From the element-level remarks --

"The `@plist` attribute contains an ordered list of identifiers of descendant section, ending, lem, or rdg elements. For example, the sequence "#A #End1 #A #End2" indicates that the section labelled 'A' comes first, then the ending labelled 'End1', followed by the 'A' section again, and finally the ending labelled 'End2'."

Using your example --
```
<section>
  <expansion plist="#exTest01 #exTest02 #exTest03"/>
  <section xml:id="exTest01">
    <measure/>
    <measure/>
  </section>
  <ending n="1" xml:id="exTest02">
    <measure/>
    <measure/>
  </ending>
  <ending n="2" xml:id="exTest03">
    <measure/>
    <measure/>
  </ending>
</section>
```

**Comment by craigsapp** [comment]
Here are more questions related to this subject:

You describe how to expand a section:

```
<section>
  <expansion plist="#exTest01 #exTest02 #exTest03"/>
  <section xml:id="exTest01">
    <measure/>
    <measure/>
  </section>
  <ending n="1" xml:id="exTest02">
    <measure/>
    <measure/>
  </ending>
  <ending n="2" xml:id="exTest03">
    <measure/>
    <measure/>
  </ending>
</section>
```

But another problem is specifying a sequence of sections.   The typical example is a Menuet and Trio movement, where the menuet is played, then the trio, and then the menuet is played again:

Score order:
```
Minuet: A A1 A2  B B1 B2  Trio: C D D1 D2
```
The minuet has two sections A and B, and the trio has two sections C and D, with A1 meaning the first ending, and A2 the second ending for the A section.  And saying perhaps that the C section should be repeated (but no difference in the endings each time, so just a regular repeat).

The normal performance order of the score segments:
```
A A1 A A2 B B1 B B2 C C D D1 D D1 A A2 B B2
```
Notice that section A follows section D, and the return of the minuet involves only taking the second repeats in the minuet.  Related to the return of the minuet, how could the alternate expansion be encoded within the section expansion list, or would there be a way of overriding section expansions at a higher level in the tree structure?

In Humdrum files, I typically have two expansion lists: one for playing as written, and another for playing with no repeats.  The second one is more useful for analysis purposes.

For example, the full repeat of the minuet and trio is given above, and the "no-repeat" version would be:
```
A A2 B B2 C D D2 A A2 B B2
```
There is a similar case of dealing with expansion lists for music with dislocated codas and dal segnos/da capos.

**Comment by pe-ro** [comment]
@craigsapp: I'm not sure I understand the point you're trying to make with the minuet and trio example.  Nothing seems amiss to me.  The performance order can be any sequence of section-like elements necessary.  There's no mechanism for expansion lists within expansion lists.  But, `<expansion>` is repeatable, so it's possible to accommodate "full" and "no-repeat" versions.  I think it makes the most sense to place the expansion lists on the outer-most section element, i.e., at the top of the document hierarchy.

**Comment by lpugin** [comment]
Added here 40ffceeb38d9d2c97b7d26baac4bd54940bb53e5
