### ISSUE TITLE
adding loc

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#411]
I started to work on support for `@loc`. Works fine so far (see MEI file at the end): 
![rest loc](https://cloud.githubusercontent.com/assets/7693447/21621135/f9d827cc-d1f7-11e6-91bb-528120fb35d2.png)

As you can see: problem is, that `loc="0"` doesn't work, as libmei takes 0 as default, which isn't. Every element has a different "default staff location"; `@loc` should be empty by default. Could (should) that be changed? 

Another, more global and far better approach (with more work to be done) would be, to have a function that converts `@ploc/@oloc` and `@pname/@oct` to the right `@loc` for the current staff, fill `m_loc` and use this for rendering. Advantage would be, that this could then be easily overwritten with `@loc`. 

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt>
        <date />
      </pubStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" key.sig="0" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <rest dur="8"/>
                  <rest dur="8" loc="-2"/>
                  <rest dur="8" loc="0"/>
                  <rest dur="8" loc="2"/>
                  <rest dur="8" loc="4"/>
                  <rest dur="8" loc="6"/>
                  <rest dur="8" loc="8"/>
                  <rest dur="8" loc="10"/>
                </layer>
              </staff>
            </measure>
            <measure n="2">
              <staff n="1">
                <layer n="1">
                  <rest dur="4"/>
                  <rest dur="4" loc="-2"/>
                  <rest dur="4" loc="0"/>
                  <rest dur="4" loc="2"/>
                  <rest dur="4" loc="4"/>
                  <rest dur="4" loc="6"/>
                  <rest dur="4" loc="8"/>
                  <rest dur="4" loc="10"/>
                </layer>
              </staff>
            </measure>
            <measure n="3">
              <staff n="1">
                <layer n="1">
                  <rest dur="2"/>
                  <rest dur="2" loc="-2"/>
                  <rest dur="2" loc="0"/>
                  <rest dur="2" loc="2"/>
                  <rest dur="2" loc="4"/>
                  <rest dur="2" loc="6"/>
                  <rest dur="2" loc="8"/>
                  <rest dur="2" loc="10"/>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by lpugin** [comment]
We can easily change the default value of `@loc`. It needs to be changed as `VRV_UNSET` in https://github.com/rism-ch/libmei/blob/master/tools/includes/vrv/config.yml . I will do it.

I will look at a what can be changed in the code. Have you pushed it somewhere?

**Comment by rettinghaus** [comment]
You find it in my develop-loc branch: 
https://github.com/rettinghaus/verovio/tree/develop-loc

**Comment by craigsapp** [comment]
Can't wait to try it out...

**Comment by lpugin** [comment]
![image](https://cloud.githubusercontent.com/assets/689412/25492959/f16dfc34-2b74-11e7-8355-f333855c5eda.png)

**Comment by rettinghaus** [comment]
nice!

**Comment by lpugin** [comment]
It should work with ploc / oloc too

**Comment by rettinghaus** [comment]
Means I can delete my loc branch?

**Comment by lpugin** [comment]
Yes, I think so
