### ISSUE TITLE
Missing header file in iohumdrum.h

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#415]
https://github.com/rism-ch/verovio/blob/develop-humdrum/include/vrv/iohumdrum.h#L28

**Comment by craigsapp** [comment]
Oops,  I must have done

`mv musicxml2hum.h tool-musicxml2hum.h` rather than `git mv musicxml2hum.h tool-musicxml2hum.h`.

Now committed:

https://github.com/rism-ch/verovio/commit/f75118a6e92b702ce1e61f37cc0ac105e343d468

**Comment by lpugin** [comment]
Getting there. Is this really needed?
https://github.com/rism-ch/verovio/blob/develop-humdrum/src/hum/tool-musicxml2hum.cpp#L14

**Comment by craigsapp** [comment]
It is needed in theory, but in practice it is already included from the .h file:

https://github.com/rism-ch/verovio/blob/develop-humdrum/include/hum/tool-musicxml2hum.h#L26

So including in the .cpp is redundant.

**Comment by lpugin** [comment]
OK, I'll remove it then.

**Comment by craigsapp** [comment]
OK, that is good.  It is needed in the .h (probably originally it was only needed in the .cpp).
