### ISSUE TITLE
DEFAULT_MUSICXML_HUMDRUM vs MUSICXML_DEFAULT_HUMDRUM

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#416]
In `src/toolkit.cpp`, a preprocessor variable is called `MUSICXML_DEFAULT_HUMDRUM`, while in `src/tools/CMakeLists.txt` it is called `DEFAULT_MUSICXML_HUMDRUM`.  One of the files' spelling of the variable should be changed to match the other file's.

**Comment by lpugin** [comment]
This was not difficult to fix

**Comment by craigsapp** [comment]
It was too complicated for me :-)
