### ISSUE TITLE
ACCIDENTAL_EXPLICIT_ss vs. ACCIDENTAL_EXPLICIT_x

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#420]
The MusicXML and PAE importer both use `ACCIDENTAL_EXPLICIT_ss` instead of `ACCIDENTAL_EXPLICIT_x`.  "ss" would be rendered as "##", while "x" would be rendered as "x".

`ACCIDENTAL_EXPLICIT_ss` is only a hypothetical accidental sign, and instead `ACCIDENTAL_EXPLICIT_x` should be used for all double sharps (there is no `ACCIDENTAL_IMPLICIT_x`, so `@acc.ges` would use `ACCIDENTAL_IMPLICIT_ss` for gestural double sharps).

https://github.com/rism-ch/verovio/blob/b412e91f37232f123c3469abff231b8f1ee31a0a/src/iomusxml.cpp#L1336-L1337
https://github.com/rism-ch/verovio/blob/b412e91f37232f123c3469abff231b8f1ee31a0a/src/iomusxml.cpp#L1349

https://github.com/rism-ch/verovio/blob/b412e91f37232f123c3469abff231b8f1ee31a0a/src/iopae.cpp#L568

Also "ss" improperly mapped to "x", and "x" mapping is missing (but this does not seem to be the problem with displaying double sharps currently in verovio):

https://github.com/rism-ch/verovio/blob/b412e91f37232f123c3469abff231b8f1ee31a0a/src/view_element.cpp#L234

```
  case ACCIDENTAL_EXPLICIT_ss: symc = SMUFL_E263_accidentalDoubleSharp; break;
```
This should be:
```
  case ACCIDENTAL_EXPLICIT_x: symc = SMUFL_E263_accidentalDoubleSharp; break;
  case ACCIDENTAL_EXPLICIT_ss: symc = SMUFL_E269_accidentalDoubleSharp; break;
```

SMUFL Glyphs

 http://www.smufl.org/version/latest/range/standardAccidentals12Edo

<img width="228" alt="screen shot 2017-01-09 at 08 59 30" src="https://cloud.githubusercontent.com/assets/3487289/21775205/0902b63a-d64a-11e6-88f0-a9ca392625ba.png">
<img width="223" alt="screen shot 2017-01-09 at 08 59 34" src="https://cloud.githubusercontent.com/assets/3487289/21775208/0a8bdb3a-d64a-11e6-8bc6-36a20e0bfdea.png">

**Comment by lpugin** [comment]
Rendering will be fixed
