### ISSUE TITLE
House Styles

### ISSUE THREAD

**Issue by notator** [rism-ch/verovio#421]
Can or should Verovio support more than one "house style"?

I think there are two levels to this question:
1. line thicknesses and font(s)
2. the way particular objects are drawn.

Level 1 might just be a group of settings like those found in the standard music editors.
Level 2 would be at a deeper level. For example: there are many ways to draw slurs. Many people will be happy with Verovio's default slurs, but I'm not. So I'd like, as a programmer, to be able to supply my own code for doing that. Such code ought to be loadable by anyone who prefers my slurs to Verovio's defaults.
The same goes for ties, which I prefer not to look like slurs.
Being able to customise the way objects are drawn would also enable the output to be optimised for further editing (in any SVG editor).

I don't know enough about Verovio's architecture to know if a solution is already in place. If its not, then I think this question needs addressing now, so as to avoid unnecessary work in future.

**Comment by lpugin** [comment]
Verovio is SMuFL compliant, so you can use whatever SMuFL font you want.
http://www.verovio.org/smufl.xhtml

I can help you to use your own font if you have one.

Additional styling parameters will be added in the future. However, there is not plan to have a plugin architecture. I feel that this will be over the top.

**Comment by craigsapp** [comment]
> Verovio is SMuFL compliant, so you can use whatever SMuFL font you want.

But there is a bias towards Leipzig, probably due to some hard-coded constants.  See issue #220.

**Comment by notator** [comment]
@lpugin Thanks for the answer. I really just wanted to get a better idea of where this project is going.

Trying to use my own font in Verovio would be more trouble than its worth. It was made in the early 1990s, and was then compatible with Petrucci/Susato. But quite a few characters were added later, on the first page, so its not entirely SMuFL compatible. (It _might_ be possible to make a compliant font by copying the non-standard characters elsewhere, but that's a job that's very low on my list of priorities.)
