### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by josquin-research-project** [rism-ch/verovio#43]
It would be handy to create a file called .gitignore in the base directory which contains this content:

```
tools/CMakeCache.txt
tools/CMakeFiles/
tools/Makefile
tools/cmake_install.cmake
tools/install_manifest.txt
tools/verovio
```

This will suppress trying to archive these files/directories with git, and you won't have to ignore them or delete them before committing.

**Comment by lpugin** [comment]
Done in commit 33a8320
