### ISSUE TITLE
1 million value conversion issues

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#432]
In the latest develop version there are about one million warnings 
>Implicit conversion loses Integer precision

in the code doing some Humdrum stuff.

**Comment by craigsapp** [comment]
That is pretty impressive.

**Comment by rettinghaus** [comment]
Yes, I exaggerated a bit. There are actually only 32 issues. 
(But it still annoys me.)

**Comment by lpugin** [comment]
On develop or on master?

**Comment by rettinghaus** [comment]
On develop *and* on master!

**Comment by craigsapp** [comment]
> (But it still annoys me.)
:-)

> On develop or on master?

I am checking on them.  I think that these are already fixed in the develop-humdrum branch (except for one), but not yet merged with the develop branch?  Currently I am having float/double problems in develop branch for the file `src/view_floating.cpp` when compiling with gcc 6.2.1 in red hat linux.

**Comment by craigsapp** [comment]
> Currently I am having float/double problems in develop branch for the file src/view_floating.cpp when compiling with gcc 6.2.1 in red hat linux.

Oops, that was in the `master` branch.

**Comment by craigsapp** [comment]
They don't show up for me in MacOS command-line xcode tools, so I usually don't notice them...

Here is what I am currently for the `develop` branch in gcc 6.2.1 in red hat linux:

For `verovio/src/iohumdrum.cpp`:

```
/verovio/src/iohumdrum.cpp:3522:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < beamends.size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~
/verovio/src/iohumdrum.cpp:3528:10: warning: variable ‘beamstate’ set but not used [-Wunused-but-set-variable]
     bool beamstate = false;
          ^~~~~~~~~
/verovio/src/iohumdrum.cpp: In member function ‘void vrv::HumdrumInput::parseSignifiers(hum::HumdrumFile&)’:
/verovio/src/iohumdrum.cpp:5428:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int j = 0; j < equals; j++) {
                         ~~^~~~~~~~
/verovio/src/iohumdrum.cpp: In member function ‘std::vector<int> vrv::HumdrumInput::analyzeMultiRest(hum::HumdrumFile&)’:
/verovio/src/iohumdrum.cpp:5515:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < barindex.size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~
/verovio/src/iohumdrum.cpp:5548:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < wholerest.size(); i++) {
                     ~~^~~~~~~~~~~~~~~~~~
```

in `src/hum/MxmlPart.cpp`:

```
[ 84%] Building CXX object CMakeFiles/verovio.dir/user/c/craig/git-cloud/verovio/src/hum/MxmlPart.cpp.o
/verovio/src/hum/MxmlPart.cpp: In member function ‘void hum::MxmlPart::prepareVoiceMapping()’:
/verovio/src/hum/MxmlPart.cpp:482:3: warning: ‘homevoicenum’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (homevoicenum < 1) {
   ^~
```

I am also getting one warning in the verovio main codebase in `src/view_element.cpp`:

```
[ 70%] Building CXX object CMakeFiles/verovio.dir/user/c/craig/git-cloud/verovio/src/view_element.cpp.o
/verovio/src/view_element.cpp: In member function ‘void vrv::View::DrawArtic(vrv::DeviceContext*, vrv::LayerElement*, vrv::Layer*, vrv::Staff*, vrv::Measure*, bool)’:
/view_element.cpp:279:10: warning: variable ‘drawingCueSize’ set but not used [-Wunused-but-set-variable]
     bool drawingCueSize = false;
          ^~~~~~~~~~~~~~
```

I will check the `develop-humdrum` for warnings and fix any I find, and then Laurent can re-merge into develop.

**Comment by craigsapp** [comment]
Commit https://github.com/rism-ch/verovio/commit/d66d2f224cd187fdcb2b5ca72addd2bd8a43fe74 removes all of the compiler warnings for the `develop-humdrum` branch in src/iohumdrum.cpp and src/hum/MxmlPart.cpp that are reported in gcc 6.2.1 on Red Hat linux.

**Comment by rettinghaus** [comment]
More issues: 
MxmlEvent.cpp 349/250
GridStaff.cpp 64/134
HumGrid.cpp 643/644/794
humlib.cpp 3752/4867/4891/5653/5679/5721/5786/5789/5808/5835/9905/15615/15627/15690/17925/17976/18744/18841
toolkit.cpp 999

**Comment by lpugin** [comment]
Are you working on the latest version of develop?

**Comment by rettinghaus** [comment]
These are reports for the `master` branch. The latest `develop` looks fine fine now.

**Comment by lpugin** [comment]
OK.

**Comment by craigsapp** [comment]
> The latest develop looks fine fine now.

Hmm how did that happen?  I think that since they are warnings, you are not recompiling the files, and so the warnings do not show up.  

I am looking at the repository network:

<img width="683" alt="screen shot 2017-01-17 at 00 31 47" src="https://cloud.githubusercontent.com/assets/3487289/22013134/632e240c-dc4c-11e6-9a37-55fd754d092c.png">

And `develop` has not merged `develop-humdrum` with my fixes yet (or the network graph takes a while to update). (or you are using `-DNO_HUMDRUM_SUPPORT` :-)

**Comment by craigsapp** [comment]
> These are reports for the master branch. The latest develop looks fine fine now.

They will be expected in the `master` branch until the `develop` branch is merged into it.

**Comment by lpugin** [comment]
Yes, XCode has no humdrum support by default in the develop branch. We can see how to manage this in the future. Ideally we should have several build schemes, but this is probably over the top.

**Comment by craigsapp** [comment]
The command-line compiling process is OK, so it doesn't matter to me what happens in XCode :-)
