### ISSUE TITLE
repeats conversion in MusicXML-to-MEI importer

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#433]
It would be handy for the MusicXML-to-MEI importer to convert repeats semantically.

See section "1.1.2.3 Content of Musical Divisions" of the guidelines:
    http://music-encoding.org/documentation/3.0.0/shared
for overview of what will be needed; particularly the expansion and ending elements:
    http://music-encoding.org/documentation/3.0.0/expansion
      http://music-encoding.org/documentation/3.0.0/ending

And after implementing in MusicXML-to-MEI, implementing repeats in MEI-to-MIDI would be handy as well  (issue #235 ).

Basic example:

<img width="857" alt="screen shot 2017-01-17 at 01 44 17" src="https://cloud.githubusercontent.com/assets/3487289/22015799/59209d30-dc58-11e6-95ad-ad1d2fd9d938.png">

MusicXML data from MuseScore:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise>
  <identification>
    <encoding>
      <software>MuseScore 2.0.3.1</software>
      <encoding-date>2017-01-17</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="254.01">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>0.00</left-margin>
            <right-margin>-0.00</right-margin>
            </system-margins>
          <top-system-distance>70.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <direction placement="above">
        <direction-type>
          <metronome parentheses="no">
            <beat-unit>quarter</beat-unit>
            <per-minute>99</per-minute>
            </metronome>
          </direction-type>
        <sound tempo="99"/>
        </direction>
      <note default-x="75.17" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="119.48" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="163.79" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="208.10" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="216.77">
      <note default-x="12.00" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        <repeat direction="backward"/>
        </barline>
      </measure>
    <measure number="3" width="199.24">
      <note default-x="12.00" default-y="-40.00" print-object="no">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="4" width="199.24">
      <note default-x="12.00" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="5" width="208.24">
      <note default-x="12.00" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
```

Here is the current MEI conversion without repeats, although there is a `right="rptend"` for the orthographic repeat.  The problem is that the MusicXML data does not have semantic repeats, but this can mostly be inferred except perhaps for complicated cases such as *da capo*.

```bash
$ ./verovio input.xml -f musicxml -t mei --all-pages --no-layout
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-17 01:46:28</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Encoded with Verovio version 0.9.13-dev-a95cb2b</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000083934862">
                        <staffGrp xml:id="m-000000143605560">
                            <staffDef xml:id="staffdef-000000115466557" clef.shape="G" clef.line="2" key.sig="0" meter.count="4" meter.unit="4" n="1" label="Piano" label.abbr="Pno." lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000153732443">
                        <measure xml:id="measure-000000141466094" n="1">
                            <staff xml:id="staff-000000188699920" n="1">
                                <layer xml:id="layer-000000106895281" n="1">
                                    <note xml:id="note-000000004175409" dur="4" oct="4" pname="d" stem.dir="up" />
                                    <note xml:id="note-000000168142255" dur="4" oct="4" pname="d" stem.dir="up" />
                                    <note xml:id="note-000000093148697" dur="4" oct="4" pname="e" stem.dir="up" />
                                    <note xml:id="note-000000034583580" dur="4" oct="4" pname="f" stem.dir="up" />
                                </layer>
                            </staff>
                            <tempo xml:id="tempo-000000075705550" place="above" staff="1" startid="#note-000000004175409" midi.bpm="99">M.M. = 99</tempo>
                        </measure>
                        <measure xml:id="measure-000000137169308" n="2" right="rptend">
                            <staff xml:id="staff-000000073391727" n="1">
                                <layer xml:id="layer-000000194912343" n="1">
                                    <note xml:id="note-000000120197028" dur="4" oct="4" pname="d" stem.dir="up" />
                                    <note xml:id="note-000000013592947" dur="4" oct="4" pname="e" stem.dir="up" />
                                    <note xml:id="note-000000179153595" dur="4" oct="4" pname="f" stem.dir="up" />
                                    <note xml:id="note-000000047649706" dur="4" oct="4" pname="d" stem.dir="up" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-000000051961817" n="3">
                            <staff xml:id="staff-000000043423151" n="1">
                                <layer xml:id="layer-000000097960648" n="1">
                                    <note xml:id="note-000000163655549" dur="4" oct="4" pname="e" stem.dir="up" visible="false" />
                                    <note xml:id="note-000000061762007" dur="4" oct="4" pname="c" stem.dir="up" />
                                    <note xml:id="note-000000155213457" dur="4" oct="4" pname="d" stem.dir="up" />
                                    <note xml:id="note-000000124192510" dur="4" oct="4" pname="e" stem.dir="up" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-000000164174177" n="4">
                            <staff xml:id="staff-000000074531623" n="1">
                                <layer xml:id="layer-000000025778146" n="1">
                                    <note xml:id="note-000000105858306" dur="4" oct="4" pname="f" stem.dir="up" />
                                    <note xml:id="note-000000185100809" dur="4" oct="4" pname="c" stem.dir="up" />
                                    <note xml:id="note-000000144490860" dur="4" oct="4" pname="e" stem.dir="up" />
                                    <note xml:id="note-000000083391118" dur="4" oct="4" pname="f" stem.dir="up" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-000000106703958" n="5" right="end">
                            <staff xml:id="staff-000000209468130" n="1">
                                <layer xml:id="layer-000000160928467" n="1">
                                    <note xml:id="note-000000183841517" dur="4" oct="4" pname="d" stem.dir="up" />
                                    <note xml:id="note-000000024920041" dur="4" oct="4" pname="c" stem.dir="up" />
                                    <note xml:id="note-000000071829686" dur="4" oct="4" pname="e" stem.dir="up" />
                                    <note xml:id="note-000000140989749" dur="4" oct="4" pname="f" stem.dir="up" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by phboer** [comment]
I came across the same issue just now. Are there any plans of adding this feature soon?

Thanks!
Hugo

**Comment by lpugin** [comment]
I do not understand this issue. Also, I do not get why the first note of the third measure is marked as invisible.

**Comment by craigsapp** [comment]
> Also, I do not get why the first note of the third measure is marked as invisible.

Probably I typed a key which made it invisible by accident.  Or it was a recycled example dealing with invisible notes...

> I do not understand this issue.

The `expansion` element can be used to expand repeated sections in the MEI data when generating MIDI renderings, for example.  In other words, the expansion element(s) in the data instruct how the score-order of the measures should be re-arranged into performance-order.

@pe-ro can refine my examples below if they are incorrect.

<img width="1028" alt="screen shot 2017-02-22 at 07 31 49" src="https://cloud.githubusercontent.com/assets/3487289/23218403/0c808dba-f8d1-11e6-93d8-00cb18b19b5a.png">

The expansion element in this example:

```xml
   <section>
       <expansion plist="A A B"/>
       <section xml:id="A">
           // measures for section A (measures 1-2) 
       </section>
       <section xml:id="B">
          // measures for section B (measures 3-5)
       </section>
   </section>
```

Perhaps for simple cases such as this, the barline stylings could be used to infer the expansion lists (but this would increase the complexity of rendering repeats in MIDI conversions).

If there were a *da capo senza ripetizione* on the example (such as for a Minuet and Trio movement), it would be encoded like this:

```xml
   <section>
       <expansion plist="A A B A"/>
       <section xml:id="A">
           // measures for section A (measures 1-2) 
       </section>
       <section xml:id="B">
          // measures for section B (measures 3-5)
       </section>
   </section>
```


Expansion lists can occur inside of sections as well, to explain how to deal with endings (particularly non-standard repetitions of the endings, such as repeat the first ending twice then do the second ending):

```
<section>
  <expansion plist="A Ending1 A Ending1 A Ending2"/>
  <section xml:id="A">
    // measures in section A
  </section>
  <ending n="1" xml:id="Ending1" label="1. 2.">
    <measure n="9" right="rptend"/>
  </ending>
  <ending n="2" xml:id="Ending2" label="3.">
    <measure n="10" right="end"/>
  </ending>
</section>
<section xml:id="B">
   // measures in section B
<section>
```

In this case the full expansion would be `A Ending1 A Ending1 A Ending2 B` with `B` not repeated as there is no expansion list.

**Comment by phboer** [comment]
I thought this issue was about a missing barline for the repeats but when reading more carefully I think it is a separate issue. I expanded the music XML sample and added a barline 'start' and 'end' to the second measure. This should draw a barline for the repeat like this:
![image](https://cloud.githubusercontent.com/assets/25896800/23480772/6b7db1a0-fec9-11e6-9d32-4ac183dde912.png)

However, when I convert the xml file to MEI using the MusicXML Converter the barline is not shown. Can you confirm this is an issue? Can I create a new issue for this? The barlines for the repeats are commonly used and it would be nice if this can be supported.

Thanks,
Hugo

PS I'm new to this repository. Hope it's ok if I add comments here.

Below is the XML sample with the barline start and end extensions:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise>
  <identification>
    <encoding>
      <software>MuseScore 2.0.3.1</software>
      <encoding-date>2017-01-17</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="254.01">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>0.00</left-margin>
            <right-margin>-0.00</right-margin>
            </system-margins>
          <top-system-distance>70.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <direction placement="above">
        <direction-type>
          <metronome parentheses="no">
            <beat-unit>quarter</beat-unit>
            <per-minute>99</per-minute>
            </metronome>
          </direction-type>
        <sound tempo="99"/>
        </direction>
      <note default-x="75.17" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="119.48" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="163.79" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="208.10" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="216.77">
      <barline location="left">
        <ending number="1" type="start"/>
      </barline>
      <note default-x="12.00" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        <ending number="1" type="stop"/>
        <repeat direction="backward"/>
      </barline>
    </measure>
    <measure number="3" width="199.24">
      <note default-x="12.00" default-y="-40.00" print-object="no">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="4" width="199.24">
      <note default-x="12.00" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="5" width="208.24">
      <note default-x="12.00" default-y="-45.00">
        <pitch>
          <step>D</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="58.41" default-y="-50.00">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="104.82" default-y="-40.00">
        <pitch>
          <step>E</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <note default-x="151.23" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>

**Comment by rettinghaus** [comment]
What is barline 'start' and 'end' in MusicXML? Makes no sense to me. 
And your XML sample isn't a XML sample.

**Comment by rettinghaus** [comment]
Problem is: the importer adds measure for measure into a section and counts them up. As `<ending>` is on the same level as `<measure>` this wouldn't work. I'll get back to this as soon I have some spare time.

**Comment by craigsapp** [comment]
<img width="676" alt="screen shot 2017-03-01 at 1 09 11 pm" src="https://cloud.githubusercontent.com/assets/3487289/23481475/573548b4-fe80-11e6-89ba-1e56a6b1014a.png">

<img width="665" alt="screen shot 2017-03-01 at 1 09 23 pm" src="https://cloud.githubusercontent.com/assets/3487289/23481477/59070fec-fe80-11e6-834a-5c0ef190f17b.png">

Adding the first ending (the bracket with the "1" under it has a different meaning from the notation where there is no bracket.

The repeat expansion for the first example is: `1 2 1 2 3 4 5`.

while the second example is to be expanded as: `1 2 1 3 4 5`, with measure 2 not played the second time.

**Comment by phboer** [comment]
Hi, any update on the issue with the repeats? Not sure if it would be any easier to repeat the same notes instead of drawing a bracket with number. This would already be better then it is now.

Thanks,
Hugo

**Comment by phboer** [comment]
Can I bring this issue under the attention once more please? For me this is quite a severe one. I'm using Verovio to render scores from MusicXML and it works really great. Repeats are however often used and as far as I can see Veriovio is not handling them correctly. It makes the rendered scores that contain repeats less usable. I don't think there is a workaround at the moment?

I'm using the command-line interface to render scores with the --no-layout parameter. It would already be great if the rendered score just repeats the same notes again. It does not have to draw the actual repeat brackets themselves.

Thanks,
Hugo

**Comment by phboer** [comment]
Will this issue be pucked up any time soon? Within a few weeks or so? If not, I need to see if there is a way around the repeats issue. As explained before  It is really crucial for me. 

Thanks!
Hugo

**Comment by rettinghaus** [comment]
I still don't completely understand, what you want. Do you need ending brackets or a working midi playback?

**Comment by phboer** [comment]
Hi, I would like both. In the score the measures need to be repeated (kind of 'flattened' score, going from beginning to end without jumping). The MIDI should be alligned with the score.

Thanks,
Hugo

Op 30 mei 2017 om 09:00 heeft Klaus Rettinghaus <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I still don't completely understand, what you want. Do you need ending brackets or a working midi playback?

**Comment by rettinghaus** [comment]
That is something that Verovio will not provide. You should use a XSLT to "flatten" the repeats in the XML or edit it with another program.

**Comment by wergo** [comment]
Just a quick question: as @rettinghaus mentioned here two years ago, is there already a XSLT script that expands the `<expansion>` element in MEI into a "flattened" long MEI?
