### ISSUE TITLE
Documentation of MEI version(s) supported

### ISSUE THREAD

**Issue by billmoser** [rism-ch/verovio#438]
HI - I'm trying to use the the headshape (mei v2.1.1) or head.shape (mei v3.0.0) attribute of the <note> element.  neither appears to be supported by verovio.  I'm trying to render percussion, so it would be great to have this concept supported (or something similar, so I can change the note head shape to a diamond, x, etc - the mechanism doesn't matter to me).   But more importantly, just to know what version of MEI is being supported by a given verovio release, and the extent of the support (full schema, or some subset, etc)

**Comment by lpugin** [comment]
The `@head.shape` is indeed not supported yet. Percussion is actually already a feature request (#385)

Concerning the version supported, the current version is built on 3.0.0. Of course, only a small subset supported. We had a while ago a list of supported elements / attributes (http://www.verovio.org/supported-mei.xhtml). It is however quite outdated. Help for maintaining it would be appreciated ;-)

**Comment by rettinghaus** [comment]
@lpugin Did you have a look at my updated `supported-mei.yml`?

**Comment by lpugin** [comment]
Yes. I just notice the .xhtml file was not updated. This needs to be done by hand because gh-pages does not support plugins. See https://github.com/rism-ch/verovio/blob/gh-pages/supported-mei.xhtml#L22-L33

**Comment by rettinghaus** [comment]
Will you try it. I wasn't able to compile it.

**Comment by lpugin** [comment]
I just did it. There were a couple of missing "attributes" hashes.
