### ISSUE TITLE
stripping verovio command

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#44]
When compiling the verovio command-line program, the executable contains debugging information which will not be needed in a production setting.  To remove this content from the executable, there are two possibilities:

1. Run the strip command on the file (http://en.wikipedia.org/wiki/Strip_(Unix)): ```strip verovio```
2. Add the -s option if using gcc

For example, the verovio executable is 4.8 MB with debugging info, but 1.5 MB after stripping.  This should be done by default, since developers can adjust the makefile if they need to debug the program.

**Comment by lpugin** [comment]
Considering the size of the binary, I'll close it for now
