### ISSUE TITLE
Control event order priority

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#445]
In this sample music, the trill should go below the text direction:

<img width="295" alt="screen shot 2017-01-19 at 23 04 59" src="https://cloud.githubusercontent.com/assets/3487289/22139569/bc26895e-de9b-11e6-8074-aa7ea18ed6de.png">

Compare to original music:

<img width="290" alt="screen shot 2017-01-19 at 22 58 10" src="https://cloud.githubusercontent.com/assets/3487289/22139436/c616db36-de9a-11e6-87a7-fb7032dfa035.png">

@ahwitz: how do you like the accidental kerning in the second beat of the bottom staff? :-)

The same would apply to other ornaments such as `turn`.

MEI data for test:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2017-01-19 23:04:46</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.14-dev-ea2b196</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000019258618">
                        <staffGrp xml:id="m-000000170813431" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-000000043295121" clef.shape="G" clef.line="2" key.sig="5f" n="1" lines="5" />
                            <staffDef xml:id="staffdef-000000187826225" clef.shape="F" clef.line="4" key.sig="5f" n="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000191736514">
                        <measure xml:id="measure-L5" n="91">
                            <staff xml:id="staff-L5F2" n="1">
                                <layer xml:id="layer-L5F2" n="1">
                                    <note xml:id="note-L7F2" dur="8" accid="f" oct="4" pname="f" grace="acc" stem.dir="up" />
                                    <note xml:id="note-L9F2" dur="4" oct="4" pname="f" accid.ges="f" />
                                    <beam xml:id="beam-000000146345888">
                                        <note xml:id="note-L10F2" dur="8" oct="4" pname="e" accid.ges="f">
                                            <accid xml:id="accid-000000061758803" accid="f" func="caution" />
                                        </note>
                                        <note xml:id="note-L11F2" dur="8" oct="4" pname="f" accid.ges="f" />
                                        <note xml:id="note-L13F2" dur="8" oct="4" pname="g" accid.ges="f" />
                                        <note xml:id="note-L14F2" dur="8" oct="4" pname="a" accid.ges="f" />
                                    </beam>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L5F1" n="2">
                                <layer xml:id="layer-L5F1" n="1">
                                    <note xml:id="note-L9F1" dur="4" oct="2" pname="g" accid.ges="f">
                                        <accid xml:id="accid-000000018572229" accid="f" func="caution" />
                                    </note>
                                    <chord xml:id="chord-L10F1" dur="4">
                                        <note xml:id="note-L10F1S1" oct="3" pname="e" accid.ges="f">
                                            <accid xml:id="accid-000000154395125" accid="f" func="caution" />
                                        </note>
                                        <note xml:id="note-L10F1S2" accid="ff" oct="3" pname="b" />
                                    </chord>
                                    <chord xml:id="chord-L13F1" dur="4">
                                        <note xml:id="note-L13F1S1" oct="3" pname="e" accid.ges="f" />
                                        <note xml:id="note-L13F1S2" oct="3" pname="b" accid.ges="ff" />
                                    </chord>
                                </layer>
                            </staff>
                            <dir xml:id="dir-000000169584342" place="above" staff="1" tstamp="1.000000">sotto voce</dir>
                            <trill xml:id="trill-000000118768062" staff="1" tstamp="1.000000" />
                            <slur xml:id="slur-000000064724676" staff="1" startid="#note-L9F2" endid="#note-L14F2" />
                            <pedal xml:id="pedal-000000199018676" staff="2" tstamp="1.000000" dir="down" />
                            <pedal xml:id="pedal-000000105288649" staff="2" tstamp="3.500000" dir="up" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Initial Humdrum data:

```
**kern		**kern
*k[b-e-a-d-g-]	*k[b-e-a-d-g-]
=91		=91
*ped		*
.		8qf-/
!		!LO:TX:a:i:t=sotto voce
4GG-X		(4f-yT
4E-X 4B--	8e-XL
.		8f-
4E- 4B--	8g-
.		8a-J)
*Xped		*
=92		=92
*-		*-
```

**Comment by rettinghaus** [comment]
Do you see this as basic rule? As I said, I ordered the stacking the way LilyPond does, which seems to me as a reasonable approach as LilyPond does a quite good job when it comes to this. Is there anything about this in Behind Bars? If not, I'd suggest to leave it this way until MEI has a proper way to `@order` things.

**Comment by lpugin** [comment]
I would expect the trill to be the closest to the note by default but I am not sure.

**Comment by craigsapp** [comment]
> I would expect the trill to be the closest to the note by default but I am not sure.

I would say there is no question that the trill should be closer to the note than the dir.

**Comment by craigsapp** [comment]
> As I said, I ordered the stacking the way LilyPond does, which seems to me as a reasonable approach as LilyPond does a quite good job when it comes to this.

Where is that? I saw it yesterday or so...

**Comment by lpugin** [comment]
https://github.com/rism-ch/verovio/blob/develop/src/system.cpp#L312-L331

**Comment by craigsapp** [comment]
> https://github.com/rism-ch/verovio/blob/develop/src/system.cpp#L312-L331

There was graphic notation too.  I think on a commit.

**Comment by lpugin** [comment]
https://github.com/rism-ch/verovio/pull/434

**Comment by craigsapp** [comment]
Yest, It was in a pull request https://github.com/rism-ch/verovio/pull/434

<img width="552" alt="screen shot 2017-01-20 at 00 27 29" src="https://cloud.githubusercontent.com/assets/3487289/22141537/5143eac6-dea7-11e6-83a3-387938f839b0.png">

I would say that the *legatissimo* should go above the fermata and below the **Adagio**.

The order that I am imagining is proper is: articulation, ornament, fermata, dir, tempo
(from nearest to furthest from note).

**Comment by craigsapp** [comment]
I am thinking now that I would probably put the dynamic above the fermata.  In other words, the closer to the note, the more localized the information.  Articulations are tightly associated with a note.   Ornaments are as well, but less so since they represent multiple unwritten notes.  Then fermata as a special case.  Then dynamics, dir, and tempo, which are more global: starting on the note, but continuing to following notes.

**Comment by donbyrd** [comment]
As @craigsapp said about eight comments back, "there is no question that the trill definitely should be closer to the note than the dir. The trill is specific to a particular note, and the sotto voce applies to multiple notes." And I agree with his rule just one comment ago, "the closer to the note, the more localized the information."

I'm 99% sure that _Behind Bars_ gives the proper ordering for most if not all of the items people have mentioned, but I can't look right now.

**Comment by craigsapp** [comment]
> I'm 99% sure that Behind Bars gives the proper ordering for most if not all of the items people have mentioned, but I can't look right now.

It must be in the 1% of *Behind Bars* that I haven't checked, because I don't see it discussed in there.

Here is a hint to the answer: placing the trill mark above the *sotto voce* looks amateurish.

**Comment by donbyrd** [comment]
The table of ordering I was thinking of is on p. 427 of _Behind Bars_. But she's talking there specifically about technical directions for strings, so it does _not_ cover most of the items discussed in this thread; my mistake. However, this was well as several other places in Behind Bars makes it clear that the general principle @craigsapp gave, "the closer to the note, the more localized the information", is correct.

**Comment by craigsapp** [comment]
p. 427:

<img width="411" alt="screen shot 2017-01-20 at 17 29 32" src="https://cloud.githubusercontent.com/assets/3487289/22170683/1375f934-df36-11e6-8bde-bffbc1c703b0.png">

**Comment by donbyrd** [comment]
Thanks, Craig. This is a bit off-topic, but there's also a table of horizontal ordering of text-based technical directions on p. 426.

**Comment by craigsapp** [comment]
But that is the wrong dimension :-)

<img width="726" alt="screen shot 2017-01-20 at 18 15 03" src="https://cloud.githubusercontent.com/assets/3487289/22171133/6dedad5c-df3c-11e6-8b74-4bf0d51cb457.png">

**Comment by donbyrd** [comment]
That's why it's off-topic :-) . But it seems likely to come up at some point, so I thought it was worth mentioning now.

**Comment by sonovice** [comment]
There is a (dead?) discussion over here: music-encoding/music-encoding#390
