### ISSUE TITLE
ledgerline length

### ISSUE THREAD

**Issue by notator** [rism-ch/verovio#446]
I think this ledgerline is too short. It will disappear at small sizes.
![image](https://cloud.githubusercontent.com/assets/1655500/22142491/b0eb01c2-def6-11e6-8c53-c7ac7b9baeac.png)

I think there should be a minimum length by which a ledgerline extends out from a notehead (and that all ledgerlines on a chord should be the same length).

**Comment by lpugin** [comment]
Thanks. This was already reported here #214
