### ISSUE TITLE
Proposed head.shape implementation

### ISSUE THREAD

**Issue by billmoser** [rism-ch/verovio#458]
Hello -

I have a proposal for implementing the head.shape attribute for noteheads.
I've implemented this in my copy of master.  Attached are sample mei and pdf
illustrating the I/O.  Details of the changes are also attached (with my comments
interspersed).  I'll summarize them here:
  1)  several glyphs have been uncommented in fonts/supported.xsl, requiring
    generate_all.sh to be rerun.  This of course has the side effect that 
    several other files in data and include have been (re)regenerated
  2) "Boilerplate" has been added to include/vrv/note.h, src/iomei.cpp, and
    src/note.cpp in order to allow the head.shape attribute to be recognized.
  3) src/view_element.cpp has two additions:
        a) a function which translates MEI head.shape strings into SMuFL codes
        b) a 3-line conditional in View::DrawNote which replaces the 
           fontNo for the notehead if the head.shape attriute exists

I have a few questions:
1) Do you want these changes? If so, how should I do the pull request, 
   from a fork or a branch, and a fork or branch of what?
2) There are many more SMuFL glyphs than there are MEI head.shapes. 
   Is sticking with the MEI subset necessary, or is it possible for me to go
   with the full set of SMuFL codes/strings.  This would then differ from MEI's
   data.HEADSHAPE.list
3) is view_element.cpp the appropriate place for the string/code converter?
4) my notehead replacement is simple and context-free.  That works for me, but 
   does it work for the project overall?

Regards,
Bill

Examples:

[head-shape-mei.txt](https://github.com/rism-ch/verovio/files/733675/head-shape-mei.txt)
[head-shape.pdf](https://github.com/rism-ch/verovio/files/733669/head-shape.pdf)

Changes:

[Changes.txt](https://github.com/rism-ch/verovio/files/733683/Changes.txt)

**Comment by ahankinson** [comment]
Hi Bill,

This is more a comment on the mechanics of this contribution, rather than its implementation. I will point you to the contribution guidelines for the MEI repo, since they are largely the same as the practices for Verovio:

https://github.com/music-encoding/music-encoding/blob/develop/CONTRIBUTING.md#how-to-contribute

In short, contributions should be submitted as pull requests. Pull requests (or colloquially, PRs) make reviewing, revising, and accepting contributions much much easier for project maintainers than applying patch files directly. Once opened, a pull request becomes like an issue, with people able to comment on your contribution and request changes. Once a contribution is accepted, it can be merged into the project directly on the GitHub website.

**Comment by billmoser** [comment]
> So please, open a pull request and we can move the conversation there.

Ok, I'll do that

**Comment by craigsapp** [comment]
> my notehead replacement is simple and context-free. That works for me, but
does it work for the project overall?

Don't mind me as @lpugin is in charge, but I notice that the stems do not attach to the notes in your sample PDF:

<img width="369" alt="screen shot 2017-01-26 at 13 54 49" src="https://cloud.githubusercontent.com/assets/3487289/22352020/49cbdf42-e3cf-11e6-858b-f6832603c78c.png">

So of course proper notehead replacement will not really context free from how the stems attach to the notes.  I would expect something like this:

<img width="804" alt="screen shot 2017-01-26 at 14 17 38" src="https://cloud.githubusercontent.com/assets/3487289/22352780/72669098-e3d2-11e6-8b5a-d3727dcc7830.png">

SMuFL fonts have control points for locations to attach stems.  Are verovio noteheads using these points currently?

<img width="637" alt="screen shot 2017-01-26 at 14 27 27" src="https://cloud.githubusercontent.com/assets/3487289/22353073/9a84eb50-e3d3-11e6-80f4-d47841ad103e.png">


Other than for percussion repertories, notehead shapes would also be useful for someone doing a project with shape-note music:
     https://en.wikipedia.org/wiki/Shape_note

**Comment by lpugin** [comment]
General feature request

**Comment by sonovice** [comment]
Just came across the need for different noteheads. SMuFL anchors for notes have been introduced in https://github.com/rism-ch/verovio/commit/1c844a6cc7e73e8daadfa296d6a86a950dcfc81a

Might be worth to give noteheads another shot. I will try to look into it within the next couple of days...
