### ISSUE TITLE
Mordent/Inverted Mordent

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#464]
There is a problem with the labeling of mordents versus inverted mordents.

<img width="555" alt="screen shot 2017-02-02 at 00 18 42" src="https://cloud.githubusercontent.com/assets/3487289/22541759/2dc5890c-e8dd-11e6-932c-fbc8d2f678bf.png">

I call the first one an inverted mordent, and the second one a regular mordent.  I see the problem is explained in Wikipedia entry for mordents (unless these renderings are actually errors, as opposed to being biased by a Bach scholar :-)

https://en.wikipedia.org/wiki/Mordent

> The precise meaning of mordent has changed over the years. In the Baroque period, a mordent was a lower mordent and an upper mordent was a pralltriller or schneller. In the 19th century, however, the name mordent was generally applied to what is now called the upper mordent, and the lower mordent became known as an inverted mordent.[2]

But notice that "inverted mordent" is only supposed to be "lower mordent" and not the pralltriller or schneller.

Perhaps it might be better for MEI to call them upper and lower mordents rather than mordent and inverted mordent in order to avoid this problem if it is confusing for Baroque scholars.  The upper mordent is always the one without the line, and the lower mordent is always the one with the vertical stroke through it, so there would not be any confusion in that case.

SMuFL names them as I do:

<img width="603" alt="screen shot 2017-02-02 at 00 22 41" src="https://cloud.githubusercontent.com/assets/3487289/22541853/c2f43f28-e8dd-11e6-8ac1-26ae9ee59890.png">

MEI data demonstrating the one with the line is called the "mordent" and the one without the line is the "inverted mordent".

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-02-02T00:18:18" version="0.9.14-dev-8896136-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000085694385">
                        <staffGrp xml:id="m-000000032022887">
                            <staffDef xml:id="staffdef-000000049271635" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000211849819">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L4F1" dur="1" oct="4" pname="f">
                                        <accid xml:id="accid-L4F1" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <mordent xml:id="mordent-L4F1" staff="1" startid="#note-L4F1" />
                        </measure>
                        <measure xml:id="measure-L5" n="2" right="end">
                            <staff xml:id="staff-L5F1" n="1">
                                <layer xml:id="layer-L5F1" n="1">
                                    <note xml:id="note-L6F1" dur="1" oct="4" pname="g">
                                        <accid xml:id="accid-L6F1" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <mordent xml:id="mordent-L6F1" staff="1" startid="#note-L6F1" form="inv" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
That's *not* a Verovio problem. First I followed the SMuFL names (as you intend). But following MEI Guidelines (and MusicXML BTW) this is correct. 
http://music-encoding.org/documentation/3.0.0/mordent/

**Comment by craigsapp** [comment]
Hmmm. Probably better to rename them `upper` and `lower` mordents in MEI then...

**Comment by craigsapp** [comment]
The reason the upper mordent is called an inverted mordent in MusicXML is that Eleanor gave Michael a list of Baroque ornaments when he was naming them.  Probably the name came from this source (since the mordent was labeled as the lower mordent):

https://en.wikipedia.org/wiki/Klavierb%C3%BCchlein_f%C3%BCr_Wilhelm_Friedemann_Bach

<img width="743" alt="screen shot 2017-02-02 at 01 15 24" src="https://cloud.githubusercontent.com/assets/3487289/22543409/3db4442c-e8e5-11e6-9dca-4b96573bf452.png">

I.e., this is the reason from the Baroque nomenclature (but caused a proleptic name for the inverted mordent).

**Comment by donbyrd** [comment]
I thought the the upper mordent was called inverted. Anyway, with so much confusion, IMHO, by far the best solution is to call them upper and lower mordents.

**Comment by rettinghaus** [comment]
@lpugin this can be closed now, I think.
