### ISSUE TITLE
Stems of notes on the middle line should go downwards as a default

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/verovio#47]
medium-high violation: stems of notes on the middle line should go downwards as a default. Stems can go up for vocal repertories where the stem may collide with lyrics, or in instrumental music to keep the pattern of stems consistent (such as B4/C5 notes alternating). Behind Bars p. 14 top of page for discussion of this rule. Of course, if the input data has stems-up for such case (perhaps because of a diplomatic score), then this is not an error directly in verovio.

**Comment by lpugin** [comment]
Can be improved for notes shorter than 4th
