### ISSUE TITLE
composite ornament/accidental glyphs

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#474]
SMuFL has separate characters for ornaments that include accidentals:

<img width="711" alt="screen shot 2017-02-13 at 18 52 34" src="https://cloud.githubusercontent.com/assets/3487289/22913121/d91b7534-f21d-11e6-9bdf-7524e780a966.png">

So one possibility is to treat the ornament + accidental glyphs as a single glyph...  In the case of an editorial accidental on the ornament in parentheses or brackets that might not work so well.

**Comment by lpugin** [comment]
It is indeed more flexible not to use SMUFL composite glyphs.
