### ISSUE TITLE
center clef and meter symbols on staff

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#476]
Clefs will not be rendered if `@clef.line` is missing. But they should appear centered of the staff. 
As should the meter signature (currently this works only with an uneven number of staff lines). 

![orff](https://cloud.githubusercontent.com/assets/7693447/22981348/7e4d7424-f39c-11e6-98bd-86b451e15718.png)

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt>
      </pubStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef xml:id="scoredef-0000001121536489">
            <staffGrp xml:id="staffgrp-0000000676894997">
              <staffDef xml:id="staffdef-0000001378572237" clef.shape="C" meter.count="4" meter.unit="4" n="1" lines="5" />
              <staffDef xml:id="staffdef-0000000039525334" clef.shape="perc" meter.count="4" meter.unit="4" n="2" lines="4" />
              <staffDef xml:id="staffdef-0000001000793725" clef.shape="perc" meter.count="4" meter.unit="4" n="3" lines="1" />
            </staffGrp>
          </scoreDef>
          <section xml:id="section-0000001132119921">
            <measure xml:id="measure-0000001517163118" n="1">
              <staff xml:id="staff-0000000686555352" n="1">
                <layer xml:id="layer-0000001390366260" n="1">
                  <mRest xml:id="mrest-0000002085295690" />
                </layer>
              </staff>
              <staff xml:id="staff-0000000072098738" n="2">
                <layer xml:id="layer-0000001415020312" n="1">
                  <mRest xml:id="mrest-0000000362470464" />
                </layer>
              </staff>
              <staff xml:id="staff-0000001653569518" n="3">
                <layer xml:id="layer-0000001109336206" n="1">
                  <mRest xml:id="mrest-0000000149676583" />
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by pe-ro** [comment]
Clefs should *not* be centered on the staff.  Their location must be specified.  Otherwise, there's to way to tell the difference in meaning between, say, a G-clef on the 1st line and a G-clef on the 2nd line.  Or the various meanings of a C-clef.

In contrast, however, the percussion and TAB clefs are always rendered vertically centered on the staff.  So, in these cases, `@clef.line` isn't required.

**Comment by rettinghaus** [comment]
I know that there has to be a `@clef.line` to make sense of C, F, and G clefs. BUT if there isn't one, Verovio just ignores the *clef* and carries on rendering the accidentals and notes as if there *was* a standard G-2 clef. So IMHO the most reasonable behavior should be to put the clef in the middle of the staff.

![test](https://cloud.githubusercontent.com/assets/7693447/22994614/d93b572c-f3c7-11e6-98c5-2997fe6ed6eb.png)

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt />
    </fileDesc>
    <encodingDesc>
    </encodingDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" key.sig="1f" meter.count="3" meter.unit="4" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <note dur="4" oct="4" pname="g" stem.dir="down" />
                  <note dur="4" oct="4" pname="g" stem.dir="up" />
                  <note dur="4" oct="4" pname="g" stem.dir="down" />
                </layer>
              </staff>
            </measure>
            <measure n="2" right="end">
              <staff n="1">
                <layer n="1">
                  <note dur="4" oct="4" pname="b" stem.dir="up">
                    <accid accid.ges="f" />
                  </note>
                  <note dur="4" oct="4" pname="f" stem.dir="down" />
                  <note dur="4" oct="4" pname="e" stem.dir="up" />
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by lpugin** [comment]
We can make it have default such as line 2 for G, 4 for F and 3 or 4 for C since they are the most common clefs. Similarly we can make 5 lines a default when no `@lines` is provided. Related to this: what to do when no clef is given?

**Comment by pe-ro** [comment]
The schema (via Schematron) actually requires `@lines` on `<staffDef>` unless there's a preceding `<staffDef>` with `@lines` and the same value for `@n`.  So, in effect the first use of `<staffDef>` must have `@lines`.

A default value for `@clef.line` based on the clef shape makes sense.  But, since `@clef.line` may occur on `<scoreDef>`, one could also use the look-back method for this too and use the default values only if one isn't found on a preceding `<scoreDef>`.

> Related to this: what to do when no clef is given?

Same answer.  When no clef is provided by `<staffDef>` one can look to preceding `<scoreDef>` elements to determine the default clef.  If a clef still isn't found, then I think it's reasonable to assume a G clef on the 2nd line.

**Comment by rettinghaus** [comment]
MusicXML has default values for clefs: 

> Standard values are 2 for the G sign (treble clef), 4 for the F sign (bass clef), 3 for the C sign (alto clef) and 5 for TAB (on a 6-line staff).

https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-clef.htm

**Comment by lpugin** [comment]
@pe-ro as far as I remember Verovio already looks for a clef on scoreDef if nothing is provided on staffDef. However, having `@clef.line` on scoreDef and `@clef.shape`(or the opposite) does not work, but I do not think it really makes sense.

**Comment by pe-ro** [comment]
> having @clef.line on scoreDef and @clef.shape(or the opposite) does not work, but I do not think it really makes sense.

I think `<scoreDef>` is the place to record values that apply to the score, even if they are overridden by subsequent `<scoreDef>` or `<staffDef>` elements.

**Comment by lpugin** [comment]
I think it is best to require `@clef.line` to be given. (One should check that the musicxml import add them for the default values in musicxml)
