### ISSUE TITLE
spacing between system barline and clef

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#485]
Spacing between a system barline and the system clef used to be like this (1 vu):

<img width="421" alt="screen shot 2017-02-22 at 23 37 08" src="https://cloud.githubusercontent.com/assets/3487289/23249232/1360b2ae-f958-11e6-8108-b7a7ceb15904.png">

But now looks like this:

<img width="205" alt="screen shot 2017-02-22 at 23 37 27" src="https://cloud.githubusercontent.com/assets/3487289/23249238/1a306048-f958-11e6-9d29-9a8a7332bc01.png">

The spacing is now too small.  It should be about 1vu, or possibly down to 0.5 vu, but the above example seems to be about 0.25 vu.

Here is the default spacing in SCORE, about 1.5 vus:

<img width="174" alt="screen shot 2017-02-22 at 23 40 16" src="https://cloud.githubusercontent.com/assets/3487289/23249295/561d8dd8-f958-11e6-96a7-83fe18aa266f.png">

**Comment by lpugin** [comment]
OK, changed to 1 vu in a556c8b56e8c72235690064abcc136695cfa428b 

This will eventually be easy to change with styling.

**Comment by lpugin** [comment]
PS it was 0.5 but looked smaller because of the system line width that is not taken into account. This is not optimal but not a too serious issue.
