### ISSUE TITLE
tuplet error handling

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#487]
While generating test conversion data, I came across this case: the following example MEI data has (incorrectly) assigned `@num="0"` and `@numbase="0"` for the first tuplet in the first measure (should be 3, and 2).  But verovio does not handle the error very well (should behave something like grace notes instead of having the D4 pop to the right end of the first measure, disembodied from the beam).

<img width="1085" alt="screen shot 2017-02-26 at 5 55 29 pm" src="https://cloud.githubusercontent.com/assets/3487289/23346197/eead57ee-fc4c-11e6-8903-9bd800b1c878.png">

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-02-26T17:53:31" version="0.9.14-dev-809d327">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001778985142">
                        <staffGrp xml:id="staffgrp-0000000861327639">
                            <staffDef xml:id="staffdef-0000000146364246" clef.shape="G" clef.line="2" meter.count="6" meter.unit="8" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001542401168">
                        <measure xml:id="measure-L3" n="1" right="dbl">
                            <staff xml:id="staff-L3F1N1" n="1">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <beam xml:id="beam-L4F1-L8F1">
                                        <note xml:id="note-L4F1" dur="8" oct="4" pname="c">
                                            <accid xml:id="accid-L4F1" accid.ges="n" />
                                        </note>
                                        <tuplet xml:id="tuplet-0000001347201366" num="0" numbase="0" bracket.visible="true" num.format="count">
                                            <note xml:id="note-L5F1" dur="16" oct="4" pname="d">
                                                <accid xml:id="accid-L5F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L6F1" dur="16" oct="4" pname="e">
                                                <accid xml:id="accid-L6F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L7F1" dur="16" oct="4" pname="f">
                                                <accid xml:id="accid-L7F1" accid.ges="n" />
                                            </note>
                                        </tuplet>
                                        <note xml:id="note-L8F1" dur="8" oct="4" pname="g">
                                            <accid xml:id="accid-L8F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                    <beam xml:id="beam-L9F1-L13F1">
                                        <tuplet xml:id="tuplet-0000000433746232" num="3" numbase="2" bracket.visible="false" num.format="count">
                                            <note xml:id="note-L9F1" dur="16" oct="4" pname="a">
                                                <accid xml:id="accid-L9F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L10F1" dur="16" oct="4" pname="b">
                                                <accid xml:id="accid-L10F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L11F1" dur="16" oct="5" pname="c">
                                                <accid xml:id="accid-L11F1" accid.ges="n" />
                                            </note>
                                        </tuplet>
                                        <note xml:id="note-L12F1" dur="8" oct="5" pname="d">
                                            <accid xml:id="accid-L12F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L13F1" dur="8" oct="5" pname="e">
                                            <accid xml:id="accid-L13F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                        <scoreDef xml:id="scoredef-0000000161917173" meter.count="3" meter.unit="8" />
                        <measure xml:id="measure-L14" n="2">
                            <staff xml:id="staff-L14F1N1" n="1">
                                <layer xml:id="layer-L14F1N1" n="1">
                                    <beam xml:id="beam-L16F1-L20F1">
                                        <note xml:id="note-L16F1" dur="8" oct="4" pname="c">
                                            <accid xml:id="accid-L16F1" accid.ges="n" />
                                        </note>
                                        <tuplet xml:id="tuplet-0000001740250419" num="3" numbase="2" bracket.visible="true" num.format="count">
                                            <note xml:id="note-L17F1" dur="16" oct="4" pname="d">
                                                <accid xml:id="accid-L17F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L18F1" dur="16" oct="4" pname="e">
                                                <accid xml:id="accid-L18F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L19F1" dur="16" oct="4" pname="f">
                                                <accid xml:id="accid-L19F1" accid.ges="n" />
                                            </note>
                                        </tuplet>
                                        <note xml:id="note-L20F1" dur="8" oct="4" pname="g">
                                            <accid xml:id="accid-L20F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L21" n="3" right="end">
                            <staff xml:id="staff-L21F1N1" n="1">
                                <layer xml:id="layer-L21F1N1" n="1">
                                    <beam xml:id="beam-L22F1-L26F1">
                                        <tuplet xml:id="tuplet-0000002097708730" num="3" numbase="2" bracket.visible="false" num.format="count">
                                            <note xml:id="note-L22F1" dur="16" oct="4" pname="a">
                                                <accid xml:id="accid-L22F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L23F1" dur="16" oct="4" pname="b">
                                                <accid xml:id="accid-L23F1" accid.ges="n" />
                                            </note>
                                            <note xml:id="note-L24F1" dur="16" oct="5" pname="c">
                                                <accid xml:id="accid-L24F1" accid.ges="n" />
                                            </note>
                                        </tuplet>
                                        <note xml:id="note-L25F1" dur="8" oct="5" pname="d">
                                            <accid xml:id="accid-L25F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L26F1" dur="8" oct="5" pname="e">
                                            <accid xml:id="accid-L26F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
This is no Verovio problem as `@num="0"` and `@numbase="0"` isn't valid MEI. 
Perhaps this should be ruled out in LibMEI?

**Comment by craigsapp** [comment]
The problem is not in the input, but in the strange behavior when dealing with the input.

**Comment by lpugin** [comment]
Strange behaviour indeed. But strange data too....

**Comment by pe-ro** [comment]
`@num` and `@numbase` are required to be positive integers; that is, integers greater than 0.  Just one of the many benefits of validation.  😀

**Comment by rettinghaus** [comment]
@craigsapp I don't get it. Is this a MEI i/o errror or does this come from Humdrum? 

If the values get smaller than one NONE should be set. This will produce a fine output:
![false](https://cloud.githubusercontent.com/assets/7693447/23375331/3f5793b8-fd28-11e6-9ba8-3db56a12adcf.png)

**Comment by craigsapp** [comment]
> @craigsapp I don't get it. Is this a MEI i/o error or does this come from Humdrum?
> If the values get smaller than one NONE should be set. This will produce a fine output:

It was a degenerate case in the Humdrum converter (which is now fixed).  For some reason the tuplet scaling was not set or set set to 0 for some strange reason when it should have been 1 (for 3 against 2 as opposed to 6 against 4).

**Comment by craigsapp** [comment]
> `@num` and `@numbase` are required to be positive integers; that is, integers greater than 0. Just one of the many benefits of validation. 😀

Verovio does not have a built in validator, so it should do some protection against input which will corrupt the notation.  This is a case where the notation becomes corrupted, and the sequence of notes in the layer should not be altered due to the bad input.

Here is a recently discussed case where verovio will deal with invalid MEI data, but the notation will not be corrupted (just perverted :-):   issue https://github.com/rism-ch/verovio/issues/482

**Comment by pe-ro** [comment]
How difficult would it be to validate the file before attempting to render it?

**Comment by craigsapp** [comment]
> How difficult would it be to validate the file before attempting to render it?

It is more about time: How long does it take to validate?  Finale validates MusicXML files before loading them, but it loads MusicXML files not so fast.  What proportion of time is related to validation, and what proportion to translation into its internal format?

A second consideration is interactive editing with verovio.   After Finale/Sibelius/MuseScore loads a MusicXML file, it is no longer validates the data loaded into the editor.  If an interactive change is made to MEI data with verovio, does the entire file need to be validated before rendering to SVG again?

**Comment by pe-ro** [comment]
I meant that validation should take place when the MEI file is loaded. Of course, the time needed to validate the XML depends on the size and complexity of the file.  Skipping validation in the interest of time is a false economy -- the errors will just have to be ferreted out and dealt with at a later point.  Presumably, Verovio won't mess up its own data, so validation before rendering isn't necessary.

**Comment by craigsapp** [comment]
> Verovio won't mess up its own data.

How would verovio know what is valid data for interactive applications?

For example, here is a demonstration of editing the MEI data via JavaScript and the output SVG.  First I click on the note, then I keep pressing shift - ⬇️ to transpose it down an octave:

![bassoprofundo](https://cloud.githubusercontent.com/assets/3487289/23386105/679bff36-fd09-11e6-856f-326586ef5862.gif)

I actually limit to about C-1 or so, but I removed the limitation for the demo (same goes for high notes).

**Comment by pe-ro** [comment]
I would expect there to be limits on what pitch/octave can be created using the interactive editor.

**Comment by craigsapp** [comment]
> I would expect there to be limits on what pitch/octave can be created using the interactive editor.

But where does the limit come from?  The easiest is a hard coded value, but is there a generalized way to set it from the limit in a schema?


Finale has never had a limit:

<img width="624" alt="screen shot 2017-02-27 at 6 43 38 pm" src="https://cloud.githubusercontent.com/assets/3487289/23389445/da852fdc-fd1c-11e6-823b-925d4106a9cd.png">

But when I export this as MusicXML, here is what the note element says:

```xml
      <note default-x="86">
        <pitch>
          <step>D</step>
          <?DoletFinale Invalid octave value -30 clamped to 0?>
          <octave>0</octave>
        </pitch>
        <duration>8</duration>
        <voice>1</voice>
        <type>whole</type>
      </note>
```

So MusicXML probably limits the range, but the exporter sneaks in the invalid value as a preprocessor instruction.  Loading the file back into Finale will ignore the preprocessor note:

<img width="803" alt="screen shot 2017-02-27 at 6 47 47 pm" src="https://cloud.githubusercontent.com/assets/3487289/23389523/4a49ae10-fd1d-11e6-9a03-379605f2812c.png">

Humdrum allows any range, but I am limiting to the musical range of 10 octaves in the conversion to MEI.

**Comment by pe-ro** [comment]
> The easiest is a hard coded value, but is there a generalized way to set it from the limit in a schema?

I'm not certain I understand what you mean.  The schema is a just a text file so reading it and applying the values there shouldn't be particularly difficult, but as far as I know, it would require writing the necessary code.

**Comment by craigsapp** [comment]
> The schema is a just a text file so reading it and applying the values there shouldn't be particularly difficult, but as far as I know, it would require writing the necessary code.

Schemas are for documents, but are they used in applications as well, such as TEI applications?  For example would someone use an XPath query to extract range or data types from a schema or ODD document?

**Comment by pe-ro** [comment]
I can't point to an example off the top of my head, but there's no reason why a schema can't function as a kind of "configuration file" for an application.  Since the source file/ODD for MEI and the RNG schema are both XML, XPath against either one would be fine.
