### ISSUE TITLE
Install doesn't work on Windows

### ISSUE THREAD

**Issue by misingnoglic** [rism-ch/verovio#490]
Hello,

I'm trying to install verovio on Windows, and when I run the command
`python setup.py build_ext
`

Or the command:

`python setup.py build_ext
`
I get this issue:
`../include/hum\humlib.h(80): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2`

Any idea how to fix this?

**Comment by craigsapp** [comment]
Hmm.

On line 77 of include/hum/humlib.h change the line:
```cpp
#define USING_URI 1
```
to
```
#define USING_URI 0
```
or best, delete the line.

That line should not be there (I was probably using for debugging).  That define sets up code which will only run in linux.   I'll remove it from the `develop-humlib` branch.

@lpugin: is there also a way to disable humdrum in the python build of verovio?

**Comment by misingnoglic** [comment]
Now I'm getting this, is it related?

`toolkit.obj : error LNK2001: unresolved external symbol "public: bool __thiscall hum::Tool_musicxml2hum::convert(class std::basic_ostream<char,struct std::char_traits<char> > &,class pugi::xml_document &)" (?convert@Tool_musicxml2hum@hum@@QAE_NAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAVxml_document@pugi@@@Z)
toolkit.obj : error LNK2001: unresolved external symbol "public: __thiscall hum::Tool_musicxml2hum::Tool_musicxml2hum(void)" (??0Tool_musicxml2hum@hum@@QAE@XZ)
build\lib.win32-3.6\_verovio.cp36-win32.pyd : fatal error LNK1120: 2 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120`

**Comment by craigsapp** [comment]
The problem seems to be that the file for the Tool_musicxml2hum class is not include in the python setup file.

The easiest thing to do is probably to change these lines in `verovio/python/setup.py`:

```python
EXTRA_COMPILE_ARGS = ['-DPYTHON_BINDING']
if platform.system() != 'Windows':
    EXTRA_COMPILE_ARGS += ['-std=c++11', '-Wno-write-strings', '-Wno-overloaded-virtual', '-Wno-unused-private-field']
else:
    EXTRA_COMPILE_ARGS += ['-DNO_PAE_SUPPORT']
```

To the following  (adding the last line):

```python
EXTRA_COMPILE_ARGS = ['-DPYTHON_BINDING']
if platform.system() != 'Windows':
    EXTRA_COMPILE_ARGS += ['-std=c++11', '-Wno-write-strings', '-Wno-overloaded-virtual', '-Wno-unused-private-field']
else:
    EXTRA_COMPILE_ARGS += ['-DNO_PAE_SUPPORT']
    EXTRA_COMPILE_ARGS += ['-DNO_HUMDRUM_SUPPORT']
```

Alternatively, adding missing files to the sources variable is needed (I'll test out both right now).

**Comment by misingnoglic** [comment]
Thank you! Adding that line worked for me.

**Comment by craigsapp** [comment]
Can't really be closed until all new files in `include/hum` and `src/hum` are added to setup.py (probably by adding a glob for code in those directories) and/or adding `-DNO_HUMDRUM_SUPPORT` (ideally as an optional flag either on or off by default).

**Comment by lpugin** [comment]
ok
