### ISSUE TITLE
Toolkit not working properly on Python/Windows

### ISSUE THREAD

**Issue by misingnoglic** [rism-ch/verovio#491]
Hello,
When I try to run the startup code, here is the error I get:

```
PS C:\Users\misin> python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import verovio
>>> tk = verovio.toolkit()
[Error] Font directory '/usr/local/share/verovio/Bravura' cannot be read
[Error] Bravura font could not be loaded.
[Error] Font directory '/usr/local/share/verovio/Leipzig' cannot be read
[Error] Leipzig font could not be loaded.
[Error] Expected 197 default SMUFL glyphs but could load only 0.
>>> tk.loadFile("01_durations.mei")
```
After I run that last command, Python crashes on Powershell, and just prints False on the CMD. I assume it's because '/usr/local/...' is not a folder on Windows.

**Comment by craigsapp** [comment]
The compile instructions (for the terminal) on the page:
https://github.com/rism-ch/verovio/wiki/Building-instructions#building-the-python-toolkit
doesn't mention fonts, and in particular for Windows, where there will not be in `/usr/local/share/verovio`

This is related to issue #111, perhaps @sonovice can comment on fonts for Windows/Python setup?

The solution on that page for specifying the font path manually is:

```python
   tk = verovio.toolkit( False )
   tk.setResourcePath( "/absolute/path/to/the/dir" )
```

But it looks like there might still be problems with that solution.

**Comment by misingnoglic** [comment]
I think there might also be an issue with paths on windows?
Here is my code and the response
`>>> tk.setResourcePath("OneDrive\Documents\GitHub\verovio\data")
[Error] Font directory 'OneDrive\Documents\GitHuberovio\data/Bravura' cannot be read
[Error] Bravura font could not be loaded.
[Error] Font directory 'OneDrive\Documents\GitHuberovio\data/Leipzig' cannot be read
[Error] Leipzig font could not be loaded.
[Error] Expected 197 default SMUFL glyphs but could load only 0.
False`

**Comment by sonovice** [comment]
> `tk.setResourcePath("OneDrive\Documents\GitHub\verovio\data")`

This is most probably not a valid path. The OneDrive folder is usually placed in your own user profile directory, e.g. "C:\Users\misingnoglic\OneDrive". Try to prepend this to your path.

**Comment by misingnoglic** [comment]
When I open the REPL, I am in C:\Users\misingnoglic, so "OneDrive\Documents\GitHub\verovio\data" is a valid path

I realized the error though. I think in windows, the \ slash is some kind of escape, so I just made it a raw string. 
tk.setResourcePath(r"OneDrive\Documents\GitHub\verovio\data")

Thank you, and sorry about that!

**Comment by sonovice** [comment]
The backslash is not Windows specific. It's just the escape symbol for special characters in python strings. You could also replace them by double backslashes: "\\"

**Comment by fosfrancesco** [comment]
Even when setting the "/absolute/path/to/the/dir" verovio still put a slash (not backslash) before the name of the font, so it will not work.
Example: `\Desktop\verovio\fonts\/Bravura`
