### ISSUE TITLE
Hide an entire parts/stem/staff in the svg, including hairpin

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#493]
I wish to hide and show individual parts/stem/staff of the svg file, this with the help of eg jquery.

I found this example and it's a part of the way, http://www.verovio.org/gh-tutorial/topic03-highlighting.html

The issue is to hide and show hairpin nodes, there's no information in the svg wich staff the hairpin belongs to.

I'm missing something?

**Comment by lpugin** [comment]
No, you are not missing anything. If you look at MEI you will see that a hairpin does not belong to a staff. This is preserved in the SVG. Also, one hairpin can apply to multiple staves. See for example the last example at the bottom here http://www.verovio.org/features.xhtml?id=dynams-hairpins

**Comment by k-ljung** [comment]
My source is a MusicXML file and what I can see from the file there is a relation to a `<part>`, but I guess this relatin is discared when converting from MusicXML to MEI?

I also have texts above some of the staff but again, in the svg there's no relation.

In the current Verovio implementation, is there any chance I can achive my goal to hide or show different staff in the svg?

Unless mei format supports it, it would be great if Verovio handle it if the source is a MusicXML, one solution is to add an attribute that links contents to staff, although this would create a heavier svg.

**Comment by rettinghaus** [comment]
You can do it with the MEI you'll get from converting MusicXML. Control elements (like dynamics and directives) all carry a `@staff`. From there you get the corresponding IDs for hiding the SVG elements.

**Comment by k-ljung** [comment]
@rettinghaus, there is no link between hairpin and staff in the MEI file.

**Comment by craigsapp** [comment]
> there is no link between hairpin and staff in the MEI file.

There has to be a `@staff` for hairpins; otherwise, it could not be displayed.  You are probably meaning that in the SVG, there is no link from the dynamic to the staff.

Example:

<img width="401" alt="screen shot 2017-03-01 at 6 41 53 am" src="https://cloud.githubusercontent.com/assets/3487289/23464527/361903a4-fe4a-11e6-8fb5-3b94fbc485c2.png">

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-03-01T06:41:42" version="0.9.14-dev-fab327f">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001955716613">
                        <staffGrp xml:id="staffgrp-0000001418711150" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-0000000745509843" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
                            <staffDef xml:id="staffdef-0000001752855942" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001117760840">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F3N1" n="1">
                                <layer xml:id="layer-L3F3N1" n="1">
                                    <note xml:id="note-L4F3" dur="1" oct="5" pname="e">
                                        <accid xml:id="accid-L4F3" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L3F1N1" n="2">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="1" oct="4" pname="c">
                                        <accid xml:id="accid-L4F1" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <hairpin xml:id="hairpin-0000001743014698" staff="2" tstamp="1.000000" tstamp2="1m+1.0" form="cres" />
                        </measure>
                        <measure xml:id="measure-L5" right="end">
                            <staff xml:id="staff-L5F3N1" n="1">
                                <layer xml:id="layer-L5F3N1" n="1">
                                    <note xml:id="note-L6F3" dur="1" oct="4" pname="b">
                                        <accid xml:id="accid-L6F3" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L5F1N1" n="2">
                                <layer xml:id="layer-L5F1N1" n="1">
                                    <note xml:id="note-L6F1" dur="1" oct="4" pname="d">
                                        <accid xml:id="accid-L6F1" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

SVG:

```xml
<svg width="288px" height="186px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="visible">
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E084" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -78c84 97 114 180 134 329h170c-13 -32 -82 -132 -99 -151l-84 -97c-33 -36 -59 -63 -80 -81h162v102l127 123v-225h57v-39h-57v-34c0 -43 19 -65 57 -65v-34h-244v36c48 0 60 26 60 70v27h-203v39z" />
		</symbol>
		<symbol id="E0A2" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M198 133c102 0 207 -45 207 -133c0 -92 -98 -133 -207 -133c-101 0 -198 46 -198 133c0 88 93 133 198 133zM293 -21c0 14 -3 29 -8 44c-7 20 -18 38 -33 54c-20 21 -43 31 -68 31l-20 -2c-15 -5 -27 -14 -36 -28c-4 -9 -6 -17 -8 -24s-3 -16 -3 -27c0 -15 3 -34 9 -57 s18 -41 34 -55c15 -15 36 -23 62 -23c4 0 10 1 18 2c19 5 32 15 40 30s13 34 13 55z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam {font-style:italic;}</style>
	<svg id="definition-scale" viewBox="0 0 7220 4670">
		<g class="page-margin" transform="translate(200, 200)">
			<g class="system" id="system-0000000268651600">
				<path d="M15 1145 L15 3530" stroke="#000000" stroke-width="30" />
				<path d="M-30,3510 C-390,2970 60,2518 -210,2338 C125,2518 -325,2970 -30,3510" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="20" />
				<path d="M-30,1165 C-325,1705 125,2158 -210,2338 C60,2158 -390,1705 -30,1165" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="20" />
				<g class="section boundaryStart" id="section-0000001117760840" />
				<g class="measure" id="measure-L3">
					<g class="staff" id="staff-L3F3N1">
						<path d="M0 1145 L3063 1145" stroke="#000000" stroke-width="20" />
						<path d="M0 1325 L3063 1325" stroke="#000000" stroke-width="20" />
						<path d="M0 1505 L3063 1505" stroke="#000000" stroke-width="20" />
						<path d="M0 1685 L3063 1685" stroke="#000000" stroke-width="20" />
						<path d="M0 1865 L3063 1865" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000002102430122">
							<use xlink:href="#E050" x="45" y="1685" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000000497760695">
							<use xlink:href="#E084" x="690" y="1325" height="720px" width="720px" />
							<use xlink:href="#E084" x="690" y="1685" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F3N1">
							<g class="note" id="note-L4F3">
								<use xlink:href="#E0A2" x="1298" y="1235" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="staff" id="staff-L3F1N1">
						<path d="M0 2810 L3063 2810" stroke="#000000" stroke-width="20" />
						<path d="M0 2990 L3063 2990" stroke="#000000" stroke-width="20" />
						<path d="M0 3170 L3063 3170" stroke="#000000" stroke-width="20" />
						<path d="M0 3350 L3063 3350" stroke="#000000" stroke-width="20" />
						<path d="M0 3530 L3063 3530" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000000252057721">
							<use xlink:href="#E050" x="45" y="3350" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000001704461387">
							<use xlink:href="#E084" x="690" y="2990" height="720px" width="720px" />
							<use xlink:href="#E084" x="690" y="3350" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F1N1">
							<g class="note" id="note-L4F1">
								<path d="M1286 3710 L1610 3710" stroke="#000000" stroke-width="20" />
								<use xlink:href="#E0A2" x="1298" y="3710" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="hairpin" id="hairpin-0000001743014698">
						<polygon points="1448,4005 3453,4140 3453,4120 1448,3985 " />
						<polygon points="1448,4005 3453,3870 3453,3850 1448,3985 " />
					</g>
					<g class="barLineAttr" id="bline-0000000384770431">
						<path d="M3048 1145 L3048 3530" stroke="#000000" stroke-width="30" />
					</g>
				</g>
				<g class="measure" id="measure-L5">
					<g class="staff" id="staff-L5F3N1">
						<path d="M3063 1145 L5098 1145" stroke="#000000" stroke-width="20" />
						<path d="M3063 1325 L5098 1325" stroke="#000000" stroke-width="20" />
						<path d="M3063 1505 L5098 1505" stroke="#000000" stroke-width="20" />
						<path d="M3063 1685 L5098 1685" stroke="#000000" stroke-width="20" />
						<path d="M3063 1865 L5098 1865" stroke="#000000" stroke-width="20" />
						<g class="layer" id="layer-L5F3N1">
							<g class="note" id="note-L6F3">
								<use xlink:href="#E0A2" x="3303" y="1505" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="staff" id="staff-L5F1N1">
						<path d="M3063 2810 L5098 2810" stroke="#000000" stroke-width="20" />
						<path d="M3063 2990 L5098 2990" stroke="#000000" stroke-width="20" />
						<path d="M3063 3170 L5098 3170" stroke="#000000" stroke-width="20" />
						<path d="M3063 3350 L5098 3350" stroke="#000000" stroke-width="20" />
						<path d="M3063 3530 L5098 3530" stroke="#000000" stroke-width="20" />
						<g class="layer" id="layer-L5F1N1">
							<g class="note" id="note-L6F1">
								<use xlink:href="#E0A2" x="3303" y="3620" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000001732422459">
						<path d="M4933 1145 L4933 3530" stroke="#000000" stroke-width="30" />
						<path d="M5053 1145 L5053 3530" stroke="#000000" stroke-width="90" />
					</g>
				</g>
				<g class="boundaryEnd section-0000001117760840" id="bdend0000000463322519" />
			</g>
		</g>
	</svg>
</svg>
```

Here is a highlight of the first `<measure>`:

<img width="408" alt="screen shot 2017-03-01 at 6 43 18 am" src="https://cloud.githubusercontent.com/assets/3487289/23464586/718db812-fe4a-11e6-8b96-7e1ef0e0ca92.png">

Here is a highlight of the second staff in the first measure:

<img width="408" alt="screen shot 2017-03-01 at 6 44 48 am" src="https://cloud.githubusercontent.com/assets/3487289/23464648/a05a3102-fe4a-11e6-9461-3b0bdd1f514a.png">

Notice that this selection does not include the hairpin dynamic since it is outside of the `<staff>` element:

```xml
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F3N1" n="1">
                                <layer xml:id="layer-L3F3N1" n="1">
                                    <note xml:id="note-L4F3" dur="1" oct="5" pname="e">
                                        <accid xml:id="accid-L4F3" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L3F1N1" n="2">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="1" oct="4" pname="c">
                                        <accid xml:id="accid-L4F1" accid.ges="n" />
                                    </note>
                                </layer>
                            </staff>
                            <hairpin xml:id="hairpin-0000001743014698" staff="2" tstamp="1.000000" tstamp2="1m+1.0" form="cres" />
                        </measure>
```

In this case the `<hairpin>` has an attribute `staff="2"` that means it should be placed on staff 2.  However, in the SVG, there is no indication of which staff the hairpin belongs to:

```xml
    <g class="measure" id="measure-L3">
     <g class="staff" id="staff-L3F3N1">
      <g class="clef" id="clef-0000002102430122"/>
      <g class="meterSig" id="msig-0000000497760695"/>
      <g class="layer" id="layer-L3F3N1">
       <g class="note" id="note-L4F3"/>
      </g>
     </g>
     <g class="staff" id="staff-L3F1N1">
      <g class="clef" id="clef-0000000252057721"/>
      <g class="meterSig" id="msig-0000001704461387"/>
      <g class="layer" id="layer-L3F1N1">
       <g class="note" id="note-L4F1">
       </g>
      </g>
     </g>
     <g class="hairpin" id="hairpin-0000001743014698"/>
     <g class="barLineAttr" id="bline-0000000384770431"/>
   </g>
```

In MEI, elements such as the hairpin can belong to multiple staves, so that is why they are not placed inside of a staff element.  What you are wanting could be accomplished by adding staff information to the class attributes:

```xml
    <g class="measure" id="measure-L3">
     <g class="staff staff1" id="staff-L3F3N1">
      <g class="clef" id="clef-0000002102430122"/>
      <g class="meterSig" id="msig-0000000497760695"/>
      <g class="layer" id="layer-L3F3N1">
       <g class="note" id="note-L4F3"/>
      </g>
     </g>
     <g class="staff staff2" id="staff-L3F1N1">
      <g class="clef" id="clef-0000000252057721"/>
      <g class="meterSig" id="msig-0000001704461387"/>
      <g class="layer" id="layer-L3F1N1">
       <g class="note" id="note-L4F1">
       </g>
      </g>
     </g>
     <g class="hairpin staff2" id="hairpin-0000001743014698"/>
     <g class="barLineAttr staff1 staff2" id="bline-0000000384770431"/>
   </g>
```

Then selection of the elements could be done from the `staff2` in the class attribute.  You would have to decide to include or exclude the barline which is attached to both staff1 and staff2.

**Comment by craigsapp** [comment]
Also note that the barline between the two staves in the example is a single line.  What is that supposed to do with one of the staves is hidden?  If you want it to change shape, then that probably means you should not be manipulating the SVG, but rather the MEI should be manipulated before creating the SVG image.

You would do that on the command line by first creating MEI data:

```bash
$ verovio music.xml -t mei --all-pages --no-layout
```

Then you would filter out `<staff n="2">` and floating elements which have `staff=2` attributes before running through verovio again:

```bash
$ verovio music.mei
```

How to filter out the data is left as an exercise for the reader :-).  XPath processing in some language or tool would be the most obvious method.
    http://stackoverflow.com/questions/15461737/how-to-execute-xpath-one-liners-from-shell

This won't work if you need the two staves to be aligned in the separate SVG generations.  But using the linear spacing option in verovio might get it close.

**Comment by rettinghaus** [comment]
Just noticed that `@staff` was missing on hairpins in MusicXML import, added that quickly in #498

But `@staff ` will not be set on slurs as they can start on one staff and end on another. To be sure to filter out all elements connected to a specific staff you would have to check where those `@startid`s and `@endid`s originate from.

**Comment by craigsapp** [comment]
It would be good for @pe-ro to comment on why floating elements should be given at the `<measure>` level and can't be given at the `<staff>` level.  If a floating element is attached to a single staff, then it would be better to place it inside the given `<staff>` rather than floating in the measure with `@staff`:

```xml
   <measure>
        <staff n="1">
             <layer/>
        </staff>
        <hairpin staff="1"/>
    </measure>
```

would be more logical as:

```xml
   <measure>
        <staff n="1">
             <layer/>
            <hairpin/>
        </staff>
    </measure>
```

Otherwise it is difficult to extract parts from MEI data, since the staff membership can be indirectly assigned via `@startid`.

floating elements at the measure level could be then be reserved for elements which refer to more than one staff or apply to all staves.

```xml
   <measure>
        <staff n="1">
             <layer/>
        </staff>
        <staff n="2">
            <layer/>
        </staff>
        <hairpin staff="1 2"/>
    </measure>
```

**Comment by pe-ro** [comment]
Slurs that remain on a single staff are a subset of all slurs, meaning that all slurs (staff-crossing or not) are handled the same way.

**Comment by craigsapp** [comment]
In MEI is it time-consuming to locate floating elements for a particular staff because they are all mixed into a flat list as part of the measure.  Programmatically you have to search through all elements in the measure to find the ones that apply to a particular staff. 

This is most noticeable with ties, and why verovio-to-MIDI still does not implement ties after almost one year...

In MusicXML (and Humdrum), a tie is a property of notes, so triggering a lookup procedure to deal with a tie can be done at the same time as processing notes rather than as a separate process.

---------------

A sub-question/comment is why are floating elements allowed to be direct children of measure rather than having a container for them such as `<floating>`?  This would make xpath location of the floating elements and staves easier and more efficient.  Currently floating elements can come before or after staff elements in a measure, so all children of `<measure>` have to be searched to find the list of floating elements for the measure.

**Comment by lpugin** [comment]
@craigsapp is right that the best way to handle this is to extract / hide the content you want before passing it to verovio. However, you will achieve this quite likely with XSLT and not XPath ;-)

There is an example on how to achieve this here http://www.verovio.org/tutorial.xhtml?id=topic08

**Comment by lpugin** [comment]
> This is most noticeable with ties, and why verovio-to-MIDI still does not implement ties after almost one year...

Who would need this :-) ?

**Comment by craigsapp** [comment]
> However, you will achieve this quite likely with XSLT and not XPath ;-)

Yes, considering `@startid` complications,  XPath is not possible.  I would use PugiXML :-)

**Comment by craigsapp** [comment]
> Who would need this :-) ?

I don't notice anymore, so not me :-)

I fixed the double sharp-flat exports as those were driving me crazy(er) 😈

**Comment by k-ljung** [comment]
This was a long discussion... :)

What I want to accomplish is to hide and show parts dynamically based on a server side generated SVG, to filter out this from mei file and then create SVG is not a solution that would work for me.

I need to dig deeper into this discussion to see if I can make som post processing on the svg.

**Comment by craigsapp** [comment]
> What I want to accomplish is to hide and show parts dynamically based on a server side generated SVG, to filter out this from mei file and then create SVG is not a solution that would work for me

It will not be easy to post-process the SVG to do what you want, even if the class="staff1" sort of system I described above is implemented.  Take for example the barline in my test case: That is a single line which crosses through both staves.  If your musical parts are not connected with barlines to each other, then that solves most of the problem, but there is also the barline at the beginning of the system plus any brackets or brackets which form a single unit.

A special case option could be done to overlay a `rect` with the background color to obscure a part.  The size of the box could be inferred from the positions of the staff lines (making the overlay box go 1/2 of the way to the next staff.  Or the positions of the `rects` could be determined manually if you do not have dynamic content (it would work unless you regenerate the SVG with a different layout).

This solution would be similar that at http://partifi.org/howto, where parts are extracted via cut-and-paste semi-automatically from PDFs of scanned music.

**Comment by pe-ro** [comment]
If you're looking to record a tie as a property of a note or chord, use `@tie`.

Looking for control events in a measure is easy if you're willing to enumerate all the possibilities. For example,
```
//measure/(arpeg, dynam, hairpin, line, octave, tempo, trill)
```
If not, then turn the XPath around; that is, look for elements other than `<staff>`.  For example,
```
//measure/*[not(local-name() eq 'staff')]
```
or, since control events should be linked to a start time or another event via its ID,
```
//measure/*[@startid, @tstamp]
```

Editorial elements like `<add>`, `<app>`, etc. complicate these approaches somewhat because they can have control event descendants, but that complication wouldn't be alleviated by the addition of `<floating>`.

Finding these elements associated with a particular staff isn't hard, for example 
```
//measure/(arpeg, dynam, hairpin, line, octave, tempo, trill)[number(@staff) = 1]
```
```
//measure/*[not(local-name() eq 'staff')][number(@staff) = 1]
```
```
//measure/*[@startid, @tstamp][number(@staff) = 1]
```

**Comment by lpugin** [comment]
Additionally, it is easy to have access to any attribute value from Verovio. 
http://www.verovio.org/tutorial.xhtml?id=topic05

So it is straightforward to check from the SVG to what staff a hairpin applies by looking at its `@staff` attribute. With all this you should be able to achieve what you want
