### ISSUE TITLE
Continuous Integration (and pip)

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#495]
Seeing #491 I thought about making verovio installable via pip for the python version. Thing is, someone would have to maintain this and build windows, mac and unix versions every now and then. Maybe this would be a nice starting point to include continuous integration and testing via Travis CI and AppVeyor.

Any thoughts on that?

**Comment by lpugin** [comment]
Thanks for this. What would it involve more precisely? I am not against it but I feel that it is a bit over the top and that improving the documentation and the wiki would be a more appropriate way to improve the situation. Since I do not have experience with this I would be glad to hear other opinions on it.

**Comment by sonovice** [comment]
Actually setting up a CI pipeline is pretty straight forward: One just hast to configure the build and test process. This is usually done with a YAML configuration file in the root of the repo. I can look into this for verovio (already done for windows).

Here is my sort of dream scenario:
- All git pushes are continuously build and tested. Failures can be automatically send or posted etc. to detect OS incompatibility problems faster
- Changes to the master branch are be build and released automatically for win, osx and unix
- Same applies to python builds for pip

**Comment by misingnoglic** [comment]
I would definitely really appreciate having the toolkit on pip =)

**Comment by lpugin** [comment]
Please make a PR is this is desired
