### ISSUE TITLE
Beam placement needs an overhaul

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/verovio#50]
medium-high violation: Beam placement in verovio will need a major overhaul sometime. I highlighted the two main bad ones on the page in the first measure of the 1st violin and viola parts. Tom Brodhead has the best implementation of automatic beam placement as a plugin program for SCORE. See the sample SCORE generated equivalent further below for how they were placed using his program. He implemented the algorithms in Ted Ross's notation book. Behind Bars also has a lengthly discussion of beams on pp. 17-26 (and also elsewhere in the book for other issues for beams). For example the marked viola beam violates the maximum angle rule mid-page on p20 as well as the requirement for a horizontal beam in this case from the guidlines midpage on p. 23.

**Comment by lpugin** [comment]
Improved in version 0.9.6, closing for now
