### ISSUE TITLE
mdiv selection

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#509]
Multiple-movement input to verovio was discussed in the issues somewhere, but I can't find them at the moment.

If verovio does not permit rendering multiple movements one time, it would be useful to add an mdiv selection option.

Such as for the command-line interface:

```bash
verovio input.mei --mdiv 3
```

for the third `<mdiv>` found in the children of the `<score>` element.

It might also be useful to have an option which reports how many mdivs are present in the data, such as:

```bash
verovio input.mei --count-mdiv
```

which would return "5" if there are five mdivs at the `<scores>` level.

Implementing for JavaScript, it would probably be best if verovio throws away the other mdivs as it loads the MEI data (so that it does not over-flow memory allocated by emscripten).  That might be complicated or not possible unless PugiXML has a way of not storing pieces of the XML tree structure as the XML structure is parsed.  Also, the MEI data is first copied into emscripten in full before it is processed (although there is a way of avoiding that) so it would be easy to overflow the memory when dealing with an MEI file containing all movements of a symphony.

But for smaller works such as short melodies, this would be a nice way of avoiding a separate file for 100 short pieces.

**Comment by lpugin** [comment]
Selecting the mdiv is already possible:

```
 --mdiv-xpath-query=QR      Set the xPath query for selecting the <mdiv> to be rendered;
                            only one <mdiv> can be rendered
```

For the count I would suggest to use XPath ;-) Something like `count(//mdiv)`

**Comment by rettinghaus** [comment]
On the other hand it would be good to have a Verovio representation of `mdiv` for importing multiple movements (e.g. from Humdrum).
