### ISSUE TITLE
note@accid creating within verovio

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#510]
Recently being able to creation of `note@accid` has been removed from the verovio library.  Is that correct?  Only `note/accid` can be done now.  Is there a specific reason for that?  MEI data can be still be loaded and processed with `note@accid`, but when converting from Humdrum to MEI internally in verovio, I have to use `note/accid` all of the time now.

Being able to use `note@accid` when the accidental has no special qualifiers that require promoting it to an `accid` element would make the exported MEI data easier to read, and would minimize the memory usage (which might help for larger files in emscripten).

**Comment by lpugin** [comment]
Yes, and the same applies to `note@artic`. If you want to use / export them as attribute you need to do something like:

```cpp
Accid *vrvAccid = new Accid();
vrvAccid->IsAttribute(true);
```

This will not reduce memory usage, but I do not think this is an issue.
