### ISSUE TITLE
Gootville font missing measure numbers

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#516]
The Gootville font is missing measure-number glyphs:

<img width="597" alt="screen shot 2017-03-11 at 11 11 49 am" src="https://cloud.githubusercontent.com/assets/3487289/23826176/bb3319cc-064b-11e7-8ba7-a92086b4ee4f.png">

Compare to the same music typeset with Bravura (or Leipzig):

<img width="597" alt="screen shot 2017-03-11 at 11 12 11 am" src="https://cloud.githubusercontent.com/assets/3487289/23826178/c59891e4-064b-11e7-9520-4a395ae832e6.png">

Either they should be added, or some sort of fall-back system to a font which contains a more complete set of glyphs should be implemented.

**Comment by lpugin** [comment]
Fixed with d7e00761fbb34eebad168963b00965d9b7283231

**Comment by lpugin** [comment]
There is a fall-back system to the Leipzig font
