### ISSUE TITLE
parseFloat/parseInt in JavaScript parameter parsing

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#517]
The JavaScript object that passes parameters to the verovio toolkit:

```javascript
var options = {
     scale: 40
}
```

is expected to use numeric data type for numeric parameters, and strings cannot be used for these parameters.  It would be better to clean these parameters before processing them to make the code more user-proof, such as:

```
var scale = parseFloat(options.scale) || 0;
```
or if the value will only be useful if it is an integer:

```
var width = parseInt(options.pageWidth || defaults.pageWidth);
```

Example using `scale:40`:

<img width="442" alt="screen shot 2017-03-11 at 1 38 50 pm" src="https://cloud.githubusercontent.com/assets/3487289/23827142/89ddc208-0661-11e7-98a2-c2df6ecbd828.png">

and then using `scale:"40"` (which is either displaying as if  scale were set to `0` or `NaN`):

<img width="940" alt="screen shot 2017-03-11 at 1 39 14 pm" src="https://cloud.githubusercontent.com/assets/3487289/23827144/941c90fa-0661-11e7-8868-5f6464762bef.png">

**Comment by lpugin** [comment]
The plain will be to have a JSON schema to check the content of the option object

**Comment by craigsapp** [comment]
See https://github.com/rism-ch/verovio/wiki/Backburner-Issues
