### ISSUE TITLE
The whole rests not aligned rhythmically

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#52]
The whole rests do not get aligned rhythmically with the 3rd beat in 4/4; instead, they are aligned to the center of the measure independent of horizontal rhythmic spacing. The first measure on a staff would use the starting position of the first beat in the measure rather than the system barline to the left of the clef. See Behind Bars p. 159 for centering rule, and bottom of 34 for staff line to attach whole rest (book uses English term semi-breve which is equivalent to American term whole-note).

**Comment by rettinghaus** [comment]
I guess all full bar rests should be aligned to the center of the measure. So for example Rests longer than a whole note. (See first bars of Guami_Canzona_24.mei)

**Comment by craigsapp** [comment]
The JRP style is to use centered breve (double whole note) rests for full-measure rests in music in 2/1 or 3/1:
     http://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Ock1007
(notice some sections in 2/1 and others in 3/1; probably would use centered long rest in 4/1 music, but can't remember if there is any).

The centering is done automatically, but it would be useful to be able to change the centering behavior to rhythmically align with the first beat of the measure as a global style, as well as for individual rests.  For example if barlines were invisible or removed, then the rests should not be centered.  Here is an example of this case in JRP:
     http://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Jos0603b
The tenor part has one measure for each measure in the other parts.  The underlying data encodes the tenor parts with the same measure size and rhythmic scaling as the other parts, but then divides the durations by 2 and hides barlines to generate the graphical display.  Each dotted whole note rest (semi-breve) is filling the measure in the data, but is rhythmically aligned.

Of course an exception to centering all rests filling an entire measure would be the case where the measure does not have the full duration of the current time signature.  For example if a repeat barline splits a regular measure in half, the two partial measures should not have centered rests in them.

**Comment by lpugin** [comment]
I agree the rests should be centered by default. 

Regarding Craig's examples, it seems to be that the first one could be encoded in a measure way, with the exception of the longae that would need to be split into breve. The second one would be easier to encoded in an unmeasured way with &lt;barLine&gt;. In this case, rests would be aligned with their beat position. Does this make sense?

**Comment by lpugin** [comment]
I am not sure what to do with this. Whole measure rests should be encoded as ```mRest```. There are properly centered. To be re-opened with concrete examples if necessary.
