### ISSUE TITLE
[Warning] Parent note for <syl> was not found

### ISSUE THREAD

**Issue by misingnoglic** [rism-ch/verovio#523]
Hello,

I'm back with my windows issues!

I've initialized the toolkit with the code here as follows:
```
    tk = verovio.toolkit( False )
    tk.setResourcePath(r"..\OneDrive\Documents\GitHub\verovio\data")

```   
But when I actually try to load the mei file, I get some varying errors. 

For example, when I try to load [this example](https://github.com/DDMAL/mei-test-set/blob/gh-pages/MEI-test-set/MEI/repeats/da-capo.mei) .mei file, I get all these errors, and then Python crashes...

```
>>> tk.loadFile("da-capo.mei")
[Warning] The file seems to be UTF-16 - trying to convert to UTF-8
[Warning] DarmsInput: Unkown note duration: .
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 6
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: .
[Warning] DarmsInput: Unkown note duration: .
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: .
[Warning] DarmsInput: Unkown note duration: 9
[Warning] DarmsInput: Unkown note duration: 9
[Warning] DarmsInput: Unkown note duration: /
[Warning] DarmsInput: Unkown note duration: /
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 0
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 1
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 2
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 3
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 4
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: e
[Warning] DarmsInput: Unkown note duration: 5
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: e
[Warning] DarmsInput: Unkown note duration: 6
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 7
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: "
[Warning] DarmsInput: Unkown note duration: 1
[Warning] DarmsInput: Unkown note duration: 7
[Warning] DarmsInput: Unkown note duration: 3
[Warning] DarmsInput: Unkown note duration: 3
[Warning] DarmsInput: Unkown note duration: 7
[Warning] DarmsInput: Unkown note duration: 7`
```

When I try to load this other one, which I'm pretty sure is a valid MEI:
`>>> tk.loadFile("vos_pastores.mei")`
Warning: Trying to load unknown XML data which cannot be identified.
[Message] Unsupported format
False`

This menstural MEI is the only one that's worked, but the output comes out really weirdly. 
```
>>> tk.loadFile("vos_pastores_MENSURAL.mei")
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
True

>>> tk.getPageCount()
1
>>> tk.renderToSvgFile("test.svg", 1)
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Justification stop because of a ratio smaller than 0.8
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
[Warning] Parent note for <syl> was not found
True
```
And then it comes out looking like this:
http://svgshare.com/i/yu.svg

Any idea how I could fix these issue?

**Comment by rettinghaus** [comment]
Obviously Verovio can't identify your input files, so you have to tell him
it's MEI.

Am 15.03.2017 3:47 nachm. schrieb "Arya Boudaie" <notifications@github.com>:

**Comment by misingnoglic** [comment]
How do I do that? I don't see it anywhere in the documentation.

**Comment by rettinghaus** [comment]
tk.SetFormat("mei") should do the trick

**Comment by ahankinson** [comment]
It may be a problem with UTF-8 / UTF-16 encoding (Sibelius, annoyingly, will only save in ASCII or UTF-16...).

**Comment by craigsapp** [comment]
> It may be a problem with UTF-8 / UTF-16 encoding (Sibelius, annoyingly, will only save in ASCII or UTF-16...).

Yes, that is the most likely scenario:  The "auto" format assignment algorithm in verovio will not currently identify UTF-16 XML files.  This is because I didn't have a UTF-16 file handy when implementing the "auto" feature, and verovio does not (yet) support UTF-16 files anyway.   When the "auto" algorithm cannot figure out what type of file it is, it is assigned to be "plain & easy" format, so the UTF-16 MEI file was being assigned to that format for loading (which it is not, of course).

The best thing to do is use an external application to convert the UTF-16 files into UTF-8, such as iconv or recode:
    http://stackoverflow.com/questions/265370/utf-16-to-utf-8-conversion-for-scripting-in-windows

**Comment by craigsapp** [comment]
For the mensural notation problem, it is probably related to issue #291, where @lpugin's suggested solution is:

> Cast-off is not implemented with un-measured music. You should use `--no-layout`

**Comment by ahankinson** [comment]
> ... verovio does not (yet) support UTF-16 files anyway.

It must have some basic form of support, since I can export directly from Sibelius and open it in Verovio.

**Comment by ahankinson** [comment]
I'm thinking it might be a Windows-specific problem with encoding, though.

**Comment by ahankinson** [comment]
Usually opening it up in a plain-text editor and saving will change it to UTF-8. If you do that you should change the doctype declaration though.

**Comment by misingnoglic** [comment]
Can you specify what you mean by using --no-layout?

tk.SetFormat("mei") was what I needed before though! Thank you everyone for helping me with this - I just started working with a professor on a project - and your help has been extremely generous =)

**Comment by craigsapp** [comment]
On http://www.verovio.org/python.xhtml:
>Methods
> See the ./include/vrv/toolkit.h file for the toolkit methods (to be further documented).

which is:  https://github.com/rism-ch/verovio/blob/master/include/vrv/toolkit.h

The function names in that file are converted from CamelCase to camelCase when using in Python, with this file:

https://github.com/rism-ch/verovio/blob/master/python/verovio.i


So the option `--no-layout` in command-line world is most likely `tk.setNoLayout(1)` and/or `tk.setNoLayout(True)` in Python world.

**Comment by lpugin** [comment]
PS default auto-detect is now set to MEI

**Comment by craigsapp** [comment]
> PS default auto-detect is now set to MEI

Do you mean that if no SetFormat is given, then the format is "mei" rather than "auto" (or "pae" originally)?  That is good (but not what you said).

Otherwise, setting MEI as the default (fallback) for "auto" does not make sense.  There is not a quick ID for DARMS, so that is why it is the "default" for "auto".

By the way, here is the auto-detect algorithm:

```
XML UTF-8: if starts with <
     search first 600 characters:
          MEI:    if contains "<mei", "<music",  or "<pages"
          MusicXML:  if contains "<score-partwise", "<score-timewise", or "<opus"
PAE: if starts with "@"
Humdrum: if starts with "!" or "*"
DARMS: anything else
```

**Comment by lpugin** [comment]
I see your point but darms is a very low priority and has a very basic support. We could have a basic auto detect with files starting with "K" or "!". If one day somebody works on darms we can improve it.

**Comment by craigsapp** [comment]
> I see your point but darms is a very low priority and has a very basic support. We could have a basic auto detect with files starting with "K" or "!". If one day somebody works on darms we can improve it.

The identification of all data types is active except for DARMS.  Do you want me to make DARMS also active?  I would have to change Humdrum to require "*" or "!!" to allow for "K" and "!" to detect as DARMS.

And passive identifications should probably be disallowed?, so an error should be given something like:
```
    [Error]: Cannot auto-detect input data type, specify it manually.
```

**Comment by lpugin** [comment]
> And passive identifications should probably be disallowed?, so an error should be given something like:  [Error]: Cannot auto-detect input data type, specify it manually.

Yes, this is good. We do not need DARMS unless you really want to add it. Up to you.

**Comment by karend27** [comment]
Hi all - I just wanted to introduce Arya (misingnoglic), who is student at Brandeis, working with me right now on making a website for my fourteenth-century MEI-mensural files,
Karen

**Comment by ahankinson** [comment]
Does anyone use DARMS anymore?

**Comment by craigsapp** [comment]
Frans Wiering probably still uses it :-)  

I was not able to process some DARMS data that I have with verovio (probably a different flavor of DARMS).  So leaving DARMS out of the "auto" feature is good from my point of view as well.   We can consider it a development format that requires an explicit "-f darms" option to activate.
