### ISSUE TITLE
Editing a note on a page other than the last-rendered page

### ISSUE THREAD

**Issue by ahwitz** [rism-ch/verovio#526]
I've been dealing with a weird failure/exception in Vida for a bit where if you drag-edited a note on one page it would sometimes fail the first time and then work every time after. I think I've finally narrowed it down to a block in Toolkit::Drag:
```
1046: Object *element = m_doc.GetDrawingPage()->FindChildByUuid(elementId);
1047: if (element->Is(NOTE)) {
    // ... do things
    return true;
}
return false;
```
https://github.com/rism-ch/verovio/blob/develop/src/toolkit.cpp#L1046

If I understand what's happening correctly, it's assuming that the last page rendered is where the requested edit will occur. In the case where two pages are rendered with Verovio and an edit is requested on the first, it doesn't seem to enter the `if` statement above and thus nothing happens. Because of how Emscripten prints errors, I'm getting a message along the lines of `abort(15)` with little useful debug information, and re-compiling Verovio with `-g3` in the Emscripten line doesn't really help much.

Regardless, replacing `m_doc.GetDrawingPage()->FindChildByUuid` with `m_doc.FindChildByUuid` eliminates the failure, but I have a feeling that this might lead to a bit of performance loss if I submitted a PR with that direct change. Would any of the following solutions be okay/preferred to submit as a PR, or is there a better alternative?

1. If line 1046 above can't find the element, default back to m_doc.FindChildByUUID.
2. If line 1046 above can't find the element, use Toolkit::GetPageWithElement to determine what "the current drawing page" should be.
3. Add an optional "page" property to the `action='drag'` JSON object which, if provided, is passed to `m_view.SetPage` before `Toolkit::Drag` is called.

I can submit a PR with any/all of these if desired, as I know what needs to happen to implement them.

**Comment by lpugin** [comment]
Option 1. looks like a good fix.
