### ISSUE TITLE
include mei header as metadata

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#527]
It could be useful to preserve the complete header in the rendered SVG. That could be done by putting it into a `<metadata>` container like this:
```xml
<svg>
  <metadata>
    <mei:meiHead xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
      <mei:fileDesc>
        …
      </mei:fileDesc>
    </mei:meiHead>
  </metadata>
</svg>
```

This feature should be controllable, although I don't know if it should be switch on or off by default.

**Comment by kepper** [comment]
I would strongly disagree with this, even if it's turned off by default. This seems just like additional payload that you have to carry around on your website, even though you may only need some 10% of that. Headers can become extremely large (I think your Bach files are a good example for that…), and I've seen browsers crying just about the number of music elements in a rendered MEI file (given that it's "printed" on a continuous staff). It seems much more reasonable to me to use some other mechanism to query the original file, instead of a rendered output. That's just not the purpose of a visual rendition of the music…

**Comment by craigsapp** [comment]
> I would strongly disagree with this

It is very good idea, although thoughts about avoiding SVG bloating should be considered, such as options for including only a portion of the header, etc. It also depends on how big the header is, and is all of the information really necessary from a large header -- particularly if it is to be copied onto every single page in the rendering.  Basic information such as the work title, composer, creation date, last edited date of the MEI file, and such would be wise to add at a minimum.

 For purely dynamic images, including the header is not necessary, as the MEI file can be referenced.  But in applications where the data and rendering are disassociated, some sort of this feature would be critical for managing and maintaining the separate SVG and MEI databases.   For example, if someone downloads an SVG image to put on their website, how would a link be made to what the original source file is?

> I've seen browsers crying just about the number of music elements in a rendered MEI file

Mine is happy showing an entire Beethoven sonata movement:

![screen shot 2017-03-22 at 8 55 26 am](https://cloud.githubusercontent.com/assets/3487289/24207205/93d8b7ca-0edd-11e7-8eb8-82a53c8c56d5.png)

On mobile computing platforms this might cause problems, but non-renderedable elements will probably not add rendering complexity and would be ignored when generating graphical objects on the page from the SVG.  


----------------


A related item for discussion is that I embed the entire SCORE data file used to create an SVG when I make SVGs with SCORE.   XML is prone to bloating, but not SCORE data.   As an example case look at the incipits from the Beethoven  moonlight sonata page in wikipedia:

https://en.wikipedia.org/wiki/Piano_Sonata_No._14_(Beethoven)#Adagio_sostenuto

If you click on the image for the first movement opening you get the SVG data (Wikipedia renders the SVG as PNG on the pages for security reasons):

https://en.wikipedia.org/wiki/Piano_Sonata_No._14_(Beethoven)#/media/File:Beethoven_piano_sonata_14_mvmt_1_bar_1-4.svg

If you click again on the image you get to the real SVG image:

https://upload.wikimedia.org/wikipedia/commons/8/80/Beethoven_piano_sonata_14_mvmt_1_bar_1-4.svg

<img width="785" alt="screen shot 2017-03-22 at 9 05 44 am" src="https://cloud.githubusercontent.com/assets/3487289/24207691/c65cb920-0ede-11e7-8afa-88f327141228.png">

Viewing the source of the SVG, and scrolling to the bottom, you will see a Processor Instruction containing the complete SCORE data for generating the image:

![screen shot 2017-03-22 at 9 07 22 am](https://cloud.githubusercontent.com/assets/3487289/24207773/024e3a44-0edf-11e7-9e73-fa35f63627f3.png)

If I need to make a correction to such an image, I can extract the data from the SVG image and make changes.  I do not have to go hunting around for the source data that created the image, and I do not have to worry about which version of the data created the image, etc.

If the SVG is formatted in a particular way, it is also possible to load the SVG directly into SCORE, and SCORE will extract the SCORE data and ignore the SVG elements.


----------------------


I do a similar thing with PDFs that I generate from score.

Consider my edition of Chopin Mazurka in G minor, op. 24/1 on IMSLP:

http://imslp.org/wiki/Mazurkas,_Op.24_(Chopin,_Fr%C3%A9d%C3%A9ric)

If you download the PDF and open in Adobe Acrobat, you will be able to see an attachment to the PDF ("chopi...ppmx") on the upper left:

![screen shot 2017-03-22 at 9 12 37 am](https://cloud.githubusercontent.com/assets/3487289/24208008/b5c18b94-0edf-11e7-9e03-885e0045c1fc.png)

The attached file is a text file, which looks like this if you extract it and open in a text editor:

![screen shot 2017-03-22 at 9 14 43 am](https://cloud.githubusercontent.com/assets/3487289/24208138/145b7bba-0ee0-11e7-9375-51e8f1825727.png)

The data is 41 kB, and the original PDF is 233 kB, so about 20% of the PDF's content (although the data file is probably compressed within the PDF).  The advantage of doing that outweigh the disadvantages of the extra weight, as I do not have to go hunting for the data when a correction is needed.

Also notice that the musical data is sorted in time order, so I can copy measures or systems of data if I want to create a short example from the music without having to re-enter the data.

**Comment by lpugin** [comment]
If people want to do this they can easily post-process the SVG to include whatever they need for their particular project. This will be easy with a simple XSLT.

**Comment by rettinghaus** [comment]
@kepper it's not that I thought about that before. But what data should be extracted from the header? But @lpugin is right: if you want the whole thing in there use XSLT.

**Comment by kepper** [comment]
I could understand (and support) a single pointer to the original file, and a reference to the version of Verovio used to generate the SVG at hand. Everything else should be retrieved from the MEI file, not from the resulting SVG.
