### ISSUE TITLE
Flexible pageWidth in options?

### ISSUE THREAD

**Issue by vonvlaho** [rism-ch/verovio#529]
Is it possible to configure a line never to breake, e.g. with a flexible pageWidth? We're integrating Plaine & Easie Incipits in our Werkverzeichnis and do sometimes have the issue that they autonomously breake the line. Another aspect of this is that every incipit has the same width, even if it's just a few bars long.

```javascript
var options = JSON.stringify({
                scale: 43,
                pageHeight: 5000,
                pageWidth: 2500,
                spacingStaff: 0,
                ignoreLayout: 0,
                border: 0,
                adjustPageHeight: 1
            })
```

Example: http://gluck-gesamtausgabe.local/gwv/werkregister/eintrag/ezio-prag-1750.html

![screenshot](https://cloud.githubusercontent.com/assets/23097270/24204199/0cf3ff36-0f18-11e7-8f52-02c61aa27242.jpg)

**Comment by lpugin** [comment]
Have you tried the `noLayout` option? It will generate one single long system. If I understand correctly this should fit your needs.

**Comment by vonvlaho** [comment]
Works great! Thank you very much 👍
