### ISSUE TITLE
Left align <harm> text

### ISSUE THREAD

**Issue by clubfest** [rism-ch/verovio#531]
For <harm> element representing a chord symbol such as Cmaj7, I would like the first letter, C, to be rendered where the chord actually starts, as specified by the tstamp attribute. It seems that the default behavior is to center align instead of left align, so in this case, the third letter, a, is located where the chord actually starts. Is there an option to left align the chord in verovio?

                    <section>
                        <measure xml:id="measure-000000189673240" n="1" right="end">
                            <harm place="above" staff= "1" tstamp= "1">
                                Cmaj7
                            </harm>
                            <staff xml:id="staff-000000011758963" n="1">
                                <layer xml:id="layer-000000021871880" n="1">
                                        <note xml:id="note-1" dur="1" oct="4" pname="e" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>

**Comment by lpugin** [comment]
Not yet. This should probably be a managed by styling, unless somebody sees a way or a need to handle this at the MEI encoding level?

**Comment by rettinghaus** [comment]
I would expect this to be the "normal" behavior. At least this is the way I know it from printed publications and LilyPond:
![lilychords](https://cloud.githubusercontent.com/assets/7693447/24350526/c83beca4-12e2-11e7-800a-152c766bf4af.png)

Note that it is not aligned like a Tempo indication.

**Comment by craigsapp** [comment]
Yes, it would be nice if the default horizontal alignment of `<harm>` were left-justified to the left side of noteheads at the same `@tstamp`.  

This is necessary for long chord labels.  If they were centered, then the start of the chord label would come too early.

Here is an analysis of a random sample from the web:

http://mattwarnockguitar.com/images/2015/08/Guitar-Chord-Melody-9.gif

![chords](https://cloud.githubusercontent.com/assets/3487289/24362378/6b378d22-12c1-11e7-954c-fbe376b80365.png)

The red line is the left edge of the chord labels, and the green line is approximately the center of the labels.

The horizontal spacing algorithm for chord labels in this example seems to be to (1) try to center the label on the note.  (2) if the left edge of the label crosses over the barline or a note at an earlier `@tstamp`, then shift the label to the right to avoid the crossing.

**Comment by pe-ro** [comment]
I'd suggest that all text-y type stuff (tempo, dir, etc.) be left-aligned at `@tstamp` or the time stamp of the thing pointed to be `@startid`.  When/if `@tstamp2` is provided, then we need a way to say either "center the content between tstamp and tstamp2" or "stretch the content to fit between these points".  I feel another attribute coming on.  😀

**Comment by pe-ro** [comment]
My previous comment doesn't apply to lyric syllables.  Just wanted to get it in while the "gettin' was good". 😀

**Comment by pe-ro** [comment]
Doh!  Actually, `rend/@ho` provides this facility already --
```
<measure xmlns="http://www.music-encoding.org/ns/mei">
  <!-- Without rend/@halign the default is left-alignment -->
  <dir tstamp="1" tstamp2="4">Left-aligned on @tstamp</dir>
  <!-- Explicitly left-aligned -->
  <dir tstamp="1" tstamp2="4">
    <rend halign="left">Left-aligned on @tstamp</rend>
  </dir>
  <dir tstamp="1" tstamp2="4">
    <rend halign="right">Right-aligned on @tstamp2</rend>
  </dir>
  <dir tstamp="1" tstamp2="4">
    <rend halign="center">Centered between @tstamp and @tstamp2</rend>
  </dir>
  <dir tstamp="1" tstamp2="4">
    <rend halign="justify">Justified/stretched to fit between @tstamp and @tstamp2</rend></dir>
</measure>
```

**Comment by lpugin** [comment]
Added with f6de0f7461237a671e51401b453e20c627421f8b

![image](https://cloud.githubusercontent.com/assets/689412/24401733/dd55a872-13b5-11e7-8bce-76603cd7b7e0.png)

```xml
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" clef.shape="G" clef.line="2" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1">
                            <staff n="1">
                                <layer n="1">
                                    <note dur="2" pname="f" oct="4"/>
                                    <note dur="2" pname="f" oct="4"/>
                                    <note dur="2" pname="f" oct="4"/>
                                </layer>
                            </staff>
                            <harm tstamp="1">
                                <rend halign="right">Right</rend>
                            </harm>
                            <harm tstamp="3">
                                <rend halign="center">Center</rend>
                            </harm>
                            <harm tstamp="5">
                                <rend halign="left">Left</rend>
                            </harm>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
```

**Comment by pe-ro** [comment]
This is great!  Does it also work when `@tstamp2` is present?  Or `@startid` and `@endid`? If so, can you give a couple of examples?

**Comment by rettinghaus** [comment]
Yeah works fine so far. But I think it should take the width of the object into account, so that left align means aligned to the left edge of e.g. the note column or bar line.

**Comment by rettinghaus** [comment]
Note: `text-anchor` won't get interpreted by the GIMP or the Eye of Gnome Image Viewer (and probably other programs too). Perhaps this should be noted somewhere.

**Comment by lpugin** [comment]
Actually I am seeing that rsvg-convert does not understand `text-anchor` to be overwritten. That is, in the example above, the svg generated is
```xml
<text text-anchor="middle">
	<tspan class="rend" text-anchor="end">
		<tspan class="text">Right</tspan>
	</tspan>
</text>
```
This reflects the MEI since the `@halign` is given in the child `rend` element. I guess this would not be a problem if `@halign` was allowed and put directly in `harm`. But if I understand correctly there was a reason for it not to be desirable.

@rettinghaus: there is not reason to align by taking a note or a barline width since it is attached to a timestamp. With `@startid` this could be possible even though I am not sure it will always be desirable. We can maybe style this or have it managed with `@ho` eventually.

**Comment by rettinghaus** [comment]
@lpugin with timestamp it's all right, but I think on using startid it is definitely connected to an graphical object, so it should always be desireable to align it with that very object. 

And my observation is that rsvg-convert just ignores `text-anchor` on `<tspan>`.

**Comment by lpugin** [comment]
The SVG is properly rendered by rsvg-convert and gimp with the latest version (487faf1ff57ce9d52f68c5a103b7989cda92e92a). The difference is that the text is aligned with `text-anchor` on the `text` (and not `tspan`) by looking at the first child `rend` and its `@halign` (if any). This means that mixing alignment in the MEI will not be correctly be interpreted, but I am not sure what this would represent anyway. That is, something like
```xml
<dir>
  <rend halign="center">This is centered
    <rend halign="left">but not always</rend>
  </rend>
</dir>
```
is just centered with the following SVG
```xml
<g class="dir">
	<text text-anchor="middle">
		<tspan class="rend">
			<tspan class="text">This is centered </tspan>
			<tspan class="rend">
				<tspan class="text">but not always</tspan>
			</tspan>
		</tspan>
	</text>
</g>
```

@pe-ro using `tstamp2` or `@endid` is currently ignored. The main difficulty is what to do with them when a system break (or several system breaks) occur between the beginning and the end. The text needs to be cut appropriately and aligned or justified accordingly, which does not seem straightforward to me.

**Comment by pe-ro** [comment]
> The main difficulty is what to do with them when a system break (or several system breaks) occur between the beginning and the end. The text needs to be cut appropriately and aligned or justified accordingly, which does not seem straightforward to me.

And that's why I asked. 😉 

It's not straightforward, but since this kind of thing occurs very frequently, I think it has to be done.  I believe the process begins with determining the space available for the directive before casting off.  It might be instructive to find out what existing desktop applications do.

**Comment by pe-ro** [comment]
Perhaps the new `<seg>` element could help. The following would at least divide the directive into segments between which spaces, dashes, etc. could be inserted --
```
<dir tstamp="2" tstamp2="2m+2">
  <rend halign="justify">
    <seg>Cresc.</seg>
    <seg>poco</seg>
    <seg>a</seg>
    <seg>poco</seg>
  </rend>
</dir>
```
Of course, without additional markup this won't tell you precisely where the "a" should be located.

Something like the following isn't entirely unreasonable, though --
```
<dir tstamp="2" tstamp2="2m+2">
  <rend halign="justify">
    <seg synch="#n01">Cresc.</seg>
    <seg synch="#n03">poco</seg>
    <seg synch="#n05">a</seg>
    <seg synch="#n06">poco</seg>
  </rend>
</dir>
```

**Comment by clubfest** [comment]
That was quick. Thanks, @lpugin !
