### ISSUE TITLE
Changing the noteheads in the mensural MEI files

### ISSUE THREAD

**Issue by misingnoglic** [rism-ch/verovio#533]
Hi everyone,

I was wondering if there was a way we could specify the type of noteheads in mensural MEI files (black vs white). Currently, when they're converted to SVG by verovio, they're made with white noteheads (like this: http://imgur.com/a/DqT7N) - however, for the 14th century music we're working on currently, it's better if the black noteheads would be used instead. 

Here's the closest font I could find - but I'm not sure how to go about the specific notehead swapping: https://w3c.github.io/smufl/gitbook/tables/medieval-and-renaissance-individual-notes.html

The only documentation I could find is how to specify the specific font: http://www.verovio.org/smufl.xhtml

Please let me know if there is something I can do to make this change, or if it's something that would have to be implemented in the verovio code. I tried searching for strings like "U+E95C" and "mensuralWhiteMaxima" but couldn't find anything. Thank you very much!
-Arya

**Comment by donbyrd** [comment]
In development versions of Verovio, you can specify black notation in the <staffDef>, like this:

<staffDef n="1" lines="4" notationtype="mensural.black"/>

But I don't know if this feature is available in the release version yet.
