### ISSUE TITLE
Add buffer space on terminal syllables in SVG lyrics

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#537]
It would be possible to copy/paste lyrics out of SVG images to with relative ease if a buffer space character is added to the word terminations in the SVG lyrics.

Here is an example of copying the text in an SVG (mostly lyrics, but also part abbreviation in this case):

<img width="805" alt="screen shot 2017-04-11 at 12 16 01 pm" src="https://cloud.githubusercontent.com/assets/3487289/24926713/70c88f2e-1eb1-11e7-9e17-22b0e63b842b.png">

Pasting into a text editor gets all of the text, but does not include spaces between words (elision characters are the boxes with the question mark inside):

![screen shot 2017-04-11 at 12 17 40 pm](https://cloud.githubusercontent.com/assets/3487289/24926650/3b9c426e-1eb1-11e7-8c02-538c0f273133.png)

If a space were added after each word terminating syllable (or after all text that is not lyrics), then the copy/paste would result in:

![screen shot 2017-04-11 at 12 27 18 pm](https://cloud.githubusercontent.com/assets/3487289/24926971/3b155eec-1eb2-11e7-9d96-86d74eaaf8ee.png)

The space would be added at the last moment before inserting into the SVG image, since the space should not be involved in width calculations for the text (or it could be added as a separate SVG element, etc.

Adding the space would make it easier to clean up to get the lyrics:

> Sovra l'herbette e i fiori, e i fiori La mia crudel Licori, Anci 'l cor mio, Anci 'l cor mio che fu da lei rapito; E me di piaggia in piaggia, <E me di piaggia in piaggia> Seguìa Ninfa selvaggia, Seguìa Ninfa selvaggia; Quando m'aggiunse, <Quando m'aggiunse,> e con soavi baci, e con soavi baci Mi disse: "hor prendi, hor prendi e taci, Mi disse, <Mi disse:> "hor prendi e taci, "hor prendi e taci.

(in this case I extracted from the source data file, which is the obvious source to extract from, but extracting from the SVG may be handy in certain situations).

**Comment by lpugin** [comment]
This is a pretty weird idea... I think if one wants to edit the lyrics they should get them directly from the MEI file and note the SVG. It is quite likely not complicated to have an XSLT to do that and you will get something much cleaner than this straightaway. Using Python (e.g., with LibMEI) would be another way to go.

**Comment by craigsapp** [comment]
It is low priority :-).  And now that it is mentioned here, no one else can patent it :-) 

How do you copy text off of a webpage?  With XSLT or copy/paste with a mouse click and drag?  In other words it is an interface for users not for programmers.  And it brings at least the text part of SVGs closer to behavior of text on a webpage (it would be somehow nice to be able to copy the MEI data when selecting an SVG image).

**Comment by lpugin** [comment]
> How do you copy text off of a webpage?

I don't, this is stealing... ;-) Seriously, I do not think we should change the SVG for that purpose

**Comment by craigsapp** [comment]
> Seriously, I do not think we should change the SVG for that purpose

OK, no problem.

> I don't, this is stealing... ;-)

Or fair use...  Or the text in the example is 500 years old, so public domain...

**Comment by craigsapp** [comment]
I snuck this feature in externally via the `@type` system, by adding an end-of-word class name (`t`) into the MEI data, and then in JavaScript add a space at the end of text elements selected with `svg g.syl.t text tspan`:

https://github.com/TassoInMusicProject/tasso-website/issues/52
