### ISSUE TITLE
stem direction control of longs and maximas

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#542]
The stem direction of longs and maximas cannot be controlled with `stem.dir` attributes.

Each note in this example should be alternating stem-up and stem-down:

<img width="626" alt="screen shot 2017-04-13 at 7 53 48 pm" src="https://cloud.githubusercontent.com/assets/3487289/25031629/051f2610-2083-11e7-84fc-fba3eb033131.png">

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2017-04-13T19:52:58" version="0.9.14-dev-c2f0a6e-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workDesc>
   <work>
    <titleStmt>
     <title />
    </titleStmt>
   </work>
  </workDesc>
 </meiHead>
 <music>
  <body>
   <mdiv>
    <score>
     <scoreDef xml:id="scoredef-0000001122575936">
      <staffGrp xml:id="staffgrp-0000001725706628">
       <staffDef xml:id="staffdef-0000000077033677" n="1" clef.shape="G" clef.line="2" meter.count="8" meter.unit="1" lines="5" />
      </staffGrp>
     </scoreDef>
     <section xml:id="section-0000000467746246">
      <measure xml:id="measure-L3" n="1" type="m-1">
       <staff xml:id="staff-L3F1N1" n="1">
        <layer xml:id="layer-L3F1N1" n="1">
         <note xml:id="note-L4F1" dur="long" oct="4" pname="a" stem.dir="down">
          <accid xml:id="accid-L4F1" accid.ges="n" />
         </note>
         <note xml:id="note-L5F1" dur="long" oct="4" pname="a" stem.dir="up">
          <accid xml:id="accid-L5F1" accid.ges="n" />
         </note>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L6" n="2" type="m-2">
       <staff xml:id="staff-L6F1N1" n="1">
        <layer xml:id="layer-L6F1N1" n="1">
         <note xml:id="note-L7F1" dur="long" oct="5" pname="e" stem.dir="up">
          <accid xml:id="accid-L7F1" accid.ges="n" />
         </note>
         <note xml:id="note-L8F1" dur="long" oct="5" pname="e" stem.dir="down">
          <accid xml:id="accid-L8F1" accid.ges="n" />
         </note>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L9" n="3" type="m-3">
       <staff xml:id="staff-L9F1N1" n="1">
        <layer xml:id="layer-L9F1N1" n="1">
         <note xml:id="note-L10F1" dur="maxima" oct="4" pname="b" stem.dir="up">
          <accid xml:id="accid-L10F1" accid.ges="n" />
         </note>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L11" n="4" right="end" type="m-4">
       <staff xml:id="staff-L11F1N1" n="1">
        <layer xml:id="layer-L11F1N1" n="1">
         <note xml:id="note-L12F1" dur="maxima" oct="4" pname="b" stem.dir="down">
          <accid xml:id="accid-L12F1" accid.ges="n" />
         </note>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by donbyrd** [comment]
Without looking at the code, I'm not sure, but this might be my fault, even though the staff isn't `@notationtype` mensural. But I wonder if longas -- not to mention maximas! -- should even be allowed on non-mensural staves? I don't recall ever seeing either in CWMN, do you? Anyway, I'd say that question is no higher priority than this, uh, missing enhancement.

**Comment by craigsapp** [comment]
Longas definitely must be supported in CWMN.  The reason is that the modern editorial style for representing old music in modern notation is to use the original rhythmic values instead of doing a rhythmic reduction, such as converting whole notes into quarter notes.  Just about every score in the Renaissance era also uses a longa at the end of the piece as a form of fermata for the last chord.

By extension that would also include maxima, although I have not encountered it yet in any music for JRP.

**Comment by rettinghaus** [comment]
I was about to bring that up, but @craigsapp was faster. To use Longas is definitely common practice in modern editions. And if you peek into the Guidelines, you'll see that longa is indeed already part of `data.DURATION.cmn`.

**Comment by donbyrd** [comment]
How embarrassing. After decades of annoying people with examples of extreme notation, I really should have thought about this kind of usage! Thanks for the correction.

**Comment by kepper** [comment]
However, it's important to notice that MEI makes a distinction here: in data.duration.mensural, there is a "longa" value, while data.duration.cmn has a "long"; the same applies to "brevis" and "breve". They do look the same, but they shouldn't be used across repertoire boundaries – why would MEI make this distinction if not for this very purpose?

**Comment by craigsapp** [comment]
> However, it's important to notice that MEI makes a distinction here: in data.duration.mensural, there is a "longa" value, while data.duration.cmn has a "long"; the same applies to "brevis" and "breve". They do look the same, but they shouldn't be used across repertoire boundaries – why would MEI make this distinction if not for this very purpose?

Yes, probably useful to have separate namespaces for CMN and Mensural note names -- although longs and longas will have very similar graphical syntaxes since longs are analeptic in modern notation.

**Comment by donbyrd** [comment]
Longs are central nervous system stimulants in modern notation? Wikipedia says "An analeptic, in medicine, is a central nervous system stimulant. The term analeptic typically refers to respiratory analeptics (for example, doxapram)." I've never heard the word before, and I don't see any evidence it has a musical meaning. ??

**Comment by craigsapp** [comment]
It is a fancy word for "flashback" :-) 

It is the opposite of "proleptic" which has not been co-opted by medicine yet (although they are using the word as a noun and I was using as an adjective):
     https://en.wiktionary.org/wiki/proleptic
which basically means using a calendar to retroactively assign dates before the calendar existed. 

Musically, using CMN to notation mensural music is *proleptic*; while using mensural music to notate CMN is *analeptic*.

Here is a webpage discussing analepsis and prolepsis in a literary context:

http://pseudoprofundities.blogspot.com/2006/07/expand-your-jargon-i-analeptic.html

> analepsis is "any evocation after the fact of an event that took place earlier than the point in the story where we are at any given moment." To simplify, analepsis is a flashback (going back to an earlier event), and prolepsis is like foreshadowing

**Comment by craigsapp** [comment]
And here is the definition (when converted to the noun form):

https://en.wiktionary.org/wiki/analepsis

With the first definition being the one I was intending:

> A form of flashback in which earlier parts of a narrative are related to others that have already been narrated

And medical uses due to it being  a Latinate word:

> (medicine) Recovery of strength after sickness.
> (medicine) A kind of epileptic attack, originating from gastric disorder.

**Comment by donbyrd** [comment]
Very interesting, thanks, Craig! I'm familiar with the term _proleptic_ for calendars; it didn't occur to me that analeptic was related.

**Comment by lpugin** [comment]
Fixed

**Comment by craigsapp** [comment]
But not committed yet?

**Comment by craigsapp** [comment]
Nevermind: I was using the older globally installed version of verovio instead of the just compiled version. 😛
