### ISSUE TITLE
MIDI playback - tied notes are reattacked

### ISSUE THREAD

**Issue by karend27** [rism-ch/verovio#550]
In the midi playback tied notes seem to be reattacked: see for example this motet that because of the particular mensuration had to be encoded with a lot of tied notes:

[rosa.txt](https://github.com/rism-ch/verovio/files/927005/rosa.txt)

**Comment by craigsapp** [comment]
Rendering of start of rosa.txt:

<img width="1360" alt="screen shot 2017-04-17 at 6 36 40 pm" src="https://cloud.githubusercontent.com/assets/3487289/25110977/e8c61bfa-239c-11e7-8f19-3f39fda8dedc.png">

**Comment by lpugin** [comment]
This duplicates with #196

**Comment by karend27** [comment]
Ah okay. Thanks.
