### ISSUE TITLE
Additive meter time signatures

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#554]
Although this is a libMEI issue, I leave it here, as Verovio is affected by this: 

`meter.count` is treated as `int` but it should be read as `str` as it allows "additive expression": 
> Value of datatype a string matching the following regular expression: "\d+(\.\d+)?(\s*\+\s*\d+(\.\d+)?)*"

(same applies to `@count`)
Showing a plus sign in SVG shouldn't be that hard then, is it?

**Comment by rettinghaus** [comment]
Glyph `U+EA6C` ("+") would be needed also.

**Comment by lpugin** [comment]
Why not http://www.smufl.org/version/latest/glyph/timeSigPlusSmall/ ?

**Comment by rettinghaus** [comment]
Yeah, makes more sense. So `E08D` should be it.

**Comment by lpugin** [comment]
The glyph is added. Now it is not as simple as changing to string, because this will break all the timestamp calculation. We need to think about a custom class for compound values.

**Comment by rettinghaus** [comment]
Not really. We could keep `m_meterCount` as an integer with the "resulting" count from something like "3+2+4+1". There should be a little function calculating the resulting count.

**Comment by lpugin** [comment]
General feature request

**Comment by craigsapp** [comment]
Here is a nice example:

http://imslp.eu/files/imglnks/euimg/5/51/IMSLP20283-PMLP47288-Bartok_violin_duets_part_I.pdf

<img width="813" alt="Screen Shot 2020-01-29 at 11 13 30" src="https://user-images.githubusercontent.com/3487289/73389349-d6813980-4288-11ea-9880-60522730ecd9.png">

**Comment by rettinghaus** [comment]
Support added with #2200.
