### ISSUE TITLE
JS toolkit.renderPage() creates svg element with ID, preventing multiple instances on same page

### ISSUE THREAD

**Issue by redtopia** [rism-ch/verovio#568]
I am trying to embed multiple instances of the javascript toolkit into a page with different data loaded into each instance. The data loads and displays fine, but when I call renderPage() when the window has been resized, each instance is overwritten with the same data.

This is because renderPage() is creates an svg element with an ID of "definition-scale" making it impossible to embed multiple instances on the same page. See screenshot of DOM below:

![image](https://cloud.githubusercontent.com/assets/812777/25548127/2f0eb5e8-2c28-11e7-96a1-6356503690c5.png)

Here's a complete working example:
[meitest.zip](https://github.com/rism-ch/verovio/files/965618/meitest.zip)

**Comment by craigsapp** [comment]
When you try to create a second instance of verovio, it will say


, but I generate multiple SVGs from one instance of verovio to show on a page:

http://www.tassomusic.org/incipits

**Comment by redtopia** [comment]
I can create multiple instances that draw fine, but I cannot resize the page and redraw the instances using renderPage() without overwriting each instance with each call to the method.

**Comment by redtopia** [comment]
Sorry... I'm on my iPhone and for some reason it didn't show me your full comment until after I posted. But I was thinking that there must be some kind of workaround along the lines of what you implement. I guess I could use jquery to change the id of the svg element before adding it to the DOM.

That said, this should be an easy fix.

**Comment by craigsapp** [comment]
> Sorry... I'm on my iPhone and for some reason it didn't show me your full comment until after I posted. 

I pressed shift-enter or something as I was editing my post, so it got posted in an incomplete version...

Here is what I have in mind:  One instance of verovio, and you reload the data for each instance.

```html
<!doctype html>
<html>
<head>
	<title>Verovio Test - Multiple Instances</title>
	<style>
	body {
		font-family:sans-serif;
	}
	div.mei-test {
		background-color:#fff;
		border:1px solid #ccc;
		padding:15px;
		margin:0 0 15px 0;
		overflow-x:hidden;
	}
	</style>
	<script src="jquery-1.11.3.min.js"></script>
</head>
<body>
	<h1>Verovio Test - Multiple Instances</h1>

	<div id="test-wrap"></div>
	
	<script>

	var MEIDATA = {};
	var TK;

	$(document).ready(function () {
		TK = new verovio.toolkit();
		var $testFiles = ['test1.mei', 'test2.mei'],
			$testWrap = $('#test-wrap');
		
		function getOptions (div) {
			var zoom = 40;
			return({
				inputFormat: 'mei',
				border: 50,
				pageWidth: ($(div).width() * 100) / zoom,
				ignoreLayout: 1,
				adjustPageHeight: 1,
				scale: zoom
			});
		}

		function resize (tk, div, instance) {
			tk.setOptions(getOptions(div));
			var svg = tk.renderData(MEIDATA[instance], {});
			$(div).html(svg);
		}

		function loadData (meiData, div, tk) {
			var instance = Math.floor(Math.random()*1000000),
				resizeTimer = null,
				svg;
			MEIDATA[instance] = meiData;
			tk.setOptions(getOptions(div));
			svg = tk.renderData(meiData, {})
			$(div).html(svg);

			$(window).on('resize.' + instance, function() {
				if (resizeTimer) {
					clearTimeout(resizeTimer);
				}
				resizeTimer = setTimeout(function() {
					resize(tk, div, instance);
					resizeTimer = null;
				}, 500);
			});

		}
		
		function loadTestFile (file) {
			var div = $('<div class="mei-test"><p>Loading: ' + file + '</p></div>').appendTo($testWrap);
			$.ajax({
				url: file,
				type: 'get',
				dataType: 'text',
				success: function (text) {
					loadData(text, div, TK);
				},
				error: function (xhr) {
					$(div).html('<p>An error occurred.</p>')
				}
			});
		}
		
		for (var ix = 0; ix < $testFiles.length; ix++) {
			loadTestFile($testFiles[ix]);
		}

	});
	</script>
	<script src="verovio-toolkit.js"></script>
</body>
</html>
```

**Comment by craigsapp** [comment]
Laurent can explain why only one instance of verovo is allowed at the moment.

**Comment by lpugin** [comment]
Basically only one instance is allowed because only one memory pointer is managed. The only thing to be changed for allowing multiple instances is the JS proxy. 

https://github.com/rism-ch/verovio/blob/master/emscripten/verovio-proxy.js

More precisely, instead of one pointer we need a stack of pointers and change the methods below accordingly

https://github.com/rism-ch/verovio/blob/master/emscripten/verovio-proxy.js#L64

**Comment by ahankinson** [comment]
Seems like it wouldn't be very efficient; each instance would pre-allocate a chunk of memory, and the instances couldn't share it so you would probably start running into problems with your browser pretty quickly.

**Comment by lpugin** [comment]
Indeed. I changed the "definition-scale" to a class 6101779fe90dfb2c0bcc46fad3d7ea3bc0d87f5b

**Comment by craigsapp** [comment]
> Seems like it wouldn't be very efficient; each instance would pre-allocate a chunk of memory, and the instances couldn't share it so you would probably start running into problems with your browser pretty quickly.

The build script for emscripten allocates 192 MB for the verovio toolkit:
https://github.com/rism-ch/verovio/blob/develop/emscripten/buildToolkit#L37-L44

So maybe up to 10 instances of verovio would be reasonable on a modern computer setup.

The web assembly version allocates 256 MB:
https://github.com/rism-ch/verovio/blob/develop/emscripten/buildToolkit#L90-L101

Is there a reason for that @lpugin?

WebAssembly seems to have a GrowMemory feature which ASM.js does not:

https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-section

**Comment by lpugin** [comment]
No particular reason, but last time I tried the GrowMemory option with WASM it did not work.

**Comment by craigsapp** [comment]
I was more asking about why the difference in size from 192 to 256.  What 256 a random number, or a preferential size for webassembly, or webasm needs more memory for some reason?
