### ISSUE TITLE
# versus ♯ in figured bass <f> elements

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#588]
Here is an example of some figured bass with some musings:

```xml
<harm  place="below" staff="2" tstamp=“3”>
     <fb>
          <f>3♯</f>
     </fb>
</harm>
```

Notice that the sharp is a unicode symbol and is not the ASCII "#" character.

Also note that for `<notes>s`, the `@accid` parameter uses the ASCII "#" character.

This is somewhat incongruous unless an ASCII "#" is ever expected to be needed within `<f>` (such as hashtag basso continuo).

How would a hand-encoder add this unicode character to the file?  Whenever I need to do something like that I search for "unicode sharp" in google and copy/paste the character from a matched webpage, as I am not going do it often enough to remember a numeric code for such symbols.

One idea would be to also map any occurrence of ASCII "#" to a unicode "♯" when rendering.  Another would disallow unicode ♯ and only use ASCII "#".  Free-form `<harm>` text rendering in verovio already does the mapping from ASCII "#" to unicode "♯".

**Comment by lpugin** [comment]
I think figured-bass encoding can be revised and take a more semantic approach. You can discuss it with @xhero next week.

**Comment by xhero** [comment]
Well the MEI spec says you have to enter the unicode chars for sharp, flat and natural, and so I render these as proper music chars.
I don’t like this approach: I think the alteration should be encoded, we can discuss and then propose how.
