### ISSUE TITLE
support for mei:supplied etc.

### ISSUE THREAD

**Issue by kepper** [rism-ch/verovio#59]
While mei:choice should not be handled by Verovio, it would be great if it could support elements like mei:supplied, mei:sic, mei:corr, mei:add or mei:del. The kind of support I'd be interested in is just to add an additional class to all the contained elements: g.accid.supplied, g.clef.corr etc. Another option would be to put the contents in a g.supplied which could share the @xml:id of the mei:supplied, but that might be overkill. This is just to get a simple hook to enrich output with additional information so that Javascript can make use of it…

**Comment by lpugin** [comment]
Added in 06c41317bdc8894862c07ca4fbc08d49d96a8e5a
