### ISSUE TITLE
Rendering of notes broken when using Bootstrap with Verovio

### ISSUE THREAD

**Issue by scornec** [rism-ch/verovio#590]
I try to make a web site with MEI files and Verovio javascript toolkit using Bootstrap, but I get a problem with the rendering of the notes : they are cut as shown in the first screenshot below.
The line creating the issue is this one:
       `<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">`
When commented, it works as expected see the other screenshot below.

Thanks in advance for your help !

![boostrap](https://cloud.githubusercontent.com/assets/28652197/26000228/6cef0600-3728-11e7-881e-358c67cf8b07.png)

![noboostrap](https://cloud.githubusercontent.com/assets/28652197/26000229/6cf3647a-3728-11e7-8312-132e795779e9.png)

**Comment by ahankinson** [comment]
This is a fairly common problem; see issues/79 for a solution.

**Comment by craigsapp** [comment]
See also issue #138 

Summary:

Bootstrap does this:

``` css
svg:not(:root) {
    overflow: hidden;
}
```

So you need either to delete that, or add the following CSS after loading the Bootstrap css:

``` css
svg:not(:root) {
  overflow: inherit; 
}
```
