### ISSUE TITLE
augmentation dot + flag interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#595]
The augmentation dots on notes with flags/stems on the right sides of notes are pushed too far to the right to avoid the flags:

<img width="741" alt="screen shot 2017-05-16 at 11 14 58 pm" src="https://cloud.githubusercontent.com/assets/3487289/26128805/fa81b05e-3a8d-11e7-84f3-220f2433704e.png">

The augmentation dots in each voice should line up vertically with each other.

Test data:

```
**kern
*clefG2
*^
8.c	8.A
8.d	8.B
8.e	8.c
8.f	8.d
8.g	8.e
8.a	8.f
8.b	8.g
8.cc	8.a
8.dd	8.b
8.ee	8.cc
8.ff	8.dd
8.gg	8.ee
8.aa	8.ff
8.bb	8.gg
8.ccc	8.aa
*v	*v
==
*-
```

**Comment by lpugin** [comment]
We could add a SE anchor point to the flag SMuFL char, but this will work only with the Leipzig font because quite likely other fonts will not have one.

Also, I remember having looked at this in Behind Bars and seeing that dot positioning can vary. Some put it close to the note also regardless of the flag presence. I think that if we do this with Bravura it will touch the flag.  In the end the best is probably to make it a styling option

**Comment by craigsapp** [comment]
> Also, I remember having looked at this in Behind Bars and seeing that dot positioning can vary. Some put it close to the note also regardless of the flag presence.

Regardless, the dots of the notes in the two voices must be vertically aligned as if they were in the same `<chord>`.

<img width="579" alt="screen shot 2017-05-17 at 10 14 38 am" src="https://cloud.githubusercontent.com/assets/3487289/26144601/baa92fe6-3ae9-11e7-8612-a377d245a806.png">

But notice that the augmentation dots in the first half of the dyads are poorly placed, since they are closer to the next note than to the note that they modify.


Test data:

```
**kern
*clefG2
8.c 8.A
8.d 8.B
8.e 8.c
8.f 8.d
8.g 8.e
8.a 8.f
8.b 8.g
8.cc 8.a
8.dd 8.b
8.ee 8.cc
8.ff 8.dd
8.gg 8.ee
8.aa 8.ff
8.bb 8.gg
8.ccc 8.aa
==
*-
```

**Comment by th-we** [comment]
Another option would be to  lengthen the stems instead of moving the dots. Here is a Sibelius example:

![image](https://user-images.githubusercontent.com/1147152/87451685-c28b8300-c5ef-11ea-810e-5676892c6a8a.png)

The solution in the first bar (lengthened stems for the last two chords) is nicer than the solution in the second second (shifted dots). Dots on downstem notes don't look too far away, and the spacing doesn't have to be widened because of shifted dots. Probably also much easier to implement.

This slightly depends on the font.  The flag of Sibelius/Opus is slightly shorter than that of Verovio/Leipzig.

**Comment by craigsapp** [comment]
The first mesure looks better becuase the notes are more evenly spaced (the first four versus the last two).  If the spacing between the notes were wider, then there would be less of a visual difference between the notes and the dot placement.

**Comment by th-we** [comment]
@craigsapp Exactly – but as I wrote it does not only depend on horizontal space, but also on vertical space (we don't want to drive staves too far apart/cram the page...)  But that's maybe a little too much sophistication for Verovio right now.

**Comment by craigsapp** [comment]
One diatonic vertical diatonic-step expansion between the two measure seems like not very much to worry about :-)

<img width="429" alt="Screen Shot 2020-07-14 at 1 24 41 PM" src="https://user-images.githubusercontent.com/3487289/87472862-7af7fd80-c5d5-11ea-9499-ce1b758569f7.png">

**Comment by rettinghaus** [comment]
This works now as expected:
![dots](https://user-images.githubusercontent.com/7693447/99371918-d0178900-28bf-11eb-9ee6-a9a8cc2961cd.png)

Even with manual adjusted stem lengths:
![dots2](https://user-images.githubusercontent.com/7693447/99371925-d1e14c80-28bf-11eb-9ce8-d24e7e64c96d.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0" ?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron" ?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title>Dots positioning on notes with flags and longer stem length</title>
      </titleStmt>
      <pubStmt>
        <respStmt>
          <persName role="encoder">Klaus Rettinghaus</persName>
          <corpName role="funder">Enote GmbH</corpName>
        </respStmt>
        <date isodate="2020">2020</date>
      </pubStmt>
      <seriesStmt>
        <title>Verovio test suite</title>
      </seriesStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef n="1" lines="5">
                <clef shape="G" line="2" />
              </staffDef>
            </staffGrp>
          </scoreDef>
          <section>
            <measure right="end">
              <staff n="1">
                <layer n="1">
                  <note dots="1" dur="8" oct="4" pname="c" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="d" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="e" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="f" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="g" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="a" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="b" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="c" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="d" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="e" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="f" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="g" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="a" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="b" stem.len="8" />
                  <note dots="1" dur="8" oct="6" pname="c" stem.len="8" />
                </layer>
                <layer n="2">
                  <note dots="1" dur="8" oct="3" pname="a" stem.len="8" />
                  <note dots="1" dur="8" oct="3" pname="b" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="c" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="d" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="e" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="f" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="g" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="a" stem.len="8" />
                  <note dots="1" dur="8" oct="4" pname="b" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="c" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="d" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="e" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="f" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="g" stem.len="8" />
                  <note dots="1" dur="8" oct="5" pname="a" stem.len="8" />
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

@lpugin I think this can be closed then.
