### ISSUE TITLE
stems with flags should be shortened

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#598]
Stems with flags should be shortened a bit like beamed stems, to prevent the small rough edge on the end.

![drawstem](https://cloud.githubusercontent.com/assets/7693447/26148788/2bf2816c-3af8-11e7-9d1d-322384900d5c.png)

![drawstem](https://cloud.githubusercontent.com/assets/7693447/26148872/69e850aa-3af8-11e7-83fb-a642cc25a3c2.png)

**Comment by lpugin** [comment]
This can now be corrected with the options and a smaller stem width
