### ISSUE TITLE
Measures empty in all staves of a system do not have default width

### ISSUE THREAD

**Issue by ahwitz** [rism-ch/verovio#61]
![screen shot 2014-12-23 at 2 18 35 pm](https://cloud.githubusercontent.com/assets/3514397/5542002/b57dff30-8aae-11e4-9ffd-016951e24f32.png)

MEI file from image is http://duchemin-dev.haverford.edu/mei/DC1204.xml.

**Comment by lpugin** [comment]
Fixed with commit 68f7b1c
