### ISSUE TITLE
How to make the score "barless"?

### ISSUE THREAD

**Issue by juyaolongpaul** [rism-ch/verovio#610]
Hi, awesome Verovio team!

I am trying to transcribe the medieval chant into MEI files, where there should be no barline.

I have two ways to implement in my head now:

(1) Put everything into just one bar, which looks like this now:

![screen shot 2017-06-05 at 11 15 50 am](https://cloud.githubusercontent.com/assets/9313094/26790055/5e750b36-49e0-11e7-8e7d-9a7a61ca592d.png)

The melody looks fine, but the lyrics are squished together. I wonder is there any tweak to adjust the space among them? 

(2) Alternatively, I can still put `<measure>` element into MEI file (now I put four beats into one measure), but I need to have a way to not display the barline. Do you know any method to do that?

Thank you so much!

**Comment by craigsapp** [comment]
> (2) Alternatively, I can still put <measure> element into MEI file (now I put four beats into one measure), but I need to have a way to not display the barline. Do you know any method to do that?

Add `measure@right="invis"` to the measure such as:

```xml
<measure right="invis">
    ...
</masure>
```

**Comment by juyaolongpaul** [comment]
Problem solved. Thank you!
