### ISSUE TITLE
 notes and rests should be left-aligned with time points  

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#612]
Here's a good example why notes and rests shouldn't be centred on a time point (see #581):

![glyphalign](https://cloud.githubusercontent.com/assets/7693447/26833203/1af96986-4ad2-11e7-9bc6-19394a44a43b.png)

According to Gould they should all be aligned together with their left sides. 
And this is the way other notation programs do it.

**Comment by lpugin** [comment]
See also https://github.com/rism-ch/verovio/pull/581

**Comment by rettinghaus** [comment]
fixed
