### ISSUE TITLE
MusicXML: key changes don't render?

### ISSUE THREAD

**Issue by matijama** [rism-ch/verovio#615]
I have a MusicXML file (attached as txt) with key changes encoded as:
```
      <print new-system="yes"/>
      <attributes>
        <key>
          <fifths>1</fifths>
          <mode>major</mode>
        </key>
      </attributes>

```
The changes don't render in Verovio (master checked out today), although notes have correct accidentals if I convert the musicxml file to a mei file. Is there a solution?

[musicxml.txt](https://github.com/rism-ch/verovio/files/1063216/musicxml.txt)

**Comment by rettinghaus** [comment]
Try the latest develop version.

**Comment by matijama** [comment]
Works, thanks.
