### ISSUE TITLE
Segmentation fault example

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#636]
The following MEI code produces a segmentation fault with the latest  `develop` code:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-06-23T22:29:02" version="2.0.0-dev-db68d6a-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001766463909">
                        <staffGrp xml:id="staffgrp-0000000227295800">
                            <staffDef xml:id="staffdef-0000001934586234" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000911802856">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F1N1" n="1">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <chord xml:id="chord-L5F1" dots="1" dur="4">
                                        <note xml:id="note-L5F1S1" oct="4" pname="c" accid.ges="n" />
                                        <note xml:id="note-L5F1S2" oct="5" pname="c" accid.ges="n" />
                                    </chord>
                                </layer>
                                <layer xml:id="layer-L5F2N2" n="2">
                                    <rest xml:id="rest-L5F2" dots="1" dur="4" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Segmentation fault 11 is generated when trying to convert the MEI data into an SVG file.

This is the original Humdrum content used to create the above MEI data:

```
**kern
*clefG2
=1-
*^
4.c 4.cc	4.r
*v	*v
=
*-
```

Creating the MEI transcoding did not create the segmentation fault, but when converting the MEI into SVG, the segmentation fault occurs.

I can make the segmentation fault go away by altering the music in several ways:

(1) Remove the autmentation dots on the notes:

```
**kern
*clefG2
=1-
*^
4c 4cc	4r
*v	*v
=
*-
```

<img width="250" alt="screen shot 2017-06-23 at 10 33 57 pm" src="https://user-images.githubusercontent.com/3487289/27499429-1783e782-5864-11e7-90e7-7a200f3bde8f.png">

(2) Convert the chord into a single note:

```
**kern
*clefG2
=1-
*^
4.c	4.r
*v	*v
=
*-
```

<img width="277" alt="screen shot 2017-06-23 at 10 34 56 pm" src="https://user-images.githubusercontent.com/3487289/27499455-349c714a-5864-11e7-8850-70ac1426f199.png">

and (3) Convert the rest into a note:

```
**kern
*clefG2
=1-
*^
4.c 4.cc	4.G
*v	*v
=
*-
```

<img width="314" alt="screen shot 2017-06-23 at 10 35 49 pm" src="https://user-images.githubusercontent.com/3487289/27499486-5a8aa336-5864-11e7-924d-33562dac5242.png">

Also note that the first example used to work.  Here is rendering of the above MEI data in an old version of verovio from December 2016:

<img width="227" alt="screen shot 2017-06-23 at 10 37 06 pm" src="https://user-images.githubusercontent.com/3487289/27499548-a52acd62-5864-11e7-96ef-31715631b7ab.png">

**Comment by lpugin** [comment]
The bad access is fixed https://github.com/rism-ch/verovio/commit/4764187334fdb485c86eb60ce5181962e376c22e

Layer adjustment with rests has still to be implemented
