### ISSUE TITLE
Segmentation fault: 11 error when creating timemap

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#643]
When creating timemap from MusicXML file I get the error: 
```
Segmentation fault: 11
```

It works well to create svg based on the same xml file.

I guess it has the same problem as mentioned in #636

**Comment by craigsapp** [comment]
Probably not the same, since printing the sample data in #636 to SVG does not cause a segmentation fault.  But generating a timemap of the same file does, so I will check it out.

**Comment by craigsapp** [comment]
When calculating the timemap, verovio crashes in `vrv::Glyph::GetBoundingBox`:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   verovio        vrv::Glyph::GetBoundingBox(int&, int&, int&, int&) + 4 (glyph.cpp:103)
1   verovio        vrv::Doc::SetDrawingPage(int) + 619 (doc.cpp:804)
2   verovio        vrv::Doc::CastOffDoc() + 43 (doc.cpp:647)
3   verovio        vrv::Toolkit::LoadData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 2885 (toolkit.cpp:589)
4   verovio        vrv::Toolkit::LoadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 470 (toolkit.cpp:360)
5   verovio        main + 5692 (main.cpp:398)
6   libdyld.dylib  start + 1
```

But I don't see the problem yet (which seems to be treating a NULL object as a real one).

**Comment by lpugin** [comment]
Are you setting the font resource dir?

**Comment by rettinghaus** [comment]
It seems to be the same error I described here: #634
Looks like a divide by zero bug somewhere.

**Comment by k-ljung** [comment]
No, my command is:
```
verovio "All my loving-WaV-150bpm.xml" -t timemap
```

**Comment by lpugin** [comment]
Fix here https://github.com/rism-ch/verovio/commit/8215b0484bbf5af3501130e5186e9c7f22406748

**Comment by craigsapp** [comment]
> Are you setting the font resource dir?

It didn't happen when I created an SVG, but it did happen when I created a timemap.
