### ISSUE TITLE
Generate AttComparison classes from libmei

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#65]
We should generate a comparison class for each attribute following this model using the verovio version of libmei
https://github.com/rism-ch/verovio/blob/master/include/vrv/att_comparison.h
https://github.com/rism-ch/libmei

The classes can be placed in the existing files (e.g. atts_shared.*). We can have everything in the header as in the example, or splited between header and implementation.

**Comment by ahankinson** [comment]
Is this something that could go into libmei core?

**Comment by lpugin** [comment]
Yes, this could be good. The modified version has an additional output language option for Verovio (cplusplus_vrv) activated with -l. I think there is also one additional option for the output directory, but otherwise there is no modification. It should be easy to integrate.

**Comment by lpugin** [comment]
The generation of the code is driven by a configuration file that can override the type for each attribute (if not specified, the type is determined by the schema, usually std:string but also int or double).
https://github.com/rism-ch/libmei/blob/master/tools/includes/vrv/config.yml

In the default section, for each type we can define the default value and converters for reading and writing. These are hand-coded separately in att.h.

In the modules section, the type can be specified. The default and the converters and can also be specified (or overridden if specified in the default section).

We could look if all this (or at least the module section) could be included in ODD for Verovio and then be generated from it. We talked about it with @kepper. This idea would to also generated the Verovio documentation from the same source (http://rism-ch.github.io/verovio/supported-mei.xhtml)

**Comment by ahankinson** [comment]
I'm looking at this and not sure I understand what is going on. As far as I understand, you're using the `n` attribute to check if two elements are equal?

If this is the case, why not just override `==` in `MeiElement` to provide a direct comparison by iterating through the `MeiAttribute` objects?

**Comment by lpugin** [comment]
I see. There might be a misunderstanding here. The AttComparison class is
designed for Verovio, so I am now realizing that when you asked if this
should go to the LibMEI core, I was thinking about the Verovio output (in
general) and not specifically to the AttComparison class.

The AttComparison class in an abstract class with a virtual operator() that
allow to check a property of an object when parsing the tree. This is meant
to be used in a very generic way, but the class has to be defined for each
MEI attribute (and not each element). We can use this for selecting an
object that 1) supports the attribute and 2) has a specific value. For
example, for selecting a staff with @n=2. For the att.common, we need to
have the AttCommonNComparison class, but also AttCommonLabelComparison that
would look at the label attribute, and so on. Does this make sense?

**Comment by lpugin** [comment]
PS see this commit for how it is used
https://github.com/rism-ch/verovio/commit/223c7c3085e27bab4aaa6ffe3f9a24cc48abbda1
