### ISSUE TITLE
make layout only default for SVG output

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#662]
If the output format is not SVG (i.e. Verovio is used for format conversion) the `--no-layout` and `--all-pages` options shouldn't be required (i.e. set automatically). 
See: 8215b04 and #222

**Comment by lpugin** [comment]
Not necessary `--all-pages` because you might want to have page-paged output.

**Comment by lpugin** [comment]
And actually you might also want to output the layout calculated by Verovio, so adding --no-layout is not desirable either.

**Comment by craigsapp** [comment]
Ideally `-t mei` should produce the current equivalent to `-t mei --all-pages --no-layout`.

If someone wants page MEI data, then it should be something like `-t mei --page 4` or `-t mei --all-pages`.  If neither a specific page or all pages are requested, then it should be assumed that they want unpaged/unlayedout MEI content.  This is for cases when the input is Humdrum or MusicXML, and the raw conversion to MEI before layout is applied is desired.  For MEI input it might be reasonable to require `--no-layout` and `-all-pages`, but it would be better to make it symmetric with the expected raw conversions for Humdrum and MusicXML to MEI.  In other words, `-t mei` when given MEI data as input would just echo the input to the output without doing anything to it.

I would presume that if paged MEI output, then layout would automatically be added, and if non-paged layout (raw MEI) is needed, then `--no-layout` would be automatically applied as well.

-----------------

This would somewhat parallel the `-t humdrum` output:

Given the input file `file.txt`:

```
**kern
*M4/4
*C:
=1
1c 1e 1g
==
*-
!!!filter: transpose -k d
```

The command:

```bash
verovio file.txt -t humdrum
```
will produce the file `file.krn` with this contents:

```
**kern
*Trd1c2
*M4/4
*D:
=1
1d 1f# 1a
==
*-
!!!Xfilter: transpose -k d
```

**Comment by craigsapp** [comment]
Also, omitting `--all-pages` and/or `--no-layout` when using `-t mei`, I get a segmentation fault (probably because font information is not loaded for `-t mei` option):

```bash
$ verovio test.krn -t mei
Segmentation fault: 11

$ verovio test.krn -t mei --all-pages --no-layout
Output written to test.mei.
```
