### ISSUE TITLE
Accidental attribute does not exist when retrieving note element attributes

### ISSUE THREAD

**Issue by euphonialabs** [rism-ch/verovio#668]
When using ``vrvToolkit.getElementAttr(noteid)`` to retrieve note element attributes, notes with accidentals do not have any attributes to indicate the nature of their accidental (which should be ``accid.ges``).  I've attached a short piece for testing purposes.

[test.zip](https://github.com/rism-ch/verovio/files/1226548/test.zip)

I tested this using the verovio-tutorial [https://github.com/rism-ch/verovio-tutorial] with topic 9 - "MIDI Output". I added a ``console.log`` the midiUpdate function:
```
            var midiUpdate = function(time) {
                // bug! time needs to be * 2 (- 800 for adjustment)
                var vrvTime = Math.max(0, 2 * time - 800);
                var elementsattime = vrvToolkit.getElementsAtTime(vrvTime);
                if (elementsattime.page > 0) {
                    if (elementsattime.page != page) {
                        page = elementsattime.page;
                        loadPage();
                    }
                    if ((elementsattime.notes.length > 0) && (ids != elementsattime.notes)) {
                        ids.forEach(function(noteid) {
                            if ($.inArray(noteid, elementsattime.notes) == -1) {
                                $("#" + noteid).attr("fill", "#000").attr("stroke", "#000"); 
                            }
                        });
                        ids = elementsattime.notes;
                        ids.forEach(function(noteid) {
                            if ($.inArray(noteid, elementsattime.notes) != -1) {
                                console.log("Note",vrvToolkit.getElementAttr(noteid));
                                $("#" + noteid).attr("fill", "#c00").attr("stroke", "#c00");; 
                            }
                        }); 
                    }
                }
            }
```

The output, tested with the latest versions of both production and development releases, lacked the accidental attribute.

**Comment by lpugin** [comment]
Indeed. The MEI `@accid` is internally represented as a `<accid>` child of the `<note>`. In order to retrieve it from the SVG you need to look for the `<g class="accid">` child and get the attribute from it.

**Comment by rettinghaus** [comment]
Internal conversion from attributes to elements is afaics totally undocumented. 
Should this go [here](http://www.verovio.org/structure.xhtml)?

**Comment by lpugin** [comment]
Indeed again. Yes, this would be a good place for it.

**Comment by euphonialabs** [comment]
The ``<g class="accid">`` element doesn't indicate the type of accidental. How do I extract this information from it?

Also, why does the ``accid.ges`` attribute no longer exist in the JSON object returned by ``vrvToolkit.getElementAttr(noteid)`` for a note with an accidental? This used to exist in a previous version of the library (I don't know which, but I've attached it). However, that version was buggy. For example, in the attached ``test2.xml``, all notes except the first note (quarter note) of the second measure have the ``accid.ges`` attribute. There should be no reason why that quarter note does not have that attribute as well. But I guess it doesn't matter since none of the notes have the ``accid.ges`` attribute using the latest version of the library.

[verovio-toolkit.zip](https://github.com/rism-ch/verovio/files/1228445/verovio-toolkit.zip)
[test2.zip](https://github.com/rism-ch/verovio/files/1228446/test2.zip)

**Comment by lpugin** [comment]
> The `<g class="accid">` element doesn't indicate the type of accidental. How do I extract this information from it?

You have to call `getElementAttr(accidid)`. That is, passing the `id` of the child accid and not of the parent note.

> Also, why does the accid.ges attribute no longer exist in the JSON object returned by vrvToolkit.getElementAttr(noteid) for a note with an accidental?

You will get the `@accid.ges` from the `<accid>` if it is present.

**Comment by euphonialabs** [comment]
This ``<g class="accid">`` element only exists for the first note in the measure that is sharpened/flattened. It does not exist for any of the notes following it within the same measure, even though they should have the same accidental applied to it. Therefore, I cannot even retrieve an accidid for an element that doesn't exist. Is there any other way to check the accidental on a note without querying the DOM?  

``vrvToolkit.getElementsAtTime(vrvTime)`` returns only note ids. Using these note ids, ``vrvToolkit.getElementAttr(noteid)`` returns only the color, duration, octave, pitch name, and stem direction. There is no ``accid.ges`` attribute even is the note has an accidental. Is this intentional or a bug?

**Comment by kepper** [comment]
Maybe I completely misunderstand the situation, but from my perspective, it seems like you should query the original MEI file, not an SVG instance generated from it by Verovio. Right now, you're trying to ask an image what it's sound is…

**Comment by euphonialabs** [comment]
@kepper Yes, ideally I would like to query the original MEI/XML file using the verovio toolkit as seen in the example I included in my first post on this issue. However, @lpugin advised to refer to the SVG via ``<g class="accid">`` and I explained the shortcomings of that approach in my post that proceeded yours. I do agree that referring to the SVG would be inefficient.

**Comment by lpugin** [comment]
> This `<g class="accid">` element only exists for the first note in the measure that is sharpened/flattened. It does not exist for any of the notes following it within the same measure, even though they should have the same accidental applied to it. Therefore, I cannot even retrieve an accidid for an element that doesn't exist.

You are right. This is fixed here https://github.com/rism-ch/verovio/commit/77861bb22d03069cb50d69e47844e50301198018
