### ISSUE TITLE
stem length + beam interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#683]
Probably a new thing (otherwise a feature enhancement instead of a bug :-): beamed notes do not extend all of the way to the middle line:

<img width="833" alt="screen shot 2017-08-27 at 7 53 32 pm" src="https://user-images.githubusercontent.com/3487289/29757546-78dc0714-8b61-11e7-8c48-4aa6d9d81f88.png">

The beamless notes in the 2nd and 5th measures are touching the middle staff line as expected.  But beats 2 and 3 in measures 1 and 4 have the beam too low.

I would expect more like this where all notes lower than middle C touch the middle line, both if they are stemless or if they are beamed to other notes:

<img width="1186" alt="screen shot 2017-08-27 at 8 01 17 pm" src="https://user-images.githubusercontent.com/3487289/29757736-e499bc98-8b62-11e7-89dc-a081d2599ee0.png">

Test data:

```
**kern
*M3/4
=1-
8cL
8BJ
8AL
8GJ
8FL
8EJ
=2
8c
8B
8A
8G
8F
8E
=3
4c
4B
16ALL
16G
16F
16EJJ
=4
8aaL
8bbJ
8cccL
8dddJ
8eeeL
8fffJ
=5
8aa
8bb
8ccc
8ddd
8eee
8fff
=5
4aa
4bb
16cccLL
16ddd
16eee
16fffJJ
==
*-
```

**Comment by rettinghaus** [comment]
This is less a beams problem than one of stem length. 
#630 #648

**Comment by lpugin** [comment]
Should be fixed

**Comment by craigsapp** [comment]
Looks great:

<img width="693" alt="screen shot 2017-08-28 at 6 42 30 am" src="https://user-images.githubusercontent.com/3487289/29776002-1ad084be-8bbc-11e7-8c57-f9810c2ba8f5.png">
