### ISSUE TITLE
Parsing of <harmony> from MusicXML is incomplete

### ISSUE THREAD

**Issue by yeonoson** [rism-ch/verovio#686]
Some sub-elements of a MusicXml <harmony> tag are not or only partly recognized:
- \<kind\> including its "use-symbols" attribute
- \<degree\> and its sub-elements: degree-value, degree-alter and degree-type

See following screenshot which shows measure 32 + 33 from "Moonlight Sonata Jazz Lead Sheet" rendered by MuseScore (left) and Verovio (right):

![harmony-incomplete-tags](https://user-images.githubusercontent.com/26634658/30132648-61d28820-9351-11e7-9cc0-973da7637537.png)

For Moonlight Sonata Jazz Lead Sheet see:
Link: https://musescore.com/ericfontainejazz/moonlight-sonata
MusicXML: [Moonlight_Sonata_Jazz_Lead_Sheet.xml.txt](https://github.com/rism-ch/verovio/files/1282544/Moonlight_Sonata_Jazz_Lead_Sheet.xml.txt)

**Comment by yeonoson** [comment]
It looks a lot better and complete now. However I noticed that there are still some chords that have an unusual ordering of the type-symbol and the number. I extracted these chords into a single measure: 
[wrong-harmony.xml.txt](https://github.com/rism-ch/verovio/files/1287701/wrong-harmony.xml.txt)

The rendering in MuseScore (left) and Verovio (right) looks like this:
![wrong-harmony](https://user-images.githubusercontent.com/26634658/30210029-ff9fd04a-949a-11e7-8a81-21f0d4bee2c2.png)

For the first chord I'm not sure if the rendering of MuseScore is correct at all, I think it should be G#7sus. But for the other chords the MuseScore rendering is correct.

This example (and also one measure of the unmodified "Moonlight Sonata Jazz") also shows another problem: There is no collision detection for harmonies. It is even more severe if another harmony is added to the second note. As this is another issue, should I create a new issue for this?

**Comment by rettinghaus** [comment]
For now it is a simple to-Text conversion, not very flexible. Also the MusicXML documentation is rather bad at this point. I'll improve the behaviour at some point. 
Regarding the "collision detection": I think there is already an issue. You should check this.

**Comment by lpugin** [comment]
Indeed, the alignment issue was already filed here https://github.com/rism-ch/verovio/issues/388
