### ISSUE TITLE
Change SVG style attribute to separate attributes

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#69]
Instead of having one single style attribute in SVG /g, we could have separate attribute for each parameter (stroke, stroke-opacity, fill, etc). This would make the building of the SVG tree cleaner.

Alternatively, we could have a CSS, but this can be left for a later enhancement.

**Comment by lpugin** [comment]
@kepper do you have any opinion on this?

**Comment by kepper** [comment]
I wouldn't do CSS by default, as it requires people to load another file. Right now, using Verovio is bloody simple, and I'd recommend to keep it like that. Having separate attributes for stroke and fill seems reasonable and might be helpful when someone wants to use the verovio SVG output in other applications (SVG editors etc.). However, I'd say that this doesn't need a very high priority – browsers will render the SVG both ways…
