### ISSUE TITLE
Include rest notes in timemap

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#691]
@craigsapp, Is there any reason that rest notes are not included in the timemap json?

**Comment by lpugin** [comment]
Yes, because they produce no sound...

**Comment by k-ljung** [comment]
As we use the timemap feature is to indicate where in the notes you are, this through a horizontal bar that scrolls, based on this scenario, it would help us if the rest notes are  include.

**Comment by lpugin** [comment]
I am happy to accept a PR for this.

**Comment by craigsapp** [comment]
I am sure.

**Comment by vitto32** [comment]
@k-ljung did you find a solution?

**Comment by k-ljung** [comment]
@vitto32, unfortunately not
