### ISSUE TITLE
Project doesn't compile in Visual Studio 2017

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#692]
When I'm trying to compile the project as a Visual Studio 2017 solution I get the following errors:

`'GetVersion': ambiguous call to overloaded function | verovio | C:\_Projects\Verovio\tools\main.cpp | 60 `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30256 |  `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30258 |  `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30817 |  `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30820 |  `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30936 |  `

`Error | C3861 | 'not': identifier not found | verovio | C:\_Projects\Verovio\src\hum\humlib.cpp | 30939 |  `

**Comment by lpugin** [comment]
First error is fixed

**Comment by lpugin** [comment]
@craigsapp ?

**Comment by k-ljung** [comment]
@craigsapp tested today with latest code in develop branch but still same error, @lpugin fixed the first error.

Any idea?

**Comment by lpugin** [comment]
You can add -DNO_HUMDRUM if you are not using the humdrum toolkit, but of course this is not really a fix.

**Comment by k-ljung** [comment]
I manage to compile the project but verovio craches when generating svg. 
I'm trying to convert musicxml to SVG, do I need the humdrum toolkit?

**Comment by lpugin** [comment]
No, the direct MusicXML importer is builtin by default.

**Comment by rettinghaus** [comment]
Could be helpful, to have the input file, or at least a full error description.

**Comment by craigsapp** [comment]
I didn't see this last week...  I avoid `not` as a logical operator for just such a situation, since visual studio (2013) does not allow `not` by default as a substitution for `!` (but these popped up in code I didn't write).

The `not`s should now be removed from humlib in the most recent `develop` branch: https://github.com/rism-ch/verovio/commit/eff756adaf871e015ff97d5f5fd0505877b03b42

Related discussion about and/not vs &&/|| in visual studio:

https://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators

According to this page, adding the code:

```c
#include of <iso646.h>
```

Would allow for `not` to be equivalent to `!`.

**Comment by craigsapp** [comment]
> I manage to compile the project but verovio craches when generating svg.
I'm trying to convert musicxml to SVG, do I need the humdrum toolkit?

I am wondering if you were converting with the input format being `musicxml-hum` which is the Humdrum-based path to convert MusicXML to MEI.  If Humdrum is not compiled into verovio, then this option probably would behave poorly...

**Comment by k-ljung** [comment]
@craigsapp the project is now compiled fine under Visual Studio 2017 after your fixes but verovio.exe is still craching when converting the file.

It is the:
`
std::string MusicXmlInput::GetContent(pugi::xml_node node)
{
    assert(node);

    if (node.text()) {
        return std::string(node.text().as_string());
    }
    return "";
}
` 
in iomusxml.cpp causing it to crash. The pugi::xml_node node seams to be null.

I runt `verovio -f musicxml Pride.xml -r C:\_Projects\Verovio\data`

**Comment by craigsapp** [comment]
One thought is that somehow the font is not being loaded correctly.  Is this exactly the same way that you have done the conversion in the past?  Did you do it always in Windows, or in linux previously?

For the resource directory:

```
-r C:\_Projects\Verovio\data
```

Unix/linux would not like the back slashes, and they would need to be doubled to escape the backslash.

If you are using a DOS terminal in Windows, then the backslash should be ok.

-----------

Another thing to double check is that there is content in `Pride.xml` and that it is readable.

And another check to try is to load the musicxml through Humdrum (if you have compiled with Humdrum code):

```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data
```

If that works, then there is a bug in iomusxml.cpp, but if there is a similar error, then it is probably a more general problem (I suspect font resource location the most).

Or try to output to MEI instead of SVG and see what happens:

```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data -t mei --all-pages --no-layout
```

Or MIDI:

```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data -t midi 
```

**Comment by k-ljung** [comment]
I usually do the conversion on my Mac and there it works fine, now I want to integrate the conversion into my application built in .NET C# and need a exe file, so this conversion is on a Windows running in the DOS terminal.

The Pride.xml is readable, I have debugged the `toolit.cpp` and the method `bool Toolkit::LoadData(const std::string &data)`, parameter `&data` contains the content from Pride.xml.

`input = new MusicXmlInput(&m_doc, "");` the variable `&m_doc` contains:
```
{m_header={_buffer=0x0000000000000000 <NULL> _memory=0x0000001ae34febc0 "(ìOã\x1a" } m_scoreDef={m_setAsDrawing=...} ...}
    vrv::Object: {m_unsupported={ size=0 } m_children={ size=0 } m_parent=0x0000000000000000 <NULL> ...}
    m_header: {_buffer=0x0000000000000000 <NULL> _memory=0x0000001ae34febc0 "(ìOã\x1a" }
    m_scoreDef: {m_setAsDrawing=false m_drawLabels=false m_drawingWidth=0 }
    m_drawingPageHeight: -858993460
    m_drawingPageWidth: -858993460
    m_drawingPageLeftMar: -858993460
    m_drawingPageRightMar: -858993460
    m_drawingPageTopMar: -858993460
    m_drawingBeamMinSlope: -107374176.
    m_drawingBeamMaxSlope: -107374176.
    m_drawingJustifyX: true
    m_drawingEvenSpacing: false
    m_drawingSpacingLinear: 0.25000000000000000
    m_drawingSpacingNonLinear: 0.59999999999999998
    m_drawingMinMeasureWidth: -858993460
    m_type: Raw (0)
    m_style: 0x000001ea3d604f50 {m_unit=90 m_landscape=0 '\0' m_staffLineWidth=20 ...}
    m_drawingPage: 0x0000000000000000 <NULL>
    m_drawingUnit: -858993460
    m_drawingDoubleUnit: -858993460
    m_drawingStaffSize: -858993460
    m_drawingOctaveSize: -858993460
    m_drawingBeamWidth: -858993460
    m_drawingBeamWhiteWidth: -858993460
    m_drawingLedgerLine: -858993460
    m_drawingBrevisWidth: -858993460
    m_drawingSmuflFontSize: 0
    m_drawingLyricFontSize: 0
    m_drawingSmuflFont: {pointSize=0 family=0 style=FONTSTYLE_NONE (0) ...}
    m_drawingLyricFont: {pointSize=0 family=0 style=FONTSTYLE_NONE (0) ...}
    m_currentScoreDefDone: false
    m_drawingPreparationDone: false
    m_hasMidiTimemap: false
    m_pageWidth: -1
    m_pageHeight: -1
    m_pageLeftMar: 0
    m_pageRightMar: 0
    m_pageTopMar: 0
    m_spacingStaff: 10
    m_spacingSystem: 6
    m_scoreBuffer: 0x0000000000000000 <NULL>
```
If I set `-r C:\_Projects\Verovio\data` to other directory I get this error:
```
[Error] Font directory 'C:\_Projects\Verovio\/Bravura' cannot be read
[Error] Bravura font could not be loaded.
[Error] Font directory 'C:\_Projects\Verovio\/Leipzig' cannot be read
[Error] Leipzig font could not be loaded.
[Error] Expected 228 default SMUFL glyphs but could load only 0.
The music font could not be loaded; please check the contents of the resource directory.
```
If I try your other suggestions
```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data
```
or
```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data -t mei --all-pages --no-layout
```
or
```
verovio -f musicxml-hum Pride.xml -r C:\_Projects\Verovio\data -t midi 
```
I get the same error:
```
[Message] Unsupported format
The file 'Pride.xml' could not be opened.
``` 

@craigsapp do you have access to a Windows development environment?

**Comment by k-ljung** [comment]
@craigsapp did you see my last comment?

**Comment by k-ljung** [comment]
In the case above with Pride.xml, it is the file that somehow wrong, I managed to get it to work with another xml file.

The strange thing, though, is that it works on my Mac to convert Pride.xml but not on my Windows
