### ISSUE TITLE
PAE multiple grace notes not working properly

### ISSUE THREAD

**Issue by xhero** [rism-ch/verovio#694]
qq...r creates weird results:

`'4Bt6qq{xAB}r/''4E8D6-{D8.E6F}/4A8G`

<img width="511" alt="schermata 2017-09-18 alle 13 40 26" src="https://user-images.githubusercontent.com/1691778/30540404-5374c016-9c77-11e7-8315-e614c8254c1a.png">

This problem happens cyclically when refreshing the input, sometimes disappearing, so it probably is a PAE parsing problem.

**Comment by lpugin** [comment]
This was fixed in the latest version (See #613)
