### ISSUE TITLE
Nested tuplets do not render/play correctly

### ISSUE THREAD

**Issue by euphonialabs** [rism-ch/verovio#695]
[test.zip](https://github.com/rism-ch/verovio/files/1312978/test.zip)
I've attached a MusicXML file containing examples of nested tuplets which are not rendered and played correctly by Verovio.

**Comment by craigsapp** [comment]
This file was created with MuseScore 2.1.0.  Loading the MusicXML file into MuseScore 2.1.0 again lists errors in the file:

<img width="420" alt="screen shot 2017-09-18 at 10 00 04 pm" src="https://user-images.githubusercontent.com/3487289/30576464-e6ac8bee-9cbc-11e7-9309-a0200c2a6f7c.png">

So you will have to first go to over to https://musescore.org/en/project/issues/musescore to have them fix the output from MuseScore first.

When loading the file into MuseScore but ignoring errors, there are no nested tuplets remaining:

<img width="1391" alt="screen shot 2017-09-18 at 10 04 22 pm" src="https://user-images.githubusercontent.com/3487289/30576530-5b9faefe-9cbd-11e7-8b51-62b7537a8b4f.png">

Try saving that output to MusicXML and converting to MEI with verovio, and you might have better luck.

**Comment by craigsapp** [comment]
Nested tuplet export problems in MuseScore already reported:

https://musescore.org/en/node/14131

and

https://musescore.org/en/node/22547

**Comment by craigsapp** [comment]
If you use a compound meter, one level of tuplets will be removed:

<img width="688" alt="screen shot 2017-09-18 at 10 31 35 pm" src="https://user-images.githubusercontent.com/3487289/30577145-276b7dda-9cc1-11e7-99b0-a02d82036c1c.png">
