### ISSUE TITLE
DARMS import

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#697]
What is the status of DARMS input? I tried it with some files I found, but it doesn't seem to work. Also it is not documented on the Website. 
If it is not really needed, perhaps we should introduce `NO_DARMS_SUPPORT` and switch it of by default?

**Comment by lpugin** [comment]
> we should introduce NO_DARMS_SUPPORT and switch it of by default?

I am OK with this because it is indeed currently probably quite broken

**Comment by rettinghaus** [comment]
Then I'll add those lines over the next days.

**Comment by craigsapp** [comment]
It does not work on the DARMS files that I have, so it could be for a certain variant of DARMS.
