### ISSUE TITLE
using "topic09-midi.html" template

### ISSUE THREAD

**Issue by Alex50101** [rism-ch/verovio#699]
Hello,
In my project I would put the example No. 9 from verovio tutorial in an additional html-folder and rename it. However, it stops working even if I leave it in the same folder and just rename it.
best regards
Alex

**Comment by ahankinson** [comment]
Do you see any errors in your browser's developer console?

**Comment by lpugin** [comment]
It is probably related to the `wildwebmidi.data` file that needs to be in the root, I think

**Comment by Alex50101** [comment]
1. This is how it looks if I put the file in an html folder (with proper paths, of course): [screenshot]( http://prntscr.com/gs7451). This time the renamed file in the original folder could be played...

2. There was a bug marked in script where the time variable should be divided by two as solution. 
 However, for me it worked well when I deleted the division and set the adjustment to "-90"

 ```
   // bug! time needs to be divided by 2
                    $("#midi-player").midiPlayer.seek(time);
```

```
 // bug! time needs to be * 2 (- 800 for adjustment)
                var vrvTime = Math.max(0,  time - 90);
```

3. MIDI and SVG output isn't supported by Chrome and IE, isn't it? (I didn't test it with Opera, though)

best alex

**Comment by lpugin** [comment]
> MIDI and SVG output isn't supported by Chrome and IE, isn't it? (I didn't test it with Opera, though)

No, there are both fully supported. Also, please do not mix up topics in one issue.
