### ISSUE TITLE
Placement of verovio library for qt demo

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#704]
The qt directory is in `verovio/bindings/qt`, but as part of the compiling process, a directory called `verovio/build` needs to be made to compile a dynamic library version of verovio for qt.

(1) Can the directory name `build` be made less generic?   Such as `build-library` or `verovio-library`?

(2) This is specifically for use in the qt project, so should it not go into `verovio/bindings/qt/build` rather than `verovio/build`?

Having it in the root directory is fine since having a directory dedicated to creating the dynamic library is reasonable, but what happens if some other project uses the same directory name for another purpose?

**Comment by lpugin** [comment]
qt now looks for the verovio library in `./verovio/tools`, which you will get if you run `cmake. BUILD_AS_LIBRARY=on` in `./verovio`

**Comment by craigsapp** [comment]
Or more precisely:

```
cmake . BUILD_AS_LIBRARY=on
```

The file `verovio/bindings/qt/README.md` should be updated for that, which also solves issue #705
