### ISSUE TITLE
Request: measures numbers

### ISSUE THREAD

**Issue by robertogianf** [rism-ch/verovio#708]
Hello,
it would be useful to force having measure numbers even when you create an SVG with the noLayout option; maybe it would be useful to decide on the frequency of the measures numbers (only odd, only even, every 5 measures).

Thank you for your work!

**Comment by craigsapp** [comment]
Same as or similar to issue https://github.com/rism-ch/verovio/issues/177

**Comment by lpugin** [comment]
Indeed a duplicate
