### ISSUE TITLE
staffGrp: "bracket" or "brace" should assume "line"

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#71]
For a single group of staves with @symbol="bracket" or @symbol="brace" verovio should also assume a "line" as it isn't necessary to have nested staffGrp. 
(See for example Ahle_Jesu_meines_Herzens_Freud.mei)

Or would that be an MEI issue?

**Comment by lpugin** [comment]
This is unclear in MEI and will be clarified in the next MEI release. By default, bracket or brace should indeed assume a line.

**Comment by lpugin** [comment]
Fixed in commit a711d9e6dcc6e7e3d73a7c50eac365aa4d924110
Drawing thick line (meaning of attribute symbol="line" for the next release of MEI) needs to be implemented
