### ISSUE TITLE
Update sample image

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#712]
On the page http://www.verovio.org/command-line.xhtml there is a sample image:

![screen shot 2017-10-17 at 4 28 50 pm](https://user-images.githubusercontent.com/3487289/31694288-45184874-b358-11e7-81c8-55e9fb4ed6bd.png)

that would be good to update.  However, when I use the given command to generate a new SVG:

```bash
verovio -f mei -o output.svg Hummel_Concerto_for_trumpet.mei
```
(note that `-f mei` is no longer required due to verovio auto-detecting the MEI content of the file.)

I get this:

![screen shot 2017-10-17 at 4 29 35 pm](https://user-images.githubusercontent.com/3487289/31694308-626cf7ee-b358-11e7-98e2-520af869f481.png)

which is a bit crowded....

-------

When trying `--spacing-linear=2.0` I get the message:

```
[Error] Spacing (linear) out of bounds; default is 1, minimum is 0, and maximum is 0
```

This is also true for `--spacing-non-linear=2.0`:

```
 Spacing (non-linear) out of bounds; default is 1, minimum is 0, and maximum is 0
```

So the maximum value should be increased from 0... 😄 

But trying other values of `--spacing[-non]-linear` does not seem to change the spacing and I am always getting 11 measures for the first page of the concerto, rather than the 5 or 6 that would be preferable.

--------------

When I try a simple example, the option `--spacing-linear=0.9` is working:

First with the default spacing:

![screen shot 2017-10-17 at 4 57 17 pm](https://user-images.githubusercontent.com/3487289/31694962-410ea83c-b35c-11e7-9f5c-a8b69265ae12.png)

Then with the option `--spacing-linear=0.9` added:

![screen shot 2017-10-17 at 4 57 47 pm](https://user-images.githubusercontent.com/3487289/31694970-5252d4f6-b35c-11e7-98a9-5274cdd88b2f.png)

Perhaps there is an invalid rhythm which is getting transformed into a breve for display.  Using a breve will influence the layout spacing, but it still does change.  Here is the case where I add a breve to the last measure of music otherwise in quarter notes, and using `--spacing-linear=0.9` to render:

![screen shot 2017-10-17 at 5 00 25 pm](https://user-images.githubusercontent.com/3487289/31695016-aef1c262-b35c-11e7-808d-ac9ea3c10a78.png)

Adding a long instead of a breve:

![screen shot 2017-10-17 at 5 01 31 pm](https://user-images.githubusercontent.com/3487289/31695047-dd1242d4-b35c-11e7-8d70-fe665aa79007.png)

with the default spacing generating:

![screen shot 2017-10-17 at 5 08 33 pm](https://user-images.githubusercontent.com/3487289/31695180-e0c83f9a-b35d-11e7-9da1-60c5c3c47960.png)

If the spacing problem in the Hummel concerto is related to this, then it would be good to review the adjustment made related to breve/long/maxima notes.

Here is the test piece with quarter notes, with the last note set to a long:

```
**kern
*M4/4
=1
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
4c
4d
4e
4f
=
00g;
==
*-
```

**Comment by lpugin** [comment]
You probably need to add `--ignore-layout`

**Comment by craigsapp** [comment]
Thanks!  That worked.  Perhaps that should be added to the example usage (or remove the layout from the file).

<img width="693" alt="screen shot 2017-10-17 at 11 36 21 pm" src="https://user-images.githubusercontent.com/3487289/31703996-1c526b72-b394-11e7-8092-c48c45dc93f7.png">

**Comment by craigsapp** [comment]
Hmmm, where should webpage updates go?  In `gh-pages` or `gh-pages-develop`?  And should it be a pull request or can I do it directly?
