### ISSUE TITLE
Negate --no-layout to --use-layout?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#714]
Is there currently any project which uses the layout elements in MEI data when printing with verovio?

"Layout" seems to mean only system and page breaks (`<sb>` and `<pb>` elements), however there is other important layout information needed for those line breaks to be useful.  The most important being the scaling of the music on the page, as well as the width, and then height of the page.  These are currently supplied by verovio in the cases that I have seen, and not taken from the data.  How would these be stored in an MEI file, and does verovio currently utilize these settings if they are present?  Should verovio automatically ignore `<sb>` and `<pb>` if the other important settings to given them context are not present?

Issues #291, #712, #713, #662, #638 and probably others are caused by problems with layout.

It would probably be better if `--no-layout` was removed and then replaced with `--use-layout` which is a negation of the `--no-layout` option.

**Comment by lpugin** [comment]
Maybe we can rename it it to `--no-pagination` (and `--ignore-pagination`)? This would be clearer, I think, and also avoid the additional confusion that negating options would introduce.

**Comment by pe-ro** [comment]
Perhaps I'm missing something, but I like Craig's suggestion of `--use-layout`, which to me is a clear command to use the layout info provided in the file.  If said info doesn't exist, then `--use-layout` has no effect.  The command for the default action; that is, Verovio-provided layout, is simpler -- just don't supply `--use-layout`.

**Comment by lpugin** [comment]
OK, then `--ignore-layout` becomes `--use-layout` and `--no-layout` remains. Everybody is OK with this?

**Comment by craigsapp** [comment]
> OK, then `--ignore-layout` becomes `--use-layout` and `--no-layout` remains. Everybody is OK with this?

That is OK with me, depending on what the above Swissglish means :-). `--ignore-layout` is the same as `--no-layout`, and `--ignore-layout` is the opposite of `--use-layout`.   So `--use-layout` will be added to actively preserve `pb`/`sb`; while `--no-layout` remains but function like an appendix by having no function (since the default behavior with no options will be the same as using `--no-layout`).

In other words, `--no-layout` will remain to allow current command-line scripts to not break (Javascript verovio toolkit probably won't care if there is an unknown option in its input).

------------

`--no-pagination` is not good because its meaning is ambiguous: the music will be paged regardless, but it should be done automatically and not from `pb`/`sb` in the data.  The current option `--no-layout` is also confusing in the same manner.

`--ignore-pagination` this is better as an alias for the current `--no-layout`.  "Pagination" seems to only imply ignoring `<pb>` but keeping `<sb>` information, so still somewhat ambiguous.

**Comment by lpugin** [comment]
No, `--no-layout` remains as it is now and is not changed. It is only `--ignore-layout` that is replaced by its negation `--use-layout`, which I would suggest to call `--use-encoded-layout` instead. What needs to be decided is what happen if we send contradictory options, that is `--no-layout` and `--use-encoded-layout` at the same time. I would suggest to have `--no-layout` having a precedence.

Pagination: `--no-pagination` is not ambiguous because it would not to produce any pagination at all. And `--use-encoded-pagination` take `<pb>` and `<sb>` into account. (You are complaining that `<pb>` is not all the layout, hence the proposal.)

**Comment by kepper** [comment]
Since all layout options are related, wouldn't it be more comprehensible to put everything under a common --layout flag, which can take three different values? These options could be: "use layout information as given in the file", "let Verovio determine adequate breaks" and "put everything on one system". For me, just changing names and defaults doesn't solve the most confusing issue, which is the relation between these three options. If all of them would live behind the same flag, life would be much easier from my perspective…

**Comment by craigsapp** [comment]
I was not particularly aware that there was both `--ignore-layout` and `--no-layout` and/or that they are different.  So what I really meant was replace `--ignore-layout` with `--use-layout`  to require active observance of `<pb>` and `<sb>`.

Command-line help:

```
--ignore-layout            Ignore all encoded layout information (if any)
                            and fully recalculate the layout
--no-layout                Ignore all encoded layout information (if any)
                            and output one single page with one single system
```

One problem is that both of these options use the word `layout`, which causes confusion.  The option `--no-layout` should stay as it is, and the term "layout" should be changed in the other option.

So I am currently liking  `--use-encoded-pagination` the best, but preferring it to be shorter as in `--use-pagination`.  This would replace the current `--ignore-layout`, also reversing its meaning.

-----------

Note that MIDI output is messed up by `<pb>` unless `--no-layout` is turned on.  Why is layout being done when generating MIDI files, since the layout should not be audible?

-------

> Since all layout options are related, wouldn't it be more comprehensible to put everything under a common --layout flag, which can take three different values? These options could be: "use layout information as given in the file", "let Verovio determine adequate breaks" and "put everything on one system". For me, just changing names and defaults doesn't solve the most confusing issue, which is the relation between these three options. If all of them would live behind the same flag, life would be much easier from my perspective…

Yes, from a user's point of view, the `--no-layout` option is quite confusing, and linguistically `--ignore-layout` has about the same meaning.

As separate flags:

`--no-layout` could be renamed `--single-system` or `--no-breaks`.

`--use-pagination` or `--use-breaks` would be the opposite of the current `--ignore-layout`

and no option would mean the current `--ignore-layout`.

As a single flag:

`--breaks none` == equivalent to `--no-layout`

`--breaks encoded` == equivalent to current default

`--breaks auto` or `--breaks ignore` would be the default, where verovio decided on where breaks should be added.

**Comment by lpugin** [comment]
`--breaks none` == equivalent to `--no-layout`
`--breaks encoded` == equivalent to current default
`--breaks auto` == verovio decides where breaks should be added (default)

Everybody OK with this?

**Comment by craigsapp** [comment]
That sounds great to me.

**Comment by kepper** [comment]
perfect, especially since it's not referring to layout in general, but breaks specifically…

**Comment by pe-ro** [comment]
+1

**Comment by axgeertinger** [comment]
Looking forward to this. The current terminology appears somewhat confusing to me. Using the js toolkit, I have been unable so far to make Verovio recognize encoded system breaks (`<sb>` elements) at all. If I understand the documentation correctly, specifying _no_ layout option should make Verovio render the encoded breaks, right? But Verovio keeps making its own layout. I have also tried passing the option ignoreLayout: 1 or ignoreLayout: 0 just to see the difference, but apparently it does not change anything. What have I missed?

**Comment by lpugin** [comment]
Currently the default (no parameter passed) will make Verovio recognize encoded system breaks. (If it does not this might be because there is not `<pb/>` provided - see https://github.com/rism-ch/verovio/issues/728)

**Comment by axgeertinger** [comment]
Oh, I see! Adding a `<pb>` did the trick. Thank you! I had no idea a page break was required.

**Comment by lpugin** [comment]
9b82ef9e0f82e7f58399b524c47065de98e12f70

(Default is `--breaks auto`)
