### ISSUE TITLE
Whole-note tremolos always rendered as 32nds

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#718]
The following MEI data renders a 16th-note tremolo on a whole note with three slashes rather than two:

<img width="385" alt="screen shot 2017-11-06 at 7 42 34 am" src="https://user-images.githubusercontent.com/3487289/32449498-944291ca-c2c6-11e7-9324-ee650e57e1ce.png">

Example MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Title</title>
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-11-06T07:42:54" version="2.0.0-dev-ae70647-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from MusicXML</p>
                </application>
            </appInfo>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef clef.shape="G" clef.line="2" key.sig="0" meter.count="4" meter.unit="4" n="1" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure right="end" n="1">
                            <staff n="1">
                                <layer n="1">
                                    <bTrem>
                                        <note dur="1" oct="4" pname="b" stem.mod="2slash" />
                                    </bTrem>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

The parameter `note@stem.mod="2slash"` can be changed to `1slash`, and there are still three slashes in the tremolo.

**Comment by lpugin** [comment]
This problem was quite likely introduced when the Stem object was introduced. Since the whole note has no stem, no stem modifier is found.

**Comment by craigsapp** [comment]
Probably because `bTrem@unitdur` should be used instead of `note@stem.mod` in such cases:

<img width="580" alt="Screen Shot 2019-03-18 at 12 26 03 AM" src="https://user-images.githubusercontent.com/3487289/54506635-cc29ab80-4913-11e9-96b5-4f32ed5ba705.png">


MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Title</title>
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-11-06T07:42:54" version="2.0.0-dev-ae70647-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from MusicXML</p>
                </application>
            </appInfo>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef clef.shape="G" clef.line="2" key.sig="0" meter.count="4" meter.unit="4" n="1" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure right="end" n="1">
                            <staff n="1">
                                <layer n="1">
                                    <bTrem unitdur="16">
                                        <note dur="1" oct="4" pname="b" />
                                    </bTrem>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by craigsapp** [comment]
However the current documentation:

https://music-encoding.org/guidelines/v4/content/cmn.html#cmnTrem

Says:

<img width="881" alt="Screen Shot 2019-03-18 at 12 27 43 PM" src="https://user-images.githubusercontent.com/3487289/54545740-a08cdc80-4978-11e9-9ed4-cb90bdad7dd0.png">

There are two interpretations of this (so it should be clarified or elaborated in the documentation -- in particular "must" should be changed to "should" since it is conditional on a complete visual representation and is allowed to be omitted otherwise).  The first is that the `note@stem.mod` slash parameter is required (in which case verovio does not completely implement `<bTrem>`), and the second is that `note@stem.mod` is optional if you do not want a full visual representation; in which case the slashes should be inferred from `bTrem@unitdur`.

The second interpretation is more useful in practice, and verovio has partially implemented this.  When `bTrem@unitdur` can be used to calculate the desired number of slashes on the beam, then `note@stem.mod` can (should) be omitted.   When the calculated slash count does not match the desired number of slashes, then `note@stem.mod` should be used to override the number of slashes on the note stem. (currently verovio ignores `note@stem.mod`).

**Comment by rettinghaus** [comment]
I just want to remind you of music-encoding/music-encoding#474
@lpugin and myself argued there some time ago that @stem.mod on note isn't the best approach anyway.

**Comment by craigsapp** [comment]
> I just want to remind you of music-encoding/music-encoding#474
@lpugin and myself argued there some time ago that @stem.mod on note isn't the best approach anyway.

Yes, using `note@stem.mod` to control the slashes for `<bTrem>` is ugly, since that attribute should be on `<bTrem>` rather than on the note (particular for cases such as whole notes which can have slashes for the tremolo mark, but they do not have stems).

Ideally `<bTrem>` should have a `slashes` (or recycle `fTrem@beam.float`) attribute that specifies the number of lines in the tremolo marking.  This could be used to optionally override the automatically calculated slash count from `btrem@unitdur`.

**Comment by lpugin** [comment]
I am still convinced we can improve MEI here. https://github.com/music-encoding/music-encoding/issues/474 I will re-open that issue.

**Comment by rettinghaus** [comment]
@lpugin The original issue here is solved, so this may be closed now …

**Comment by lpugin** [comment]
Thanks
