### ISSUE TITLE
Add score onset/offset for grace notes

### ISSUE THREAD

**Issue by hanwenbo** [rism-ch/verovio#720]
![image](https://user-images.githubusercontent.com/5869741/32647374-73cbe336-c5b6-11e7-9cc2-ab6bb09f1631.png)
![image](https://user-images.githubusercontent.com/5869741/32647382-7af42c36-c5b6-11e7-9423-79db72bcd7ab.png)

This bug will cause the note to be computed in 0 seconds

**Comment by craigsapp** [comment]
Technically not a bug, but would be an enhancement: grace notes are not yet assigned a position in the score:

https://github.com/rism-ch/verovio/blob/f612a16069163165ce16ea0fbdae6bda15bc8054/src/layerelement.cpp#L1240-L1241


Probably could be assigned score times easily.  Also grace notes are currently ignored in MIDI conversion:

https://github.com/rism-ch/verovio/blob/f612a16069163165ce16ea0fbdae6bda15bc8054/src/note.cpp#L820-L823

**Comment by hanwenbo** [comment]
Thank you. I'll study it

**Comment by lpugin** [comment]
Duplicate with #237
