### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#724]
Hello,

When trying to display this document: http://neuma.huma-num.fr/media/corpora/composers/cherubini/Requiem_Cherubini_Dies_Ireae/mei.xml

We get the following error.

Philippe

uncaught exception: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at jsStackTrace@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:1:1585608
stackTrace@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:1:1585779
abort@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:24:8318
abortOnCannotGrowMemory@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:1:1586661
enlargeMemory@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:1:1587106
rAa@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:16:1
Bna@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:12:1
Oxa@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:16:1
pya@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:16:1
sya@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:16:1
Hg@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:8:1
Zna@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:12:1
mpa@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:12:1
g6@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
y7@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
C7@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
x7@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
Y7@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
Z7@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:15:1
_W@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:11:1
$W@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:11:1
E$@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:11:1
bc@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:8:1
@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js line 1 > eval:1:218
verovio.toolkit.prototype.renderPage@http://neuma.huma-num.fr/static/js/verovio-toolkit-light.js:177:9
displayWithVerovio/<@http://neuma.huma-num.fr/static/js/neuma.js:80:23
n@http://neuma.huma-num.fr/static/js/jquery-1.7.min.js:2:14760
fireWith@http://neuma.huma-num.fr/static/js/jquery-1.7.min.js:2:15534
w@http://neuma.huma-num.fr/static/js/jquery-1.7.min.js:4:11659
d@http://neuma.huma-num.fr/static/js/jquery-1.7.min.js:4:17479

If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.  (source inconnue)

**Comment by lpugin** [comment]
This is usually due to a memory allocation failure with large files. But your file is not that large so this is weird. What version are you using? It seems to work with the MEI Viewer (latest develop version).

(One remark about the encoding: it seems that the lyrics (`<verse>`) have a `@n` increased for each staff. This does not make sense to me (unless I am overlooking something?) and causes weird spacing.)

**Comment by rigaux** [comment]
Thanks Laurent.

I took the last version. it works with Verovio, not with Verovio light. That's OK. Regarding the input, it comes from a Finale - MusicXML - XSLT transform. I'll tell my users to make it right.

issue closed !

Philippe
