### ISSUE TITLE
Display <fing> data

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#725]
It would be useful to have the possibility to render `fing` data. These elements contain individual finger numbers for played notes, see [http://music-encoding.org/documentation/3.0.0/fing/](http://music-encoding.org/documentation/3.0.0/fing/)

![add_64978-0003 cleaner2 - kopie](https://user-images.githubusercontent.com/8217108/33079302-92505d32-ced5-11e7-897f-aafbc180d264.jpg)

Sample encoding: https://github.com/music-encoding/sample-encodings/blob/master/MEI_3.0/Music/Complete_examples/Chopin_Etude_op.10_no.9.mei

**Comment by lpugin** [comment]
General feature request
