### ISSUE TITLE
No sound when playing MIDI

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#727]
Hi there,

When I combine with Verovio/MEI, I do not get any sound. Example here:

http://neuma.huma-num.fr/home/opus/composers:brumel:Brumel_missa/

Seems that everything is OK. I suspect that I need some audio samples. Help will be much appreciated.

Philippe

**Comment by lpugin** [comment]
I just replied on https://github.com/rism-ch/midi-player/issues/3 so let's track it there.

**Comment by rigaux** [comment]
Yes, sorry.
