### ISSUE TITLE
Verovio Setup in  Python 2.7 v. 3.6

### ISSUE THREAD

**Issue by ekoshelev** [rism-ch/verovio#729]
Hello,
I am a student currently working on Karen Desmond's measuring polyphony project.
I am having issues with getting verovio set up on my system (Ubuntu 17.04)
When running python 2.7, I have no problems retrieving the toolkit in verovio. In python 3.6 however, which we use for our website, I get the following error:
```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import verovio
>>> verovio.toolkit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'verovio' has no attribute 'toolkit'
```

Do you have any suggestions on how I can fix this problem? I would greatly appreciate any help.

**Comment by sonovice** [comment]
Could you give some more information how you compiled / installed Verovio in Python 3?

**Comment by ekoshelev** [comment]
I installed it first in virtual env without specifying the version:
```
cd project_folder
python3.6 -m pip install virtualenv
virtualenv polyphony
source polyphony/bin/activate
sudo apt-get install swig
sudo apt-get install python3-dev
*copy paste verovio directory into project_folder*
cd verovio
cd python
python setup.py build_ext
sudo python setup.py install
```
I then followed the steps again above specifying python3, and python3.6 in each install. I created a new environment and followed the steps with python 3.6.

Still the same original error where it can't find the toolkit in each virtual environment for python3.6.

I followed same steps above to install on my system (not in a virtual environment), and it worked for python2.7 and python3.6.

**Comment by lpugin** [comment]
Are you sure the `install` command installs verovio in the virtual environment?

**Comment by sonovice** [comment]
> Are you sure the install command installs verovio in the virtual environment?

That would also be my first guess. `sudo` does not use the user's environment, so make sure to execute  the actual "virtual" python:
`sudo /home/ekoshelev/venv/bin/python setup.py install` (or something close to it)
