### ISSUE TITLE
repeats in musicxml uploader

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#730]
Would be nice if the http://www.verovio.org/musicxml.html music xml uploader could also display more repeats, like 1st and 2nd ending, D.C./D.S. al Coda/Fine.

**Comment by lpugin** [comment]
General feature request.

**Comment by sannedubois** [comment]
Hello Laurent,

I received a notification about my requested feature and I saw that it's
closed. I'm not familiar with github, but does it mean that it;s not a
feature that will be implemented?

Kind regards,
Derk

2018-01-23 12:33 GMT+01:00 Laurent Pugin <notifications@github.com>:

**Comment by lpugin** [comment]
It will be implemented, but it is a general feature request and it does not bring much to have it listed here.
