### ISSUE TITLE
Page footer/header option(s)

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#736]
When `--adjust-page-height` is given as an option, then the page footer should not be displayed.

**Comment by craigsapp** [comment]
Related, what would a good option name to display/suppress the header/footer?  Obvious ones:

```
     --no-header
     --no-footer
```

And perhaps one option that can turn both off at the same time?

And as mentioned in the above message, `--adjust-page-height` should imply that the footer not be displayed; otherwise the page height cannot be adjusted.

Here is my temporary code for that for `src/toolkit.cpp`

```cpp
    // generate the page header and footer if necessary
    bool printHeaderFooter = true;
    if (this->GetAdjustPageHeight()) {
        printHeaderFooter = false;
    }
    if (printHeaderFooter) { // change this to an option
        m_doc.GenerateHeaderAndFooter();
    }
```

The header should probably still be displayed by default of `--adjust-page-height` is given since that will not affect the shrinking of the page to the last system on the page.

**Comment by lpugin** [comment]
I would like to see how to facilitate adding parameters to the cli. I have started to refactor the Style class and it will be easy to set the parameters with the json options. However, for the cli, it is a lot of hand-coding to add. Any ideas?

**Comment by craigsapp** [comment]
I use a class called Options to handle command-line options in my cli programs (included in humlib):

https://github.com/craigsapp/humlib/blob/master/include/Options.h
https://github.com/craigsapp/humlib/blob/master/src/Options.cpp

It allows for option aliases (short/long names for options).  Options are stored as strings, and can be extracted as booleans (whether they were given on the command-line or not), integers, doubles or strings, and they can have default values.

Example:

```cpp
#include <iostream>
#include "Options.h"

using namespace std;
using namespace hum;

int main(int argc, char** argv) {
   Options opts;
   opts.define("n|number=d:25");
   opts.define("b|boolean=b");
   opts.define("s|string=s:this is a string");
   opts.process(argc, argv);

   cout << "Number  = " << opts.getInteger("number") << endl;
   cout << "String  = " << opts.getString("string") << endl;
   cout << "Boolean = " << opts.getBoolean("boolean") << endl;

   return 0;
}
```

The option definition string such as:

```
     "n|number=d:25"
````

has the syntax:

```
     "option-name[|alias-1[|alias-2[|alias-3]]]=type[:default]"
```
The definition starts with the name of the option (either long or short), followed by a list of aliases for the same option separated by `|` characters.  Then an equals sign followed by the expected data type: `b` = boolean (no arguments to follow the option, `i` = integer: integer argument expected after option name, `d` = double, `s` = string.  Then optionally a colon (`:`) followed by the default value if no command-line use of the option is given.

Command-line use follows the POSIX guidelines for options.  Single character options have a single dash before them, and can be concatenated with other single-character options.  Multi-character options are prefixed with two dashes.  Example runs of the above program, using only the default values:

```
myprogram

Number  = 25
String  = this is a string
Boolean = 0
```

Setting the boolean option:

```
myprogram  -b

Number  = 25
String  = this is a string
Boolean = 1
```

Changing options with short names:

```
myprogram  -bn40 -s "This is a new string"

Number  = 40
String  = This is a new string
Boolean = 1
```

Note that the space between the `n` and the `40` is optional in this case.

Changing the parameters with the long names:

```
myprogram --boolean --number=100 --string "This is yet another string"

Number  = 100
String  = This is yet another string
Boolean = 1
```

The `=` sign after long options are optional and can be substituted for a space (but one or the other is required for long options having their own argument).

**Comment by rettinghaus** [comment]
I would argue that header/footer are part of the layout, so `--no-layout` shout omit them. Is it necessary to deal with them separately? If so, I think xslt would be a better approach here.

**Comment by craigsapp** [comment]
`--no-layout` currently involves ignoring encoded system-breaks and line-breaks.  These are a very different category compared to headers (currently the title of the work), and the footer (logo/page numbers).  It would be necessary to address the features separately even if they were also lumped into a single off-switch option.

>  I think xslt would be a better approach here.

What do you mean by that?

**Comment by rettinghaus** [comment]
I would remove `<pgHead>` or `<pgFoot>` with XSL before rendering.

**Comment by lpugin** [comment]
@rettinghaus : `--no-layout` will be removed, so we need to think about it. In any case, I am not sure about that disabling the header in this case will be always desirable. So people will simply have to add --no-header.

Considering the option to remove `<pgHead>`: Verovio now generates one from the MEI header when nothing is provided, so we do need at least one option to switch this on or off. So --no-header seems to be appropriate in all cases.

**Comment by lpugin** [comment]
@craigsapp is 'hum_type' used?

**Comment by craigsapp** [comment]
Yes, the `--hum-type` option is used to embed pitch and rhythm into MEI note@type which then passes into SVG as class information (allowing embedded pitch and rhythm data in the SVG).  In other words I use it to add MIDI-like information to the SVG images.  

Without `--hum-type` a note is converted without adding the markup to `@type`:

```
<note xml:id="note-L3F1" dur="1" oct="4" pname="c" accid.ges="n" />
```

With `--hum-type` the same note:

```
<note xml:id="note-L3F1" type="qon-0 qoff-4 pname-c acc-n oct-4 b40c-2 b12c-0 " dur="1" oct="4" pname="c" accid.ges="n" />
```
This page demonstrates use of CSS on the resulting SVG image to color notes by pitch class or do music analysis on the SVG image directly:
     http://doc.verovio.humdrum.org/myvhv/svg_notes

**Comment by lpugin** [comment]
Added here b7fbcc64eeb8a5eac33a81e2fd4ad8cbc85c7aa4

**Comment by earboxer** [comment]
Is there a way when `--adjust-page-height` is given as an option, for the page footer to **be** displayed? (as if we just cut the white space out of the score with scissors and taped the footer back onto the score).

I think that should be the default behavior of `--adjust-page-height`, (with `--footer none` required if you really want to hide the footer).

**Comment by craigsapp** [comment]
The purpose of `--adjust-page-height` is to shrink the page to fit a short example, or to generate an SVG image of the entire movement into a long SVG image where the length of the page is not known or interesting.  In both cases a footer is less necessary than for a fixed height page.  In the case of the small examples, there may be many images on the same page, and a footer is not desired.  In the case of a very long page, the footer is of less use or interest since it is far down on the image.

**Comment by earboxer** [comment]
The use case for [my application](https://github.com/christian-classics-ethereal-library/dynamic-presentation) is just to vertically center the image (and still be able to see the header and footer), otherwise there will be an uneven distribution of blank space on the screen.

I think an easy way to solve this issue would be to define the footer negatively in the SVG (`y="100%" dy="-1100px"` in the following snippet).

```svg
          <g xmlns="http://www.w3.org/2000/svg" id="pgfoot-0000000496614672" class="pgFoot">
            <text x="0" y="100%" dy="-1100px" font-size="0px" >
               <tspan id="rend-0000000983891603" class="rend" text-anchor="start">
                  <tspan id="text-0000000642089721" class="text">
                     <tspan font-size="405px" class="text">My song's footer here</tspan>
                  </tspan>
               </tspan>
            </text>
         </g>
```

Would this be an acceptable technique to use for solving this here?

**Comment by craigsapp** [comment]
Yes, that is a good idea.  The placement of the footer is not currently optimal and would be good to refine further: it is attached directly below the bottom system on the page and it is difficult to adjust the margin between the bottom staff (except when there is a large space between the bottom of the staff and the bottom of the page size that last time I checked).

Here is a diagram for basic discussion of margins:

<img width="540" alt="Screen Shot 2020-11-04 at 3 33 22 PM" src="https://user-images.githubusercontent.com/3487289/98179211-209be900-1eb3-11eb-92d1-3fc786e5cdfd.png">

The footer would be given a specific height, and the footer would be bottom justified in that region.  This would allow controlling the margin between the footer and the music, particularly when `justifyVertically` is used.

Maybe a musicHeight could be used instead of pageMarginBottom?  And/or the footerHeight would be incorporated into the pageMarginBottom when calculating the musicHeight.

There are other complications dealing with the pageHeader, pageHeader2, and pageFooter2.   For example a musicHeight, and musicHeight2 or similar controls to adjust the margins on the title page versus the rest of the pages would be good.
