### ISSUE TITLE
--page-bot-mar?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#743]
In the list of options, I see three related to page margins:

```
 --page-left-mar <i>               The page left margin (default: 50; min: 0; max: 500)
 --page-right-mar <i>              The page right margin (default: 50; min: 0; max: 500)
 --page-top-mar <i>                The page top margin (default: 50; min: 0; max: 500)
```

There is no `--page-bottom-mar`.  Is that intentional? (In the Option class source code I see that there is also no `m_pageBottomMar` variable, so it must be.)

Also you use `mar` rather than `margin` -- is there a reason for that (three extra letters will not increase the length of the current option names very much :-), and `margin` is used in other option names (for element margins).   

It might be nice to also have a `--margin` or `--page-margin` option that would set all four margins to the same value, with the ability of using the individual margin options to override that global margin value.  This would function similar to the `--border` option which is going away, and would function similar to CSS `margin` and `left-margin`, `right-margin`, etc.

**Comment by lpugin** [comment]
I added the bottom margin option and renamed them pageMarginXXX.

**Comment by lpugin** [comment]
Having a pageMargin option would mean allowing -1 for pageMarginXXX options. Then these would be used only if they have a value greater than -1.

**Comment by lpugin** [comment]
Any better idea for the default value?
