### ISSUE TITLE
--format input labels

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#744]
For the `--format` option, the command-line help documentation says:

```
 -f, --format <s>      Select input format: darms, mei, pae, xml (default is mei)
```
However, the code in toolkit.cpp requires `musicxml` rather than `xml` as the option argument:

https://github.com/rism-ch/verovio/blob/2dd2cfc78d459a3fb4d59cc6d14067e0b4255331/src/toolkit.cpp#L125-L127

So either the documentation should be change `xml` to `musicxml`, or the code should be changed to allow for `xml` as an alias for `musicxml`, such as:

```cpp
 else if ((informat == "musicxml") || (informat == "xml")) { 
     m_format = MUSICXML; 
 } 
```

**Comment by lpugin** [comment]
changed c8bbb8f8ef7e73db0436c060ba661b769ffdcb89
