### ISSUE TITLE
type option in emscripten

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#745]
This message will be displayed if the `type` option is given to the javascript toolkit of verovio:

```
verovio-toolkit.js:1 [Error] Unsupported option 'type'
```

which comes from the line:

https://github.com/rism-ch/verovio/blob/2dd2cfc78d459a3fb4d59cc6d14067e0b4255331/src/toolkit.cpp#L622

This error message does not show in the command-line version of verovio, and it also seems that the `type` option (to select the output data type) seems to be working in the emscripten version (I can select svg or mei output using the `type` option).  So perhaps the `type` option is not being filtered out at a point where it should be.

**Comment by lpugin** [comment]
Indeed, just before in the loop. I'll fix it.

**Comment by lpugin** [comment]
Do you use it for the humdrum toolkit? Because otherwise it does not make sense to pass the output option to the JS toolkit. The output type is implicitly define by the calls to it (e.g., renderToMidi, renderToSvg)

**Comment by craigsapp** [comment]
Indeed.  The `type` option is not needed in the javascript toolkit.  I am using `vrvToolkit.getHumdrum()` to extract humdrum output, and `.getMEI()` for MEI data, etc.
