### ISSUE TITLE
Possible issue with alignment of parts (and Midi output) of mensural MEI in perfect mensurations

### ISSUE THREAD

**Issue by karend27** [rism-ch/verovio#747]
Hi,
I'm not sure if this is a new issue, or if it's possible a problem with our code. I thought that this worked previously, but now when I render a piece with perfect mensuration, the alignment of the parts is off, and the midi rendering is also off. See the attached file fauvel_nous_MENSURAL
[fauvel_nous_MENSURAL.txt](https://github.com/rism-ch/verovio/files/1690728/fauvel_nous_MENSURAL.txt)
However, pieces that are in imperfect mensurations (imperfect modus, imperfect tempus) seem to work fine. See the attached file adesto_MENSURAL
[adesto_MENSURAL.txt](https://github.com/rism-ch/verovio/files/1690729/adesto_MENSURAL.txt)
Thanks!

**Comment by lpugin** [comment]
With the latest version you need to have `@notationtype="mensural"` on each `<staffDef>`. This attribute is new in MEI 4.0 and this is still poorly documented. Sorry about it.

```xml
<staffDef xml:id="m-30" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="triplum" lines="5" n="1" modusmaior="2" modusminor="3" tempus="3" notationtype="mensural">							
</staffDef>
<staffDef xml:id="m-33" clef.dis="8" clef.dis.place="below" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="motetus" lines="5" n="2" modusmaior="2" modusminor="3" tempus="3" notationtype="mensural">
</staffDef>
<staffDef xml:id="m-36" clef.dis="8" clef.dis.place="below" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="tenor" lines="5" n="3" modusmaior="2" modusminor="3" tempus="3" notationtype="mensural">
</staffDef>
```

(Also, I am noticing the with the clef with octava bassa will yield mixed old and new typefaces, with does not look good. Any ideas what to do with this?)

**Comment by karend27** [comment]
Oh okay - thanks. That's an easy fix. I'm not sure about the clef, but we do need it as the octave clef.
