### ISSUE TITLE
Static Att class member functions?

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#751]
The `Att` class:

https://github.com/rism-ch/verovio/blob/master/src/att.cpp

https://github.com/rism-ch/verovio/blob/master/include/vrv/att.h

Has a lot of functions that do not depend on class variables.  It would be nice to make such functions static so that they can be used without declaring a variable of type `Att`.

In other words, I am doing this to set the fontsize in a page header:

```cpp
        Att att;
        rend->SetFontsize(att.StrToFontsize("x-small", true));
```
But I want to do:

```cpp
        rend->SetFontsize(Att::StrToFontsize("x-small", true));
```

Or is there a better way of setting the fontsize to "x-small" for a Rend object?

**Comment by lpugin** [comment]
Why don't you just have a Att member in the importer? Then you can do

```
rend->SetFontsize(m_att.StrToFontsize("x-small", true));
``

**Comment by craigsapp** [comment]
> Why don't you just have a Att member in the importer? Then you can do

One reason is that the start of the `att.h` file says:

> It is not an abstract class but it should not be instantiated directly.

But in general all of the `x-To-y` sort of functions in the `Att` class are well suited to be static, since they do not contain any dependencies on internal state variables.  They could also be expressed as functions in a namespace rather than member functions of a class, which also implies that static member functions would work well.

**Comment by lpugin** [comment]
> It is not an abstract class but it should not be instantiated directly.

We should remove it

**Comment by craigsapp** [comment]
The comment, you mean?  I can do that, and also stick `static` in front of most of the functions in that class :-)

**Comment by lpugin** [comment]
You also need to modify the code produce by LibMEI (See https://github.com/rism-ch/verovio/blob/master/doc/guidelines.md#libmei and https://github.com/rism-ch/libmei).

**Comment by craigsapp** [comment]
At the moment I am bypassing using the `Att` class and instead trying to read in an MEI string (as you have noticed :-).

**Comment by lpugin** [comment]
One more comment on this question: I would suggest not to use the string converter but instead the enum data type. So setting the font size would be:
```
data_FONTSIZE fs;
fs.SetTerm(FONTSIZETERM_x_small);
rend->SetFontsize(fs);
```
I know this is one more line of code but this is due to the fact the data.FONTSIZE is now a compound data type in MEI (https://music-encoding.github.io/guidelines/v4/data-types/data.fontsize.html). It would still be better for code maintenance (e.g., if the values changes in the data types you will not notice it with the string but you will with the enum data types).
