### ISSUE TITLE
stacked rends too tightly spaced

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#764]
When two adjacent rends are done for the header(/footer), cases like this can occur:

<img width="884" alt="screen shot 2018-02-19 at 1 26 51 pm" src="https://user-images.githubusercontent.com/3487289/36397627-65c8254e-1578-11e8-84d6-cdcfc365ad0d.png">

In this case the COMPOSER text has no elements of the letters going below the baseline, and the 1900-2000 text extends the full height of the text, but there is no space to separate the two lines.  In other words, the line height is equal to the letter height, but the line height should be about 10% larger.

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>TITLE</title>
            </titleStmt>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5"/>
                        </staffGrp>
                        <pgHead>
                            <rend fontsize="x-large" halign="center" valign="middle">TITLE</rend>
                            <rend halign="right" valign="bottom" fontsize="small">COMPOSER</rend>
                            <rend halign="right" valign="bottom" fontsize="small">1900–2000</rend>
                        </pgHead>
                    </scoreDef>
                    <section>
                        <measure n="1">
                            <staff n="1">
                                <layer n="1">
                                    <mRest />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

There is also the case where the letters will drop below the baseline, and extra space is allocated in these cases:

<img width="261" alt="screen shot 2018-02-19 at 1 32 33 pm" src="https://user-images.githubusercontent.com/3487289/36397837-1577317e-1579-11e8-90e4-2a35ba550dcd.png">

But that is very tight with no space between the lines as well.  Also it is not great to space according to the bounding box of the text.  This would cause left/right aligned text to become out of alignment based on the contents of the text.  It would be better to control spacing by line height (dependent on the largest fontsize found on the line).

The line height should roughly be the sum of the maximum extent of the font below the baseline plus above the baseline, all multiplied by about 1.1 to add a 10% minimum spacing between characters on different lines.

**Comment by lpugin** [comment]
Improved 553ac4d3d787a720fa684ab6c53673aa000ef3d4
