### ISSUE TITLE
dynam + arpeg interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#772]
Dynamics and arpeggios are not aware of each other:

<img width="314" alt="screen shot 2018-02-25 at 12 37 01 pm" src="https://user-images.githubusercontent.com/3487289/36646130-496a1cf4-1a28-11e8-88e7-afec63258b9f.png">

(The forte and the arpeggio squiggle should not be touching each other).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-02-25T12:35:44" version="2.0.0-dev-89c99fa-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000982230592">
                <score xml:id="score-0000001484168428">
                    <scoreDef xml:id="scoredef-0000002064049474" midi.bpm="156">
                        <staffGrp xml:id="staffgrp-0000000500398529" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-0000000246987317" clef.shape="G" clef.line="2" key.sig="2f" meter.count="3" meter.unit="4" n="1" lines="5">
                                <label xml:id="label-0000001859003652" />
                            </staffDef>
                            <staffDef xml:id="staffdef-0000001418469859" clef.shape="F" clef.line="4" key.sig="2f" meter.count="3" meter.unit="4" n="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001089512544">
                        <measure xml:id="measure-L6" n="15">
                            <staff xml:id="staff-L6F2N1" n="1">
                                <layer xml:id="layer-L6F2N1" n="1">
                                    <beam xml:id="beam-L7F2-L9F2">
                                        <note xml:id="note-L7F2" dur="8" oct="5" pname="g" accid.ges="n" />
                                        <rest xml:id="rest-L8F2" dur="16" />
                                        <note xml:id="note-L9F2" dur="16" oct="5" pname="a" accid.ges="n" />
                                    </beam>
                                    <note xml:id="note-L10F2" dur="4" oct="5" pname="b" accid.ges="f" />
                                    <beam xml:id="beam-L11F2-L12F2">
                                        <note xml:id="note-L11F2" dur="8" oct="5" pname="a" accid.ges="n" />
                                        <note xml:id="note-L12F2" dur="8" oct="5" pname="g" accid.ges="n" />
                                    </beam>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L6F1N1" n="2">
                                <layer xml:id="layer-L6F1N1" n="1">
                                    <note xml:id="note-L7F1" dur="4" oct="3" pname="e" accid.ges="f" />
                                    <chord xml:id="chord-L10F1" dur="4">
                                        <note xml:id="note-L10F1S1" oct="4" pname="g" accid.ges="n" />
                                        <note xml:id="note-L10F1S2" oct="4" pname="e" accid.ges="f" />
                                        <note xml:id="note-L10F1S3" oct="3" pname="b" accid.ges="f" />
                                        <note xml:id="note-L10F1S4" oct="3" pname="g" accid.ges="n" />
                                    </chord>
                                    <rest xml:id="rest-L11F1" dur="4" />
                                </layer>
                            </staff>
                            <dynam xml:id="dynam-L9F3" staff="1" tstamp="1.750000">f</dynam>
                            <arpeg xml:id="arpeg-L10F1" staff="2" startid="#chord-L10F1" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
I am not sure about the expected behavior here. Vertical layout adjustment is not possible. Horizontal adjustment could be possible but only if `tstamp` is not the same as in your example. However, I would not be surprise to see cases where the arpeggio line is interrupted and the dynamic remains at its position. Could interrupting the arpeggio be another desirable behavior?

**Comment by donbyrd** [comment]
Offhand, I can't think of an example of an interrupted arpeggio line, though it's probably been done. But in this situation, I'd expect the dynamic to move slightly to the left and/or the chord (and simultaneous note on the top staff) to move slightly to the right.

**Comment by craigsapp** [comment]
> Could interrupting the arpeggio be another desirable behavior?

It would be very unusual to interrupt an arpeggio for layout adjustments.

> Horizontal adjustment could be possible but only if `tstamp` is not the same as in your example. 

What do you mean?  The forte `tstamp` is 1.75 (last 16th of first beat), and the arpeggio is attached a chord with an implied `tstamp` of 2.0.

> I'd expect the dynamic to move slightly to the left and/or the chord (and simultaneous note on the top staff) to move slightly to the right.

Basically this:  The horizontal spacing between tstamp 1.75 and tstamp 2.0 should increase to prevent overlap between the `f` and arpeggio symbols.

**Comment by lpugin** [comment]
> What do you mean?

I mean that it would not be logical to space them if they occur at the same position.

**Comment by craigsapp** [comment]
But they are not at the same position (tstamp 1.75 compared to 2.0).  If the tstamp of the `f` were 2.0, then it would be placed above the chord:

<img width="429" alt="screen shot 2018-03-06 at 6 51 55 am" src="https://user-images.githubusercontent.com/3487289/37038757-83fb1e2a-210a-11e8-9d2a-07e5d3d71e40.png">

**Comment by lpugin** [comment]
Yes, exactly, and this is why I am saying that "Horizontal adjustment could be possible" here.

**Comment by craigsapp** [comment]
> Yes, exactly, and this is why I am saying that "Horizontal adjustment could be possible" here.

OK, then we can agree to agree.  Perhaps this Swissglish at the end of the sentence is causing confusion 😜 :

>  ... but only if tstamp is not the same as in your example. 

Perhaps reworded as:

"Horizontal adjustment could be possible in cases like your example, since the tstamps are not the same."

**Comment by lpugin** [comment]
Current rendering
![image](https://user-images.githubusercontent.com/689412/100643036-da169e80-3339-11eb-8d1c-79740870df4e.png)

**Comment by craigsapp** [comment]
Looks great!
