### ISSUE TITLE
Add support for pedal automatic alignment with corresponding options

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#774]
`<pedal>` elements currently ignore the `vgrp` attribute, and it would be nice for them to not ignore it.

Here is a score without vertical grouping for horizontal alignment:

<img width="399" alt="screen shot 2018-02-25 at 1 52 31 pm" src="https://user-images.githubusercontent.com/3487289/36646920-20b659ac-1a33-11e8-803a-fa731f7a8a67.png">

Here is the same score with vertical grouping of the dynamics in group 1 and the pedal up/down markings in group 2:

<img width="407" alt="screen shot 2018-02-25 at 1 56 33 pm" src="https://user-images.githubusercontent.com/3487289/36646936-680e472e-1a33-11e8-8f20-0d6ee4f08c89.png">

The `<dynam>` and `<hairpin>` elements align as expected, but the `<pedal>` markings do not.

Test data without `vgrp ` attributes:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-02-25T13:52:38" version="2.0.0-dev-89c99fa-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000110248674">
                <score xml:id="score-0000000751976446">
                    <scoreDef xml:id="scoredef-0000001734584451">
                        <staffGrp xml:id="staffgrp-0000001507450204">
                            <staffDef xml:id="staffdef-0000001115969784" clef.shape="G" clef.line="2" n="1" lines="5">
                                <label xml:id="label-0000001789011566" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001729138185">
                        <measure xml:id="measure-L2" n="1">
                            <staff xml:id="staff-L2F1N1" n="1">
                                <layer xml:id="layer-L2F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="2" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L7F1" dur="2" oct="4" pname="d" accid.ges="n" />
                                </layer>
                            </staff>
                            <pedal xml:id="pedal-0000001696551029" staff="1" tstamp="1.000000" dir="down" />
                            <dynam xml:id="dynam-L4F2" staff="1" tstamp="1.000000">p</dynam>
                            <hairpin xml:id="hairpin-L4F2" staff="1" tstamp="1.000000" tstamp2="0m+3.0" form="cres" />
                            <dynam xml:id="dynam-L7F2" staff="1" tstamp="3.000000">f</dynam>
                            <hairpin xml:id="hairpin-L8F2" staff="1" tstamp="3.500000" tstamp2="0m+4.5" form="dim" />
                            <pedal xml:id="pedal-0000002088708031" staff="1" tstamp="5.000000" dir="up" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Test data with the vertical grouping attributes added:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-02-25T13:52:38" version="2.0.0-dev-89c99fa-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000110248674">
                <score xml:id="score-0000000751976446">
                    <scoreDef xml:id="scoredef-0000001734584451">
                        <staffGrp xml:id="staffgrp-0000001507450204">
                            <staffDef xml:id="staffdef-0000001115969784" clef.shape="G" clef.line="2" n="1" lines="5">
                                <label xml:id="label-0000001789011566" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001729138185">
                        <measure xml:id="measure-L2" n="1">
                            <staff xml:id="staff-L2F1N1" n="1">
                                <layer xml:id="layer-L2F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="2" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L7F1" dur="2" oct="4" pname="d" accid.ges="n" />
                                </layer>
                            </staff>
                            <pedal xml:id="pedal-0000001696551029" vgrp="2" staff="1" tstamp="1.000000" dir="down" />
                            <dynam xml:id="dynam-L4F2" staff="1" vgrp="1" tstamp="1.000000">p</dynam>
                            <hairpin xml:id="hairpin-L4F2" staff="1" vgrp="1" tstamp="1.000000" tstamp2="0m+3.0" form="cres" />
                            <dynam xml:id="dynam-L7F2" staff="1" vgrp="1" tstamp="3.000000">f</dynam>
                            <hairpin xml:id="hairpin-L8F2" staff="1" vgrp="1" tstamp="3.500000" tstamp2="0m+4.5" form="dim" />
                            <pedal xml:id="pedal-0000002088708031" vgrp="2" staff="1" tstamp="5.000000" dir="up" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
I wonder if we could not implement a default rendering that would be more pedal-specific. For example, aligning them by measure. This would be better than nothing. Another option could be to align them by pair down-up. Then `@vgrp` can be used to align differently (including to break default groups).

**Comment by lpugin** [comment]
Aligning all of them by default will not be a good solution for the same reason as with hairpins. In dynamic rendering, we can have much longer systems than with printed output, and we have to take this into account.

I am not a big fan of introducing some threshold, so I think the best starting point is to have `@vgrp` implemented, and possibly a grouping by pair or by measure.

**Comment by craigsapp** [comment]
Yes, I think for now implementing `@vgrp` is best, and then we can think later about how any automatic layout should work.  Automatically pairing pedal on/off and within the measure is good, but may not always work.   For now I will probably apply `@vgrp` to all pedal markings, and then explicitly ungroup the ones that should not be grouped (in the Humdrum-to-MEI converter).

**Comment by donbyrd** [comment]
What do you mean by "within a measure"? It's trivial to pair pedal on/off _correctly_, i.e., by semantics: they strictly alternate, and it has nothing to do with measures. Okay, I'm sure there are publications that have pedal downs but omit the matching ups, but I think that's rare; I can't think of an example offhand. Or do you mean reset to default position at every barline? Anyway, I'd guess some kind of pairing on/off is better than nothing, but it certainly will not always work! As Craig points out, it's very possible there will be a very low note above one but not the other.

**Comment by craigsapp** [comment]
Here is an example of a single pedal mark out of alignment with the rest due to a low note:

http://ks.imslp.net/files/imglnks/usimg/e/ec/IMSLP410926-PMLP02289-SLUB_360345158.pdf

<img width="1111" alt="screen shot 2018-02-26 at 8 54 05 pm" src="https://user-images.githubusercontent.com/3487289/36711332-ae361984-1b37-11e8-9cd4-9f6a131a31a0.png">

In this case all of the ped/* marks would be in the same group except for the one under the low E-flat, which would not be in a `@vgrp`.

And from the same PDF, a case where the pedal on/off markers are aligned as a pair when one of them has to move down due to a low note:

<img width="1081" alt="screen shot 2018-02-26 at 8 55 05 pm" src="https://user-images.githubusercontent.com/3487289/36711378-df4023bc-1b37-11e8-929d-f61a6eaac90f.png">

In this case there would be either two or three `@vgrp`: one for the middle pair that is hight, and then one or two groups for the other two pairs.

Looking at how various editions do these two lines of music:

http://ks.imslp.net/files/imglnks/usimg/0/03/IMSLP86542-PMLP02289-chopin-mazurkas_opus_7.pdf

This one moves all pedal markings down to the lowest one:

<img width="1459" alt="screen shot 2018-02-26 at 9 02 29 pm" src="https://user-images.githubusercontent.com/3487289/36711441-1d409b7e-1b38-11e8-8a54-9e4bb79fca05.png">

So all ped/* would be put into the same `@vgrp`. 

But this editino does similar to the first edtion where the marks in the measures are aligned separately:

<img width="507" alt="screen shot 2018-02-26 at 9 04 07 pm" src="https://user-images.githubusercontent.com/3487289/36711468-5c4cab96-1b38-11e8-9e8f-3e8d9cb9402d.png">

Another edition:

http://ks.imslp.net/files/imglnks/usimg/d/d0/IMSLP29440-PMLP02289-Chopin_Klindworth_Band_1_Bote_Bock_Op.7.pdf

This one is similar to the last edition:

<img width="1333" alt="screen shot 2018-02-26 at 9 05 43 pm" src="https://user-images.githubusercontent.com/3487289/36711503-848c6358-1b38-11e8-9dce-0277b3a6a322.png">

But different for the second example, where just a single pedal marking is moved down, not the pair:

<img width="618" alt="screen shot 2018-02-26 at 9 06 37 pm" src="https://user-images.githubusercontent.com/3487289/36711528-aa2944f0-1b38-11e8-806d-ddb53ced2892.png">

Cortot edition:

http://ks.imslp.net/files/imglnks/usimg/d/d5/IMSLP368704-PMLP02289-Chopin_-_Opus_7_-_Cortot_french.pdf

Similar to the first edition in the first example:

<img width="1083" alt="screen shot 2018-02-26 at 9 13 11 pm" src="https://user-images.githubusercontent.com/3487289/36711691-95751696-1b39-11e8-8e4d-6904de2d2401.png">

And similar to the first edition in the second example:

<img width="775" alt="screen shot 2018-02-26 at 9 14 46 pm" src="https://user-images.githubusercontent.com/3487289/36711743-ccd055ba-1b39-11e8-8d88-d38fcf9c99fd.png">

**Comment by craigsapp** [comment]
One possible automatic treatment that could be done in verovio is to have a default implicit `@vgrp` for pedal markings when there is no explicit `@vgrp` on the `pedal` element (internally it could be implemented as `@vgrp="0"` for example since that is not an allowed MEI value for the attribute). Then exceptions to this default group would be explicitly encoded with `@vgrp` values. 


For this example:

<img width="1111" alt="screen shot 2018-02-26 at 8 54 05 pm" src="https://user-images.githubusercontent.com/3487289/36711884-b270e6fc-1b3a-11e8-97bf-90a3d73159f5.png">

The "Ped" in measure 3 would be encoded with `@vgrp="1"` and the others would be encoded without a `@vgrp` (or vice-versa, but that would involve more work adding more attributes to more elements).  If you want to get picky about vertical placement, it looks like the first ped marking in the first measure is also in its own group.  

Another way to encode without using the `@vgrp` system, but in some other way, would be to say that all pedal markings on a line should be grouped together vertically, but have an attribute which means that a particular pedal marking should be vertically justified independent of any other pedal markings on the line.  This feature can be implemented in the `@vgrp` system, but it is more cumbersome since you have to give unique groups to each pedal marking that should be justified independently (and adding a new group runs into the potential problem of re-using an existing `@vgrp` value.   When more than one pedal mark needs to be grouped together then `@vgrp` would be used (but not when using the "default" position or the isolated-justification case).  

Or another related possibility is to allow a value for `@vgrp` which states that a pedal should not be aligned with any other pedal marking on the line (including the implicit alignment group), and should be independently vertically justified on its own (depending on what note or other musical object is above it).  Perhaps something like `@vgrp="none"` which would prevent any automatic vertical grouping of the pedal marks.


In this example:

<img width="1081" alt="screen shot 2018-02-26 at 8 55 05 pm" src="https://user-images.githubusercontent.com/3487289/36711926-f937c7fe-1b3a-11e8-9ab6-e6b43f384312.png">

The first and last ped/* pairs would be in the default group while the middle pair would be in its own explicitly encoded `@vgrp` group.


There would be some problems created when displaying the music with different line breaks.  How to encode the exceptions to the "default" `@vgrp` for pedal markings would control how the display changes when the layout changes.  But at least when creating or emulating a specific print layout, using `@vgrp` or the variants described above should work well.

**Comment by craigsapp** [comment]
Also, I notice in all of the above examples from several editions, the "Ped." mark is centered on the center of the note note rather than left justified to the left side of the note, as is currently done in verovio.

**Comment by pe-ro** [comment]
I'd like to discuss a general solution to most, if not all, of the vertical placement issues, not just piano pedals.

We have `@vo` for "nudging" of lots of things, including pedal markings, to a post-layout location.  We also already have a way to grouping items so that they all land at the same vertical height, but the actual location is determined by Verovio.  In addition, there are attribute for setting a desired distance from the staff for dynamics, harmonic labels, and text (with the caveat that Verovio can override these values to avoid collisions).  We can certainly add `@pedal.dist` if needed.

It seems what we lack is a way of specifying an exact placement value, pre- or post-layout.  Adding a new attribute, say `@vdist`, on (probably) all control events would allow precise placement of an individual item like a pedal marking.  The value of `@vdist` would be relative to the top line of the staff when `@place="above"` and below the bottom line of the staff when `@place="below"`.  Negative values would be allowed, so placement inside the staff could be specified.  Because `<pedal dir="down">` and `<pedal dir="up">` are independent of each other, either one or both could be moved when necessary.  Without the presence of `@vdist`, Verovio is free to implement whatever collision-avoidance measures it can, including by-measure or by-pair alignment, based on `@vgrp` or not as appropriate.

**Comment by lpugin** [comment]
>  We can certainly add `@pedal.dist if` needed.

I think this would be good. The plan for Verovio is to extend options but to keep them in line with MEI attributes. So a `--pedal-dist` option can then be specified or overwritten directly in the MEI file via `scoreDef@pedal.dist`.

Adding `@vdist` also makes sense to me. This does not preclude, however, to think about grouping mechanisms, and if we look at adding options to Verovio I am interested to see how they relate to existing or potential attributes in `<scoreDef>`. Now I don't think all control event will have a need for this, and they might need different grouping possibilities. For example, grouping by pair down-up is specific to pedal. Of course I am fine if this has to remain only in Verovio.

**Comment by craigsapp** [comment]
Mostly you should be careful about semantic versus non-semantic placement schemes.  In other words a fixed offset would be good for one layout arrangement, but not good for another.  So concentration on placement cues which allow for multiple layouts would be good.

Here is some analysis of the rules that could be applied to the example above.

First there is this interesting placement of the pedal sign:

![screen shot 2018-02-27 at 12 29 16 pm](https://user-images.githubusercontent.com/3487289/36753072-e8483a30-1bb9-11e8-856d-7e45d97750bb.png)

Optimally it would go underneath the F1 whole note; however, it is moved to the right of the note since the next system's music does not allow the Ped mark to be placed in the expected position.  In other words, the precedence of the system placement is given more priority over the placement of the Ped mark (probably to fit more lines of music on the page).  If the music were given more vertical space, then the Ped mark could be placed under the F1.  If you force the Ped mark to be in the unusual location through a placement attribute, then the context of the spacing cannot adjust it, and it would be fixed to the current configuration for all types of layout both squeezed and loose.

Also in this musical context, delaying the pedal mark is equivalent musical effect as placing it underneath the whole note.  If this were not so, then the Ped could not be placed after the whole notes (perhaps it would have to be placed before the whole note).  It would be difficult for a computer to make this sort of musical decision, however.  In the most verbose scenario, you would add a print suggestion to the Ped mark that it is allowed to migrate to the right and up from the bottom whole note if the system below is crowding the Pedals desired position.

The ending `*` mark seems to be well suited to using `@vgrp` to link it to the Ped mark:

![screen shot 2018-02-27 at 12 38 54 pm](https://user-images.githubusercontent.com/3487289/36753533-4453087c-1bbb-11e8-975a-44ea027693a0.png)

Both of them would be given the same `vgrp` number, and the Ped would also be given a horizontal and vertical offset or absolute position.  Since the Ped is assigned a fixed vertical position, then the `*` mark would automatically be assigned the same vertical position (even if this would obscure music).

The next measure is somewhat strange:

![screen shot 2018-02-27 at 12 49 23 pm](https://user-images.githubusercontent.com/3487289/36753991-b158f25a-1bbc-11e8-954c-fc91b8fd4346.png)

All of the pedal markings are basically at the same vertical position, but the first ped mark is moved down a little bit to avoid collision with the wholenote.  So this case is not exactly coverted by the `@vgrp` system.  This is a "soft" `@vgrp` system of sorts, where the vertical positions of the elements in the group are minimized, but not given a constant vertical position.  Probably in such cases the average optimal position would be calculated, and then exceptions granted to elements which would otherwise have collisions.  This sort of soft grouping would be useful for dynamics, but probably hard to implement...

What music is this?  It is fairly nondescript noodling, so I cannot tell 😛 .  How do other editions of the same work layout the music?  Mostly the choice for layout of the pedal is due to a tight spacing between the systems (tighter spacing requires more human intervention to ensure that the music remains readable).  And a confounding factor is that there are very low notes in the music at the same time as the squeezed vertical spacing.

**Comment by lpugin** [comment]
Support for `@vgrp` is added. I'll rename the issue for automatic alignment

**Comment by wergo** [comment]
A `pedal@vgrp` gives me a MEI validation error (`"vgrp" not allowed here`), but works great in Verovio. Has this been scheduled to be added to the schematron?

**Comment by craigsapp** [comment]
More to the point, it is not an allowed attribute in MEI `<pedal>` elements:

https://music-encoding.org/guidelines/v4/elements/pedal.html

So when it is added as an allowed attribute (similar to `<dynam>`), then the schematron would not complain about it.

**Comment by wergo** [comment]
So, it would be good to add it as allowed attribute of the `<pedal>` element in the MEI schematron.

**Comment by craigsapp** [comment]
Technically that is an issue for the `music-encoding/music-encoding` repository:

https://github.com/music-encoding/music-encoding/issues

In theory verovio does not implement elements/attributes unless they are added to the MEI scheme; however, `@vgrp` is a new feature for MEI 4.0, and application to `<pedal>` was probably overlooked when adding to the schema.  Probably because it was mostly discussed for `<dynam>` and `<hairpin>` elements.
