### ISSUE TITLE
add new func attribute to pedal

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#778]
Although this is more of a libmei feature request, I'll add it here. 
Then, when SMUFL U+E659 (keyboardPedalSost) is added, Sostenuto marks could be supported in Verovio.

**Comment by lpugin** [comment]
SMuFL glpyh was added 82983ee772a59b2564488e063f0fa21f1a832063

**Comment by lpugin** [comment]
@rettinghaus : are you planning to do this?

**Comment by rettinghaus** [comment]
starting now!

**Comment by lpugin** [comment]
Thanks!
