### ISSUE TITLE
rendering problem Firefox

### ISSUE THREAD

**Issue by bwbohl** [rism-ch/verovio#79]
If rendering a snippet to a div in Firefox all notation symbols on the staff miss a portion at the top

![image](https://cloud.githubusercontent.com/assets/2430401/7044425/9b738b12-ddf3-11e4-90ad-82feca42e974.png)

whereas in chrome everthing looks perfect

![image](https://cloud.githubusercontent.com/assets/2430401/7044436/b6bfccbe-ddf3-11e4-8a2b-e2d17c4d49ca.png)

Is there a way to debug this or to get more feedback from verovio?

**Comment by bwbohl** [comment]
In the case of noteheads this seems somehow related to the 'height' and 'y' attributes on the contained 'use' element; increasing 'height' results in a full notehead being rendered, using 'y' it can be adjusted to the correct position on the staff

**Comment by bwbohl** [comment]
It seems the problem arises from a css rule that bootstrap brings along:

```svg:not(:root) {
    overflow: hidden;
}```

disabling this rule renders the staff perfectly.
This might turn out to be a browser specific issue not related to verovio ;_)

**Comment by lpugin** [comment]
Solved in 30min, this is good! Thanks. If you can think where to document
it, thus would be great.
