### ISSUE TITLE
Add alternating/mixed meters

### ISSUE THREAD

**Issue by axgeertinger** [rism-ch/verovio#791]
Are there plans to support `<meterSigGrp>` in the foreseeable future? 
![c3](https://user-images.githubusercontent.com/3779074/37030410-2263e04e-213b-11e8-824b-9ce6b6bd2b2f.png)
And perhaps also support glyphs in order to be able to add the fermata (though I'm not sure yet about the best way to encode it)?
-axel

**Comment by lpugin** [comment]
I will keep it in mind.

Regarding the fermata above the time signature, I also have no idea what would be the best way to encode it. There are some similar questions with tempo indications, which are usually aligned with the time signature, but these, when encoded in `<scoreDef>` are, as far as I understand it, outside tstamp ranges. @pe-ro?

**Comment by donbyrd** [comment]
I've _never_ seen a fermata over a time signature! What is this for, Axel? Does it appear in Nielsen??

**Comment by pe-ro** [comment]
A fermata aligned with the time signature is not outside the range of `@tstamp`.  Its values range from zero to the numerator of the time signature + 1.  Zero is at the left barline and the maximum value at the right barline.  

The time stamp value for the fermata should be between 0 and 1.  The precise value, however, depends on how Verovio treats the stuff, like time and key signatures, that come before beat 1.  If the time and key signatures don't have tstamps themselves (and why would they?), then it seems to me it would be difficult to automatically align the fermata with the time signature, for example.  But, it should be trivial to place the fermata according to the instructions given in the MEI file.  In this sense, a fermata is no different from any other directive.  In other words, it's not related to the thing underneath/above it -- they just occur at the same time stamp.  Theoretically, one should be able to position anything relative to a staff using `@staff`, `@tstamp`, and `@place`.

**Comment by axgeertinger** [comment]
It's actually possible to have Verovio render it, but the encoding does not make any sense. The above image was actually made with Verovio: the mixed meter is made up of a `<scoreDef meter.sym="cut">` and a `<mensur num="3">` which is rubbish, of course. The fermata is easily placed above the "3" by using the mensur element's xml:id as `@startid` (or above one of the `<meterSig>` elements in a mixed meter if Verovio supports it some day). But even if it is possible to place the fermata correctly, I was wondering whether it would be possible to encode it as part of the mixed meter somehow. That would make it easier to identify all of the symbols included in the meter.

**Comment by axgeertinger** [comment]
@donbyrd: This is definitely not Nielsen! It's actually from Thomissøn's Danish hymn book from 1569, so it's not even to be understood as modern notation but as mensural notation. So the fermata has probably really nothing to do with a fermata; it's some additional information about the mensuration. If you have any idea what it means I'd be happy to know  :-) Here's what it looks like:
![th1569_80r_capture](https://user-images.githubusercontent.com/3779074/37115844-b157fcce-224c-11e8-9ad5-1513f06f7b5c.png)

**Comment by pe-ro** [comment]
If we don't know what the fermata means with regard to the meter signature(s), then why include/associate it with the meter signature in the encoding?  It makes more sense to me to leave things as they are; that is, encode the meter and the fermata separately, then associate them with each other by some other means, using `<annot>`, for example.

I'm afraid that if we go down the path of encoding any/every association with a markup hierarchy, then the logical conclusion will be that virtually any element may contain any other element.

**Comment by axgeertinger** [comment]
I'm not asking to allow fermatas in time signatures. I was just wondering if there was a way to define a custom symbol to be used as (part of) the meter :-) Otherwise I'm fine with encoding it as a fermata and giving it the appropriate `@startid`.

**Comment by craigsapp** [comment]
It will of course depend on what the meaning of the fermata is, but I would think it is not properly part of the time signature in the same was that a fermata is not part of a note (at least in MEI encoding).

I would give the mensuration an `xml:id`, and then place the fermata over that meter using `fermata@plist` rather than doing a hack such as `@tstamp="0.64"`.

A complication is that the fermata is centered over the 3 of the mensuration, so the above method would not be completely right, since it should center the fermata over both symbols in the mensuration.  However the music is typeset, and the mensuration has two characters in it, so centering the fermata in the source was not possible (maybe they would have preferred it to be centered). 

 > If you have any idea what it means I'd be happy to know :-) 

We would need to see the wider context (such as most particularly the other parts for the same music), and whether there are other similar uses in the book, etc...  My random guess is that the music for the part is to be played slowly or slower than cut-c-3 (but I have also never seen a fermata being used on a mensuration sign).

**Comment by pe-ro** [comment]
@axgeertinger, As I see it, a custom symbol to be used **_as part of a meter signature_** is the same thing as asking for fermatas in time signatures.  It's the "arbitrary symbol as part of" concept that opens the door to all kinds of modelling terrors.

One can, however, define a custom symbol, containing a cut-time symbol, a large 3, and a fermata, for example, as a replacement for the entire meter signature.  Presumably, if the symbol were defined using SVG, then it would scale up/down as the size of the music changed.  Of course, this is completely theoretical until Verovio actually supports it. :grinning:

**Comment by axgeertinger** [comment]
Please excuse my bad English – it seems that I am unable to explain what I mean. 

> One can, however, define a custom symbol, containing a cut-time symbol, a large 3, and a fermata, for example, as a replacement for the entire meter signature.

That's exactly what I am aiming at. I do *not* want the word 'fermata' to appear in the meter signature if I can avoid it, as it probably is a sign that resembles a fermata but means something different. And I am also reluctant to define a fermata somewhere separate from the meter and place it above the meter (and even if using `@startid` or the like is less misleading than `@tstamp='0'`, it still does not seem right to me), again because it's not a fermata occuring before the music starts, but something else related to the meter. Hence my thoughts about defining a custom meter symbol by pointing to, for instance some SMuFL glyph (or using SVG) without calling it a fermata. 

@craigsapp, the example is from a hymn book (text book for congregational singing with unison melodies), so there are no other parts. The 'fermata' appears in a few other cases in the same book, always above a '3', but not always preceded by the cut C. I am not aware of any other sources using it.

**Comment by lpugin** [comment]
I do not think that `<meterSigGrp>` is the right solution for this problem. I am closing the issue. If you have clear cases where `<meterSigGrp>` is desirable, open another issue with encoding snippets.
