### ISSUE TITLE
make Verovio citable

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#794]
As it becomes more common to cite software in the DH it would be nice to have this feature in Verovio, too. 
Here are some infos on that: 
https://research-software.org/citation/

Part of that is having a DOI for Verovio, which could be easily done with Zenodo, that supports DOI versioning: 
http://help.zenodo.org/

**Comment by lpugin** [comment]
I was recently considering this http://joss.theoj.org/

**Comment by lpugin** [comment]
This is the most appropriate paper to cite http://www.terasoft.com.tw/conf/ismir2014/proceedings/T020_221_Paper.pdf

**Comment by rettinghaus** [comment]
I didn't mean "write an article about Verovio", I meant "make the software itself citeable".

**Comment by craigsapp** [comment]
Why not cite with the link:
    http://www.verovio.org

or specifically the code:
    https://github.com/rism-ch/verovio

or specific lines of the code:
     https://github.com/rism-ch/verovio/blob/b03ac6/src/iomei.cpp#L95-L101

**Comment by lpugin** [comment]
> I didn't mean "write an article about Verovio"

The article is already written ;-) Let's talk about it next time we meet
