### ISSUE TITLE
automatic system breaks

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#798]
Now Verovio wraps every line in a system element which is somewhat unMEIish. 
IMHO a better approach would be to generate `<sb>` elements and output them in the SVG. This would be more consistent with MEI *and* the way Verovio handles missing `<pgHead>` and `<mNum>` elements.

**Comment by lpugin** [comment]
What to do mean by "wraps every line in a system element"? Could you give an example?

**Comment by rettinghaus** [comment]
Sure. 
current SVG output:
```xml
<g class="page-margin">
  <g class="system">
    <g class="measure"/>
    <g class="measure"/>
    <g class="measure"/>
  </g>
  <g class="system">
    <g class="measure"/>
    <g class="measure"/>
    <g class="measure"/>
  </g>
</g>
```

desired SVG output:
```xml
<g class="page-margin">
  <g class="sb autogenerated"/>
  <g class="measure"/>
  <g class="measure"/>
  <g class="measure"/>
  <g class="sb autogenerated"/>
  <g class="measure"/>
  <g class="measure"/>
  <g class="measure"/>
</g>
```
which would be more like MEI.

**Comment by lpugin** [comment]
I am not convinced. The SVG output reflects the page-based MEI structure as it is in memory. I know it is quite disliked and considered not to be MEI, but it is there and trying to hide it will create other issues.

Generated `<pgHead>` and `<mNum>` are different. They are generated only because they are probably desired, not because of the layout calculation.

**Comment by rettinghaus** [comment]
I see your point. On the other hand, it is an unexpected, or at least non-intuitive behaviour, that you can select the measure that starts a system with CSS `g.sb + g.measure` only if it *is* encoded.

**Comment by lpugin** [comment]
You can select it through `g.system/g.measure` in all cases, can't you?
