### ISSUE TITLE
Clarification of license for Leipzig font

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#80]
With the whole project the Leipzig Font comes under a GPL License. But if a GPL font is embedded in a document, that document must be wholly licensed under the GPL too. Could be problematic in some cases I guess. Using SIL Open Font License may solve this. 

See: http://yro.slashdot.org/article.pl?sid=05/04/17/2118203&tid=117

**Comment by donbyrd** [comment]
I've run into this "viral" aspect of the GPL before. I agree it can be problematic; if there's a reasonable alternative, it's better to avoid the GPL.

--Don


On Apr 21, 2015, at 11:44 AM, Klaus Rettinghaus <notifications@github.com>
 wrote:

> With the whole project the Leipzig Font comes under a GPL License. But if a GPL font is embedded in a document, that document must be wholly licensed under the GPL too. Could be problematic in some cases I guess. Using SIL Open Font License may solve this.
> 
> See: http://yro.slashdot.org/article.pl?sid=05/04/17/2118203&tid=117
> 
> �
> Reply to this email directly or view it on GitHub.
> 

---
Donald Byrd
Woodrow Wilson Indiana Teaching Fellow
Adjunct Associate Professor of Informatics
Visiting Scientist, Research Technologies
Indiana University Bloomington

**Comment by lpugin** [comment]
Good point, I did not think about it. It seems that we could add and exception to the license, I think that would fix it.
https://www.gnu.org/licenses/gpl-faq.html#FontException

I would also be fine to have the font under the SIL Open Font Licence, but I am not sure how to specify it. Can we have just the font under another license?

Considering the general discussion about the license, one possibility I could envisage is to have a dual licensing option. One for open source projects, and one for projects that want to use it differently.

**Comment by ahankinson** [comment]
The GPL for JavaScript libraries, or even compiled libraries, is a pretty sticky situation on the whole. Embedding software in a web page can be construed as "linking," and there is no end of controversy over whether downloading and running JavaScript on the client is "distributing."

Personally, I avoid the GPL at all times. However, if you want something that's like the GPL but avoids the controversy, you could choose the LGPL.

**Comment by rettinghaus** [comment]
As Gootville and Bravura comes under OFL this should be stated somehow anyway. At least by putting a readme in the fonts folder. 
Putting just the font under OFL should be going well: 
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ofl-faq_web#68092c0f

**Comment by lpugin** [comment]
I can't see any problem in having Leipzig under OFL. If you have a readme sample file to be added to the fonts folder, please just make a pull request.
