### ISSUE TITLE
edited word extentions music-xml

### ISSUE THREAD

**Issue by sannedubois** [rism-ch/verovio#801]
When I resize word-extensions of my lyrics, export as music-xml 3.0 and import in http://www.verovio.org/musicxml.html it doesn't handle the shortened length: it stops at staff end.

**Comment by sannedubois** [comment]
I guess this is not possible, for I see when exporting from finale to music-xml only a </extend> tag, not anything to indicate its length.

**Comment by lpugin** [comment]
This is unclear. Please make is clear whereas this is a musicxml import issue and / or what it should be in MEI
