### ISSUE TITLE
Black mensural notation noteheads 

### ISSUE THREAD

**Issue by karend27** [rism-ch/verovio#813]
Is it possible to change the appearance of the black mensural noteheads? 

You might look at the example on p. 3 of the following piece (link followed by screen shot):

[https://ekoshelev.github.io/measuring_polyphony_jekyll/display.html?/measuring_polyphony_jekyll/assets/mensural/310_MENSURAL.mei](url)
<img width="1038" alt="screen shot 2018-04-02 at 11 20 07" src="https://user-images.githubusercontent.com/11195203/38201882-d0323b76-3667-11e8-9e0c-4f9dbdbce7a0.png">

I'd like the noteheads of the longa and the brevis to be more square than rectangular (i.e., less horizontal width), and the semibreves to be wider horizontally (incidentally that might fix the ledger line issue seen here too - the semibreves do not seem to be exactly centered compared to the longs and breves and the ledger lines, that is, the semibreves seem to be left-aligned, and so are often out of sync with their ledger lines).

For a neophyte like me, perhaps someone (@donbyrd) might explain how I could change noteheads (my student @ekoshelev will be implementing it).

**Comment by pe-ro** [comment]
I'll leave the question for someone else to answer.  

First, I'm interested in why the encoding doesn't parse against MEI v. 3.0.0 as the file claims with its `@version` attribute.  Are you using a customized schema?

**Comment by karend27** [comment]
The original file had meiversion=2013, so there is probably now a copy and paste mistake when we were doing some updates to the meiHead. But can you point me to an easy explanation of how to check the validation because ideally we would like it to validate against the latest MEI version (I have Oxygen so presumably I can point that to the MEI site to check validation?).

**Comment by lpugin** [comment]
The latest version fixes the note head / ledger lines issue. The size of the brevis and longa is adjusted. Also, the dot placement is improved and now set to the middle between the surrounding notes. This looks better, I think.

![image](https://user-images.githubusercontent.com/689412/38291823-b5c85a60-37e1-11e8-8746-981333204c2e.png)

One thing left is the clef, and I am not sure how to solve this. The mensural clef shape is triggered by the `@notationType` on `<staffDef>`. However, there is no such thing as octava bassa mensural clef. Would it be acceptable to keep the original clefs?

Validation: there are obviously some issues related to the update from 2013 to 3.0.0. There is also one issue due to the use of the `@notationType` (MEI 4.0) that is required by the version 2.0 of Verovio, so validating against 3.0.0 will be problematic.

**Comment by lpugin** [comment]
PS The same with Bravura. Semibreve noteheads are wider.

![image](https://user-images.githubusercontent.com/689412/38292134-e450738a-37e2-11e8-9680-47d80c30005b.png)

**Comment by karend27** [comment]
This looks excellent!!! Thanks so much!!

As for the clef, it looks a little weird but it's not such a big deal. Is there anyone I can get in touch with to ask them to add an octava bassa mensural clef at some point?

For the validation issue, would it be best then to leave the MEIVersion as 2.0? Would I also have to get someone to create a customized schema for elements we use that are not in 2.0?

Finally, one last question relating to the black mensural font - is it possible to have all the stems on the longs have a default of descending? We can certainly make sure in our encoding that stemdir="down" but it is also the case that in black mensural notation, longs always have descending stems, with the one exception of the ascending plica long, which has two ascending stems, with the right stem longer than the left stem.

**Comment by lpugin** [comment]
> As for the clef, it looks a little weird but it's not such a big deal. Is there anyone I can get in touch with to ask them to add an octava bassa mensural clef at some point?

How should it look like? I cannot think of an example. Do you have one?

> For the validation issue, would it be best then to leave the MEIVersion as 2.0? Would I also have to get someone to create a customized schema for elements we use that are not in 2.0?

Making a customisation would be the proper way to do it. As far as I can see you need version 3.0.0 + `@notationType` on `<staffDef>`.

> Finally, one last question relating to the black mensural font - is it possible to have all the stems on the longs have a default of descending? We can certainly make sure in our encoding that stemdir="down" but it is also the case that in black mensural notation, longs always have descending stems, 

Absolutely. This is currently wrong and I'll fix it.

> with the one exception of the ascending plica long, which has two ascending stems, with the right stem longer than the left stem.

How are they encoded? This should probably go in the customisation too. It will be no problem to implement.

**Comment by lpugin** [comment]
The longa stem direction issue is now fixed

**Comment by karend27** [comment]
Thanks for the longa stem fix!!

Actually, what I want to use in these instances in the mensural encoding is just the normal treble clef. I know that in black mensural notation you would only ever find either the C or F clef, but here I am presenting scored-up mensural notation, but using modern features such as editorial accidentals above the staff, and notating with modern clefs. I only use these two clefs:

<img width="48" alt="screen shot 2018-04-05 at 12 44 13" src="https://user-images.githubusercontent.com/11195203/38379651-5101b3bc-38cf-11e8-89c7-a78dd83beb2c.png">
<img width="57" alt="screen shot 2018-04-05 at 12 46 29" src="https://user-images.githubusercontent.com/11195203/38379710-8e65615e-38cf-11e8-86d9-43d610fedeef.png">

The attributes for the clefs in our code look the same in the CMN version of the file and the mensural version (this is from the CMN file): `<scoreDef xml:id="m-26" midi.bpm="800" meter.count="6" meter.unit="1" ppq="256" >
						<staffGrp xml:id="m-27">
							<staffGrp xml:id="m-37" n="1" symbol="bracket">
								<staffDef xml:id="m-28" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="triplum" lines="5" n="1">
									
									<instrDef xml:id="m-30" midi.channel="1" midi.pan="26" midi.volume="100" />
								</staffDef>
								<staffDef xml:id="m-31" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="motetus" lines="5" n="2">
									
									<instrDef xml:id="m-33" midi.channel="1" midi.pan="26" midi.volume="100" />
								</staffDef>
								<staffDef xml:id="m-34" clef.dis="8" clef.dis.place="below" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="Tenor Solo" lines="5" n="3">
									
									<instrDef xml:id="m-36" midi.channel="1" midi.pan="46" midi.volume="100" />
								</staffDef>
							</staffGrp>
						</staffGrp>
					</scoreDef>:` 

and this is from the mensural file: 
`<scoreDef xml:id="m-26">
						<staffGrp xml:id="m-37" n="1" symbol="bracket">
							<staffDef xml:id="m-28" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="triplum" lines="5" n="1" modusmaior="2" modusminor="3" tempus="3">
								
								<instrDef xml:id="m-30" midi.channel="1" midi.pan="26" midi.volume="100" />
							</staffDef>
							<staffDef xml:id="m-31" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="motetus" lines="5" n="2" modusmaior="2" modusminor="3" tempus="3">
								
								<instrDef xml:id="m-33" midi.channel="1" midi.pan="26" midi.volume="100" />
							</staffDef>
							<staffDef xml:id="m-34" clef.dis="8" clef.dis.place="below" clef.line="2" clef.shape="G" key.mode="major" key.sig="0" label="Tenor Solo" lines="5" n="3" modusmaior="2" modusminor="3" tempus="3">
								
								<instrDef xml:id="m-36" midi.channel="1" midi.pan="46" midi.volume="100" />
							</staffDef>
						</staffGrp>
					</scoreDef>`

I would like for the mensural version to use the same clef glyphs as the CMN version, i.e., like this:
<img width="960" alt="screen shot 2018-04-05 at 12 54 11" src="https://user-images.githubusercontent.com/11195203/38380004-7952f5c8-38d0-11e8-8377-98b95df06920.png">

**Comment by karend27** [comment]
As for the plica, right now we have encoded the plica simply as an attribute of note, e.g.:

Which I don't believe is currently part of v.3 though I think Giuliano has been discussing including it in v.4?

You find several of them in this piece:
https://ekoshelev.github.io/measuring_polyphony_jekyll/display.html?/measuring_polyphony_jekyll/assets/mensural/bona_MENSURAL.mei

In black mensural notation you can have a plica long or plica breve and they can be ascending or descending. Both have stems on the right and left side, ascending if the plica is ascending and descending if the plica is descending: the plica long has a longer right stem, the plica breve has a longer left stem.

In this transcription, there are ascending plica longs in the first system and ascending plica breves in the second system:
<img width="954" alt="screen shot 2018-04-05 at 13 09 27" src="https://user-images.githubusercontent.com/11195203/38380734-a730aa4c-38d2-11e8-9255-233ad632b219.png">

As to the rendition in performance, it is thought the plica indicates melodic motion filling in a leap with one note of a shorter rhythmic duration, but I think for simplicity sake I would leave that interpretation up to the performer and not actually encode the intervening pitch, since what that pitch is (or its rhythm) is sometimes ambiguous, and by actually inserting a pitch and rhythm I think is at the level of editorial intervention that I don't want to include yet in this encoding (perhaps later down the line).

**Comment by karend27** [comment]
One more question on stems (sorry - if it is better for me to start a new issue I can):
Some semibreves in this notation have descending stems, which we encode with the attribute stem.dir="down". Is is possible to have these render in Verovio as semibreves but with descending stems?

**Comment by donbyrd** [comment]
Karen, I'm probably the person to handle this. Please do start a new issue, but a quick answer: yes, it's possible (though not immediately).

**Comment by karend27** [comment]
Thanks Don - will do!

**Comment by lpugin** [comment]
@donbyrd : I'll do the stem for semibreves now because this is just a few lines. Could you check the status of the plica encoding?

**Comment by pe-ro** [comment]
It seems to me that we may have uncovered a case of divergent meanings of stems in CMN and mensural notation.  Plicae probably shouldn't use `@stem.*` attributes at all, but have their own attributes for controlling multiple stem directions, lengths, colors, etc.

We'll need to allow "regular" stems in CMN encoding; that is, when the mei-CMN schema is used or when `@notationtype` equals "cmn", and plicae stems when the mei-Mensural schema is used or when `@notationtype` contains "mensural".  We could be more specific in the latter case if plicae stems occur only in black mensural notation.

**Comment by donbyrd** [comment]
Stems in mensural notation certainly mean something different from stems in CMN. In CMN, their only meaning is as an indication of voice where there are two or more voices on a staff. In mensural notation, they never (as far as I know) mean that, since there are never two voices on a staff; instead they indicate the duration, but not always, or at least not always the same way, as Karen's question. But I'm not an expert on mensural notation. @pe-ro, I think you're right that plicae shouldn't use `@stem` attributes, but maybe not only plicae.I think plicae occur only at the end of a ligature, but there are also cases where notes in the middle of a ligature have two stems. There's a white notation example in the Guidelines -- I can't find it at the moment -- with two double-stemmed notes in the middle of a ligature. But Karen, please correct me if necessary!

**Comment by craigsapp** [comment]
Here is a sampler of some ligature stems:

<img width="428" alt="screen shot 2018-04-07 at 8 49 29 am" src="https://user-images.githubusercontent.com/3487289/38457011-1bf09022-3a40-11e8-9b8d-e88360833c78.png">

**Comment by karend27** [comment]
In mensural notation theory treatises, the 'plica' is almost equivocated with the vertical stroke that is added to the note - therefore we might think of it as an extra sort of stem added to a note that indicates a melodic ornamentation of that note.

That's why I think the best encoding would make 'plica' an attribute of a single note or a note within a ligature, and it could have the allowed terms of either 'asc' or 'desc'. You find them as modifications if single notes - longs or breves - in the way I described above; or as a modification to a ligature, where the stem is added to the last note of a ligature 

(the examples of the ligatures Craig gives here are the standard Franconian ligatures (in the first row) that by being modified in appearance change the durations of the pitches: by the presence or absence of a stem at the beginning of a ligature or a change in the usual appearance of the end of a ligature - by being made oblique, or facing outwards, but none of these are plicas.

**Comment by karend27** [comment]
Although I see another way to go would be to follow how ornaments are currently encoded in CMN, which is as a separate element (see mordent for example) and tied to the affected note via the tstamp attribute.

**Comment by pe-ro** [comment]
Right now, I'm thinking we can add a `<plicaStem>` element as a child of `<note>` which may have the following attributes: `@color`, `@dir`, `@len`, and `@pos`.  This makes it possible to address the various qualities represented by the attributes independently for the "stem" on the left and the "stem" on right, for example,
```
<note>
  <plicaStem pos="left" dir="down" len="3.5" color="red"/>
  <plicaStem pos="right" dir="down" len="7" color="green"/>
</note>
```
This level of detail may seem unnecessary now, but in my experience more detail is better, given the unpredictability of musical notation, especially the further back one goes in history and esp. during transition periods, and the unknown needs of future encoders.

This doesn't preclude the addition of a `@plicata` attribute on `<note>`, based on Karen's suggestion, with values of "asc" and "desc" (or "up" and "down" to be consist with the values of other, similar attributes).  This kind of encoding emphasizes semantics, while the use of `<plicaStem>` favors a visually-oriented approach.

`<plicaStem>` and `@plicata` can be placed in the MEI.mensural module, so that they're only available when that module is available.

Additional conditions can be enforced via Schematron, for instance, the simultaneous of use `@plicata` and `<plicaStem>` can be disallowed if necessary.  Likewise, a rule that disallows or warns against the use of either on a note that isn't the last one in a ligature could help guide encoders.  Also, if there's never a possibility of "regular" stems and "plica stems" occurring on the same note, then this could also be disallowed by Schematron.

Does this sound reasonable?

**Comment by karend27** [comment]
Perry - sorry for the delay in replying. Giuliano had also posted a long post about the plica on the email list. But I like what you suggest, and I think the two of you seem to be on the same page, suggesting that we could have two encodings, one that is a child of note and describes the graphic qualities of the added stem <plicaStem>, and another, an attribute of note, that adds a layer of interpretation, by denoting the meaning of the stem, that it indicates an ornamentation of the note with an added ascending or descending note. 

For the attributes of plicaStem I imagine color is not necessary because I don't know of any case where the plica is drawn in a different color ink to the notation. 

The only other wrinkle I can think of that might be somewhat confusing is that a longa already has a descending stem on the right, that is part of its normal graphic appearance. When the longa is drawn as a descending plica long, it gets an extra stem (the plicaStem) on its left side, descending. When the long is drawn as an ascending plica long, it gets the extra stem (plicaStem) on the right, but also its normal (rightside) stem now ascends. But I guess this encoding could be taken care of, if one wants to encode all these details, by adding an attribute to <note> of the stem.dir?

**Descending plica long:**
```
<note dur="longa">
<plicataStem pos="left" dir="down">
</note>
```

**Ascending plica long:**
```
<note dur="longa" stem.dir="down">
<plicataStem pos="left" dir="down">
</note>
```
Perry, I wonder If you are a member of that mei-mensural-ig - perhaps you might post this solution there, or I could copy and paste it there for you too. 

P.S. Actually, one thing that is not captured here yet is how the editorial interpretation of the pitch and duration of the plica (ornamental) note, and how the plicated note's duration is modified because of the plica (i.e., it will be shortened).

**Comment by rettinghaus** [comment]
I would go for a more generic approach: 

```xml
<note dur="longa" stem.dir="up">
    <stem func="plica" pos="left" dir="up">
</note>
```

that would allow e.g. to encode disconnected (misprinted) stems (via `@ho` and `@vo`)
