### ISSUE TITLE
Changing Instrument on MIDI

### ISSUE THREAD

**Issue by ekoshelev** [rism-ch/verovio#816]
Hello,
I am a student working for Karen Desmond, and I am currently looking for a way to change the instrumentation of the midi player from piano to organ. I tried a few different things, being the following:
1) Change metadata in MEI file to include: `<instrDef xml:id="instrdef-0000001055366288" midi.instrnum="20" />`  (which is supposed to correspond to a church organ sound), as in [issue #80](https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/80), but it still played as piano.
2) Go in and change the instrument patch for wildwebmidi.data (I posted my process for doing this [here](https://github.com/zz85/wild-web-midi/issues/5) , but it played as silence.)
 I am about to try my next step, which is to go in and create an MP3 for each verovio score using timidity, then going in and aligning the highlighted notes with timestamps for the MP3. Before I move to this step, is there a simpler way of changing the instrument in the midi playback verovio? Did I perhaps miss something in my first two steps?

**Comment by lpugin** [comment]
`instDef` is not supported yet. I will add other instruments to the https://github.com/rism-ch/midiplayer

**Comment by rettinghaus** [comment]
`instrDef` is supported, but will not work with midiplayer, as there is only one instrument.

**Comment by lpugin** [comment]
Yes, you are right!

**Comment by andrewacashner** [comment]
I set the `@midi.instrname` in `scoreDef/staffDef`, then create a MIDI file with Verovio and play it with `timidity`. It uses the default piano sound, as described above. If I run `timidity mei_output.mid --default-program=52` then it plays the correct instrument. So it seems like timidity is not picking up the instrument definition from the Verovio output.

**Comment by rettinghaus** [comment]
@andrewacashner You are right, but by default it's zero indexed. MEI differentiates between 0-indexed and 1-indexed values, see https://music-encoding.org/guidelines/v4/data-types/data.midivalue.html.
