### ISSUE TITLE
@meter.sym should ignore @meter.count and @meter.unit by default

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#82]
Verovio engraves a doubled time signature in cases like 
<scoreDef meter.count="2" meter.unit="2" meter.sym="cut"/>

**Comment by lpugin** [comment]
I now there is something unclear there. Do you have a concrete example?

**Comment by rettinghaus** [comment]
Like in the Example Ahle_Jesu_meines_Herzens_Freud.mei
![ahle](https://cloud.githubusercontent.com/assets/7693447/7345110/01ae77d8-ecd2-11e4-97a8-a5783dbd014f.png)

**Comment by lpugin** [comment]
Fixed with commit e01c377
