### ISSUE TITLE
MusicXML sound element

### ISSUE THREAD

**Issue by k-ljung** [rism-ch/verovio#833]
I'm experiment with tempo changes and wondering what Verovio have for requirements to handle this?

If I create an arrangement in MuseScore, the `<sound tempo = "120" />` element is located in the `<direction>` element but if I export from Finale, the  `<sound tempo = "120" />` is located directly below the `<measure>` element and Verovio does not handle tempo change.

The MusicXML spec states:
```
They can stand alone within a part/measure, or be a component element within a direction.
```

**Comment by rettinghaus** [comment]
Tempo changes are supported, as long as you make a *visual* tempo change (i.e. inside a `direction`).
Try the attached MusicXML. 
[tempi.zip](https://github.com/rism-ch/verovio/files/1950804/tempi.zip)
