### ISSUE TITLE
Key signature should be nearer to clef

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#84]
![clefkey](https://cloud.githubusercontent.com/assets/7693447/7345272/6063566c-ecd3-11e4-840e-64fe31e10cec.png)

**Comment by rettinghaus** [comment]
this is now a duplicate of #135

**Comment by rettinghaus** [comment]
While MEI is rendered nicely, with PAE it's still an issue.

**Comment by lpugin** [comment]
This was improved with the last commit, so hopefully this will fix it. The issue was different spacing (after the time sig) depending on the meter.unit value, which of course should not be the case.
