### ISSUE TITLE
https for Verovio.org

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#843]
With GithHub enabling secure connections (see #353) it is now possible to go to https://www.verovio.org/index.xhtml
But it won't work correctly, as all urls for resources are hardcoded to `http://www.verovio.org/some_resource` in the source. Is this done by Jekyll and fixable?

**Comment by craigsapp** [comment]
Some or all of the problem could be fixed by changing http to https in this file:

https://github.com/rism-ch/verovio/blob/gh-pages/_config.yml

**Comment by rettinghaus** [comment]
I see. 
But wouldn't that mean forcing secure connections? I would prefer that anyway, but some may not.

**Comment by craigsapp** [comment]
I don't think it will be a problem to force a secure connection, as any unsecure website that uses a secure asset (i.e., verovio-toolkit.js) should not have a problem (but the reverse as you notice can be a problem).

**Comment by craigsapp** [comment]
Here is the Github page related to this issue: https://help.github.com/articles/securing-your-github-pages-site-with-https/
