### ISSUE TITLE
Use smufl glyphs for longas, maximas and breves. 

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#844]
These noteheads shouldn't be drawn by a function, but instead use the proper SMuFL glyphs.

**Comment by lpugin** [comment]
This was already discuss. One major issue with fonts is that they will not be appropriate for oblique ligatures because only a fix set of interval can be considered. If ligatures cannot be rendered with font glyph, then it is better also not to render breve (and others) with font glyph.

**Comment by rettinghaus** [comment]
Makes sense. 
But then they shouldn't use SVG path, as it won't work with MEI color.
