### ISSUE TITLE
Thickness of mensuration signs

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#848]
In this example:

<img width="1046" alt="screen shot 2018-05-05 at 3 10 57 pm" src="https://user-images.githubusercontent.com/3487289/39668020-caef34a0-5077-11e8-98f6-c84818ce914e.png">

The mensuration sign is too thin.  Is there a way to control the thickness from the user side?  In any case it should be at least as thick as note stems, and otherwise thicker than staff lines.  I would probably like it at least as thick at the vertical lines on the C-clef to its left.

Test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000002104579224">
                <score xml:id="score-0000000459868031">
                    <scoreDef xml:id="scoredef-0000000787335713" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001325984713">
                            <staffDef xml:id="staffdef-0000001364710838" clef.shape="C" clef.line="3" key.sig="0" mensur.sign="C" n="1" notationtype="mensural" lines="5">
                                <label xml:id="label-0000000059499059" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000208351464">
                        <measure xml:id="measure-L2" right="invis" n="0">
                            <staff xml:id="staff-0000001722782619" n="1">
                                <layer xml:id="layer-L2F1N1" n="1">
                                    <note xml:id="note-L8F1" dots="1" dur="brevis" oct="4" pname="f" accid.ges="n" />
                                    <dot xml:id="dot-0000001030309977" />
                                    <note xml:id="note-L9F1" dots="1" dur="semibrevis" oct="4" pname="e" accid.ges="n" />
                                    <note xml:id="note-L10F1" dur="semibrevis" oct="4" pname="d" accid.ges="n" />
                                    <note xml:id="note-L11F1" dur="semiminima" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L12F1" dur="minima" oct="4" pname="e" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L13F1" dur="semiminima" oct="4" pname="d" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L14F1" dur="semiminima" oct="4" pname="e" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L15F1" dur="minima" oct="4" pname="f" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L16F1" dur="semiminima" oct="4" pname="e" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L17F1" dur="semiminima" oct="4" pname="d" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L18F1" dur="semiminima" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L19F1" dur="minima" oct="3" pname="b" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L20F1" dur="semibrevis" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L21F1" dur="minima" oct="4" pname="d" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L22F1" dur="brevis" oct="4" pname="e" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
copy of #824

**Comment by lpugin** [comment]
I am not against using SMuFL glyphs, but my impression is that SMuFL does not cover all cases. I have no example at hand, but I have seen the use of a perfect circle with three dots in it. So the starting point would be for the mensural IG to have a look at this and to make a list of additions to be made to SMuFL. Once we have this we can switch. OK?

**Comment by rettinghaus** [comment]
We have to combine the SMuFL glyphs. Your example can be put together with: 
https://www.smufl.org/version/latest/glyph/mensuralProlation2
https://www.smufl.org/version/latest/glyph/mensuralProlationCombiningThreeDots

**Comment by craigsapp** [comment]
Here are mensuration signs found in the JRP repertory (about 1,200 works, covering perhaps 90-95% of Renaissance mensuration signs):

http://ribbon.humdrum.org/doc/mensuration-sampler

Image of the list is given below.  The list is sorted from most common to least common mensuration signs.  Tinctoris created his own mensuration signs which are found near the bottom of the list, for example, since no one else used them.

The 5th column lists the SMUFL glyphs needed to create the mensuration sign.  The 3rd column links to an example score that uses that mensuration sign (you will have to scroll through the piece to find it sometimes).  The 6th column is the MuseData rendering of the mensuration sign, and the 7th column is the SMUFL rendering of the mensuration sign (a few faked ones near the end).

<img width="654" alt="screen shot 2018-05-06 at 12 38 22 pm" src="https://user-images.githubusercontent.com/3487289/39677092-4750f13e-512a-11e8-9561-cb7dd037c93d.png">
<img width="608" alt="screen shot 2018-05-06 at 12 38 44 pm" src="https://user-images.githubusercontent.com/3487289/39677095-4bc430d2-512a-11e8-9f55-c7dcb76246f2.png">

**Comment by lpugin** [comment]
OK, when https://github.com/w3c/smufl/issues/88 is solved we will switch to SMuFL glyphs.
