### ISSUE TITLE
Implement SetMensurOrient()

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#852]
libmei has functionality for mensuration orientation, but not completely connected to verovio.

`SetMensurOrient()` should be implemented in:

```
../libmei/atts_mensural.cpp 
../libmei/atts_mensural.h
```

But this might also require implementing the rotations of the mensuration glyphs in other locations in the code (probably mensur.cpp)

This would allow for displaying reverse-C and reverse-cut-C mesurations:

<img width="140" alt="screen shot 2018-05-06 at 11 47 38 pm" src="https://user-images.githubusercontent.com/3487289/39688458-c65c943a-5187-11e8-8ec3-defa58eae3c3.png">
<img width="123" alt="screen shot 2018-05-06 at 11 47 47 pm" src="https://user-images.githubusercontent.com/3487289/39688460-c8162b4c-5187-11e8-9ce4-9f516ff1d328.png">

(occur in 10 JRP pieces)

**Comment by rettinghaus** [comment]
now available:
![849](https://user-images.githubusercontent.com/7693447/39987268-95583d02-5764-11e8-8691-3154131a775a.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="C" clef.line="1" mensur.slash="1" mensur.sign="C" mensur.orient="reversed" n="1" notationtype="mensural" lines="5">
                <label />
              </staffDef>
            </staffGrp>
          </scoreDef>
          <section>
            <staff n="1">
              <layer n="1">
                <note dots="1" dur="brevis" oct="4" pname="f" />
                <note dots="1" dur="semibrevis" oct="4" pname="f" />
                <note dur="semibrevis" oct="4" pname="g" />
                <note dur="minima" oct="4" pname="f" />
                <note dur="minima" oct="4" pname="c" />
                <note dur="minima" oct="4" pname="f" />
                <dot />
                <note dur="semiminima" oct="4" pname="g" />
                <note dur="minima" oct="4" pname="a" />
              </layer>
            </staff>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by craigsapp** [comment]
Looks great!

<img width="695" alt="screen shot 2018-05-14 at 2 41 59 am" src="https://user-images.githubusercontent.com/3487289/39989934-2d279c44-5720-11e8-8809-cda4ee457d60.png">
