### ISSUE TITLE
visibility="hidden" vs. opacity="0" for SVG elements

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#859]
Related to issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/89

It may be nice to change `visibility="hidden"` to instead use `opacity="0"` in the SVG renderings of music notation from verovio.  This would allow the invisible element to receive mouse click events.

Piotr's jsfiddle demo:

https://jsfiddle.net/p93e6dfr/3

The first square is a regular visible one, and you can click on it.  The second one has `visibility="hidden"` and it cannot be clicked on, and the third one has `opacity="0"` but can be clicked on.

**Comment by rettinghaus** [comment]
This will not work, because MEI allows e.g. 
```
<layer visible="false">
  <note/>
  <note visible="true"/>
  <note/>
</layer>
```
which looks in SVG like: 
```
<g class="layer" visibility="hidden">
  <g class="note"/>
  <g class="note" visibility="visible"/>
  <g class="note"/>
</g>
```
whereas you can't do this with `opacity`: 
```
<g class="layer" opacity="0">
  <g class="note"/>
  <g class="note" opacity="1"/>
  <g class="note"/>
</g>
```

**Comment by craigsapp** [comment]
Is there a way of setting CSS opacity in MEI?  

Perhaps best via `@label="invisible"` that maps to a `@class="invisible"`  in the SVG, which in turn could have an opacity setting of 0 via `g.invisible` in CSS...

**Comment by rettinghaus** [comment]
You could use `color` directly, as MEI supports all CSS colors, e.g. `color="rgba(0,0,0,0)"` or `color="hsl(0,0%,100%)"`.

**Comment by rettinghaus** [comment]
btw `@label` isn't mapped to `@class`, `@type` is.

**Comment by craigsapp** [comment]
> btw `@label` isn't mapped to `@class`, `@type` is.

Thanks! `@label` and `@type` are LBBs:

https://thetech.com/2013/11/12/birds-v133-n53

The color possibility is interesting -- I'll try out both and see what is the most convenient.
