### ISSUE TITLE
Default value for 'scale' (100) option is not managed correctly in the JavaScript toolkit

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#864]
Hello,

It seems that the default value for 'scale' (100) option is not managed correctly if it was previously set in a previous call to setOptions, renderData (or any method of the JavaScript toolkit taking options in parameter), in the same page.

Using the HTML code provided in defect #858, comment the second appearance of the scale option:

                     //scale: 80,

and you will notice that the second incipit is displayed with the same size as the one above, so with a scale factor of 60%, and not 100% as expected.

Thanks

**Comment by lpugin** [comment]
I can see two sizes here https://github.com/rism-ch/verovio/issues/858#issuecomment-388658102 so it seems to work.

**Comment by craigsapp** [comment]
It is not mentioned the other way as well 😛

**Comment by efreja** [comment]
Easy answer ;-) But honestly adding the two lines above in the documentation would have avoided spending time to understand what was wrong in my code, and time to enter that issue...
I don't know if you realize how much development would be simplified if the code documentation (in general) was acurate..

**Comment by craigsapp** [comment]
Why do you want to show music with different fonts on the same page?

Why do you want to show music with different sizes on the same page?

The same goes for what the motivation for submitting the issues as you have.

**Comment by efreja** [comment]
??????????
This is totally off topic!!
But I can answer that in a private mail elsewhere if you want.

**Comment by craigsapp** [comment]
That is OK, I don't need to know if it is top secret.  Changing the musical font within a webpage is a bit weird, so I was wondering if there was a practical use, or you are just being thorough in testing verovio.  I have come across a similar problem (not in verovio), and had to do a similar solution of changing the IDs of the items in the SVG content.  The easy solution is to load the svg content in an `<img>` tag since that isolates the IDs between images.

**Comment by efreja** [comment]
You answer was abrupt, but this is not top secret. You can get in touch through my website mentioned on my profile.

**Comment by craigsapp** [comment]
Nice website, and I see that you have a French accent (it sounded like German to me).

**Comment by efreja** [comment]
Thanks, ... and exact ;-)
