### ISSUE TITLE
The size occupied by the rendered <svg> element in the JavaScript toolkit is too wide

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#865]
Hello,

The size occupied by the <svg> element returned by renderData (ore renderPage , etc..) in the JavaScript toolkit is far too wide, leaving empty space on the right.
As we don't know if the space is fully occupied or not, it prevents from rescaling it appropriately as necessary for responsive design.

As an example, with code provided in issue #858, the inspector reveals a width of 2216, whereas probably 2/3 of the width would have been sufficient:

![capture d ecran 2018-05-14 a 22 31 27](https://user-images.githubusercontent.com/16109195/40022428-47f8aa6a-57c8-11e8-915f-1597d487667e.png)

Thanks

PS : It's not because it contains bugs that Verovio is not a Great soft !!! ;-)

**Comment by lpugin** [comment]
You should set the page width to the minimum you would like to have. With `noLayout` (now `breaks=none`) the width will then be extended as required.

**Comment by efreja** [comment]
Thanks.
Indeed noLayout=1 works, but watch out: it's undocumented.
On:
http://www.verovio.org/javascript.xhtml
you find ignoreLayout=1 (only in the example), which doesn't seem to work.
And I couldn't have breaks=none or breaks="none" work either…

**Comment by efreja** [comment]
My mistake : breaks:"none" works in the JSON options...

**Comment by craigsapp** [comment]
Here are the list of functions that are available in the toolkit (accurate regardless of documentation):

https://github.com/rism-ch/verovio/blob/f6a21feab2a590e1199ad9e870bc8298301ae27f/emscripten/buildToolkit#L165-L188

**Comment by lpugin** [comment]
This is indeed the great thing with open source projects, which is that you can always look at the code if the documentation is not clear enough ;-). And if you do want the documentation to be clearer, the great thing with github is that you can improve it and submit a pull request.

**Comment by efreja** [comment]
Yes I totally agree and tried to participate a while a go but my XCode version was outdated...
Let's say that pointing out the bugs/the lacks is already an improvement for the future users..
Whithout speaking of the many references to Verovio on my website www.partitionnumerique.com
