### ISSUE TITLE
Title, composer, metadata are not visible

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#868]
Hello,

We use the javascript toolkit. Looking at the MEI viewer, I notice that the score shows the title, creator, etc. However, this is not true for  us, even though the MEI seems to be complete. Example:

http://neuma.huma-num.fr/home/opus/qualeval:Handel_Arie/

MEI: http://neuma.huma-num.fr/media/corpora/qualeval/Handel_Arie/mei.xml

What are we doing wrong? Thanks for your help.

Philippe

**Comment by rettinghaus** [comment]
This is a feature of Verovio version 2. You would have to update to the latest development version.

**Comment by rigaux** [comment]
Great. Thanks a lot.
