### ISSUE TITLE
Scale ignored with latest version?

### ISSUE THREAD

**Issue by rigaux** [rism-ch/verovio#869]
Hello,

We tried the development version. Fine for the title, but it seems that the 'scale' parameter is ignored. The score is much larger than expected, and we cannot reduce its size.

Cheers

P.

**Comment by lpugin** [comment]
Please double check the console. There used to be a deprecation warning about options being passed as stringified json object. String is no longer supported and the options have to be a json object.

**Comment by rigaux** [comment]
My mistake, I should have checked. Many thanks, it works.
