### ISSUE TITLE
Single Eighth Notes with beams display incorrectly

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/verovio#87]
This is related to music-encoding/sibmei#13, however, I think it's also a Verovio bug.

A single eighth note with a beam is being displayed in Verovio as a quarter note. 

Verovio displays:

![vrvbeams](https://cloud.githubusercontent.com/assets/163183/7515781/f77973c6-f497-11e4-854d-49a578c01095.png)

For the input:

```
<?xml version="1.0" encoding="UTF-16" ?>
<mei meiversion="2013" xmlns="http://www.music-encoding.org/ns/mei" xmlns:xlink="http://www.w3.org/1999/xlink">
<meiHead>
	<fileDesc>
		<titleStmt>
			<title/>
			<respStmt>
				<persName/>
			</respStmt>
		</titleStmt>
		<pubStmt>
			<availability>
				<useRestrict>Copyright © </useRestrict>
			</availability>
		</pubStmt>
	</fileDesc>
	<encodingDesc>
		<appInfo>
			<application version="7" xml:id="sibelius7">
				<name>Sibelius</name>
			</application>
		</appInfo>
	</encodingDesc>
	<workDesc>
		<work>
			<titleStmt>
				<title/>
				<respStmt/>
			</titleStmt>
		</work>
	</workDesc>
</meiHead>
<music>
	<body>
		<mdiv>
			<score>
				<scoreDef meter.count="4" meter.unit="4" page.botmar="12.7mm" page.height="297mm" page.leftmar="12.7mm" page.rightmar="12.7mm" page.topmar="12.7mm" page.width="210mm" ppq="256">
					<staffGrp>
						<staffDef clef.line="2" clef.shape="G" key.mode="major" key.sig="0" lines="5" n="1" xml:id="sd1"/>
					</staffGrp>
				</scoreDef>
				<section>
					<pb n="1"/>
					<measure label="1" n="1">
						<staff n="1">
							<layer n="1">
								<note dots="1" dur="2" dur.ges="768p" oct="5" pname="c" xml:id="p1ccd5n0v1b1s1"/>
								<note dur="4" dur.ges="256p" oct="5" pname="f" xml:id="p1cfd5n768v1b1s1"/>
							</layer>
						</staff>
					</measure>
					<measure n="2">
						<staff n="1">
							<layer n="1">
								<note dots="1" dur="4" dur.ges="384p" oct="5" pname="d" xml:id="p1cdd5n0v1b2s1"/>
								<beam>
									<note dur="8" dur.ges="128p" oct="5" pname="f" xml:id="p1cfd5n384v1b2s1"/>
								</beam>
								<note dur="2" dur.ges="512p" oct="5" pname="c" tie="i" xml:id="p1ccd5n512v1b2s1"/>
							</layer>
						</staff>
					</measure>
					<measure n="3">
						<staff n="1">
							<layer n="1">
								<note dur="2" dur.ges="512p" oct="5" pname="c" tie="t" xml:id="p1ccd5n0v1b3s1"/>
								<rest dur="2" dur.ges="512p" xml:id="p1r512v1b3s1"/>
							</layer>
						</staff>
					</measure>
					<measure n="4" right="end">
						<staff n="1">
							<layer n="1">
								<mRest/>
							</layer>
						</staff>
					</measure>
				</section>
			</score>
		</mdiv>
	</body>
</music>
</mei>
```

**Comment by lpugin** [comment]
Yes, I suspect it is. However, shouldn't a beam with one single not be forbidden in the first place?

**Comment by ahankinson** [comment]
I'm working on that part... ;)

**Comment by lpugin** [comment]
I was thinking in MEI itself. At least with a schematron rule?

**Comment by pe-ro** [comment]
There already is a schematron rule that attempts to catch this kind of error:

<constraintSpec ident="When_not_copyof_beam_content" scheme="isoschematron">
  <constraint>
    <sch:rule context="mei:beam[not(@copyof)]">
      <sch:assert test="count(descendant::*[local-name()='note' or local-name()='rest' or
              local-name()='chord' or local-name()='space']) &gt; 1">A beam without a copyof
              attribute must have at least 2 note, rest, chord, or space descendants.</sch:assert>
    </sch:rule>
  </constraint>
</constraintSpec>

Validating Andrew's markup against http://music-encoding.googlecode.com/svn/tags/MEI2013_v2.1.1/schemata/mei-all.rng catches the error.

What this rule doesn't enforce is that the events (note, rest, chord, etc.) should be siblings.  Without this, the following markup will also pass:

<beam>
  <app>
    <rdg><note/></rdg>
    <rdg><note/></rdg>
  </app>
</beam>

I'll see what I can do about this, but there are a large number of possibilities so it may not be possible to stop every one.

--
p.


__________________________
Perry Roland
Music Library
University of Virginia
P. O. Box 400175
Charlottesville, VA 22904
434-982-2702 (w)
pdr4h (at) virginia (dot) edu
________________________________

**Comment by lpugin** [comment]
Great. I suspect this one would also pass?

<beam>
  <chord>
    <note/>
    <note/>
  </chord>
</beam>

As far as Verovio is concerned, I would be more in favor of emitting a
warning than rendering it properly. Even though this would mean
re-implementing the schmatron rule. And as we can see it is not trivial, so
let's do it only in one place (schematron). We have enough to do with
correct encoding... ;-)

**Comment by pe-ro** [comment]
Yep, that would pass too.  :-(

Here's my first attempt at re-writing the rule:

<sch:assert
  test="descendant::*[local-name()='beatRpt' or local-name()='bTrem' or local-name()='chord' or
  local-name()='halfmRpt' or local-name()='note' or local-name()='rest' or local-name()='space' or local-name()='tuplet']
  [following-sibling::*[local-name()='beatRpt' or local-name()='bTrem' or local-name()='chord' or
  local-name()='halfmRpt' or local-name()='note' or local-name()='rest' or local-name()='space' or local-name()='tuplet']]"
  >A beam without a copyof attribute must have at least 2 note, rest, chord, or space descendants.</sch:assert>

--
p.

__________________________
Perry Roland
Music Library
University of Virginia
P. O. Box 400175
Charlottesville, VA 22904
434-982-2702 (w)
pdr4h (at) virginia (dot) edu
________________________________

**Comment by lpugin** [comment]
I am close it for now. We can re-open it if necessary
