### ISSUE TITLE
Rendering harmony as text using <rend rend="sup"> fails

### ISSUE THREAD

**Issue by peterkorgaard** [rism-ch/verovio#886]
I'm trying to format the text within `<harm>` using `<rend>`  in MEI without success. I'm using javascript toolkit version 2.0.0-dev-5b37cd0

`<harm place="above" staff="1" tstamp="1">F<rend rend="sup">5b</rend></harm>`

This does not give the intended result - see below. Is this a bug or is there another reason?

![image](https://user-images.githubusercontent.com/22868391/40904742-f98eb40e-67db-11e8-8336-c8001dbbe6de.png)

**Comment by rettinghaus** [comment]
There is a problem here: `<rend>` within `<harm>` has the position re-set. So there is an error in *DrawHarmString* with `VRV_UNSET`.

**Comment by peterkorgaard** [comment]
Is this also the reason why the text is not rendered as sup?

**Comment by rettinghaus** [comment]
No. `@rend="sup"` isn't implemented yet, and will not work anyway, as this SVG feature (`baseline-shift`) isn't supported by any browser currently. 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseline-shift

**Comment by lpugin** [comment]
Then we close it for now

**Comment by lpugin** [comment]
This is now implemented. 
![image](https://user-images.githubusercontent.com/689412/66896025-652cbc00-eff4-11e9-9ee7-6aff9f1073f2.png)
