### ISSUE TITLE
Upgrade key.sig.showchange to keysig.showchange

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#888]
MEI files 3.0 should be upgraded following this attribute change

**Comment by craigsapp** [comment]
Does `@key.sig` change to `@keysig` as well?

**Comment by pe-ro** [comment]
Sorry for arriving late for the party -- We could change the name of `@key.sig` to `@keysig` in v. 4, if that makes things clearer.

**Comment by craigsapp** [comment]
Done: https://github.com/music-encoding/music-encoding/issues/525

**Comment by pe-ro** [comment]
Thanks.
