### ISSUE TITLE
Check page range in emscripten_main.cpp

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#895]
In `verovio/tool/main.cpp` there is a check for a valid page:

https://github.com/rism-ch/verovio/blob/f4fef8d19ba4144ec3818a6fc01074885981f0cd/tools/main.cpp#L445-L454

But the `verovio/emscripten/emscripten_main.cpp` version of `main.cpp` does not have such a check, such as when creating an SVG image of a page:

https://github.com/rism-ch/verovio/blob/5c506e5a3fd1ddb431ba035591906ad5ec4b5f8d/emscripten/emscripten_main.cpp#L145-L150

It would be good to add page-range checks in `emscription_main.cpp` in a manner similar to `main.cpp`.

Perhaps better would be to do the page range checking in the Toolkit class, and print Error or Warning messages from there when the page is out of range (such as in `Toolkit::RenderToSVG()` in this case).

**Comment by lpugin** [comment]
Simple JavaScript change. Please make a PR
