### ISSUE TITLE
Note flags randomly appear on some music sheets

### ISSUE THREAD

**Issue by efreja** [rism-ch/verovio#907]
Hello,

While testing https://wordpress.org/plugins/music-sheet-viewer/ I found a random bug in Verovio that makes that sometimes note flags may randomly appear close to note heads, like:

![bugappogiaturas](https://user-images.githubusercontent.com/16109195/41874866-66d8ceb6-78c9-11e8-94ce-979e8d2e9b1e.png)

I reproduced this on a very simple code:

```xhtml
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="http://www.verovio.org/javascript/latest/verovio-toolkit.js" type="text/javascript"></script>
</head>
<body>
<div id="output"></div>
<div id="output2"></div>
<script type="text/javascript">
var vrvToolkit = new verovio.toolkit();
var data = "@clef:F-4\n\
@keysig:xF\n\
@timesig:c\n\
@data:qq,3{DnF'D}r/2Fqq,3{DnF'D}r2Aqq3,{DF'D}r/b1B,qq3{EG'C}r/1A//";
var svgdata = vrvToolkit.renderData(data,{adjustPageHeight: 1});
document.getElementById("output").innerHTML = svgdata;
var svgdata2 = vrvToolkit.renderData(data,{adjustPageHeight: 1});
document.getElementById("output2").innerHTML = svgdata2;
</script> 
</body>
</html>
```

where you can see that the same code is rendered twice. The first time it's not generated correctly, the second time it is. If there's only one div, it's correct!!

Hope it helps.

Etienne

**Comment by craigsapp** [comment]
This is similar or the same as issue: https://github.com/rism-ch/verovio/issues/613

which was originally fixed with this commit: https://github.com/rism-ch/verovio/commit/e5695b4b1559c81857a66ef3ac88bc4c5cee488f

Perhaps this code has been reverted somehow, or there is a similar uninitialized variable that needs to be initialized to fix the bug.

**Comment by craigsapp** [comment]
I get the same result (running in Safari):

![screen shot 2018-06-25 at 2 31 57 pm](https://user-images.githubusercontent.com/3487289/41876994-913a5ff2-7884-11e8-9636-ef4a1154f077.png)

Interestingly, I do not get the problem when switching to the Humdrum-enabled version of the verovio toolkit, even though the rest of the code is the same, and the input is still Plaine & Easie data.

The only difference in this code is that the toolkit url is changed to:

https://verovio-script.humdrum.org/scripts/verovio-toolkit.js

This version should be very close to the "latest" script that you are using.

```xhtml
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit.js" type="text/javascript"></script>
</head>
<body>
<div id="output"></div>
<div id="output2"></div>
<script type="text/javascript">
var vrvToolkit = new verovio.toolkit();
var data = "@clef:F-4\n\
@keysig:xF\n\
@timesig:c\n\
@data:qq,3{DnF'D}r/2Fqq,3{DnF'D}r2Aqq3,{DF'D}r/b1B,qq3{EG'C}r/1A//";
var svgdata = vrvToolkit.renderData(data,{adjustPageHeight: 1});
document.getElementById("output").innerHTML = svgdata;
var svgdata2 = vrvToolkit.renderData(data,{adjustPageHeight: 1});
document.getElementById("output2").innerHTML = svgdata2;
</script> 
</body>
</html>
```
 
![screen shot 2018-06-25 at 2 33 49 pm](https://user-images.githubusercontent.com/3487289/41877061-cb1dab02-7884-11e8-9724-daf5b2ac383c.png)

**Comment by lpugin** [comment]
This is indeed bug #613 that is fixed in the develop version.
