### ISSUE TITLE
Half flat (Arabic quarter-tone flat)

### ISSUE THREAD

**Issue by elachkarcharbel** [rism-ch/verovio#910]
verovio doesn't show the Arabic quarter-tone flat (the flat with a slash through it to represent a quarter-flat symbol) that can be added to MEI using the <accid> tag and giving the "glyphnum" attribute a value equal to "U+E442" : 

```xml
<note dur="4" oct="5" pname="e">
    <accid accid="1qf" glyphnum="#xE442" />
</note>
```

<img title="arabic_music_notation_half_flat" src="https://user-images.githubusercontent.com/40386389/42269676-7acaba82-7f87-11e8-8f67-0f6207fdd22f.png" height="100">

http://www.smufl.org/version/latest/glyph/accidentalBakiyeFlat/. 
It is needed also to implement this flat in the key signature.

**Comment by ramagottfried** [comment]
I was also just trying to do this, but with other accidentals in the Bravura font, like these: https://w3c.github.io/smufl/gitbook/tables/extended-helmholtz-ellis-accidentals-just-intonation.html --  is there a way to use accidentals and other glyphs by using the MEI `<accid glyph.name="U+etc" />`?

**Comment by elachkarcharbel** [comment]
> I was also just trying to do this, but with other accidentals in the Bravura font, like these: https://w3c.github.io/smufl/gitbook/tables/extended-helmholtz-ellis-accidentals-just-intonation.html -- is there a way to use accidentals and other glyphs by using the MEI `<accid glyph.name="U+etc" />`?

Hello @ramagottfried . Thanks for asking this question. I am afraid that in my case this is not a solution. I am trying to target Arabic accidentals. Sometimes you will find accidentals that have the same functionality but different annotation/visual encoding. Take the case of the half-flat ( see the image the below ). This one has the same functionality of  `<accid glyph.name="U+E2E2" />` but way different representation when it comes to the visual encoding.
![image](https://user-images.githubusercontent.com/40386389/87800749-72aef500-c857-11ea-9b60-c3675dbf4d2c.png)

**Comment by ramagottfried** [comment]
hi @elachkarcharbel -- thanks for your response! 
for me this accidental doesn't display, is it supposed to? 

here is what I'm testing:

```
<head>
     <!--   <script src="node_modules/verovio-dev/index.js"></script> -->
     <script src="http://www.verovio.org/javascript/latest/verovio-toolkit.js"></script>

</head>
<body>
<div id="foo"></div>

<script>
        let vrvToolkit = new verovio.toolkit();
        
        vrvToolkit.setOptions({
                scale: 100,
                evenNoteSpacing : true,
                font: "Bravura" 
        });

        let mei = `<mei xmlns="http://www.music-encoding.org/ns/mei">
                    <meiHead>
                        <fileDesc>
                            <titleStmt>
                                <title/>
                            </titleStmt>
                            <pubStmt/>
                        </fileDesc>
                    </meiHead>
                    <music>
                        <body>
                            <mdiv>
                                <score>
                                    <scoreDef>
                                        <staffGrp>
                                            <staffDef clef.shape="G" clef.line="2" n="1" lines="5"/>
                                        </staffGrp>
                                    </scoreDef>
                                    <section>
                                        <measure>
                                            <staff n="1">
                                                <layer>
                                                    <note pname="c" oct="4" dur="4">
                                                        <accid glyph.name="U+E2E2" />
                                                        </note>

                                                    <note pname="c" oct="4" dur="8"/>
                                                    <note pname="c" oct="4" dur="16"/>
                                                    <note pname="c" oct="4" dur="4"/>

                                                </layer>
                                            </staff>
                                        </measure>
                                    </section>
                                </score>
                            </mdiv>
                        </body>
                    </music>
                    </mei>`;


       
        vrvToolkit.loadData(mei);
        let svg = vrvToolkit.renderToSVG(1, {});

        let foo = document.getElementById("foo");
        foo.innerHTML = svg;

</script>

</body>

```

**Comment by elachkarcharbel** [comment]
I'm not sure if `<accid glyph.name="U+E2E2" />`  works.
If you want to visualize this accidental, it is already supported in MEI and can be visualised using verovio by replacing the above line of code with this one `<accid accid="1qf" />`.
Welcome!
NB: "1qf" means one-quarter flat. you can also see the one-quarter sharp by writing "1qs" instead.

**Comment by ramagottfried** [comment]
right, yes the accid attribute works, but I am interested in being able to use the full range of glyphs in the standard Bravura font. It seems like that would be really useful in many different situations. hopefully this will be implemented in verovio someday!

**Comment by rettinghaus** [comment]
This has been recently added to MEI (see https://music-encoding.org/guidelines/dev/data-types/data.accidental.written.aeu.html), so basically it can be implemented into Verovio now …

**Comment by elachkarcharbel** [comment]
Perfect! I had already drawed the symbols shown in the attached images as SVG. But it would be perfect if Verovio provide the support to the ones that you already mentioned

**Comment by infojunkie** [comment]
Fyi, SMuFL has a section for Arabic accidentals https://w3c.github.io/smufl/gitbook/tables/arabic-accidentals.html

**Comment by lpugin** [comment]
https://github.com/rism-ch/verovio.org/blob/gh-pages/_tests/accid/accid-007.mei

![image](https://user-images.githubusercontent.com/689412/106278277-bf2db100-623a-11eb-9d63-8534137d900e.png)

**Comment by elachkarcharbel** [comment]
Thank you @lpugin 
This will help us in encoding eastern music scores in MEI

**Comment by lpugin** [comment]
Great! You can open another issue if it is not working for key signatures. I haven't look at this.
