### ISSUE TITLE
Att::GetTstamp2() quanitization problem

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#922]
In `Att::MeasurebeatToStr()`, the beat value is limited to one fractional digit.  Why is that?

https://github.com/rism-ch/verovio/blob/6fd52221603c4a3fc2d195a7deba9dd430e8e23f/src/att.cpp#L302-L305

This should be removed or at least 4 or 5 digits after the decimal should be given.

This is the cause of issue https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/140 where a trill line endtime is internally changed from 2.75 to 2.8 by this function, causing the trill line to extend too far.

**Comment by lpugin** [comment]
Please change it to 4 decimal.

**Comment by craigsapp** [comment]
Done with commit https://github.com/rism-ch/verovio/commit/1e3c4ba91ccb723538ed6e5b02c1392a55c95ec9

New test example:

```
 <trill xml:id="trill-L5F1" staff="1" startid="#note-L5F1" tstamp2="0m+2.7500" />
```

You do not want to use the stringstream class for such functions?   That will avoid trailing zeros when converting doubles into strings.


```cpp
std::string Att::MeasurebeatToStr(data_MEASUREBEAT data) const
{
    std::stringstream ss;
    ss << data.first << "m+" << data.second;
    return ss.str();
}
```

Example output with such a function:

```
<trill xml:id="trill-L5F1" staff="1" startid="#note-L5F1" tstamp2="0m+2.75" />
```

If rounding for tuplets is important, then this can be done to limit it to a particular number of digits like this:

```
std::string Att::MeasurebeatToStr(data_MEASUREBEAT data) const
{
    std::stringstream ss;
    ss << data.first << "m+" << (int)(data.second*1000000.0)/1000000.0;;
    return ss.str();
}
```

This limits the number of digits to 6 while also avoiding trailing zeros in the fractional part of the number.


The above code will produce the same as the previous example, since there are only two decimal digits:

```
 <trill xml:id="trill-L5F1" staff="1" startid="#note-L5F1" tstamp2="0m+2.75" />
```
