### ISSUE TITLE
match music21 objects with svg output

### ISSUE THREAD

**Issue by mxordn** [rism-ch/verovio#923]
I'm currently working on an educational app that uses the music21 toolkit for manipulating scores in the backend and verovio to display results in the browser.

For an interaction with the music21 backend it would be helpful to be able to match the ID e.g. of a note or its offset in the verovio-output with the stream data-model of music21.

The workflow would be then:
- parse an input file (musicxml, MEI) with IDs/offsets for every note element to verovio
- Browser displays the svg
- By clicking on the svg element, the browser is able to send back the ID/offset of the note which can then be matched with the music21 element to apply changes to the score at this point.

Or maybe there is another much simpler solution?

Best Regards

**Comment by rettinghaus** [comment]
I don't think there's an easy solution. You would have to write a native music21 importer for Verovio or do the ID generation within your backend. 
Or maybe I just do not understand.

**Comment by lpugin** [comment]
Are the MEI xml:ids preserved in the music21 importer http://web.mit.edu/music21/doc/moduleReference/moduleMeiBase.html ? If yes you can probably use them, can't you?
