### ISSUE TITLE
Midi output: slur over two notes produces a single one

### ISSUE THREAD

**Issue by fjorba** [rism-ch/verovio#925]
Thanks for creating Verovio, it fills a need for rendering Plaine and Easie Code.

Although midi output has improved from 1.1.6 to current dev releases, it sometimes still gets confused with slurs.  For example, this pae file:

```
@clef:G-2
@keysig:bB
@timesig:c
@data:2-''C/C-/=/2D+C/C-/-C/4C-2-/=//
```

Renders correct svg ouput, but the fourth bar is wrong in the midi output, as it produces a single whole note instead of two half-notes.  Tested with 2.0.0-dev-28b8852.

**Comment by fjorba** [comment]
I may understand it incorrectly, as I'm not much familiarized with English music technical terms.  However, according to PAE standard, I see the slur word (http://www.iaml.info/plaine-easie-code#toc-13).

This file was created using your own pae editor (https://www.verovio.org/pae-editor.xhtml) by a musicologist (not me, certainly) to code this incipit: https://ifmuc.uab.cat/record/2171.  Which would be the correct coding?

**Comment by rettinghaus** [comment]
In the IAML description it says explicitly:
“only for same-pitch notes”
(see the example)

So the correct encoding would be without the plus sign.

**Comment by fjorba** [comment]
You are right! So, the bug is in your https://www.verovio.org/pae-editor.xhtml, then?

**Comment by rettinghaus** [comment]
Again, there is no bug. No engraving program will ever try to fix your bad encoding.

**Comment by fjorba** [comment]
I've asked the musicologist if it was him who added the +; I understood that it came right from https://www.verovio.org/pae-editor.xhtml, and that's the reason of my question.

We are testing the tools provided by Verovio, and being human persons as we are, and novices coding PAE, we are obviously susceptible of commiting errors.  I'm sorry if opening this issue has bothered you.

**Comment by rettinghaus** [comment]
Neither the documentation of Plaine & Easie, nor the one of Verovio are near perfect. 😃

**Comment by lpugin** [comment]
If I understand correctly the issue can be closed. Just open it again and explain the problem more precisely if I am wrong.

**Comment by fjorba** [comment]
Well, I was waiting for the musicologist answer to my private mail (about the origin of the +) to close it myself, but he may be on vacation, as he doesn't reply. So yes, let's keep it closed unless there is a reason to reopen it.

Anyway, thanks again for writing Verovio!

**Comment by fjorba** [comment]
Now I have the answer from the musicologist. He was writing the PAE code by hand (thus, not using the keyboard or any the aids in the top of the screen), and watching the pentagram output to check that the code was correct. So, the + sign was manually added by him.

Sorry for my confusion, as I wrongly understood that everything, from the notes to the + sign had been generated by Verovio.
