### ISSUE TITLE
clef changes in different layers rendered twice

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#935]
Clef changes are supposed to be given for every layer on a staff within a measure.

But the following example causes problems rendering in verovio, since the implicit timestamps of the two clefs cannot be made the same:

<img width="384" alt="screen shot 2018-10-02 at 7 04 57 am" src="https://user-images.githubusercontent.com/3487289/46353560-5eadeb00-c611-11e8-94bd-d76f62cf086d.png">

The problem is that the clef change in the first layer is at beat 1.5, but in the second layer it is at beat 2, so verovio renders this example instead as:

<img width="406" alt="screen shot 2018-10-02 at 7 10 51 am" src="https://user-images.githubusercontent.com/3487289/46353927-2eb31780-c612-11e8-99e7-322cbfda28ef.png">

How should this be fixed?  Related to previous discussion on how to encode clef changes in MEI (perhaps in the music-encoding issues), the clef in the second layer could be given a `@sameas` attribute that points to the clef in the first layer, causing the second clef to not be displayed.

Alternatively, adding an "invisible" attribute to clefs might be useful (although this would not be as optimal a solution as the `@sameas` one).

Another possibility is to give the clef in the second layer a time offset such as with `@tstamp` so that it overlaps with the clef change in the first layer, although such a solution is probably not optimal as well.

Test data:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-10-02T07:11:32" version="2.0.0-dev-eebabfa">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000423522553">
                <score xml:id="score-0000001000653264">
                    <scoreDef xml:id="scoredef-0000001104367153">
                        <staffGrp xml:id="staffgrp-0000001737249930">
                            <staffDef xml:id="staffdef-0000000226698908" clef.shape="F" clef.line="4" n="1" lines="5">
                                <label xml:id="label-0000001046762150" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-L1F1">
                        <measure xml:id="measure-L1" n="0">
                            <staff xml:id="staff-0000001732895402" n="1">
                                <layer xml:id="layer-L1F1N1" n="1">
                                    <beam xml:id="beam-L4F1-L8F1">
                                        <note xml:id="note-L4F1" dur="8" oct="3" pname="b" accid.ges="n" />
                                        <clef xml:id="clef-L5F1" shape="G" line="2" />
                                        <note xml:id="note-L6F1" dur="8" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L7F1" dur="8" oct="4" pname="a" accid.ges="n" />
                                        <note xml:id="note-L8F1" dur="8" oct="4" pname="g" accid.ges="n" />
                                    </beam>
                                </layer>
                                <layer xml:id="layer-L4F2N2" n="2">
                                    <note xml:id="note-L4F2" dur="4" oct="3" pname="b" stem.len="5.500000" accid.ges="n" />
                                    <clef xml:id="clef-L5F1b" shape="G" line="2" />
                                    <note xml:id="note-L7F2" dur="4" oct="4" pname="f" stem.len="5.500000" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
This is (partially) fixed with the implementation of `clef@sameas`? The second clef is not showing up anymore. 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-10-02T07:11:32" version="2.0.0-dev-eebabfa">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000423522553">
                <score xml:id="score-0000001000653264">
                    <scoreDef xml:id="scoredef-0000001104367153">
                        <staffGrp xml:id="staffgrp-0000001737249930">
                            <staffDef xml:id="staffdef-0000000226698908" clef.shape="F" clef.line="4" n="1" lines="5">
                                <label xml:id="label-0000001046762150" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-L1F1">
                        <measure xml:id="measure-L1" n="0">
                            <staff xml:id="staff-0000001732895402" n="1">
                                <layer xml:id="layer-L1F1N1" n="1">
                                    <beam xml:id="beam-L4F1-L8F1">
                                        <note xml:id="note-L4F1" dur="8" oct="3" pname="b" accid.ges="n" />
                                        <clef xml:id="clef-L5F1" shape="G" line="2" />
                                        <note xml:id="note-L6F1" dur="8" oct="4" pname="b" accid.ges="n" />
                                        <note xml:id="note-L7F1" dur="8" oct="4" pname="a" accid.ges="n" />
                                        <note xml:id="note-L8F1" dur="8" oct="4" pname="g" accid.ges="n" />
                                    </beam>
                                </layer>
                                <layer xml:id="layer-L4F2N2" n="2">
                                    <note xml:id="note-L4F2" dur="4" oct="3" pname="b" stem.len="5.500000" accid.ges="n" />
                                    <clef sameas="clef-L5F1" />
                                    <note xml:id="note-L7F2" dur="4" oct="4" pname="f" stem.len="5.500000" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
![image](https://user-images.githubusercontent.com/689412/46817466-f909df00-cd33-11e8-8643-9e16418a7e55.png)
However, the spacing is altered because the two clefs are not at the same timestamp position. Verovio swallows it, but I wonder if this is actually correct semantically. Maybe in that case it would be better to allow for the second clef to be invisible and to encode something like:
```xml
<clef corresp="clef-L5F1" shape="G" line="2" visibility="false"/>
```
Any thoughts on the encoding?

**Comment by craigsapp** [comment]
The second clef should not have any width to it.  Is that what you mean by "Verovio swallows it"?  If so, then that is good.  Using `clef@visibility="false"` would not be great, because in CSS terminology, "visibility" means that it should possess a width even though it is invisible.  The CSS analogy in this case would be `display:none` rather than `visibility:hidden`.


How it is encoded currently is geared to the software implementation.  There can only be one clef on a staff (other than degenerate cases that @donbyrd can give :-), so encoding a clef in multiple layers is always redundant.  But placing them in each layer makes it easy to process the data, since the clef and the notes in all layers do not have to be pre-sorted to determine the vertical position of the notes on the staff as a layer is processed.

Here is how I would typically encode the example in Humdrum:

```
**kern
*clefF4
*^
8BL	4B
*clefG2	*
8b	.
8a	4f
8gJ	.
*v	*v
=
*-
```

I put one clef in the data, and it comes in the first (left-most) layer.

I allow duplicating the clef:

```
**kern
*clefF4
*^
8BL	4B
*clefG2	*clefG2
8b	.
8a	4f
8gJ	.
*v	*v
=
*-
```

But this is redundant, because if there were two different clefs at the same time, there is no graphical syntax for displaying them in CMN.

When I convert the first encoding example into MEI, at each point where there is a `*` in the data for the second (right-most) layer, I look to the left on the line until the first layer to check for any clef-change event that needs to be inserted into the layer at that timestamp.

Encoding the clef in the second layer:

```
**kern
*clefF4
*^
8BL	4B
*	*clefG2
8b	.
8a	4f
8gJ	.
*v	*v
=
*-
```

will currently cause an error in the MEI conversion, since the clef will be ignored (I only convert the clef if it is present in the first layer and ignore any clefs in higher-numbered layers).

An ideal encoding of clefs would be to encode them as floating elements, similar to fermata or hamony elements.  This would allow it to be generalized in such a way to split a durational event in a layer, which clefs are currently not allowed to do so.

**Comment by craigsapp** [comment]
> I am simply questioning the idea to use @sameas for an element that is not at the same timestamp position. But we can probably ignore is.

I think that it is reasonable.  When two clefs on a staff have the same timestamps, then it is obvious that they are `@sameas` (and they would overstrike in the notation and appear as a single clefs).  The `@sameas` is needed in the cases where one of the clefs cannot be placed at the same timestamp as the other due to the durational sequence of items in the layer.  For such a case, the `@sameas` would indicate that the two clefs should be the same, and presumably the one possessing the `@sameas` attribute should not be displayed [because its timestamp is off by a little bit and therefore will not overstrike with its companion(s)].  In effect it would be adopting the same timestamp as its companion.  Of course, this interpretation depends on being consistent with other applications of `@sameas`.

**Comment by craigsapp** [comment]
Posting the current solution with `@sameas`:

<img width="208" alt="Screen Shot 2020-01-20 at 12 16 23" src="https://user-images.githubusercontent.com/3487289/72755168-b5309700-3b7e-11ea-893c-497619c835af.png">


```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-01-20T12:14:48" version="2.5.0-dev-4909cf1-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000114529519">
    <score xml:id="score-0000001348545719">
     <scoreDef xml:id="scoredef-0000000299626341">
      <staffGrp xml:id="staffgrp-0000001550396434">
       <staffDef xml:id="staffdef-0000001500902321" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="0">
       <staff xml:id="staff-0000000317234278" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L5F1-L9F1">
          <note xml:id="note-L5F1" dur="8" oct="3" pname="b" stem.dir="up" accid.ges="n" />
          <clef xml:id="clef-L6F1" shape="G" line="2" />
          <note xml:id="note-L7F1" dur="8" oct="4" pname="b" accid.ges="n" />
          <note xml:id="note-L8F1" dur="8" oct="4" pname="a" accid.ges="n" />
          <note xml:id="note-L9F1" dur="8" oct="4" pname="g" accid.ges="n" />
         </beam>
        </layer>
        <layer xml:id="layer-L5F2N2" n="2">
         <note xml:id="note-L5F2" dur="4" oct="3" pname="b" accid.ges="n" />
         <clef xml:id="clef-L6F1b" sameas="clef-L6F1" shape="G" line="2" />
         <note xml:id="note-L8F2" dur="4" oct="4" pname="f" stem.len="5.500000" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```
