### ISSUE TITLE
Do not optimize scoreDef when an tempo change occurs

### ISSUE THREAD

**Issue by lpugin** [rism-ch/verovio#936]
Standard practice for orchestra score is to show all staves when a tempo change occurs.

**Comment by donbyrd** [comment]
I don't recall an official rule, but my first thought was that's unlikely; it'd waste too much paper and add too many page turns. So I looked at two scores that I thought would have counterexamples, Debussy's Prelude to the Afternoon of a Faun (International edition), and the Mahler 4th (Universal edition). Sure enough, p. 21 of the Debussy has an instance of a tempo mark on a system with hidden staves; the Mahler has a number of examples, the first in just the first few pages of the first movement.

This brings up the question of what "all staves" even means! This is a very nontrivial question, one that I'm sure has come up before, and this probably isn't the right place to discuss it. But, for example, the first page of the Debussy pieces has each pair of woodwinds on one staff, and both harps on one "grand staff" (two staves with a brace). Later on there are spots are where the flutes each have their own staff and where the harps each have their own pair of staves. And of course there are many pieces where the strings are divisi and written on different numbers of staves at different points.

**Comment by craigsapp** [comment]
Yes, it may depend on the style of the music.  Mozart would not have many tempo changes, or a larger number of orchestral parts, so showing the entire score at a tempo change is not much of a problem.

Note that it is definitely always true that multi-measure rests must be split at tempo changes in an orchestral part.

An extreme example would be the Rite of Spring by Stravinsky.  The Dover edition opening does not give the full score:

http://www.petruccilibrary.us/linkhandler.php?path=files/imglnks/music_files/PMLUS00725-complete1.pdf

<img width="625" alt="screen shot 2018-10-04 at 12 22 27 pm" src="https://user-images.githubusercontent.com/3487289/46497673-17ba2400-c7d0-11e8-82b4-59043c1e6216.png">

at the recapitulation of the opening theme, the staves actually contract at the a tempo:

<img width="380" alt="screen shot 2018-10-04 at 12 24 07 pm" src="https://user-images.githubusercontent.com/3487289/46497752-50f29400-c7d0-11e8-8f12-8408067ddce4.png">

Looking at the Dover edition of Beethoven's 5th, 2nd movement, I see that the score does not expand at the tempo change.

http://conquest.imslp.info/files/imglnks/usimg/0/03/IMSLP00080-Beethoven_-_Symphony_No_5_in_C_Minor,_Op_67_-_II_-_Andante_con_moto.pdf

The opening system is in full score:

<img width="758" alt="screen shot 2018-10-04 at 12 30 21 pm" src="https://user-images.githubusercontent.com/3487289/46498068-3c62cb80-c7d1-11e8-84cd-4682608ec5c3.png">

a Più mosso near the end of the movement does not expand to the full score (i.e., the resting brass section are now shown):

<img width="721" alt="screen shot 2018-10-04 at 12 32 19 pm" src="https://user-images.githubusercontent.com/3487289/46498140-6ddb9700-c7d1-11e8-8fb9-d2e1a7463632.png">

**Comment by craigsapp** [comment]
Note also that the Rite of Spring example shows the need for an option to start the optimization at the start of the movement (which would typically not be optimized).

For JRP scores, I had some request related to a type of optimization which I will have to look for.  I think it is the same as the Rite of Spring example (allow optimization at the first system).

**Comment by lpugin** [comment]
Optimizing the start is quite easy. The only question is - as often - do we want to add another Verovio option, or rethink the type of scoreDef@optimize (which is now a boolean)? For the second option, we should move the discussion to the MEI repo.

**Comment by lpugin** [comment]
Fixed 6f8594b76455c58d196cd515cfa9dfcf3c66a881
