### ISSUE TITLE
Update and check tutorials

### ISSUE THREAD

**Issue by MusStudent** [rism-ch/verovio#941]
Faced with the fact that on different sites different versions of verovio-toolkit.js are used, linked from different sources:

- http://www.verovio.org/javascript/latest/verovio-toolkit.js
- https://www.verovio.org/javascript/develop/verovio-toolkit.js
- downloaded from GitHub
- http://verovio-script.humdrum.org/scripts/verovio-toolkit.js (bigger then other versions about 2Mb)

The code from one example did not work with the version of Verovio from another example (I'm trying with  localhost and test domain in Web).

Some examples caused an errors in the console. The problem was solved by overwriting a toolkit file from another source (from verovio-script.humdrum.org)
![img-2018-10-21-08-34-22](https://user-images.githubusercontent.com/6236403/47263329-6ece3180-d510-11e8-8993-9cd214f55141.png)

The examples contains options that will deprecated soon:
- options: **border** instead **pageMarginBottom** etc.
![img-2018-10-21-09-00-42](https://user-images.githubusercontent.com/6236403/47263298-0bdc9a80-d510-11e8-9924-2c0cbc1675e8.png)

The examples uses obsolete **renderToSVG** methods instead **renderData**.
![img-2018-10-21-09-04-10](https://user-images.githubusercontent.com/6236403/47263325-5a8a3480-d510-11e8-8316-b070f8b25782.png)

**Comment by lpugin** [comment]
The tutorials seem to all work.
