### ISSUE TITLE
How to contribute to submodule gh-tutorial?

### ISSUE THREAD

**Issue by musicEnfanthen** [rism-ch/verovio#954]
Please provide workflow (maybe in Contributing.md) how to contribute to submodule gh-tutorial. 

Tried to follow the description here: https://stackoverflow.com/a/5542964 but it ends at the point when it comes to `git push` in the submodule because pushing to origin (rism-ch/verovio) is not allowed obviously.

Now forked the submodule verovio-tutorial, made a PR there, wait for merge to point to the latest commit from the parent module afterwards.

If that's the way to go, it is quite a trip to just change one line (or two). Probably I am missing something, are there any other ways to go that I do not see?

**Comment by lpugin** [comment]
Submodules are quite cumbersome to update. The purpose of having one was to make the tutorials easy to clone and run independently. I still think it is beneficial and I would suggest to leave it like this. We can update the contribution guidelines with:

```
For updating the tutorial: fork the submodule verovio-tutorial, made a PR there, wait for a merge to point to the latest commit from the parent module afterwards.
```

OK?

**Comment by musicEnfanthen** [comment]
Yes, the benefit is evident. And yes, having a hint like the one above would be great to have on contribution guidelines. 

Could you also have a short look at the PR rism-ch/verovio-tutorial#3 in submodule please?
