### ISSUE TITLE
Setting option "appXPathQuery" without "loadData" has no effect

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#956]
I am using readings to encode different verses of a song:
```XML
<note xml:id="m-482" dur="4" dur.ges="256p" oct="4" pname="g" pnum="67" stem.dir="up">
    <app xmlns="">
        <rdg n="1">
            <verse xml:id="m-490">
                <syl xml:id="m-491" wordpos="i">dem,</syl>
            </verse>
        </rdg>
        <rdg n="2">
            <verse xml:id="m-494">
                <syl xml:id="m-495" wordpos="t">schen</syl>
            </verse>
        </rdg>
        <rdg n="3">
            <verse xml:id="m-498">
                <syl xml:id="m-499" wordpos="t">le,</syl>
            </verse>
        </rdg>
        <rdg n="4">
            <verse xml:id="m-500">
                <syl xml:id="m-501" wordpos="i">dem,</syl>
            </verse>
        </rdg>
    </app>
</note>
```
This way, I was hoping that I could simply select the verse to be displayed by choosing the corresponding reading:

```JavaScript
function renderPage(pageNum, verseNum) {
    vrvToolkit.setOptions({
        appXPathQuery: "./rdg[contains(@n, '" + verseNum + "')]",
    });
    svgDiv.html(vrvToolkit.renderToSVG(pageNum));
}

renderPage(1, 3); // Render page 1 with verse 3
```

Unfortunately, Verovio only pays attention to the `appXPathQuery` option when calling `loadData(...)`. Is there any way to still get the functionality that I want without reloading the MEI file?

**Comment by sonovice** [comment]
> As it is now you indeed do have to reload the file because the selection is performed by the xpath 1.0 implementation of pugixml used to load the file.

That's what I feared, but thanks anyway.

Do you maybe have another idea how I could achieve the verse selection without reloading the MEI file? Using the `app` tag is kinda abusing the specifications...

**Comment by lpugin** [comment]
> Do you maybe have another idea how I could achieve the verse selection without reloading the MEI file? Using the app tag is kinda abusing the specifications...

Not really but I will think about it.

**Comment by sonovice** [comment]
Thanks. I just realized, that simply calling `loadData(...)` every time that I want another reading does not suffice. I have to create new `toolkit` instances to make it work.

**Comment by rettinghaus** [comment]
Did you try to render all Verses at once and show/hide them with CSS/JavaScript? Try to set n-attribute to 1 on all verses and add a type attribute to identity them in SVG.

**Comment by sonovice** [comment]
> Did you try to render all Verses at once and show/hide them with CSS/JavaScript?

I actually tried that but hat no luck because some notes had less verses than others and thus I was not able to identify them properly. Let's try it with the type attribute! I didn't know that Verovio does not get rid of it in the SVG. Thank you!

**Comment by sonovice** [comment]
> Thanks. I just realized, that simply calling `loadData(...)` every time that I want another reading does not suffice. I have to create new `toolkit` instances to make it work.

Turns out that th  `appXPathQuery` option has to be an array if new MEI data get's loaded repeatedly. I guess it's a bug. Or at least it's not documented anywhere.
