### ISSUE TITLE
fix inter-layer alignment

### ISSUE THREAD

**Issue by minamouse** [rism-ch/verovio#96]
There are still problems with the layout with multiple layers.
Here, for example, many of the accidentals overlap, or are generally placed too close to each other.
![screen shot 2015-05-21 at 2 43 01 pm](https://cloud.githubusercontent.com/assets/11529868/7756417/1d742526-ffc9-11e4-80aa-66b170cc3219.png)
instead of:
![screen shot 2015-05-21 at 2 51 12 pm](https://cloud.githubusercontent.com/assets/11529868/7756444/46ddf34c-ffc9-11e4-9e4e-1ebfb2591221.png)

Also note-head alignment needs to be fixed in close notes
![screen shot 2015-05-21 at 2 19 48 pm](https://cloud.githubusercontent.com/assets/11529868/7757385/e52c97a0-ffcf-11e4-9417-62c13fa2a9b4.png)

**Comment by mborsodi** [comment]
Also, when layers cross, the notes need to be farther apart to differentiate
![screen shot 2015-05-21 at 4 28 17 pm](https://cloud.githubusercontent.com/assets/11529868/7758268/6d9785ea-ffd6-11e4-951c-75015cbe337d.png)

**Comment by rettinghaus** [comment]
what's with this?

**Comment by craigsapp** [comment]
The second example is for of crossed voices where the lower layer has higher notes and the higher layer has lower notes (in the second measure):

<img width="566" alt="screen shot 2017-06-10 at 11 20 58 am" src="https://user-images.githubusercontent.com/3487289/27001617-e7058ba0-4dce-11e7-8f5f-ef57740891cb.png">

Still needs to be done.  Here is the expected rendering:

<img width="595" alt="screen shot 2017-06-10 at 11 18 10 am" src="https://user-images.githubusercontent.com/3487289/27001611-d045f292-4dce-11e7-889f-22d63641813c.png">

(the seconds are now correct)

```
**kern
*M4/4
*^
4dd	4d
4cc	4e
4b	4f
4a	4g
=	=
4g	4a
4f	4b
4e	4cc
4d	4dd
*v	*v
=
*-
```

**Comment by craigsapp** [comment]
Here is an example where cross-voice stemming is causing an offset:

<img width="527" alt="screen shot 2018-01-28 at 11 12 22 am" src="https://user-images.githubusercontent.com/3487289/35485999-8474d4e6-041c-11e8-9f2e-46e129b1a953.png">

The augmentation dots in measure 2 seems to be causing an offset of the E4 pitch, but the correct offset direction should be in the opposite direction:

<img width="752" alt="screen shot 2018-01-28 at 11 12 13 am" src="https://user-images.githubusercontent.com/3487289/35486005-9b9cfdb0-041c-11e8-82ef-d981530f3808.png">

Test data:

```
**kern
=1
*^
2.c	2.e@
=2	=2
2.c 2.g	2.e@
=3	=3
2c 2g	2e@
*v	*v
==
*-
!!!RDF**kern: @ = marked note, color="#ff00ff"
```
