### ISSUE TITLE
False rendering with some P&E triplets

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/verovio#966]
eg. in https://muscat.rism.info/admin/sources/455002955

From KK:

> "Diese Incipit führt zur falschen Darstellung der Triole, obwohl prinzipiell richtig codiert (wenn auch umständlich).: G-2 - 2/4 - 8,B/4(8{GB'E};3)({FD,B})/8'G-8.-6,B/4({8'EGB};3)({BBB})/8B-8.-6B/4({8CAC};3)({bCAC})/8,B-8.-6'A/
> Die jeweils 2ten Triolen müssen 8tel sein, nicht 32tel. ... …};3) bedeutet nur, dass auf den Viertelwert (4 vor runder Klammer) 3 Noten kommen.
> Titel: 455002955. Incipit 1.3.1"
> 

![image](https://user-images.githubusercontent.com/6461776/48890298-c413a080-ee38-11e8-83d2-cfa692908c40.png)

**Comment by rettinghaus** [comment]
refers to #829
General problem in incorrect handling of tuplets.

**Comment by lpugin** [comment]
See also 
https://muscat.rism.info/admin/sources/700011041
![image](https://user-images.githubusercontent.com/689412/55073435-07ec1000-508e-11e9-97b8-947c0c0b9c1f.png)

**Comment by rettinghaus** [comment]
This also doesn't work:
`4({'6DEFGAG};3)`
![TUPLETS_001](https://user-images.githubusercontent.com/7693447/55293061-40734d00-53f2-11e9-9c83-c44e0b7f6e07.png)
