### ISSUE TITLE
beams and stem directions in multiple layers

### ISSUE THREAD

**Issue by mborsodi** [rism-ch/verovio#97]
In 2 layers, when one of the parts has notes which are connected by a beam, the stem direction is sometimes wrong. What happens is that, instead of defaulting to the correct layer direction, it defaults to the stem direction that it would have if it weren't in a layer. 
For example:
![screen shot 2015-05-25 at 11 47 19 am](https://cloud.githubusercontent.com/assets/11529868/7801090/54cb471c-02ed-11e5-8c07-f985bb43e3f0.png)

However, when I take out the beam, it works the way it should:
![screen shot 2015-05-25 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/11529868/7801099/74b8e2be-02ed-11e5-9d22-5bed5bffa756.png)
This problem is also not fixed when you go in and add "stem.dir="up".

**Comment by lpugin** [comment]
Fixed
