### ISSUE TITLE
tuplet bracket placement

### ISSUE THREAD

**Issue by axgeertinger** [rism-ch/verovio#970]
While waiting for `<bracketSpan func='ligature'>` I am using tuplets to draw brackets indicating ligatures in the original (mensural) notation, and I would like to have the brackets above the notes always. `@bracket.place='above'` doesn't seem to have any effect. With whole notes, the tuplet bracket always seems to be placed below the notes. Adding `@stem.dir` to the notes (which works fine to flip the direction of a slur, for instance) does not have any effect in this case. With smaller note values, the bracket is always placed on the stem side. Is there a way of forcing them to appear above the notes?

![tuplet_brackets](https://user-images.githubusercontent.com/3779074/50164177-40878b00-02e2-11e9-9ded-332fae4e5603.png)

**Comment by axgeertinger** [comment]
Here's a sample code snippet (apologies for the formatting – I've been struggling to make GitHub display the code readable but gave up):
`<tuplet num="2" numbase="2" bracket.visible="true" bracket.place="above" num.visible="false" label="Ligatur" type="cursorHelp" xml:id="Th_1569_LN1426_004r_m-40">
    <note xml:id="Th_1569_LN1426_004r_m-39" dur="1" dur.ges="1024p" oct="3" pname="g" pnum="55">
        <verse xml:id="Th_1569_LN1426_004r_m-57" n="1">
            <syl xml:id="Th_1569_LN1426_004r_m-58" con="d" wordpos="i">skul</syl>
        </verse>
    </note>
    <note xml:id="Th_1569_LN1426_004r_m-41" dur="1" dur.ges="1024p" oct="3" pname="a" pnum="57"/>
</tuplet>`

**Comment by craigsapp** [comment]
Use three back-ticks at the start and end of multi-line quotes of XML code (these should be on a line by themselves).  If you add the text "xml" (without quotes) on the same line after the opening back-ticks, the XML will be colorized. (I edited your example above to do that).

**Comment by lpugin** [comment]
The initial implementation for `<bracketSpan>` was pushed yesterday. I still need to adjust the horizontal positioning. Once this is done I will update the JavaScript toolkit. The bracket will always be horizontal above the staff.

**Comment by axgeertinger** [comment]
Great! Thanks to both of you. I am closing this issue for now – don't know if the placement of tuplet brackets is important to others.

**Comment by lpugin** [comment]
This is the current status. No assumption is made on how to render ligature or coloration bracketSpan@func. This is left to the encoder with the adjustment of `@lwidth` and `@lform`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>BracketSpan example</title>
            </titleStmt>
            <pubStmt/>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" xml:id="s1" clef.line="2" clef.shape="G" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure label="feature-example" n="1">
                            <staff n="1">
                                <layer n="1">
                                    <note dur="1" pname="c" oct="4" xml:id="n01"/>
                                    <note dur="1" pname="d" oct="4" xml:id="n02"/>
                                    <note dur="1" pname="e" oct="4" xml:id="n03"/>
                                    <note dur="1" pname="f" oct="4" xml:id="n04"/>
                                    <note dur="1" pname="g" oct="4" xml:id="n05"/>
                                    <note dur="1" pname="f" oct="4" xml:id="n06"/>
                                    <note dur="1" pname="e" oct="4" xml:id="n07"/>
                                    <note dur="1" pname="d" oct="4" xml:id="n08"/>
                                    <note dur="1" pname="c" oct="4" xml:id="n09"/>
                                    <note dur="1" pname="g" oct="4" xml:id="n10"/>
                                </layer>
                            </staff>
                            <bracketSpan func="ligature" startid="#n01" endid="#n02" staff="1"></bracketSpan>
                            <bracketSpan func="ligature" startid="#n03" endid="#n04" staff="1" lwidth="medium"></bracketSpan>
                            <bracketSpan func="ligature" startid="#n05" endid="#n06" staff="1" lwidth="0.5vu"></bracketSpan>
                            <bracketSpan func="ligature" startid="#n07" endid="#n08" staff="1" lform="dotted"></bracketSpan>
                            <bracketSpan func="ligature" startid="#n09" endid="#n10" staff="1" lform="solid"></bracketSpan>
                            <bracketSpan func="ligature" tstamp="1.0" tstamp2="0m+41.0" staff="1" lform="dashed"></bracketSpan>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>

```

![image](https://user-images.githubusercontent.com/689412/50208779-69eff780-0372-11e9-922b-1d5df9e9e591.png)
![image](https://user-images.githubusercontent.com/689412/50208852-973ca580-0372-11e9-9c03-5a48b29a71ef.png)

**Comment by axgeertinger** [comment]
Awesome! :-)
