### ISSUE TITLE
Unnecessary trailing zeros in timestamps

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#975]
When converting into MEI data from another data format (MusicXML, Humdrum, or I presume P&E), the timestamps are quite ugly:

From MusicXML importer:
```xml
       <harm xml:id="harm-0000001676348108" staff="1" tstamp="1.000000">Am</harm>
       <harm xml:id="harm-0000001651477441" staff="1" tstamp="7.750000">Dm</harm>
       <harm xml:id="harm-0000002053616025" staff="1" tstamp="14.500000">G</harm>
```

And via the Humdrum importer

```xml
         <harm xml:id="harm-L12F5" staff="1" tstamp="1.000000">Am</harm>
         <harm xml:id="harm-L13F5" staff="1" tstamp="4.000000">Dm</harm>
         <harm xml:id="harm-L14F5" staff="1" tstamp="7.000000">G</harm>
```

If someone is using verovio to generate SVG images, it will not matter since there is no MEI output in that case.  But when using MEI to convert from other formats, these extra zeros make the data harder to read and pad the filesize with unecessary characters.

A `@tstamp` of `1.000000` would look better as `1` instead.  The cause of the extra zeros is due to the use of sprintf rather than stringstream.  Is there a reason for this @lpugin?  It would be nicer to not have the trailing zeros by using stringstream instead.

I can make this fix myself, if you like 😃

**Comment by lpugin** [comment]
> I can make this fix myself, if you like

Please change it if you want. However, I would suggest `1.0` instead of `1`

**Comment by craigsapp** [comment]
> Please change it if you want. However, I would suggest 1.0 instead of 1

Any particular reason? (such as some validator expects `@tstamp` to contain a decimal point?)

Current:

```
         <harm xml:id="harm-L12F5" staff="1" tstamp="1.000000">Am</harm>
         <harm xml:id="harm-L13F5" staff="1" tstamp="4.000000">Dm</harm>
         <harm xml:id="harm-L14F5" staff="1" tstamp="7.000000">G</harm>
```

With one decimal digit minimum:

```
         <harm xml:id="harm-L12F5" staff="1" tstamp="1.0">Am</harm>
         <harm xml:id="harm-L13F5" staff="1" tstamp="4.0">Dm</harm>
         <harm xml:id="harm-L14F5" staff="1" tstamp="7.0">G</harm>
```

Without any fractional digits (if all are zero):


```
         <harm xml:id="harm-L12F5" staff="1" tstamp="1">Am</harm>
         <harm xml:id="harm-L13F5" staff="1" tstamp="4">Dm</harm>
         <harm xml:id="harm-L14F5" staff="1" tstamp="7">G</harm>
```

I don't see any advantage to include `.0`.  If there is no fractional part, then it is quicker to distinguish that the tstamp is on a meter-unit integral.

**Comment by lpugin** [comment]
It makes it clear that `@tstamp` is of a fractional type. But I don't mind either way.

**Comment by craigsapp** [comment]
True, and I always add a `.0` in C++ when the data type is supposed to be a float/double even if it would be automatically typcaset into a double.

But there are no `.0` on the tstamps in https://github.com/music-encoding/sample-encodings/tree/master/MEI_4.0/Music/Complete_examples, which is of course the acme of encoding standards for MEI 😛 

So people that usually type MEI in by hand probably are not used to adding `.0` and therefore not used to seeing it.
