### ISSUE TITLE
missing glyphs in develop

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#978]
> Expected 222 default SMUFL glyphs but could load only 220.

**Comment by craigsapp** [comment]
I get a related error sometimes when I download a new version of develop that has added glyphs.  In those cases, I have to do a `make install` to install the new glyphs in the system file structure.  I for safety, I also delete the cmake files in the veorvio/tools directory and recompile everything:

```bash
cd verovio/tools
rm -rf CMakeFiles
rm CMakeCache.txt
cmake .
make
make install
```

This will solve that type of error for me.

**Comment by rettinghaus** [comment]
My fault again! 
I forgot to `cmake . `
