### ISSUE TITLE
'breaks' option not functioning as expected in node api

### ISSUE THREAD

**Issue by jamesopstad** [rism-ch/verovio#981]
Setting the 'breaks' option doesn't seem to work correctly in the npm package. Setting the option to 'encoded' seems to be ignored and setting to 'none' acts strangely. Both work correctly on the same mei file when using the cli.

**Comment by lpugin** [comment]
It works for me, something must be wrong on your side.

**Comment by jamesopstad** [comment]
I've located the issue. The 'break' option needed to be set before loading the data. This didn't apply to the other options I specified.
