### ISSUE TITLE
Consider moving more attributes to embedded style sheet

### ISSUE THREAD

**Issue by jamesopstad** [rism-ch/verovio#983]
There are a lot of attributes that are currently attached to every element in a group even though they are exactly the same. For example, with the default settings, `stroke="#000000"` and `stroke-width="22"` will be added to every ledger line. Why not style these using the embedded style sheet e.g.

`
g.ledgerLines{stroke:#000000;stroke-width:22}
`

This would make it a lot easier to override styling and reduce the overall quantity of code.

**Comment by lpugin** [comment]
Styling can be done using the Verovio options (e.g., changing the line width). But I am not completely against it, so please make a PR with the desired modifications.

**Comment by jamesopstad** [comment]
OK, thanks. I've not used C++ before but will have a look into it when I have some time.

**Comment by lpugin** [comment]
Great. The current SVG output was tested to work with Firefox, Chrome, Safari, Edge and also to import properly into Gimp and Inkskape. I noticed differences and that some features for SVG do not always work as expected.

**Comment by rettinghaus** [comment]
There was a reason why I left it this way, but honestly I can't remember. So give it a shot.

**Comment by lpugin** [comment]
See this https://github.com/rism-ch/verovio/issues/556 (handling of color) and this https://github.com/rism-ch/verovio/pull/528 (different behavior with Gimp)

**Comment by jamesopstad** [comment]
Thanks for the help. I do intend to contribute to the project but that won't be possible anytime soon I'm afraid. Maybe this issue should be marked as low priority. In the meantime, I hope you don't mind me raising other issues as I encounter them.
