### ISSUE TITLE
SMuFL codes in <rend>

### ISSUE THREAD

**Issue by jamesopstad** [rism-ch/verovio#992]
As is stated in #915 and the Verovio docs, `<rend>` can be included within `<tempo>` elements to render SMuFL notes for use in metronome markings. The only SMuFL codes that currently work are the individual notes, as listed here - https://w3c.github.io/smufl/gitbook/tables/individual-notes.html. These glyphs don't work well for metronome markings, however, as they don't align well with the text. This is stated at the bottom of the linked page. It is also evident in the example given in #915, shown below.

<img width="164" alt="43135527-02fdf626-8f46-11e8-86ee-92e49f449105" src="https://user-images.githubusercontent.com/13586373/52435332-7b02ec80-2b09-11e9-8686-6d6995ccee93.png">

The SMuFL spec includes additional codes, specifically designed for metronome marks, which can be found here - https://w3c.github.io/smufl/gitbook/tables/metronome-marks.html. It would be much better to include these.

Also, I'm a little unclear about how `VerovioText` works. Does it use the same font that has been selected for rendering the notation?

**Comment by lpugin** [comment]
You can see the glyphs included in VerovioText here https://github.com/rism-ch/verovio/blob/develop/fonts/VerovioText-1.0.ttf
What glyphs are missing for you?

**Comment by craigsapp** [comment]
Somewhat related: https://github.com/humdrum-tools/verovio-humdrum-viewer/issues/92
It would be useful to add the segno and coda symbols (S with slash and dots and the O with a + inside it) to the `VerovioText` font:

<img width="171" alt="screen shot 2019-02-07 at 3 09 05 pm" src="https://user-images.githubusercontent.com/3487289/52448926-59463d00-2aea-11e9-9814-1579b3a15307.png">
  

https://www.smufl.org/version/latest/range/repeats/
Coda:  E048
Segno: E047

I am currently entering them as regular unicode text, but the PDF output does not have acess to the a full unicode font and some browsers do not have the standard unicode glyphs in their font as well.

[If there are dedicated MEI elements for displaying those, then you can tell me about it (there is no dedicated `<coda>` and `<segno>`, so I have been using`<dir>` for these.)

**Comment by lpugin** [comment]
Aligning music symbols with text is often problematic. I am quite OK with how VerovioText aligns in the above tempo mark. What is wrong for you?

**Comment by lpugin** [comment]
Here is an example text with VerovioText and BravuraText typed in MS Word. VerovioText is larger for it to be used in tempo / metronome marks. You can also see that some music glyphs are cut when used in the text, but so do they with BravuraText.
![image](https://user-images.githubusercontent.com/689412/52463017-9d325400-2b75-11e9-817d-e11176503de9.png)

(With the PDF generated from the same file on my computer, glyphs are not cut but overlap.)
![image](https://user-images.githubusercontent.com/689412/52462995-81c74900-2b75-11e9-9fb2-49f56378ac58.png)

**Comment by lpugin** [comment]
@craigsapp 
> If there are dedicated MEI elements for displaying those, then you can tell me about it (there is no dedicated `<coda>` and `<segno>`, so I have been using`<dir>` for these.)

There is not. Could you raise the question on music-encoding? Maybe something should be changed.

**Comment by craigsapp** [comment]
> There is not. Could you raise the question on music-encoding? Maybe something should be changed.

I see that I already have 😉  :  

https://github.com/music-encoding/music-encoding/issues/520

The current guidelines (v3 at least) says that `<dir>` element should be used, although `<coda>` and `<segno>` would be good (their stack order would be quite high, since they should be above anything except rehearsal marks, and probably closest in behavior to `<fermata>`).

**Comment by jamesopstad** [comment]
> Aligning music symbols with text is often problematic. I am quite OK with how VerovioText aligns in the above tempo mark. What is wrong for you?

Here is the same example rendered using Dorico:

![doricooutput](https://user-images.githubusercontent.com/13586373/52474369-34a4a080-2b90-11e9-8960-5f4c159c7abf.png)

As can be seen, the stem is shorter (this is clearly a 'metronome mark' glyph) and the bottom of the notehead aligns with the bottom of the text. To me, this looks much better and is more similar to the output of other notation software. I also prefer the overall positioning of the metronome mark. Verovio generally seems to position markings (including dynamics, text etc.) very close to the staff.

**Comment by craigsapp** [comment]
> Verovio generally seems to position markings (including dynamics, text etc.) very close to the staff.

An option similar to `lyric-top-min-margin` could be added for `<tempo>` minimum spacing to the staff.   That example looks a bit too high to me, but probably better for orchestral scores where the tempo markings need to be more noticeable for the conductor.

Examining a random score that does not have the need for extra vertical padding (in the cello part):

http://conquest.imslp.info/files/imglnks/usimg/a/ab/IMSLP24641-PMLP55541-Faure_Cello_Sonata_No1_Op109_Cello_Piano.pdf

<img width="1071" alt="screen shot 2019-02-08 at 6 37 14 am" src="https://user-images.githubusercontent.com/3487289/52476122-b59d7100-2b6b-11e9-9393-04e543acba6c.png">

The spacing of the tempo indication is 2 staff lines, or 4 diatonic steps (MEI spacing units).

Typesetting the same situation in verovio:

<img width="669" alt="screen shot 2019-02-08 at 6 42 04 am" src="https://user-images.githubusercontent.com/3487289/52476360-52600e80-2b6c-11e9-9072-09174af90016.png">

Where the spacing is about 1.75 diatonic steps.

It would be good to set the default minimum to twice this at 4 units.

**Comment by lpugin** [comment]
> To me, this looks much better and is more similar to the output of other notation software. I also prefer the overall positioning of the metronome mark. 

Maybe. And somebody else will prefer something else. I just looked a different scores and they can look very different. So the best would be to allow for the VerovioText font to be replaced with a user one, including with a shorter stem. What do you think? Are you willing to make a PR for this?

> Verovio generally seems to position markings (including dynamics, text etc.) very close to the staff.

This is a different issue concerning the general question on how to go ahead with styling. One solution is to add additionnal options to Verovio. I would prefer this to be discuss at a more general level on how styling can be defined.

**Comment by craigsapp** [comment]
> Maybe. And somebody else will prefer something else. I just looked a different scores and they can look very different.

In general the stem of the note should be shorter than an octave in such cases.  The example I gave had a very short stem, perhaps due to being close to the staff above the mark.  There is probably no standard height for such text-based notes, but I would say at least 1.5 diatonic steps shorter stem would be the overall convention.

**Comment by jamesopstad** [comment]
> Maybe. And somebody else will prefer something else. I just looked a different scores and they can look very different. So the best would be to allow for the VerovioText font to be replaced with a user one, including with a shorter stem. What do you think? Are you willing to make a PR for this?

I agree that different people may have different preferences. Have you found any examples, however, of professional scores where the metronome marks look as they currently do in Verovio (with the baseline of the notehead higher than the baseline of the text)? I've never seen one but I'm happy to be proved wrong about this. My first point is therefore that the default behaviour should reflect common practice. My second point is that as Verovio uses SMuFL, its usage and the associated codes should be inline with the spec.

Regarding making a PR, I wish I could help but, as mentioned in another issue, I currently lack both the time and expertise. I hope this doesn't prevent me from looking at Verovio critically and raising issues.

> This is a different issue concerning the general question on how to go ahead with styling. One solution is to add additionnal options to Verovio. I would prefer this to be discuss at a more general level on how styling can be defined.

I agree and will raise a separate issue about this.
