### ISSUE TITLE
License is prohibitive for ios apps

### ISSUE THREAD

**Issue by aclaussen1** [rism-ch/verovio#998]
Would be great to be able to include this library for ios apps. LGPL license is a bit shaky for distributing on app stores (see this reddit thread: https://www.reddit.com/r/programming/comments/15j36a/your_lgpl_license_is_completely_destroying_ios/)

would be great if either the license was changed to a more permissive license (MIT perhaps), or there was a minor exemption added to the license that would allow static linking for ios/android apps.

**Comment by lpugin** [comment]
Opinions vary significantly on the use of LGPL code in the Appstore. As Vervovio is a project that is mostly funded by public research money, the choice of LGPL is to ensure that modifications and improvements to the library are made available to the community, and also credits to be given. In the case of an app, this would typically be located with other meta-app information in an about section of the app and of your website. Of course, modifications to the library (in any) have to be published under the same license.

**Comment by lpugin** [comment]
@aclaussen1 see two examples of credits in the meta-app:
https://itunes.apple.com/us/app/nomadplay-play-together/id1443790777 (see more, and the notice "NomadPlay utilise la librairie open-source Verovio (www.verovio.org)") 
https://itunes.apple.com/US/app/id1441294568?mt=8

**Comment by craigsapp** [comment]
I also notice that there are some sub-libraries used in Verovio with licenses of their own:

https://github.com/craigsapp/midifile/blob/master/LICENSE.txt
https://github.com/rism-ch/verovio/blob/develop/include/pugi/pugiconfig.hpp#L51-L74
https://github.com/rism-ch/verovio/blob/develop/include/json/LICENSE
and if compiled with the Humdrum module:
https://github.com/craigsapp/humlib/blob/master/LICENSE.txt
